### ISSUE TITLE
Zim de http://inciclopedia.wikia.com

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#101]
_From @kelson42 on October 19, 2016 9:38_

_Copied from original issue: openzim/mwoffliner#28_

**Comment by kelson42** [comment]
Seems not possible for now, see https://github.com/openzim/mwoffliner/issues/399

**Comment by kelson42** [comment]
@rgaudin Could you please schedule
```
mwoffliner --mwUrl="https://inciclopedia.org" --adminEmail="kelson@kiwix.com" --verbose --customZimFavicon="https://images.uncyclomedia.co/inciclopedia/es/b/bc/Wiki.png"
```

**Comment by kelson42** [comment]
First version available https://download.kiwix.org/zim/other/inciclopedia_es_all_2019-05.zim

**Comment by rgaudin** [comment]
Done. As for the previous version, it has no format. Let me know if this is OK.
