### ISSUE TITLE
Are we having duplicate files in the Stack Exchange repo?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1017]
I'm looking at our stackexchanges and I see a bunch of files with almost similar descriptions yet very different size. 
I haven't investigated yet but @RavanJAltaie can you please have a look?

![Screenshot 2024-05-31 at 16 01 28](https://github.com/openzim/zim-requests/assets/21675885/27ca405e-dbef-4a5c-8ec9-83f6eff0380c)
![Screenshot 2024-05-31 at 16 05 38](https://github.com/openzim/zim-requests/assets/21675885/82c6d532-e2da-44d1-96a5-3be68d06ca1d)

**Comment by benoit74** [comment]
Korean issue has already been pointed by a contributor a long time ago, but no-one cared: https://github.com/openzim/zim-requests/issues/838 (there was also a Portuguese file pointed in this issue).

English this is weird.

**Comment by RavanJAltaie** [comment]
@benoit74 I checked in the library
<img width="874" alt="image" src="https://github.com/openzim/zim-requests/assets/116940574/9c7a9f1a-eb0c-431f-9a84-f82fdd969f2f">

There is only 1 file per language with different description.
@Popolechien Which files you mean to delete?

**Comment by Popolechien** [comment]
@RavanJAltaie The correct search term would be `Korean` (https://library.kiwix.org/#lang=eng&q=korean), in which case you get this:
![Screenshot 2024-07-04 at 13 13 24](https://github.com/openzim/zim-requests/assets/21675885/139477eb-e27b-432b-ae68-5dd5ccf777a1)

The first one (on the left) is labeled as `Mul`, which is incorrect since this is for English speakers learning Korean. Not sure we can fix and restart the recipe, but at least try.

The second one is from 2020, so you need to find it on download.kiwix.org and ask for deletion. I have no idea why the older one should be bigger than the more recent one, maybe this should be investigated in case the recent one is broken / faulty.

**Comment by benoit74** [comment]
There is at least these two issues:
- https://library.kiwix.org/#lang=&q=english+enthusiasts (2 instead of 1)
- https://library.kiwix.org/#lang=&q=korean+Q%26A (3 instead of 1)

I don't achieve to get a grasp on why there is 3 "English" ZIMs in the imager service catalog. This is probably a bug in imager service, will be easier to confirm once the rest is cleaned-up

**Comment by Popolechien** [comment]
I see we also have a problem with https://library.kiwix.org/#lang=eng&q=english&category=stack_exchange 

So please @RavanJAltaie try to identify how many of these duplicates we have and ask for deletions. Regarding korean and looking at download.kiwix.org/zim/stack_exchange I see that 
[   ] [korean.stackexchange.com_en_all_2020-10.zim](https://download.kiwix.org/zim/stack_exchange/korean.stackexchange.com_en_all_2020-10.zim)              2020-10-27 14:14   31M   
[   ] [korean.stackexchange.com_ko_all_2023-05.zim](https://download.kiwix.org/zim/stack_exchange/korean.stackexchange.com_ko_all_2023-05.zim)              2023-05-02 08:07   14M   
[   ] [korean.stackexchange.com_ko_all_2023-10.zim](https://download.kiwix.org/zim/stack_exchange/korean.stackexchange.com_ko_all_2023-10.zim)

Should probably be deleted. @benoit74 any idea why the library would chose to display the 2020 file rather than the 2023 one?

**Comment by benoit74** [comment]
> @benoit74 any idea why the library would chose to display the 2020 file rather than the 2023 one?

korean.stackexchange.com_en_all is not equal to korean.stackexchange.com_ko_all

For korean.stackexchange.com_en_all, the 2020-10 version is the last one

For korean.stackexchange.com_ko_all, the 2023-10 version is the last one

**Comment by benoit74** [comment]
> The first one (on the left) is labeled as Mul, which is incorrect since this is for English speakers learning Korean. Not sure we can fix and restart the recipe, but at least try.

Not possible with sotoki AFAIK, at least for now.

**Comment by Popolechien** [comment]
Good catch. But then why don't we have three of them (`mul, `ko` and `en`) appearing on the library?

**Comment by benoit74** [comment]
> Good catch. But then why don't we have three of them (mul, ko and en) appearing on the library?

Either scraper has changed or metadata sourced from StackExchange has changed. I think the second option is most probable.

**Comment by benoit74** [comment]
I've created the deletion request: https://github.com/openzim/zim-requests/issues/1103

Let's keep this open to see what happens with the triple english once deletion is done.

**Comment by benoit74** [comment]
No need to keep this opened, I found the bugs: https://github.com/openzim/sotoki/issues/321 and https://github.com/offspot/imager-service/issues/436
