### ISSUE TITLE
Many problems with freecodecamp

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#1021]
* two freecodecamp entries in the library https://dev.library.kiwix.org/#lang=&q=Freecode
* They are old although the recipe generates new versions 
* See https://farm.openzim.org/pipeline/99f3e115-8124-4f4e-807e-75b4b3a276d7

**Comment by Popolechien** [comment]
Related to #1017  and #838 ?

**Comment by kelson42** [comment]
This is an invalid bug report from me. I have taken dev.library.kiwix.org in place of library.kiwix.org. See https://library.kiwix.org/#lang=&q=Freecode&category=. Sorry about that.
