### ISSUE TITLE
ready.gov ZIMs both contains all languages, only homepage is changed

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1028]
We have two recipes for ready.gov, one for English and one for Espanol.

Currently the only difference between these two ZIMs is the homepage. Both ZIMs contains all pages in all supported languages (mainly Espanol and English, but in fact many pages are translated in many languages, see for instance https://www.ready.gov/calor-extremo).

Properly filtering the pages is probably going to be a waste because the sheer size of the ZIM to come from images, JS code and fonts which are anyway reused across all languages (e.g on https://www.ready.gov/es/calor-extremo page, only the HTML is specific to the language and weight 14.73kB, but all other resources needed to load the page weight 3.63MB, with at least few images specific to this page only weighting more than 260k)

My recommendation would rather be to create only one ZIM, and clearly indicate that most content is in English and Espanol, but also list all supported languages in the ZIM metadata.

@Popolechien @kelson42 @RavanJAltaie WDYT?

**Comment by benoit74** [comment]
I've just created and requested https://farm.openzim.org/recipes/www.ready.gov_mul_all to test my recommendation scenario. 

It made me realize that we do not support multiple languages in warc2zim: https://github.com/openzim/warc2zim/issues/300

**Comment by Popolechien** [comment]
Yeah I suspect I'm the one that created that recipe a while back. Tbh I increasingly see `mul` as an mistake and would rather keep two files, even if 2.6 GB is not exactly trivial. At the end of the day if the landing page has the right language and users can work from there, then we're good in term of UX I would say.

Other languages seem to be used anecdotally on a variety of pages, but the only consistent, across-the-board translation seems only to be for the EN-ES couple.

**Comment by Jaifroid** [comment]
> Other languages seem to be used anecdotally on a variety of pages, but the only consistent, across-the-board translation seems only to be for the EN-ES couple.

This is definitely a highly multilingual resource, with multiple language versions of many different articles. You can even browse many pages in Tagalog! I would have thought it's a prime candidate for labelling as `mul`... Also, it seems a bit problematic potentially to mislead the kind of user we are targeting into downloading 2.6GB twice if they decide they also want a "Spanish" version, only to find that a single page is different...

**Comment by benoit74** [comment]
OK, then let keep the recipes as is, I will close this issue
