### ISSUE TITLE
Four flavours of wikipedia_en_medicine is one too many

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1036]
The wikipedia_en_medicine zim file currently has four flavours:
* [wikipedia_en_medicine](https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine) - with all videos, ca. 6GB
* [wikipedia_en_medicine_maxi](https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_maxi) - no videos, 1.7 GB
* [wikipedia_en_medicine_nopic](https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic) - no images, 842M
* [wikipedia_en_medicine_mini](https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_mini) - intro only, 173 MB

The larger zim goes against our current no videos policy and does not abide by any naming convention. I cannot find a ticket where its creation has been agreed upon. It should at the very least be renamed, or entirely deprecated.

**Comment by RavanJAltaie** [comment]
@benoit74 could you please advise the way to fix this?

**Comment by benoit74** [comment]
You need to:
- reach consensus onwhich ZIMs we want, and how they should be named
- place a ZIM request to rename existing files which needs to be or to delete the files you do not want anymore in the library
- update the recipe to create the ZIMs you want (with the "format" parameter, as usual with mwoffliner)

First point is the most important one of course, and need consensus before moving things around

**Comment by benoit74** [comment]
Since it looks like no-one is very attached to this topic, I have:
- modified the recipe to not create `wikipedia_en_medicine` anymore (the big one with videos)
- deleted existing `wikipedia_en_medicine` files from our server
- trigerred library update
