### ISSUE TITLE
WikiChip.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#104]
https://en.wikichip.org/

Site is under CC-by-SA

**Comment by RavanJAltaie** [comment]
Rejected
The Website is not under any free license 
"WikiChip is operated by WikiChip LLC which conducts the industry research of commercial and consumer hardware and technologies.
Content curation
Although WikiChip uses MediaWiki as the publishing software platform for content, WikiChip curates almost of all of the content (99%) with anonymous contributions (< 1%) usually limited to typos, grammar, and minor detail correction"
