### ISSUE TITLE
New request: deployedmedicine.com

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1041]
I'm opening this issue because we have a Zimfarm recipe at but no corresponding Github issue.

FYI, I don't get what we want to ZIM, everything aside the homepage seems to be behind a login wall.

I disabled the recipe which was running for nothing.

**Comment by Popolechien** [comment]
Top of the website indicates `Starting 14DEC2023, users must be signed in to access Deployed Medicine’s content` . So I guess it's become out of reach for us.

Should we reach out and engage?

**Comment by Popolechien** [comment]
Ok nevermind it is a commercial entity working on behalf of the DHA. Might as well reach out directly to the latter. I'd close the issue, but should we also not delete the recipe?

**Comment by benoit74** [comment]
We should indeed delete the recipe, I let you do that.

**Comment by Popolechien** [comment]
Ok. I've reached out to DHA as well.
