### ISSUE TITLE
ghana-bece-past-questions_en is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1045]
### Recipe URL

https://farm.openzim.org/recipes/ghana-bece-past-questions_en

### Last log lines

```true
failed to connect to https://www.passco.org/courses/jhs-past-questions/: 404 Client Error: Not Found for url: https://passco.org/courses/jhs-past-questions/
```

### How many times the recipe failed in a row?

Many

### How many ZIM have been produced before failure?

Many

### Which action did you undertake so far?

I have disabled the recipe for now

### What's next?

This has to be fixed by content team

**Comment by benoit74** [comment]
Looks like updated URL should be https://passco.org/courses/jhs-bece-past-questions-1990-2022/ ; to be ran once with Zimit2 then disabled since content is not updated anymore?

**Comment by benoit74** [comment]
(or maybe keep it enabled and run bi-annually just to update ZIM with whatever changes we might have at ZIM format / scraper level)

**Comment by Popolechien** [comment]
Yep looks like they archived and moved to a new URL.

**Comment by benoit74** [comment]
Configuration fixed and task requested.

**Comment by benoit74** [comment]
Updating the URL worked, ZIM is updated on library.
