### ISSUE TITLE
lesfondamentaux.reseau-canope.fr_fr_all_2022-11.zim is not working properly

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1046]
### ZIM(s) location

https://library.kiwix.org/viewer#lesfondamentaux.reseau-canope.fr_fr_all_2022-11

### Recipe(s) URL

https://farm.openzim.org/recipes/lesfondamentaux

### Readers tested

- [ ] Kiwix-serve on iOS (iPad / iPhone)
- [ ] Kiwix-serve on Android (phone or tablet)
- [ ] Kiwix-serve on Windows
- [ ] Kiwix-serve on Linux
- [ ] Kiwix-serve on Raspberry Pi (e.g. hotspot)
- [X] Kiwix-serve on Mac
- [ ] pwa.kiwix.org
- [ ] Kiwix JS - Chrome extension
- [ ] Kiwix JS - Firefox extension
- [ ] Kiwix JS - Edge extension
- [ ] Kiwix for Android application
- [ ] Kiwix for MacOS application
- [ ] Kiwix for iOS (iPad/iPhone) application

### Which ZIM versions are impacted?

There is only PROD one version which is impacted

### Details

This is the Zimit ZIM of https://lesfondamentaux.reseau-canope.fr/international

ZIM is significantly broken, everything besides one video is just not working on kiwix-serve.

I recommend to delete the ZIM

I'm not sure the recipe needs to be kept because there is anyway only "showcase" videos on the website, far from the whole content which need the user to be logged-in + subscribed to a paying thing.

**Comment by Popolechien** [comment]
Ok so please delete both zim and recipe.

**Comment by benoit74** [comment]
Done
