### ISSUE TITLE
Delete old lowtechmagazine.com ZIMs

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1047]
We still have two old lowtechmagazine.com_en_all_2023-02.zim and lowtechmagazine.com_en_all_2023-08.zim files, from the old lowtechmagazine.com website.

The website has been deprecated and migrated to solar.lowtechmagazine.com for which we have 

Any concern if I delete these two files from the library now that solar.lowtechmagazine.com is well in place?

**Comment by benoit74** [comment]
And shall I delete the recipe as well?

**Comment by Popolechien** [comment]
I'm all for cleanup and coherent offers.
