### ISSUE TITLE
New request: survivalmanual.github.io

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1049]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://survivalmanual.github.io/home
- License: Public domain (see https://github.com/ligi/SurvivalManual?tab=readme-ov-file#about)
<img width="853" alt="image" src="https://github.com/openzim/zim-requests/assets/7102089/768686e4-a630-488b-9a0b-22d27035199b">
- Desired ZIM Title: Survival Manual
- Desired ZIM Description: Survival manual/guide based on the public domain US Army Survival Field Manual
- Desired ZIM Icon –png (URL or attach one): https://github.com/ligi/SurvivalManual/blob/master/assets/icon_512.png
- Language (ISO 639-3): eng
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/survivalmanual.github_en_all
I'll update the library link once ready

**Comment by benoit74** [comment]
Don't we have duplicates: https://farm.openzim.org/recipes?name=survival ?

**Comment by Popolechien** [comment]
Yes and no: https://farm.openzim.org/recipes/survivalmanual.github_en_all/edit points to a U of Iowa press? Clearly a naming problem there.

**Comment by benoit74** [comment]
I think you used wrong link, https://farm.openzim.org/recipes/survivalmanual.github.io_en_all/config is pointing to U of Iowa press, indeed.

But U of Iowa press is at https://farm.openzim.org/recipes/iastate.pressbooks_en_all/config

I think we should just delete  https://farm.openzim.org/recipes/survivalmanual.github.io_en_all/

@RavanJAltaie do you confirm?

**Comment by Rexadev** [comment]
What is U of Iowa press survivalmanual ? Can't find website or issue for it.

**Comment by Popolechien** [comment]
@Rexadev It obviously is an error in cloning an existing recipe. @RavanJAltaie please delete.

**Comment by RavanJAltaie** [comment]
@benoit74 I confirm, recipe deleted.

**Comment by Rexadev** [comment]
@RavanJAltaie deleted why
