### ISSUE TITLE
Last task of cheatography.com takes too long

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1056]
### Recipe URL

https://farm.openzim.org/recipes/cheatography.com_en_all

### Task URL

https://farm.openzim.org/pipeline/0dcc313a-243c-4431-8839-372500323f28

### Details

Crawler spends ages crawling all member profiles, including many many members which has no contribution and nothing interesting in their profile.

I've reconfigured the recipe to filter out member pages `https://cheatography.com/members/` (and all subpages) and followers `https://cheatography.com/<username>/followers/`. With this I expect we will only scraper members who have submitted something to the site (at least one comment on one cheat sheet). I hope it will make the crawling finish way faster.

**Comment by benoit74** [comment]
Edit: followers where already excluded in fact

**Comment by benoit74** [comment]
Last task succeeded in 5 days, 20 hours, 60 minutes. There are 215265 records. ZIM is viewable at https://dev.library.kiwix.org/viewer#cheatography.com_en_all_2024-06/

From these 215265 records, 69575 could be saved with a fuzzyrule to ignore timestamp in `cheatography.com/scripts/useful.min.js?v=2&q=1719224193` (all requests have a different `q` value but return the same JS, so we duplicated the same JS file 69575 times).

We have something like 68 Youtube videos included, see e.g. https://cheatography.com/sparkledaisy/cheat-sheets/ethics-dsst/. Not sure we really want to grab these videos, good question.

A custom CSS to hide all the things highlighted in grew below would help a lot:

![cheatography com-1-amended](https://github.com/openzim/zim-requests/assets/7102089/41188d2d-3924-4690-b0f8-e495c5018a62)

![cheatography com-2-amended](https://github.com/openzim/zim-requests/assets/7102089/a7f820b0-3b55-4a97-a2ac-41d178079ac0)

![cheatography com-3-amended](https://github.com/openzim/zim-requests/assets/7102089/efd07b23-8f06-4126-b6aa-033138d977d0)

![cheatography com-4-amended](https://github.com/openzim/zim-requests/assets/7102089/eecbd773-6c6a-45f9-b8c0-2eb211d0669b)

Do you see anything else to fix/hide? Nota: I've disabled the recipe for now, I will create the custom CSS once we're on the same page + will probably run next task from artifacts to avoid scraping the website again

**Comment by Popolechien** [comment]
> Do you see anything else to fix/hide?

Nope. LGTM

**Comment by RavanJAltaie** [comment]
I went through the file in Dev library, LGTM as well.

**Comment by benoit74** [comment]
File moved to Prod. Recipe enabled and configured to push to `/zimit` warehouse path. All is fixed now.
