### ISSUE TITLE
gbf.wiki

### ISSUE THREAD

**Issue by ahxxm** [openzim/zim-requests#106]
it's API is https://gbf.wiki/api.php (does not support `visualedit` though)

**Comment by kelson42** [comment]
Problem with that, see https://github.com/openzim/mwoffliner/issues/388

**Comment by kelson42** [comment]
A first version has been done here https://download.kiwix.org/zim/other/granbluefantasy_en_all_2018-09.zim

**Comment by ahxxm** [comment]
thank you!

will cron jobs be arranged for upcoming versions?

**Comment by kelson42** [comment]
@ahxxm yes
