### ISSUE TITLE
Go by Example

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1065]
- Website URL: https://gobyexample.com/
- License: **Creative Commons - Attribution**
- Desired ZIM Title: **Go by example**
- Desired ZIM Description: **a hands-on introduction to Go using annotated example programs**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/gobyexample.com_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
File is ready in the library
https://library.kiwix.org/viewer#gobyexample.com_en_all_2024-08
