### ISSUE TITLE
Learning Statistics with R

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1068]
- Website URL: https://learningstatisticswithr.com/
- License: CC BY-SA 4.0
- Desired ZIM Title: Learning Statistics with R
- Desired ZIM Description: Introductory statistics class turned into a book
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/learningstatisticswithr.com_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
The file is ready at the library 
https://library.kiwix.org/viewer#learningstatisticswithr.com_en_all_2024-08
