### ISSUE TITLE
Statistics: Data Analysis and Modelling

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1069]
- Website URL: https://mspeekenbrink.github.io/sdam-book/
- License: CC BY-SA 4.0
- Desired ZIM Title: Statistics: Data Analysis and Modelling
- Desired ZIM Description: _Data analysis through modelling_
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/mspeekenbrink_en_all
I'll update the library linke once ready
