### ISSUE TITLE
Hitchhiker's Guide to Online Anonymity

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1072]
- Website URL: https://anonymousplanet.org/
- License: **Creative Commons Attribution-NonCommercial**
- Desired ZIM Title: **The Hitchhiker's Guide to Online Anonymity**
- Desired ZIM Description: _A guide to tracking, ID verification, and anonymous online identities_
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
The recipe created
https://farm.openzim.org/recipes/anonymousplanet.org_en_all
I'll update the library link once the file is ready

**Comment by RavanJAltaie** [comment]
The file is ready in the library
https://library.kiwix.org/viewer#anonymousplanet.org_en_all_2024-08

**Comment by Rexadev** [comment]
@RavanJAltaie rename title `anonymousplanet.org The Hitchhiker’s Guide to Online Anonymity`

**Comment by Popolechien** [comment]
@Rexadev Not sure what you are triyng to achieve here - file name nomenclature includes the source URL and is not meant to be a description. 
Description is already [The Guide to online anonymity](https://library.kiwix.org/#lang=eng&q=guide+to+online) (adding `Hitchhiker's` would exceed allowed character length)

**Comment by Rexadev** [comment]
@Popolechien it's easy to remember/distinguish with URL. I suggest `AnonymousPlanet.org Online Anonymity Guide`
