### ISSUE TITLE
Rico's cheatsheets

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1073]
- Website URL: https://devhints.io/
- License: https://kiwix.freshdesk.com/a/tickets/71169
- Desired ZIM Title: Bash scripting cheatsheet
- Desired ZIM Description: _A modest collection of software commands cheatsheets (ruby, bash, vim, etc.)_
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/devhints.io_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
File succeeded
https://dev.library.kiwix.org/viewer#devhints.io_en_all_2024-07
@benoit74 how can I remove the search bar from the file?

**Comment by benoit74** [comment]
With a custom CSS, as usual

**Comment by RavanJAltaie** [comment]
@benoit74 could you please create the custom CSS for this recipe?

**Comment by benoit74** [comment]
CSS done, recipe reconfigured and requested again

**Comment by RavanJAltaie** [comment]
Thanks @benoit74 
The file is ready in the library
https://library.kiwix.org/viewer#devhints.io_en_all_2024-08
