### ISSUE TITLE
VoA Let's Learn English with Anna in Uzbek

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1075]
- Youtube playlist: https://www.youtube.com/watch?v=EuSNoQSftgU&list=PLd9hCvj34W5jP6jkbSMvXGEAvGRpAG2KW&pp=iAQB
- License: **Public domain** 
- Desired ZIM Title: **Keling, Anna bilan ingliz tilini o’rganamiz!**
- Desired ZIM Description: _Dastur 8-12 yoshdagi bolalar uchun mo'ljallangan._
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **uzb**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/voa_uzb_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
File successfully released to the library
https://library.kiwix.org/viewer#voa_uzb_all_2024-07
