### ISSUE TITLE
New request: https://superuser.com/

### ISSUE THREAD

**Issue by vitaly-zdanevich** [openzim/zim-requests#1078]
- Website URL: https://superuser.com/
- License: **CC BY-SA**
- Desired ZIM Title: **superuser.com**
- Desired ZIM Description: **Questions and answers about computers**
- Desired ZIM Icon –png view-source:https://cdn.sstatic.net/Sites/superuser/Img/favicon.ico?v=4852d6fb3f5d
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
Already available: https://library.kiwix.org/#lang=eng&q=super+user
