### ISSUE TITLE
LOST

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1085]
- Website URL: https://lost-stats.github.io/
- License: **GPL 2**
- Desired ZIM Title: **Library of Statistical techniques**
- Desired ZIM Description: _Make it easy to execute statistical techniques in statistical software._
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/lost-stats.github.io_en_all
I'll update the library file once ready

**Comment by RavanJAltaie** [comment]
The file is ready in the library
https://library.kiwix.org/viewer#lost-stats.github.io_en_all_2024-07
