### ISSUE TITLE
Remake a ZIM of Wikipedia for schools

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#109]
With FT index

**Comment by kelson42** [comment]
Done

**Comment by tim-moody** [comment]
@kelson42 thanks for doing this.
could I ask that the name follow the convention that the only hyphen is between year and month so that it is not an exception to parsing the name, so for_schools, not for-schools.

**Comment by kelson42** [comment]
@tim-moody It is the same name pattern like in the past, see https://download.kiwix.org/zim/wikipedia/

**Comment by tim-moody** [comment]
sorry. yes you are right. I guess my parsing only relies on the underscore before year being the last underscore in the name.

btw. I notice there is now a name field in library_zim.xml. Can we rely on this always being there and always having the form kiwix.<zim name without year and month>?

**Comment by kelson42** [comment]
@tim-moody Here is the doc http://www.openzim.org/wiki/Metadata#Keys

**Comment by tim-moody** [comment]
@kelson42 Thanks. At some point I will use name instead of parsing.
