### ISSUE TITLE
VoA Let's Learn English with Anna in Bambara

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#1092]
Youtube playlist: https://www.youtube.com/watch?v=jyl7eHbvTwE&list=PLd9hCvj34W5jnNlm-YM5-FQKzOYFtYEzE
License: Public domain
Desired ZIM Title: Tubabukan kalan ni Anna ye!
Desired ZIM Description: O porogaramu dabɔra denmisɛnw kama minnu si bɛ san 8-12 la.
Desired ZIM Icon –png (URL or attach one): n/a
Language (ISO 639-3): bam
Is this a MediaWiki?: no

**Comment by kelson42** [comment]
@rgaudin Looks good actually!

**Comment by RavanJAltaie** [comment]
File is released successfully to the library
https://library.kiwix.org/viewer#voa_bm_all_2024-07
