### ISSUE TITLE
New request: UpToDate

### ISSUE THREAD

**Issue by BKAZF** [openzim/zim-requests#1100]
- Website URL: https://archive.org/details/Uptodate21.6
- License: Creative Commons
- Desired ZIM Title: UpToDate21.6
- Desired ZIM Description: UpToDate is a an evidence-based medical compendia
- Desired ZIM Icon –png (URL or attach one): https://icon-library.com/images/uptodate-icon/uptodate-icon-3.jpg
- Language (ISO 639-3): eng
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
@benoit74 this request is part of archive.org
which scope will make sure the scraper gets only this targeted content?

**Comment by benoit74** [comment]
Which scraper do you intend to use?

I don't think that zimit is a wise choice. As far as I've understood the request, the user want a ZIM containing the UpToDate medical compendia. And it seems they are already pushing this website to archive.org.

But what needs to be inside the ZIM is what is inside the archive.org archive, i.e content which can be seen at https://ia801309.us.archive.org/view_archive.php?archive=/8/items/Uptodate21.6/Uptodate_21.6.rar

AFAIK, we do not have any scraper capable to do this for now.

My other concern is that it is not clear at all for me why license is Creative Commons. Uptodate seems to be a subscription-based service: https://www.wolterskluwer.com/en/solutions/uptodate. We need to make it clear why this archive can be considered Creative Commons.

**Comment by RavanJAltaie** [comment]
@Popolechien what do you think? shall we tag this issue as "need scrapper"?

**Comment by Popolechien** [comment]
Well I just went to the Up to Date website licensing terms (https://www.wolterskluwer.com/en/know/clinical-effectiveness-terms) and they seem pretty clear: 
_Except as expressly permitted in this Agreement, any copying, distributing, or modifying of the Licensed Content is strictly prohibited._
Why the Internet Archive would flag it as open license I have no idea, but it is not the case.

**Comment by benoit74** [comment]
AFAIK, it is not the Internet Archive which flag files uploads, it is the person / organization who upload the files. And they probably do not have sufficient resources / incentives to check all files uploads, so unless some claims a copyright issue, the uploader decision is displayed.
