### ISSUE TITLE
Unable to get PDF files from Radio Zamaneh

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1105]
The page at https://dev.library.kiwix.org/viewer#radiozamaneh-com_far_all_2024-06/www.radiozamaneh.com/757249/ presents reports for download (see bottom of page), however I'm unable to get them - the links point at https://downloads.zamaneh.com/labor-annual-2022x-fa-pdf directly, which is first blocked and then directly accessed from the live website.

**Comment by benoit74** [comment]
Indeed these documents are not considered as part of the ZIM because we've requested to ZIM the `www.radiozamaneh.com` domain, not the `downloads.zamaneh.com` domain.

Do we agree that we want to add these resources as well?

**Comment by Popolechien** [comment]
Well yes.

**Comment by benoit74** [comment]
Recipe reconfigured with `\/\/(?:www\.radiozsamaneh|downloads\.zamaneh)\.com\/` as include rule.

**Comment by benoit74** [comment]
(and task requested, it will take about 10 days to complete however)

**Comment by benoit74** [comment]
Issue solved
