### ISSUE TITLE
New request: UESP

### ISSUE THREAD

**Issue by xXTheCoolGamerXx** [openzim/zim-requests#1119]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.uesp.net/
- License: **Creative Commons | Public domain | ...**
- Desired ZIM Title: **UESP**
- Desired ZIM Description: **Full zim of the UESP Wiki**
- Desired ZIM Icon –png (URL or attach one): https://images.uesp.net/4/40/NewUESPLogo1.png
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
duplicate of #595
