### ISSUE TITLE
Japanese wikipedia zim file is not working properly with apple iOS/macOS reader

### ISSUE THREAD

**Issue by HiroyasuNishiyama** [openzim/zim-requests#1124]
### ZIM(s) location

https://download.kiwix.org/zim/wikipedia/wikipedia_ja_top_mini_2024-06.zim

### Readers tested

- [ ] Kiwix-serve on iOS (iPad / iPhone)
- [ ] Kiwix-serve on Android (phone or tablet)
- [ ] Kiwix-serve on Windows
- [ ] Kiwix-serve on Linux
- [ ] Kiwix-serve on Raspberry Pi (e.g. hotspot)
- [ ] Kiwix-serve on Mac
- [ ] pwa.kiwix.org
- [ ] Kiwix JS - Chrome extension
- [ ] Kiwix JS - Firefox extension
- [ ] Kiwix JS - Edge extension
- [ ] Kiwix for Android application
- [X] Kiwix for MacOS application
- [X] Kiwix for iOS (iPad/iPhone) application

### Which ZIM versions are impacted?

All PROD versions are impacted

### Details

Search on Japanese wikipedia zim files do not work properly with Kiwix reader for Apple devices.

I have checked with a small test program that simplifies the search behavior of the reader for macOS and suspected that the ZIM files does not have the proper n-gram index.

For example, if you search for the word “東京” (Tokyo in English), libzim calls Xapian to generate n-gram query `Query((東@1 AND 東京@1 AND 京@1))` at [here](https://github.com/openzim/libzim/blob/03fb9c3b5b73a36709e68c952927c4d9ad3e9ef6/src/search.cpp#L160).  A Xapian index database search with this query returns an empty `Xapian::MSet`.  However, a simple query with `Query(東京@1)` will succeed in the search.  
This appears to be due to the fact that the n-gram indexes are not properly generated.

**Comment by kelson42** [comment]
@HiroyasuNishiyama Thank you for Our bug report. We are aware of the problem. We need to support latest version of libzim tomget rid of the bug, see https://github.com/openzim/mwoffliner/issues/1576. Closing as this bug is already tracked there.
