### ISSUE TITLE
noted.lol has something strange !

### ISSUE THREAD

**Issue by hamoudak** [openzim/zim-requests#1127]
I have downloaded two zims of this website:
noted.lol_en_2024-07.zim
noted.lol_en_2024-02.zim 

the first one when I choose any article there is a loading indicator keeps spinning and subscribe area on the right side below is not displaying well. the second one has the same issue but subscribe area is there. is there any fix for this (loading ) or a good version ? its suppose to be a place for  sign up  instead . also  the videos not working for both of them.
<img width="960" alt="spinning" src="https://github.com/user-attachments/assets/efc8963a-8ab0-4d84-a9b6-57ac910fd8bb">

 live-web screenshot

<img width="960" alt="live-web" src="https://github.com/user-attachments/assets/25471ff3-d5c4-414e-89ea-1e91972b2fcc">

**Comment by hamoudak** [comment]
it still needs a custom CSS  the 2024 -10 hasn't updated yet.

**Comment by benoit74** [comment]
Thank you @hamoudak for expressing your interest in seeing this fixed!
I fixed the spinning wheel and removed some "subscribe" and "search" forms.
However I failed to find where we have a problem with video. Can you share a link to an article with a failing video?
I also had to fix the ZIM name which was not matching our convention.
Zimfarm recipe is currently recreating the file in dev.
Thanks!

**Comment by benoit74** [comment]
@hamoudak @Popolechien can you have a look at https://dev.library.kiwix.org/#lang=&q=noted please?

**Comment by hamoudak** [comment]
very good . I've download it once it has been fixed. thank you. it looks better now .

**Comment by Popolechien** [comment]
LGTM, thanks.

**Comment by benoit74** [comment]
I've just requested update of prod file.

**Comment by benoit74** [comment]
Prod file published and OK
