### ISSUE TITLE
What to do with Aimhi Youtube ZIM

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1131]
In https://github.com/openzim/zim-requests/issues/770, we have decided 8 months ago to keep ZIMs of Aimhi channel because content is evergreen and we have their permissions.

Concern is that these ZIMs contains videos encoded in VP8 (old format known to not work on old readers + consume lot of unnecessary space) + they use the old Youtube UI (pre 3.0) and will never get updated.

Should we really continue to serve these files given all these drawbacks?

**Comment by Popolechien** [comment]
I think these should be deprecated, but I would archive rather than delete, if possible.

**Comment by benoit74** [comment]
Sure, I archived them to https://download.kiwix.org/archive/zim/aimhi/
