### ISSUE TITLE
Learning statistics with Python

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1136]
- Website URL: https://ethanweed.github.io/pythonbook
- License: **Creative Commons**
- Desired ZIM Title: **Learning statistics with Python**
- Desired ZIM Description: ** Introductory statistics class turned into a book**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/ethanweed.github.io-pythonbook_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
File is ready in the library
https://library.kiwix.org/viewer#ethanweed_en_all_2024-08
