### ISSUE TITLE
Learning statistics with CogStat

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1137]
- Website URL: https://learningstatisticswithcogstat.com/
- License: **Creative Commons**
- Desired ZIM Title: **Learning statistics with CogStat**
- Desired ZIM Description: **A tutorial for psychology students and other beginners**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/8/89/CogStat_logo.jpg
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/learningstatistics_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/learningstatistics_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#learningstatistics_en_all_2024-08
