### ISSUE TITLE
NHS Medicines A to Z

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1138]
- Website URL: https://www.nhs.uk/medicines
- License: **OGL** (Open Government license)
- Desired ZIM Title: **NHS' Medicines A to Z**
- Desired ZIM Description: **How medicines work, how and when to take them, side effects and common questions**
- Desired ZIM Icon –png (URL or attach one): https://www.nhs.uk/static/nhsuk/img/favicons/favicon-192x192.43924bfe6c7e.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

Pretty much a copy of #323

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/nhs.uk-medicines_en_all
I'll update the library once ready

**Comment by RavanJAltaie** [comment]
The file is ready at the library

**Comment by RavanJAltaie** [comment]
File is ready at the library 
https://library.kiwix.org/viewer#nhs.uk-medicines_en_all_2024-08

**Comment by kelson42** [comment]
Not ready, all top bar links are directly pointing to the online Web site.

**Comment by Popolechien** [comment]
@kelson42 That's because we only scraped a subset of the top-level site I believe.
Either way, I suspect this fits what I described at https://github.com/openzim/zimit/issues/374

**Comment by benoit74** [comment]
Any reason to not hide the top bar then, if it only contains links to non-working parts, I see little reason to keep it? 

Only concern it that we have no more button/link to "home" if we remove the top links, but most readers have one, isn't it?

And since we also scrape the "conditions" part in a different ZIM, do we really need to have two distinct ZIMs ? The medicine part seems to be only few 10s of MB, not something very concerning to justify being put aside, or do I miss something?

**Comment by Popolechien** [comment]
While it may make sense for the NHS website to have both conditions and medicines on a single website, I would argue that the way we present content makes it more approchable if it is one zim = one type of content.

Agree on removing the top bar, though we would lose the NHS branding and that is a bit of a bummer; but I see two home buttons (which don't work as they point to nhs.uk) - the NHS logo and the `Home` hyperlink. 
![Screenshot 2024-09-02 at 10 01 54](https://github.com/user-attachments/assets/f432d2a7-2b0d-4976-a02f-1d0800348730)

**Comment by benoit74** [comment]
OK then let's go for two ZIMS (but ZIM names will have to be fixed, see https://github.com/openzim/zim-requests/issues/1153).

Not sure it is feasible, but what you should request me to do (from my own PoV, I'm clearly a silly person ^^) is to remove following zones in red:

![Screenshot 2024-09-02 at 11 52 40](https://github.com/user-attachments/assets/529de91f-32ab-4cbc-a1f3-9200aad48827)

![image](https://github.com/user-attachments/assets/f000a695-84a5-437b-990d-29ee13fc9d22)

**Comment by RavanJAltaie** [comment]
@benoit74 clearly you can do this for sure (Deleting the upper bar)

**Comment by benoit74** [comment]
Custom CSS created, recipe updated to publish to dev with this custom CSS and requested, let's see.

**Comment by benoit74** [comment]
> clearly you can do this for sure (Deleting the upper bar)

I just realize this is very ambiguous. I proposed to delete far more than the upper bar. Current CSS deletes everything marked in red in my screenshot.

**Comment by Popolechien** [comment]
LGTM ¯\_(ツ)_/¯

**Comment by Popolechien** [comment]
the cookie banner is still here but other than that this looks good to go
![Screenshot 2024-09-17 at 15 23 00](https://github.com/user-attachments/assets/e85c085a-7904-4ac8-a0e0-7e5cb43780c9)
Or was your custom CSS also supposed to take care of the banner?

**Comment by benoit74** [comment]
I never realized there is a cookie banner. I'm a bit sad you did not insisted on this before. It is straightforward to remove for me. CSS updated and recipe launched again.

**Comment by RavanJAltaie** [comment]
@benoit74 the file looks perfect, I've pushed to library.

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#nhs.uk-conditions_en_all_2024-09

**Comment by benoit74** [comment]
Your link is about conditions not medicines, and it is not updated with the proper CSS update to hide cookie banner and irelevant links

**Comment by benoit74** [comment]
File is now really ready in the library: https://library.kiwix.org/viewer#nhs.uk_en_medicines_2024-09
