### ISSUE TITLE
New request: Bobo.id

### ISSUE THREAD

**Issue by anindy139** [openzim/zim-requests#1139]
- Website URL: https://bobo.grid.id/
- License: Creative Commons
- Desired ZIM Title: Bobo.id Teman Bermain dan Belajar
- Desired ZIM Description: Memberikan edukasi dan menginspirasi anak-anak Indonesia.
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/5/59/Logo_Majalah_Bobo.png
- Language (ISO 639-3): id
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
Hi @anindy139 could you please link to the page where is says the content is Creative Commons? All we see so far is _Hak Cipta © Bobo.ID 2024_ at the bottom

**Comment by RavanJAltaie** [comment]
I've found in the website:
Content on www.Bobo.Grid.Id service are not permitted to share or resell this data.
Therefore, the issue is closed.
