### ISSUE TITLE
Biology Courses

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1144]
- Website URL: https://www.youtube.com/@biologycourses
- License: **Creative Commons**
- Desired ZIM Title: **Biology Courses**
- Desired ZIM Description: **Biology teaching resources from De Montfort University and other UK universities**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/biologycourses_en_all
I'll update the library link once ready

**Comment by benoit74** [comment]
Type should be set to `user`. I've updated recipe and requested it.

**Comment by benoit74** [comment]
Please review https://dev.library.kiwix.org/viewer#biologycourses_en_all_2024-09/index.html, it seems OK to go to production from my PoV.

**Comment by Popolechien** [comment]
I've only had a cursory look but that was enough to change the background color to #FFFFFF instead of the current pink^^

**Comment by benoit74** [comment]
@RavanJAltaie why did you moved the file to prod, without even saying something here? The background is still pink, there is a problem here. And the background is also pink in dev, so there is really no reason to have moved the file without this being fixed.

**Comment by benoit74** [comment]
Updated to push to dev again (let's live with prod file, I'm tired of deleting this and this one is not totally bad).

Updated recipe to set secondaryColor (background is secondaryColor, mainColor is used for buttons if I'm not mistaken)

**Comment by benoit74** [comment]
And now it is on a white background: https://dev.library.kiwix.org/viewer#biologycourses_en_all_2024-09/index.html

**Comment by benoit74** [comment]
Publishing again to prod

**Comment by benoit74** [comment]
File is ready in production: https://library.kiwix.org/#lang=eng&q=biology+courses
