### ISSUE TITLE
New request: moneymuseum.by

### ISSUE THREAD

**Issue by vitaly-zdanevich** [openzim/zim-requests#1149]
- Website URL: https://moneymuseum.by
- License: **Public domain and special open license for money and bonds**
- Desired ZIM Title: **moneymuseum.by: belarussian museum of money and bonds**
- Desired ZIM Description: **Thousands of good scans**
- Desired ZIM Icon –png (URL or attach one): view-source:https://moneymuseum.by/local/templates/art_krut/images/favicon.png
- Language (ISO 639-3): **ru**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
© Нацыянальны банк Рэспублікі Беларусь 

Coins may be public domain, not the website design ☹️
