### ISSUE TITLE
Fix nhs.uk ZIM names

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1153]
Current names:
- nhs.uk-conditions_en_all
- nhs.uk-medicines_en_all

Proper names according to our convention (and my PoV):
- nhs.uk_en_conditions
- nhs.uk_en_medicines

@rgaudin do you agree?

Names have to be fixed in recipes, recipe renamed, ZIM moved in library, ...

**Comment by rgaudin** [comment]
Yes, those new ones look good.

**Comment by RavanJAltaie** [comment]
@benoit74 both recipe names and zim file names have been updated.

**Comment by benoit74** [comment]
This will lead to duplicate entries in the catalog/library, we need to rename old ones or delete them

**Comment by RavanJAltaie** [comment]
@benoit74 
These are the files links in the library:
1- https://download.kiwix.org/zim/zimit/nhs.uk-conditions_en_all_2024-08.zim
2- https://download.kiwix.org/zim/zimit/nhs.uk-conditions_en_all_2024-09.zim

**Comment by benoit74** [comment]
Files renamed, thank you
