### ISSUE TITLE
Marine species.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1154]
This recipe https://farm.openzim.org/recipes/marinespecies.org_en was created a while back (and not in response to a ticket here, which is odd), yet fails to produce a working zim: only the front page is scraped, the rest seems to be a database so not sure how to go about it.

**Comment by benoit74** [comment]
I suspect this never worked, `url` is `https://marinespecies.org/` but `include` is set to `^https://edu.gcfglobal.org/en/`, which has nothing to do with original domain. Obviously, this is not going to work.

**Comment by benoit74** [comment]
Original ticket is at https://github.com/openzim/zim-requests/issues/4
