### ISSUE TITLE
remove webster's dictionary

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1155]
for some reason the receipe is set to dev but the (non-working) zim from August is present in the library... 

https://download.kiwix.org/zim/zimit/websters1913_en_all_2024-08.zim

**Comment by benoit74** [comment]
Nothing happens randomly in the Zimfarm, task [05bcd530-48f9-417b-8be8-b16d7d6f4167](https://farm.openzim.org/pipeline/05bcd530-48f9-417b-8be8-b16d7d6f4167) was configured to push files to /zimit (prod): https://api.farm.openzim.org/v1/tasks/05bcd530-48f9-417b-8be8-b16d7d6f4167

![image](https://github.com/user-attachments/assets/1dbc82be-8d31-4bf9-87bb-f64b2ae0a47e)

I will delete the file this morning, no worries.

**Comment by benoit74** [comment]
Done
