### ISSUE TITLE
New request: S2 Underground YT

### ISSUE THREAD

**Issue by S2W1-Wallace** [openzim/zim-requests#1156]
- Website URL: https://youtube.com/@s2underground?si=1EqJThO0GLyWSlNa
- License: Creative Commons 
- Desired ZIM Title: S2 Underground 
- Desired ZIM Description: Video archive of the content created by the S2 Underground project.
-Desired ZIM Icon: https://www.google.com/imgres?imgurl=https%3A%2F%2Fc10.patreonusercontent.com%2F4%2Fpatreon-media%2Fp%2Freward%2F6734479%2Fafff0ba2055c4b24a6c56fe9676be582%2FeyJ3Ijo0MDB9%2F2.JPG%3Ftoken-time%3D2145916800%26token-hash%3DqTGjF4IJwnS1NA26ZMU5FLnoH5N4fdoYIiiwIGXQ9yk%253D&tbnid=kQw1L5BQ3b_ozM&vet=1&imgrefurl=https%3A%2F%2Fwww.patreon.com%2Fuser%3Fu%3D30479515&docid=kKOs-nvmpMHifM&w=400&h=350&itg=1&hl=en-gb&source=sh%2Fx%2Fim%2Fm1%2F3&kgs=c0d9b9d87290b407&shem=abme%2Ctrie
- Language (ISO 639-3): ENG
- Is this a MediaWiki?:  no

**Comment by Popolechien** [comment]
See https://kiwix.freshdesk.com/a/tickets/75577

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/s2underground_en_all/ Let us see what happens.

**Comment by S2W1-Wallace** [comment]
> Created https://farm.openzim.org/recipes/s2underground_en_all/ Let us see what happens.

Hiya seen that the scrape attempt failed, what will be the steps going forward in regards to this??

-S2W1

**Comment by Popolechien** [comment]
Moved from channel to playlists and then got one of the playlist ID wrong 😞

**Comment by benoit74** [comment]
But now it is working ^^

**Comment by S2W1-Wallace** [comment]
> But now it is working ^^

Third times a charm eh? Cheers for the update it's appreciated and thank you to the team for working with us through this.

-S2W1

**Comment by Popolechien** [comment]
@benoit74 Is it me or the file can not be found on dev.library?

**Comment by Popolechien** [comment]
And here we go: https://library.kiwix.org/#lang=eng&q=s2

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#s2underground_en_all_2024-09
