### ISSUE TITLE
Delete recipe mali-pour-les-nuls-mp4

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#1160]
I believe we don't need it anymore now that we have fixed our problems around webm
https://farm.openzim.org/recipes/mali-pour-les-nuls-mp4

**Comment by benoit74** [comment]
@rgaudin @Popolechien do you confirm?

**Comment by Popolechien** [comment]
I believe so, we have https://farm.openzim.org/recipes/mali-pour-les-nuls already pushed to prod

**Comment by benoit74** [comment]
Recipe and ZIM files deleted.

**Comment by rgaudin** [comment]
Don't mention me if you can't wait 1h for a feedback…
