### ISSUE TITLE
Delete NHS conditions zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1163]
Too many videos harvested but not readable. I have put the [corresponding recipe](https://farm.openzim.org/recipes/nhs.uk_en_conditions) on pause.

https://download.kiwix.org/zim/zimit/nhs.uk-conditions_en_all_2024-09.zim
https://download.kiwix.org/zim/zimit/nhs.uk-conditions_en_all_2024-08.zim

**Comment by benoit74** [comment]
Done
