### ISSUE TITLE
Medical sciences stack exchange

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1165]
- Website URL: https://medicalsciences.stackexchange.com/
- License: n/A
- Desired ZIM Title: **Medical sciences**
- Desired ZIM Description: Q&A for professionals in medical and allied health fields
- Desired ZIM Icon –png (URL or attach one): https://cdn.sstatic.net/Sites/medicalsciences/Img/apple-touch-icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by benoit74** [comment]
This is unfortunately not yet dumped by stack exchange. Let's wait for next dump which should arrive soon.

**Comment by benoit74** [comment]
In fact, https://health.stackexchange.com is redirecting to https://medicalsciences.stackexchange.com/, and we already have [health.stackexchange.com](https://farm.openzim.org/recipes/health.stackexchange.com_en)
