### ISSUE TITLE
Why do we have ZIMs in zimfarm drive?

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#1166]
https://drive.farm.openzim.org/custom%20apps/ is full of ZIM files. Why is that?

**Comment by kelson42** [comment]
@rgaudin This is the work of @Popolechien. These ZIM files have to be published in zim/.hidden/custom_apps.

**Comment by Popolechien** [comment]
Yeah IIRC this was meant to be a transitory thing while we tested the CAN custom apps.

**Comment by rgaudin** [comment]
OK then @Popolechien close this issue once you're removed the files

**Comment by Popolechien** [comment]
Done.
