### ISSUE TITLE
ZIM of http://t4-wiki.de

### ISSUE THREAD

**Issue by elkooo** [openzim/zim-requests#117]
Would be nice to be able to fix my car with offline support on my smartphone... ;)
https://www.t4-wiki.de

thanks

**Comment by elkooo** [comment]
ZIM of t4-wiki.de...
now... how can this be achieved?
would really appreciate it! If I knew how to do it, I would... unfortunately I dont... so please help!

**Comment by Popolechien** [comment]
@elkooo basically we're waiting for the release of Mediawiki Offliner 1.8 or 1.9 in a few weeks, and then when someone is ready to take up the ticket we'll create the zim file (no idea when that will happen though).

**Comment by kelson42** [comment]
I should be able to do it from now

**Comment by elkooo** [comment]
wouldbe a blast to see this! let me know when / how to get the zim file!

**Comment by kelson42** [comment]
Recipe create at https://farm.openzim.org/recipes/t4wiki. ZIM should be available in the next days.
