### ISSUE TITLE
New request: Metapedia

### ISSUE THREAD

**Issue by AnonymousGitAcct** [openzim/zim-requests#1171]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.metapedia.org
- License: ** GFDL**
- Desired ZIM Title: **Metapedia**
- Desired ZIM Description: **The alternate encyclopedia**
- Desired ZIM Icon –png (URL or attach one): https://en.metapedia.org/m/images/9/93/Metapedia-logo.jpg
- Language (ISO 639-3): **English**
- Is this a MediaWiki?: **yes**

Note that this is in no way endorsing the material presented. Just want an offline copy to be able to pick apart for personal use.

**Comment by Popolechien** [comment]
Yeah we try to not help propagate negationnist content, sorry.
