### ISSUE TITLE
First set of icons for DevDocs ZIM

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1179]
We need a first set of icons for DevDocs ZIMs. Mostly the same as online at https://devdocs.io

The icon must be 48x48, PNG, with transparent background.

The icon must be free to use and distribute, or we must have permission from right holder.

The first set we need is for (let's name these "languages"):
- cpp
- lua
- r
- vue

See https://github.com/freeCodeCamp/devdocs/tree/main/public/icons/docs for current icons used by DevDocs as inspiration. Their icons are only 16x16 and some are outdated, but the "SOURCE" file inside each folder helps to check we are on the right project.

I think we should use the same approach:
- one folder per "language"
- inside the folder, the icon + a text file named "SOURCE" with details about where the file comes from / details about permission to use if needed (we probably should have a mail about this permission with contact@kiwix.org in CC)

We need these icons by the end of the month.

Any question?

**Comment by siemsie** [comment]
Hi @benoit74. You'll find the first 4 in the google folder. I question the use of text at that size, and found the Lua logo used without the text, so I put two options. I'll let you choose. https://drive.google.com/open?id=137DCcWtfp72UpPeRPzdhCgoz8yDD0mTt&usp=drive_fs

**Comment by benoit74** [comment]
Thank you!

For the record, I've uploaded them to https://drive.farm.openzim.org/devdocs/ where Zimfarm will be able to use them directly.
