### ISSUE TITLE
cest-pas-sorcier_fr_astronomie is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1184]
### Recipe URL

https://farm.openzim.org/recipes/cest-pas-sorcier_fr_astronomie

### Last log lines

[youtube2zim::2024-10-12 14:48:02,499] INFO:compute playlists list to retrieve
[youtube2zim::2024-10-12 14:48:02,500] DEBUG:query youtube-api for Ofa1OV6d5xc by forHandle
[youtube2zim::2024-10-12 14:48:02,543] WARNING:Failed to find Ofa1OV6d5xc by forHandle
[youtube2zim::2024-10-12 14:48:02,543] DEBUG:query youtube-api for Ofa1OV6d5xc by id
[youtube2zim::2024-10-12 14:48:02,585] WARNING:Failed to find Ofa1OV6d5xc by id
[youtube2zim::2024-10-12 14:48:02,585] DEBUG:query youtube-api for Ofa1OV6d5xc by forUsername
[youtube2zim::2024-10-12 14:48:02,632] WARNING:Failed to find Ofa1OV6d5xc by forUsername
[youtube2zim::2024-10-12 14:48:02,633] ERROR:Interrupting process due to error: Impossible to find Ofa1OV6d5xc, check for typos
[youtube2zim::2024-10-12 14:48:02,633] ERROR:Impossible to find Ofa1OV6d5xc, check for typos
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/youtube2zim/scraper.py", line 326, in run
    self.extract_playlists()
  File "/usr/local/lib/python3.12/site-packages/youtube2zim/scraper.py", line 592, in extract_playlists
    ) = extract_playlists_details_from(self.collection_type, self.youtube_id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/youtube2zim/youtube.py", line 328, in extract_playlists_details_from
    channel_json = get_channel_json(youtube_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/youtube2zim/youtube.py", line 108, in get_channel_json
    raise Exception(f"Impossible to find {channel_id}, check for typos")
Exception: Impossible to find Ofa1OV6d5xc, check for typos
[youtube2zim::2024-10-12 14:48:02,637] INFO:removing temp folder

### How many times the recipe failed in a row?

Many

### How many ZIM have been produced before failure?

Zero

### Which action did you undertake so far?

I have disabled the recipe for now

### What's next?

I don't know

### More details

I'm a bit surprised about the fact we do not have much history for this recipe.

@kelson42 it looks like you're the one who cancelled / requested it. Is it a new recipe you're trying to setup?

**Comment by kelson42** [comment]
> kelson42 it looks like you're the one who cancelled / requested it. Is it a new recipe you're trying to setup?

Yes, see #1183

**Comment by benoit74** [comment]
Oups, sorry, this is a duplicate then
