### ISSUE TITLE
Zim of plant pest wiki

### ISSUE THREAD

**Issue by samuk** [openzim/zim-requests#119]
https://wiki.pestinfo.org/wiki/Main_Page

Useful for farmers/growers worldwide.

**Comment by kelson42** [comment]
Recipe is here https://farm.openzim.org/recipes/pestinfo

**Comment by samuk** [comment]
Great thanks :) will try it out.

**Comment by kelson42** [comment]
@samuk Unfortunately, the API returns DB error, I had to deactivate the recipe, see https://farm.openzim.org/pipeline/7ec6124057047f55f610bff5/debug
