### ISSUE TITLE
New request: majles.alukah.net

### ISSUE THREAD

**Issue by hamoudak** [openzim/zim-requests#1192]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://majles.alukah.net/
- License: Powered by vBulletin
  Copyright © 2024 vBulletin Solutions، Inc. All rights reserved.
- Desired ZIM Title: المجلس العلمي - الألوكة
- Desired ZIM Description:  نشر العلم والمعرفة على منهج أهل السنة والجماعة
- Desired ZIM Icon –png : https://i.ibb.co/vx3Gcgg/unnamed.png 
- https://majles.alukah.net/favicon.ico
- Language (ISO 639-3): ara
- Is this a MediaWiki?: no

* Notes: I need it with " novid", and hiding all things related to : follow us on twitter etc, enhanced by google search, ads, and date.
also the links within the black bar except that redirect to the main page. If advanced search box not working in zim you can remove it,
otherwise keep it. anyway thank you.

**Comment by Popolechien** [comment]
@hamoudak it does explicitely say and yourself wrote: _© 2024 vBulletin Solutions، Inc. All rights reserved_

Is there any reason to believe we have permission to copy?

**Comment by hamoudak** [comment]
hii, I see a message above the date box  simply says , attention , all posted materials on the domain, their owners agreed to be published, and if any have any complaint about property rights, contact us on : ipr@alukah.net

I think this is a good way to copy, and besides this forum was archived before over the web as here for example : https://old.shamela.ws/index.php/book/29974 . what do you think?

**Comment by Popolechien** [comment]
Yeah, the good old "What's yours is mine, but what is mine is mine". I'm afraid it is not good enough, sorry :-/

I'll close the issue until we can figure out otherwise.

**Comment by hamoudak** [comment]
am gonna try to take their permission, I hope so. I didn't mean to do the crawl but I was consulting you.

**Comment by Popolechien** [comment]
@hamoudak If you reach out (and they respond) please copy contact **at** kiwix.org so we can file the permission.

**Comment by hamoudak** [comment]
no response from them yet.  I have sent a message from contact us on the main domain about crawling the forum.
https://www.alukah.net/contactus.aspx
