### ISSUE TITLE
zim of Encyclopedia of Life

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#12]
_From @amirh123123 on May 2, 2018 15:45_

hi please make zim file for Encyclopedia of Life
eol.org

_Copied from original issue: openzim/mwoffliner#330_

**Comment by kelson42** [comment]
_From @darkenvy on May 11, 2018 18:43_

Pleas see https://github.com/openzim/mwoffliner/issues/331 for the same answer :)

**Comment by kelson42** [comment]
_From @darkenvy on May 29, 2018 16:13_

> " In short, all information you share with EOL must also be shared with the rest of the world under at least one of the creative commons licenses that allow re-use."

Turns out to be CC and okay for reuse. This site is heavily fragmented. Is there a particular part of the site you are interested in? Like the education section located at http://eol.org/discover ? Are you still interested in this?

_discliamer: If Im able to rip this, its something I would be doing myself and not something the openzim team would be expected to do._

**Comment by RavanJAltaie** [comment]
@amirh123123 We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
