### ISSUE TITLE
Zim Equity unbound course - digital literacies with an equity and intercultural learning focus,

### ISSUE THREAD

**Issue by samuk** [openzim/zim-requests#120]
http://unboundeq.creativitycourse.org/category/overview/

Equity Unbound is an emergent, collaborative curriculum which aims to create equity-focused, open, connected, intercultural learning experiences across classes, countries and contexts.

**Comment by kelson42** [comment]
@samuk Do you know a technical solution to get that content statically on the hard disk?

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/unboundeq.creativitycourse.org_en
