### ISSUE TITLE
CDC traveler's health is not working properly

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1206]
### ZIM(s) location

https://library.kiwix.org/viewer#wwwnc.cdc.gov_en_all

### Recipe(s) URL

https://farm.openzim.org/recipes/wwwnc.cdc.gov_en_all

### Readers tested

- [ ] Kiwix-serve on iOS (iPad / iPhone)
- [x] Kiwix-serve on Android (phone or tablet)
- [ ] Kiwix-serve on Windows
- [ ] Kiwix-serve on Linux
- [ ] Kiwix-serve on Raspberry Pi (e.g. hotspot)
- [ ] Kiwix-serve on Mac
- [ ] pwa.kiwix.org
- [ ] Kiwix JS - Chrome extension
- [ ] Kiwix JS - Firefox extension
- [ ] Kiwix JS - Edge extension
- [ ] Kiwix for Android application
- [ ] Kiwix for MacOS application
- [ ] Kiwix for iOS (iPad/iPhone) application

### Which ZIM versions are impacted?

All PROD versions are impacted

### Details

The `select destination` pull-down menu returns an error (Kiwix server), but going to `View all destinations` and then pick up which ever country works (meaning that the pages are scraped correctly but the pulldown fails for some reason.
On Android the `Go` button simply does not respond.

**Comment by benoit74** [comment]
The pulldown cannot be fixed easily (warc2zim limitation probably not going to be solved anywhere in the near future). Only solution is to hide the pulldown with CSS and rely on the `View all destinations` buttons. OK for you?

**Comment by Popolechien** [comment]
Yup, LGTM. Thanks.

**Comment by benoit74** [comment]
And we need to remove the top search box as well.

**Comment by benoit74** [comment]
CSS configured, recipe requested in dev: https://farm.openzim.org/pipeline/834b1427-0b0a-4271-832f-c6cf080895a5

**Comment by benoit74** [comment]
Please have a look at https://dev.library.kiwix.org/#lang=&q=health+travel

It is not absolutely perfect, but at least there is no more "visible bug" AFAIK

**Comment by Popolechien** [comment]
Perfect, thanks.

**Comment by benoit74** [comment]
Please restart the scraper, it is not a big recipe.

**Comment by Popolechien** [comment]
Done.
