### ISSUE TITLE
Practical Action - Appropriate tech documents

### ISSUE THREAD

**Issue by samuk** [openzim/zim-requests#121]
https://answers.practicalaction.org/

all creative commons

We believe that there is enough knowledge in the world to have a significant impact on reducing global poverty. The problem is that the knowledge is not always in the right place or the right format. It can be inaccessible to people who don’t have a mobile phone or internet connection. It is also inaccessible if people don’t know it exists.

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by samuk** [comment]
However the file linked from this page

https://farm.openzim.org/pipeline/5b3a2c961f6cee6427d42936

404's https://mirror.download.kiwix.org/zim/zimit/Practical%20Action_2022-12.zim

**Comment by Popolechien** [comment]
Can't see the files in the library either.

**Comment by RavanJAltaie** [comment]
Updated recipe
https://farm.openzim.org/recipes/practical_action_en_all

**Comment by Popolechien** [comment]
@RavanJAltaie File does not show in library.kiwix.org - please open a ticket in https://github.com/openzim/zimfarm/issues/ when that is the case.
