### ISSUE TITLE
Remove Physicell wiki

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1210]
The Physicell.org website has been revamped and not relying on a wiki anymore. 

Irrespective of this, the zim we currently host also has its issues, with [no available internal links to start with](https://library.kiwix.org/viewer#physicell_en_all_maxi).

I suggest removing https://download.kiwix.org/zim/other/physicell_en_all_maxi_2023-01.zim and https://download.kiwix.org/zim/other/physicell_en_all_maxi_2022-12.zim

and start afresh using zimit (not sure in that regard if https://farm.openzim.org/recipes/physicell should also be deleted outright.

**Comment by benoit74** [comment]
Files deleted. 

Regarding the fact that we need to switch to zimit, I don't get the idea. Original request https://github.com/openzim/zim-requests/issues/252 was about ZIMing the wiki which seemed to be a user manual. I don't find it anymore at http://physicell.org/, and it looks to me there is no really valuable information on this website for offline usage. There is just a bunch of info page on the project, links to other websites (sourceforge, ...), and downloads of the software. What would we really like to ZIM?

**Comment by benoit74** [comment]
I've deleted the recipe
