### ISSUE TITLE
New request: www.explainthatstuff.com/

### ISSUE THREAD

**Issue by julius-gun** [openzim/zim-requests#1218]
Hi, please get this

- Website URL: https://www.explainthatstuff.com/
- License: **Creative Commons** (do NOT request copyrighted material)
- Desired ZIM Title: explainthatstuff
- Desired ZIM Description: Explain that Stuff is an online book written by science writer Chris Woodford. It includes over 400 easy-to-understand articles.
- Desired ZIM Icon –png (URL or attach one): https://www.explainthatstuff.com/favicon.ico
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: ** no**
Thanks.

**Comment by Popolechien** [comment]
Hello @julius-gun I see their copyright notice is pretty strongly worded and not CC at all AFAICT:

> Articles from this website are registered at the US Copyright Office. Copying or otherwise using registered works without permission, removing this or other copyright notices, and/or infringing related rights could make you liable to severe civil or criminal penalties.
> Text on this page copyright © Chris Woodford 2006, 2024. Text elsewhere on this website is copyright © Chris Woodford with copyright dates as noted in each individual article. All rights reserved. [Full copyright notice and terms of use](https://www.explainthatstuff.com/copyright-and-legal-notices.html).

They do have a contact form, feel free to reach out and explain how Kiwix works (you can also cc hello@kiwix.org ). I will close this request for the time being.
