### ISSUE TITLE
FootballDatabse pages always display a cookie banner

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#1219]
### ZIM(s) location

https://library.kiwix.org/viewer#footballdatabase.com_en_all_2024-11

### Recipe(s) URL

https://farm.openzim.org/recipes/footballdatabase.com_en

### Readers tested

- [ ] Kiwix-serve on iOS (iPad / iPhone)
- [ ] Kiwix-serve on Android (phone or tablet)
- [ ] Kiwix-serve on Windows
- [ ] Kiwix-serve on Linux
- [ ] Kiwix-serve on Raspberry Pi (e.g. hotspot)
- [ ] Kiwix-serve on Mac
- [ ] pwa.kiwix.org
- [ ] Kiwix JS - Chrome extension
- [ ] Kiwix JS - Firefox extension
- [ ] Kiwix JS - Edge extension
- [ ] Kiwix for Android application
- [ ] Kiwix for MacOS application
- [x] Kiwix for iOS (iPad/iPhone) application

### Which ZIM versions are impacted?

All PROD versions are impacted

### Details

See screenshot
![Image](https://github.com/user-attachments/assets/7cedb808-0f9a-483d-92ed-ecafa583199f)

It should not display it at all

In addition, searchbox should be hidden

**Comment by benoit74** [comment]
CSS configured, running in dev to confirm

**Comment by benoit74** [comment]
@Popolechien @kelson42 can you please have a look at https://dev.library.kiwix.org/viewer#footballdatabase.com_en_all_2024-11/footballdatabase.com/ and confirm I did not missed something?

**Comment by kelson42** [comment]
@benoit74 LGTM! Thank you!

**Comment by Popolechien** [comment]
LGTM too, thanks.

**Comment by benoit74** [comment]
Requested in prod

**Comment by kelson42** [comment]
I don't get it, but somehow on ios I keep seeing the cookie banner!
![Image](https://github.com/user-attachments/assets/0a884fe3-07c0-46e4-bf52-3c1d5ec6be75)

**Comment by benoit74** [comment]
Explanation is simple: not sufficiently tested in DEV, one CSS rule was missing (I hide the cookie banner, but there is also a cookie window on smaller screen sizes). CSS updated and requested again (directly in prod).

**Comment by benoit74** [comment]
Fixed.
