### ISSUE TITLE
Zim of Modern Philosophy

### ISSUE THREAD

**Issue by samuk** [openzim/zim-requests#122]
https://opentextbc.ca/modernphilosophy/

CC by A

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/modern_philosophy

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by samuk** [comment]
Nice, so this will show up as a download option in Kiwix on Android?

**Comment by Popolechien** [comment]
@samuk There seems to be an issue with several files that are not moved out of quarantine: I do not see it listed in the library (even though the zimfarm confirmed a while back that the file had been created)
