### ISSUE TITLE
Remove Epicurieux zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1227]
https://download.kiwix.org/zim/videos/jamy_fr_all_2024-09.zim
https://download.kiwix.org/zim/videos/jamy_fr_all_2024-07.zim

Zimfarm recipe has been deleted already.

**Comment by benoit74** [comment]
To clarify why: after discussion with Popolechien and Kelson, it became clear that:
- the content is copyrighted
- we do not have permission to reproduce
- we have no corresponding ZIM request
- noones recall why the Zimfarm recipe has been created and the ZIM pushed to production

I've marked the file for deletion, they will be gone from the library soon. I'll will really delete them afterwards once I'm sure they are not used in the imager.

**Comment by benoit74** [comment]
Files deleted from storage.
