### ISSUE TITLE
New request: Wikipedia Simplified Chinese

### ISSUE THREAD

**Issue by tedaz** [openzim/zim-requests#1228]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://zh.wikipedia.org/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: Wikipedia Simplified Chinese 
- Desired ZIM Description: 海纳百川，有容乃大
- Desired ZIM Icon –png (URL or attach one): https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5
- Language (ISO 639-3): zho
- Is this a MediaWiki?: yes 

Please create with the latest libzim, as there previous zim contains bug, refer https://github.com/openzim/libzim/issues/794

**Comment by kelson42** [comment]
duplicate
