### ISSUE TITLE
Zim of offline android apps

### ISSUE THREAD

**Issue by samuk** [openzim/zim-requests#125]
I'm interested in a Zim file of this page: http://rosettaphone.org/apps/

Where the .apk links link to a .apk resource within a /app folder of Zim file itself

The Zim would be a self-contained way to install any of those apps. You would click on the .apk link, and the download would start from whatever computer is hosting the Zim, to whatever computer is accessing the web frontend.

I'll have a go at this one myself when I get a chance (As with the other ticket's I've opened)

**Comment by kelson42** [comment]
@samuk As the page is really simple, the best is to use a standard web scrapping software and then use http://zip2zim.openzim.org

**Comment by RavanJAltaie** [comment]
@kelson42 shall we close this ticket?
