### ISSUE TITLE
EPIC: New selections based on improved layout

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#127]
Here are subsets to generate with the layout described in [#449](https://github.com/openzim/mwoffliner/issues/449)
They should be generated in languages that are among the top ten most used amongst Kiwix downloads (when that makes sense - no point making a cricket zim in French or German):
EN/ES/PT/AR/FR/DE/ZH/HI/RU/TR

Here are the subsets to generate (based on wikiprojects available on enwp):
* **Football by Wikipedia** 
Description: A subset of Wikipedia articles dedicated to football. https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Football
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://en.wikipedia.org/wiki/File:Soccer_ball.svg

* **Basketball** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Basketball 
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Basketball.svg

* **History** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_History
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:P_history.png

* **Geography** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Geography 
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Globe.svg

* **Maths** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Mathematics **This is an update of an existing zim**
Languages EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Hypercube.svg

* **Physics** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Physics **This is an update of an existing zim**
Languages EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Stylised_atom_with_three_Bohr_model_orbits_and_stylised_nucleus.svg 

* **Chemistry** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Chemistry **This is an update of an existing zim**
Languages EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Gnome-applications-science.svg

* **Movies** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film AND https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Actors_and_Filmmakers
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Biofilm.png

* **Musicians** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Music AND https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Musicians
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Gibson-sg.svg

* **Comics** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Comics 
Languages: EN/FR/ES/DE
Image: https://commons.wikimedia.org/wiki/File:Speech_balloon.svg

* **Bollywood** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Indian_cinema_task_force 
Languages EN/HI **This is an update of an existing zim**
https://commons.wikimedia.org/wiki/File:Bollywoodbarnstar.JPG

* **Cricket** https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Cricket 
Languages: EN/HI
Image: https://commons.wikimedia.org/wiki/File:Cricketball.svg

**Comment by kelson42** [comment]
For non EN languages, I need first to do https://github.com/openzim/wp1_selection_tools/issues/11

**Comment by kelson42** [comment]
@Popolechien I have published football, basketball and history. Please have a look to the ZIM files... I have already discovered a problem, see https://github.com/openzim/wp1_selection_tools/issues/13

**Comment by Popolechien** [comment]
Honestly it looks pretty good to me, except that the selection algortihm picked some funny winners, e.g. Drew Carey in the Football selection - the guy merely appeared in a US TV show and as such was selected into the Wikiproject football. Likewise, I'm suprised to see the Peruvian National Team on the selection/landing page. Does that mean that these two articles are overall near the top100 most read, or too much weight has been given to their GA/FA status?

**Comment by amirh123123** [comment]
i download wikipedia football but dont have all articles about football example leagues not article for bundesliga or not all teams example fc bayern munikh and not all players example neymar and not football seasons example 2017 18 bayern munikh season and not all national teams example mexico national football team and not all world cup example not 2018 fifa world cup

**Comment by kelson42** [comment]
@amirh123123 yes, this is a bug I have already fixed, I will generate a new ZIM file in the next days.

**Comment by Popolechien** [comment]
Here are the (Google-) translated titles for
**Football by Wikipedia**
A selection of Wikipedia articles dedicated to football. 

AR (hopefully this one we can write right to left?)
كرة القدم من ويكيبيديا
مجموعة مختارة من مقالات ويكيبيديا المخصصة لكرة القدم.
DE
Fußball von Wikipedia
Eine Auswahl von Wikipedia-Artikeln zum Thema Fußball.
ES
Fútbol por Wikipedia
Una selección de artículos de Wikipedia dedicados al fútbol.
FR
Football par Wikipedia
Une sélection d'articles de Wikipedia consacrés au football.
HI
फुटबॉल विकिपीडिया द्वारा
फुटबॉल को समर्पित विकिपीडिया लेखों का चयन।
PT
Futebol pela Wikipédia
Uma seleção de artigos da Wikipedia dedicados ao futebol.
RU
Футбол от Википедии
Подборка статей из Википедии, посвященных футболу.
TR
Wikipedia'dan Futbol
Futbol adanmış bir Vikipedi makaleler.
ZH
维基百科的足球
一系列致力于足球的维基百科文章。

**Comment by Popolechien** [comment]
Basketball
A selection of Wikipedia articles on Basketball 

AR
كرة السلة من ويكيبيديا
مجموعة مختارة من مقالات ويكيبيديا المخصصة لكرة السلة.
DE
Basketball von Wikipedia
Eine Auswahl von Wikipedia-Artikeln zum Thema Basketball.
ES
Baloncesto por Wikipedia
Una selección de artículos de Wikipedia dedicados al baloncesto.
FR
Basketball par Wikipedia
Une sélection d'articles de Wikipedia sur le basketball.
HI
विकिपीडिया द्वारा बास्केटबॉल
बास्केटबॉल के लिए समर्पित विकिपीडिया लेखों का चयन।
PT
Basquete pela Wikipédia
Uma seleção de artigos da Wikipedia dedicados ao basquete.
RU
Баскетбол от Википедии
Подборка статей из Википедии, посвященных баскетболу.
TR
Basketbol Wikipedia tarafından
Basketbol adanmış bir Wikipedia makalesi.
ZH
维基百科的篮球
一系列致力于篮球的维基百科文章。

**Comment by Popolechien** [comment]
History
A selection of Wikipedia articles on History EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU

AR
تاريخ ويكيبيديا
مجموعة مختارة من مقالات ويكيبيديا المخصصة للتاريخ.
DE
Geschichte von Wikipedia
Eine Auswahl von Wikipedia-Artikeln zur Geschichte.
ES
Historia por Wikipedia
Una selección de artículos de Wikipedia dedicados a la historia.
FR
Histoire par Wikipedia
Une sélection d'articles de Wikipedia consacrés à l'histoire.
HI
विकिपीडिया द्वारा इतिहास
इतिहास के लिए समर्पित विकिपीडिया लेखों का चयन।
PT
História pela Wikipedia
Uma seleção de artigos da Wikipedia dedicados à História.
RU
История от Википедии
Подборка статей из Википедии, посвященных истории.
TR
Wikipedia'dan Tarihçe
Geçmişe adanmış bir Vikipedi makalesi.
ZH
维基百科的历史
一系列致力于历史的维基百科文章。

**Comment by Popolechien** [comment]
So here is an XML file with all translations
https://docs.google.com/spreadsheets/d/1kYGoLkfJ8TCaxqQCyyHae8PD6ZCO8sdZ4ZwIL5aAfc0/edit?usp=sharing

**Comment by kelson42** [comment]
@Popolechien For "Musicians" and "Movies" selections, this is the intersection of the two categories, or the union?

**Comment by Popolechien** [comment]
@Kelson42 Union.

**Comment by kelson42** [comment]
@Popolechien Wikproject "Musicians" is going to be quite complex, are there is basically no category gathering all articles about Music.

**Comment by Popolechien** [comment]
Then skip it

**Comment by rgaudin** [comment]
Just to confirm that we'll drop Musicians as there is no source ATM.

Also, for **Bollywood**, there is no *Project* nor *Custom* that matches the selection in the WP1 folder.
@kelson42, did I miss something?

FYI, I changed the bollywood icon (jpg in the issue) to its png counterpart (present on commons with background transparency).

**Comment by kelson42** [comment]
@rgaudin @Popolechien I have moved the musician stuff to #151.
@rgaudin The Bollywood ZIM should be continued but based on https://download.kiwix.org/wp1/enwiki/projects/Indian_cinema (and local translations)

**Comment by rgaudin** [comment]
Thanks.

Here are the expected (generated) output names:

```
wikipedia_en_football_nopic_2019-05.zim
wikipedia_en_football_novid_2019-05.zim
wikipedia_en_basketball_nopic_2019-05.zim
wikipedia_en_basketball_novid_2019-05.zim
wikipedia_en_history_nopic_2019-05.zim
wikipedia_en_history_novid_2019-05.zim
wikipedia_en_geography_nopic_2019-05.zim
wikipedia_en_geography_novid_2019-05.zim
wikipedia_en_mathematics_nopic_2019-05.zim
wikipedia_en_mathematics_novid_2019-05.zim
wikipedia_en_physics_nopic_2019-05.zim
wikipedia_en_physics_novid_2019-05.zim
wikipedia_en_chemistry_nopic_2019-05.zim
wikipedia_en_chemistry_novid_2019-05.zim
wikipedia_en_movies_nopic_2019-05.zim
wikipedia_en_movies_novid_2019-05.zim
wikipedia_en_comics_nopic_2019-05.zim
wikipedia_en_comics_novid_2019-05.zim
wikipedia_en_indian_cinema_nopic_2019-05.zim
wikipedia_en_indian_cinema_novid_2019-05.zim
wikipedia_en_cricket_nopic_2019-05.zim
wikipedia_en_cricket_novid_2019-05.zim
```

The project (wikipedia) is retrieved from the Wiki domain and the topic is from the articlesList filename.
Customizing the filename (with `--filenamePrefix` would allow better customization but we'll loose the `_novid` and `_nopic` part).

So @kelson42, if you want to have a nice `bollywood` filename, you could copy the `Indian_cinema` project articles list to the customs folder with a `bollywood` name.

**Comment by kelson42** [comment]
@Popolechien Is that a problem if we rename Bollywood to "Indian Cinema" ?

**Comment by Popolechien** [comment]
Nope.

**Comment by Popolechien** [comment]
No, it is not.

**Comment by kelson42** [comment]
@rgaudin Good to me

**Comment by rgaudin** [comment]
OK.

**Comment by rgaudin** [comment]
All above-mentioned selections scheduled.

See at the bottom of https://farm.openzim.org/schedules

**Comment by kelson42** [comment]
@rgaudin Really great, all titles are like in the google doc (I think I can not see that in the schedule through the web)?

**Comment by rgaudin** [comment]
You can but you have to scroll all the way to the bottom.
beware it's a rolling scroll so you have to do it a few times.

**Comment by kelson42** [comment]
@rgaudin even so, customtitle and customDescription are not visible to me.

**Comment by rgaudin** [comment]
yes you can only see it through the API or in the task once it is created
