### ISSUE TITLE
Consider scrapping https://libretexts.org/

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#131]

**Comment by kelson42** [comment]
There is a PDF generator in Node, this can be helpful if we want to write in in JS:
https://github.com/LibreTexts/Libretext/blob/master/nodePrint/nodePrint.js

**Comment by kelson42** [comment]
Comment from Henry (Libretexts)

>  1. We have some small pieces of helper code already written in
>     Javascript to get page information. Since these interact with the
>     Mindtouch/LibreTexts REST API, these should be very easy to
>     replicate in other languages if needed.>      1. If you want to use Javascript/NodeJS, there is plenty of code we
>         can pull from our PDF generator:
>      2. https://github.com/LibreTexts/Libretext/blob/master/nodePrint/nodePrint.js
>  2. For scraping, the two approaches would be to use the API versus a
>     traditional web scraper. If all you need is the webpage content +
>     attachments, I’m not sure you even need to tap into the API.
>      1. In the past, I have utilized the page modified date for
>         efficiency for our PDF generator. However, for scraping I’m not
>         sure if this is needed as downloading the content is much more
>         computationally cheap than rendering out the content.
>  3. For Kolibri, we were pursuing their scraper since (a) someone at
>     learning equality had already built it and (b) a graduate student of
>     Robert Belford is using Kolibri + RPi for their thesis. We’ve been
>     having problems solving the dependency chain to get the code
>     running. At this point, I believe the two efforts will remain separate.
>  4. For the server, I wanted to let you know that we are currently using
>     DigitalOcean droplets for our auxiliary computing purposes. These
>     are fixed-cost servers with free ingress, but their SSD storage
>     prices are relatively high. They also have Kubernetes and FaaS on
>     Kubernetes. I don’t know if you have a preference for self-hosting
>     on one of your servers or not, but I just wanted to let you know
>     what we are doing already for our other mini-projects.

**Comment by kelson42** [comment]
First version will be done using https://github.com/openzim/kolibri2zim, currently being developed.

**Comment by kelson42** [comment]
@rgaudin @mgautierfr @Miniland1333 Considering that we have a version 1.0 working, could we close this ticket?

**Comment by Miniland1333** [comment]
Would you be able to provide some links to commits/PRs/branches that relate to this version 1.0? I've been out of the loop so I haven't kept track of your progress.

**Comment by rgaudin** [comment]
We've fixed the [sushi chef repo](https://github.com/openzim/librechef/) creating the Kolibri channel and created a first version of the https://github.com/openzim/kolibri2zim tool to produce a Zim off a Kolibri channel.

I believe we've produced a first ZIM file based on Engineering to have a basis for feedback and directions. @Popolechien has this been shared?

**Comment by RavanJAltaie** [comment]
@Popolechien what's the update for this issue? shall we close it?

**Comment by Popolechien** [comment]
@RavanJAltaie Yes, we'll reopen if a potential for partnership materializes again.
