### ISSUE TITLE
Make zim of AudioBooks

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#137]
https://www.youtube.com/channel/UC2ys611IBQH6GiyrCsdT_hQ/playlists
All audios and books are Public domain; a book is divided into chapters that are assembled into a playlist, which is neat.

Ideally, next to a massive zim file bundling all playlists together we could also have smaller, individual playlists scrapped an put into an "AudioBooks" directory on [download.kiwix.org/zim](https://download.kiwix.org/zim)

Bonus: sort playlists by language (most are in English but there's a couple of Spanish, German and Italian books)

**Comment by Popolechien** [comment]
Added/created the ``Youtube`` label as we already have a scraper for that one.

**Comment by kelson42** [comment]
@Popolechien What should we do with that ticket? Configure it in the zimfarm?

**Comment by Popolechien** [comment]
No, I don't think it is bound to expand as a playlist, and I would be suprised if they re-recorded the books. If the whole playlist has been zimmed, then we can close the ticket.

**Comment by kelson42** [comment]
@Popolechien AFAIK there is no zim, otherwise we would have close that ticket already.

**Comment by kelson42** [comment]
@Popolechien I have created one here https://farm.openzim.org/recipes/los_miserables_audiobook... but we have dozens of them... Not sure exactly how I should create all the recipes. @rgaudin An idea?

**Comment by rgaudin** [comment]
Please explain clearly what you expect from me here.

**Comment by kelson42** [comment]
@rgaudin Do you know an easy way to create all the necessary recipes?

**Comment by rgaudin** [comment]
we could certainly script it but the problem would be to find out the langue for each playlist. maybe we should do it in 2 steps : first gen a CSV with the list ID and titles for easy language assignation and then create the recipes.

this might require the creation of a zimfarm tag...

**Comment by RavanJAltaie** [comment]
@Popolechien Let's please discuss this to know the next steps.
