### ISSUE TITLE
Wikibooks space not read on xx.wikibooks.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#139]
As most books seem stored on "bookshelfs" in the wikibooks: namespace, we're pretty much left with a not super useful landing page where nothing much can be accessed (unless one know already which books are out there).
https://en.wikibooks.org/wiki/
http://library.kiwix.org/wikibooks_en_all_novid_2017-07/

**Comment by automactic** [comment]
so the change will be: for all wikibooks schedules except English (this one is already using namespace=112), flag `--addNamespaces=4` will be added. Sounds good?

**Comment by kelson42** [comment]
@automactic For ALL wikibooks (English included) add `--addNamespaces=4`

**Comment by automactic** [comment]
wait. for English wikibooks: the flag will be `--addNamespaces=4 --addNamespaces=112`, is this correct?

**Comment by kelson42** [comment]
@automactic Sorry, for English, it should be probably `--addNamespaces=4,112`, of course the custom namespaces already mirrored should be kept.

**Comment by automactic** [comment]
I think it really should be `--addNamespaces="4,112"`?

**Comment by kelson42** [comment]
@automactic yes

**Comment by automactic** [comment]
done!
