### ISSUE TITLE
Include portals and project pages in Wikipedia ZIMs

### ISSUE THREAD

**Issue by veeara282** [openzim/zim-requests#140]
I think portals should be included in Wikipedia offline distributions because they're convenient for readers who want to explore topics. Topical subsets of Wikipedia, such as the medical distributions, could include portals such as [Portal:Medicine](https://en.wikipedia.org/wiki/Portal:Medicine), [Portal:Anatomy](https://en.wikipedia.org/wiki/Portal:Anatomy), and [Portal:Molecular and cellular biology](https://en.wikipedia.org/wiki/Portal:Molecular_and_cellular_biology).

Additionally, every Wikipedia distro should include certain project pages, such as:
- [Wikipedia:About](https://en.wikipedia.org/wiki/Wikipedia:About)
- A subset of the [FAQ](https://en.wikipedia.org/wiki/Wikipedia:FAQ/Index), especially:
  - [Wikipedia:FAQ/Readers](https://en.wikipedia.org/wiki/Wikipedia:FAQ/Readers)
  - [Wikipedia:FAQ/Schools](https://en.wikipedia.org/wiki/Wikipedia:FAQ/Schools)
- Disclaimers
  - [Wikipedia:General disclaimer](https://en.wikipedia.org/wiki/Wikipedia:General_disclaimer), [Wikipedia:Content disclaimer](https://en.wikipedia.org/wiki/Wikipedia:Content_disclaimer), and [Wikipedia:Risk disclaimer](https://en.wikipedia.org/wiki/Wikipedia:Risk_disclaimer) should be included in all distributions for ethical reasons
  - [Wikipedia:Medical disclaimer](https://en.wikipedia.org/wiki/Wikipedia:Medical_disclaimer) for use in medical institutions
  - [Wikipedia:Legal disclaimer](https://en.wikipedia.org/wiki/Wikipedia:Legal_disclaimer)
  - [Wikipedia:Survey disclaimer](https://en.wikipedia.org/wiki/Wikipedia:Survey_disclaimer) are probably less important

This idea originated on iiab/iiab#1534.

**Comment by kelson42** [comment]
@aidan-fitz For now we can only mirror things on a namespace base. "Wikipedia:" being a meta namespace and not a content namespace, it has been decided so far not to mirror it. Regarding the "Portal:" namespace, it is different. I think we should mirror it. @automactic Could you please add WPEN "Portal:" namespace (number `100`) to the list of namespace we mirror?

**Comment by kelson42** [comment]
@Popolechien Your feedback about this enhancement request would be welcome IMO.

**Comment by Popolechien** [comment]
My two cents:
* Most portals are dead / underused and very much an inside thing (I have seen little evidence they receive substantial traffic; for instance Portal:Star Wars gets 24 view per day, whereas the article has over... 10'000). I'd rather focus on subsets presenting the relevant Wikiprojects.
* [Wikipedia:About](https://en.wikipedia.org/wiki/Wikipedia:About) does not bring any significant infor compared to the regular Wikipedia article in most languages;
* I have mixed feelings about the FAQ (neither for nor against);
* Disclaimers could be useful, or a cheap way to cover our asses. I'd focus on the generic disclaimer as it is most likely to be available in all languages.
The question, then, becomes how and where do we include it ?

**Comment by RavanJAltaie** [comment]
@Popolechien Any update on this issue?

**Comment by RavanJAltaie** [comment]
@Popolechien A gentle reminder so we know what to do with this issue?

**Comment by kelson42** [comment]
I hav etaken on me to just close it, things should be assessed case by case. So far a few Wikipedias include the portal namespace and other could be done... if requested and justified.
