### ISSUE TITLE
add Department: / Shelf: / Regale: namespaces to wikibooks zims

### ISSUE THREAD

**Issue by cm8** [openzim/zim-requests#142]
The main page kind of serves as an index to the book collection and it links heavily to the "Departments:" and "Shelf:" namespace ("Regale:" in german version).

Its very hard to navigate or explore the content without this/these namespaces being part of the zim.

The search function in general is useful if you know (exactly) what you are looking for, but to explore the content of this zim, the Department links on the main page should work.

The wikibooks projects also have lists of all books that are missing from the zim file and could in theory serve as an index, e.g. [Wikibooks:Buchkatalog](https://de.wikibooks.org/wiki/Wikibooks:Buchkatalog) and [Wikibooks:Card_Catalog_Office](https://en.wikibooks.org/wiki/Wikibooks:Card_Catalog_Office).

Thanks in advance to anyone taking on this effort or who maybe points to relevant recipes on how to cook a custom wikibooks zim containing these namespaces.

**Comment by kelson42** [comment]
@cm8 is that only for wben and wbde or is this namespace available in all languages?

**Comment by cm8** [comment]
In fr.wikibooks.org it is 'Catégorie:'  so, unfortunately, it seems each localized variant has developed their own indexing system  (unless of course 'Catégorie:', 'Shelf:' and 'Regale:' would all reliably map to a unique namespace id).

**Comment by cm8** [comment]
I've looked further into this and it turns out neither 'Shelf:' nor 'Department:' is an actual namespace - these are just Prefixes with colon in the main namespace.

However: 'Subject:' and 'Wikibooks:' (ids 112 and 4) are and they contain parts of the indexing system - the latter carries the book catalogue and the former may be roughly equivalent to 'Regal:' (id 102) for german wikibooks.

The french version uses a localized translation 'Catégorie:' of what usually is the 'Category:' namespace (id 14)  for the structured indices to the books.

This means you unfortunately cannot simply pass a single id for all language wikibooks to mwoffliners' --addNamespaces option, but have to consider separate custom options for each language version of wikibooks.

**Comment by cm8** [comment]
For finegrained/custom control about what to include in a zim file I've learned about
* --articleList
* --addNamespaces

options of mwoffliner utility.  To produce wikibooks versions with the index system included, tweaking these does work (tested with a subset of articles here).  However, it would be nice if we had a third option
* --additionalArticleList

If used, all articles should be scraped as for a normal invocation and  articles from the list passed to that option should be ''additionally added'' (as opposed to exclusively).

This may be handy to include some specific articles from otherwise excluded namespaces only.  E.g. the 'Wikibooks:' namespace may have many more pages than just the book catalog, but only the later may be of interest for inclusion.

**Comment by kelson42** [comment]
@cm8 Thank you very much for your ticket and investigation. I understand that not all the pages of Wikibooks are scraped. We can handle this for now only by adding support of namespaces. Unfortunately, I don't really know which pages are missing, which is where we should start. It might be good to just focus on Wikibooks in English fisrt. Or do you prefer to talk about Wikibooks in German? So my question is: what are the missing pages on Wikibooks?

**Comment by cm8** [comment]
I've successfully done a dump of the german wikibooks containing relevant index pages in 'Regale:' and 'Wikibooks:' namespaces.  Since I've rewritten the mwoffliner script to include PDFs from upload.wikimedia.org as well, the result is 3,3 GB (without a fulltext index!), compared to the one available on download.kiwix.org that is ~686MB.

The relevant patches are posted in the recent other issues, you can review and study them.  Anyone working with the code should know how to apply patches to a working copy and push to master.  If that is too much effort for you guys, just leave it or take it on next week or month with a little more enthusiasm.  The convenience of a PR ("rule" you put it - wtf!?) may be rather contra-productive in generating that - besides you can use the patch files to put up a PR yourself if you absolutely need github to do your work.

The invocation of patched mwoffliner, specifically the part to exclude articleIds containing the string '_Druckversion', I've used was:

```bash
#!/bin/bash

# Domainname des Gesamtprojekts.
U=de.wikibooks.org

O=~/node_modules/.bin/mwoffliner
O="$O --adminEmail=foo@bar.net"
O="$O --redis=redis://127.0.0.1:6379"
#O="$O --requestTimeout 500"
O="$O --speed 0.5"
O="$O --mwUrl=https://$U"
O="$O --addNamespaces=102,4,14"
O="$O --withoutZimFullTextIndex"
O="$O --verbose"

#cd /dev/shm
cd /tmp
$O
```

**Comment by cm8** [comment]
For automated generation of the german wikibooks version, just adding namespace 102 should suffice.  With the others you may pull a lot of unneeded maintenance page like 'deletion requests' or 'admin discussions' into the ZIM.

Maybe it's a good idea to document how to build custom dumps on the Kiwix Wiki, in case people are dissatisfied with the ones available from download.kiwix.org - in any case, my motivation to build one initially was driven by the fact that the Main Page of the ZIM was basically useless, because all the pointers to the (virtual) book shelfs were unlinked.

Within the scope of wikibooks it would have been good to adopt standards across localized variants.  For example, having a thematic index to the books available in namespace 102 is _not_ a standard.  The english version and the french version each distribute their book index across other or the main namespace.  Yes, this is really unfortunate for automated retrieval, but it seems there's nothing we can do about it, but to accept the peculiarities.  It's not a complaint in your direction either, just an assessment.

**Comment by kelson42** [comment]
@cm8 I still don't understand what is the basic problem you wanted to report with Wikibooks in German. Quite sad after so many comments. Happy to read you have achieved to help yourself.

**Comment by cm8** [comment]
The basic problem is that mwoffliner fails to do what it advertises to do.  Generate ZIM dumps of wiki projects.  But go on and ignore that if it makes you happy.  Bye for now.

**Comment by kelson42** [comment]
@cm8 Please read both https://github.com/openzim/overview/blob/master/REPORT_BUG.md and https://github.com/openzim/overview/blob/master/CONTRIBUTING.md next time, this will help everybody.
