### ISSUE TITLE
Create zim files of e-books Youtube channel

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#145]
Link is here:
https://www.youtube.com/channel/UC-yXHUyLqMxx9fTlAeB0dQQ

There's about 250 books there for the taking.
Considering the size of each "book" and the fact that some of them (e.g. Nietzche or Kant) are split over a couple of videos, I see a couple of ways forward:
- individual zim file for each book (or group of books) to have manageable individual size for the end user;
- huge zim file only separated by language.

Also, we need to find a way to separate books by language. Should we build a list here?

**Comment by kelson42** [comment]
@Popolechien Faire les playlists custom par langue.

**Comment by Popolechien** [comment]
ok here they are:
Title / link
Philosophy audiobooks / https://www.youtube.com/playlist?list=PLyorzdODa1PPrQm8jAA8X-jXmgQWAa8ol 
Audiobooks / https://www.youtube.com/playlist?list=PLyorzdODa1PP_wNLk5JdIo1hWJ3kZKpup
Audio livres / https://www.youtube.com/playlist?list=PLyorzdODa1PNybxx7QH7PzuOZA9L9DOFv
Poésie en audiolivres / https://www.youtube.com/playlist?list=PLyorzdODa1PPVarYHnzPv9rVgYr8KCerd
Audiolivres de philosophie / https://www.youtube.com/playlist?list=PLyorzdODa1PODCJiYczVIBIyv08MT43aW
Théâtre en audiolivres / https://www.youtube.com/playlist?list=PLyorzdODa1POzGchN7hkrbBBhe-zhdQfz

**Comment by kelson42** [comment]
@Popolechien I think we can close this ticket http://library.kiwix.org/litterature-audiobooks-poetry_fr
