### ISSUE TITLE
Fix Wiktionary landing page

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#147]
The idea is to improve the Wiktionary's landing page so that it is less cluttered, lighter and  more mobile friendly.

There is a whole suite of offline [dictionary apps](https://play.google.com/store/apps/details?id=livio.pack.lang.en_US) based off the Wiktionary made by Livio : they are pretty awesome in that they are simple and do the job efficiently.

Here's an example landing page for both:
![Screenshot_20190404-113604](https://user-images.githubusercontent.com/21675885/55546089-d9de7f80-56ce-11e9-91cc-9a7ba4557fa1.jpg)

The first order of thing would be to fix the landing page in a manner that is wiki agnostic (ie we can upgrade all landing pages in a semi-automated way, even in languages we do not speak). Doing something similar to [#mwoffliner/449](https://github.com/openzim/mwoffliner/issues/449) does not seem super practical. 

Could we have simple function links (random, history, bookmarks, etc.) directly on the landing page as in Livio's app, and still have it work no matter the platform (android, desktop, rapsberry)? Or if not, then what?

**Comment by julianharty** [comment]
More info on the app @Popolechien mentioned e.g. how they provide offline language packs of content http://thesaurus.altervista.org/dictionary-android

**Comment by kelson42** [comment]
@Popolechien Someone should prepare an alternative page on the Wiktionary if we want that.

**Comment by Popolechien** [comment]
@kelson - yes but that is static and needs human oversight (and presumably understanding of the language). My question is more arount the idea of making it semi-automated.

**Comment by rahulps108** [comment]
its their in the 3dot tab

**Comment by kelson42** [comment]
@Popolechien Before doing things automatically, we should do things a few time manually. This ticket is quite old and not so specific anymore. I would like to see this one close and if needed specific tickets open at openzim/mwoffliner.

**Comment by kelson42** [comment]
@Popolechien Considering that this is not clear what to do next here, I’ll close this ticket. It can be reopen one time this is clear.
