### ISSUE TITLE
Simplify Wiktionary content

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#148]
Here is an example comparison for a random wiktionary word between Livio dictionary (based off the Wiktionary) and Kiwix' Wiktionary zim:
![scaturient](https://user-images.githubusercontent.com/21675885/55546388-7a34a400-56cf-11e9-979f-216dab092a6e.png)

There is a lot less information and, as a result, the files is a lot lighter, more user-friendly, and has 25 million downloads across 5 languages.

One thing that seems to appear consistently across wikis is that the first level heading tag (==) is the word's home language (in the example above, English). If the goal is to a) save space and 2) make a consistent dictionnary (rather than a multilingual one), I suggest we remove entirely the text from the first heading marker (==): if the user downloads an English dictionary, it is of very little added value to say that the word they're reading is in English anyway.

The logic of this is that we should remove altogether everything that appears from the second occurence of the top-level Heading onwards: in the case above, this means removing ==English== and then everything from ==Latin== downwards, so that at the end the entry only keeps what was between these two:

![scaturient light](https://user-images.githubusercontent.com/21675885/55557665-9eea4500-56ea-11e9-9881-a5b2c45f1e82.png)

Then comes the issue when the word is _not_ in use in the dictionary's home language (see, e.g. [ambulera](https://en.wiktionary.org/wiki/ambulera) (Choctaw) or even [тупраҡ](https://en.wiktionary.org/wiki/%D1%82%D1%83%D0%BF%D1%80%D0%B0%D2%A1) (Bashkir)): this turns the dictionary into a multilingual dictionary, and for our purpose should be considered unnecessary and/or overreach.

In English and a few other language we could weed these out by simply checking the top heading against the zim's purported home language (e.g. checking for ``==``_``word``_``==``, where if _word_ is ``home language`` then the line is removed, and if _word_ != ``home_language`` then the article is not included at all in the zim.

Each Wiktionary has its own rules regarding format, but at least these rules are consistent within that format, so I suspect we'll need to adapt the scraper to each and everyone individually.

**Comment by Popolechien** [comment]
See also #147

**Comment by jberkel** [comment]
I agree with you regarding the usability, but I'm not sure this is the right place to adapt the presentation of the content, you can't compare a purpose-built dictionary app with a generic ZIM reader.

**Comment by rahulps108** [comment]
i personally like the Kiwix and Aard2 Style

**Comment by ynikitenko** [comment]
"Then comes the issue when the word is not in use in the dictionary's home language (see, e.g. ambulera (Choctaw) or even тупраҡ (Bashkir)): this turns the dictionary into a multilingual dictionary, and for our purpose should be considered unnecessary and/or overreach. "
If you really want to cripple Wiktionary, please leave a separate file for the original one. I like the style and the idea how it was created. It is a multilingual dictionary in the first place.

**Comment by rgaudin** [comment]
> If you really want to cripple Wiktionary, please leave a separate file for the original one. I like the style and the idea how it was created. It is a multilingual dictionary in the first place.

This ticket is about a special, simplified version.

**Comment by kelson42** [comment]
@Popolechien This ticket is quite old and not so specific anymore. I would like to see this one close and if needed specific tickets open at openzim/mwoffliner.

**Comment by kelson42** [comment]
Done, further work will be done in other tickets if necessary.
