### ISSUE TITLE
Star Wars selection

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#149]
Star Wars ep.IX is coming out soon, so let's ride that wave.
 
There's a [wikiproject Star Wars](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Star_Wars) in several languages. It would be interesting to have it in English, French, German, Spanish, Arabic ideally with landing pages based on the tiled layout.

**Comment by RavanJAltaie** [comment]
@Popolechien Can we create a zim file for this link:
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Star_Wars
it's a page in the English Wikipedia and not a specific website by itself, and already it's accessible through offline English Wikipedia

**Comment by Popolechien** [comment]
@RavanJAltaie Yes, tbd with @kelson42 and @audiodude to some extent.

**Comment by RavanJAltaie** [comment]
@Popolechien As discussed earlier, we are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
