### ISSUE TITLE
Remove Inupiak wiktionary (ik_wiktionary)

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#150]
The page is still up but the project [has been closed](https://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Inupiak_Wiktionary).
Generally speaking, should I post this here or on /mwoffliner?

**Comment by rgaudin** [comment]
FYI it's not in the zimfarm.

**Comment by Popolechien** [comment]
Well a zim was generated in March and April. Was it manually done?
In any case and whereever it is -> let's remove it.

**Comment by kelson42** [comment]
I have deleted the files:
* wiktionary_ik_all_nopic_2019-03.zim
* wiktionary_ik_all_nopic_2019-04.zim
* wiktionary_ik_all_novid_2019-03.zim
* wiktionary_ik_all_novid_2019-04.zim

**Comment by Popolechien** [comment]
@kelson42 Any reason why [wiktionary_ik_all_novid_2019-04](http://library.kiwix.org/wiktionary_ik_all_novid_2019-04/A/Makpi%C4%A1aaq_Kanna) is still visible on library.kiwix.org (I haven't checked the others)

**Comment by kelson42** [comment]
@Popolechien library.kiwix.org is currently updated only one time a day. So you have a max delay of 24 hours. See https://github.com/kiwix/kiwix-tools/issues/243 to fix this inconvenient.
