### ISSUE TITLE
New WIkipedia selection about Music

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#151]
Musicians https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Music AND https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Musicians
Languages: EN/ES/PT/AR/FR/DE/ZH/HI/TR/RU
Image: https://commons.wikimedia.org/wiki/File:Gibson-sg.svg

It was difficult to do so within #127

**Comment by RavanJAltaie** [comment]
We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
