### ISSUE TITLE
Remove deprecated wikis

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#152]
A number of wikis have been abandoned or deprecated (see #150 ) and should be removed from the library (and zimfarm):
wikibooks_aa

wikiquote_bm
wikiquote_kr
wikiquote_kw
wikiquote_nds
wikiquote_qu
wikiquote_tk
wikiquote_ug
wikiquote_vo
wikiquote_wo

wiktionary_bho
wiktionary_bm
wiktionary_bo
wiktionary_ch
wiktionary_ha
wiktionary_mh
wiktionary_pi
wiktionary_rm
wiktionary_rn
wiktionary_sc
wiktionary_sn
wiktionary_to
wiktionary_tw
wiktionary_xh

wikipedia_kr
wikipedia_ng
wikipedia_bpy_medicine

**Comment by kelson42** [comment]
I still need to remove the files.

**Comment by kelson42** [comment]
@Popolechien @rgaudin I have removed the files in download.kiwix.org
