### ISSUE TITLE
Education et Numérique

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#154]
- Website URL: http://catalogue.education-et-numerique.org/
- License: **Copyrighted**
- Desired ZIM Title: **Éducation & Numérique**
- Desired ZIM Description: **Des activités dans toutes les matières du primaire au lycée**
- Desired ZIM Icon –png (URL or attach one): http://37.187.103.49/catalogue/media/images/00-logo.png
- Language (ISO 639-3): *fra*
- Desired Main Page (homepage): **Custom (to be created)**
- Is this a MediaWiki?: **no**
- Articles List URL (mediawiki): **n/a**

**Comment by Popolechien** [comment]
Content is under CC-by-NC-SA
https://www.education-et-numerique.org/cgu/ but the platform probably is copyrighted. I'll ask.

**Comment by Popolechien** [comment]
Ah, the platform is free and open-source o_0
https://www.education-et-numerique.org/faq-2/

**Comment by rgaudin** [comment]
OK, at least it's open but I'm not sure how useful the code is going to be.

It's located at https://github.com/Education-Numerique and hasn't been updated since 2015. Not much documentation and… no exports of the DB. Might me useful if we wanted to implement the platform on the hotspot-installer for instance. [They wanted to document the Pi installation at some point](https://github.com/JBTouchard/ENPI)

I think that we'll be better off scraping it ; with the advantage of having the JS source code.

**Comment by kelson42** [comment]
@Popolechien @rgaudin Things start to be a bit more urgent meanwhile. What is the final strategy to propose a corresponding ZIM file? Do we have the DB? or should we scrape https://www.education-et-numerique.org/?

**Comment by Popolechien** [comment]
I suspect their project is dead or dormant - I've tried to reach out, to no avail.
What's the most time-effective way to scrap a zim, and would there be any difference in the final product with another method?

**Comment by rgaudin** [comment]
Are we still talking about E&N ? @Popolechien you sent me the 3.5GB archive or the project and it was discussed we both of you during a meeting: we have a static version of the product. It's mostly JSON files.

I think it's a few days of work max to make a ZIM out of it and I don't think we need anything else.

**Comment by rgaudin** [comment]
ZIM: http://download.kiwix.org/zim/other/education-et-numerique_fr_2014-12.zim
Scrapper: https://github.com/openzim/education-numerique
Docker image: https://github.com/openzim/education-numerique
