### ISSUE TITLE
"Computer" zim is either too big or too small

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#155]
See attached image: the computer zim file is 16Gb large but covers a lot more than Computer science (even though the landing page *is* the computer science article). The zim currently also covers physics, but only part of chemistry and Earth science.

![capture d ecran 2018-04-03 a 15 12 33](https://user-images.githubusercontent.com/21675885/38251361-8a406f3a-3751-11e8-8dd5-395e92d0ca5c.png)

**Comment by kelson42** [comment]
@Popolechien Dmitriy, an old time user of Kiwix reported exactly about the same issue https://sourceforge.net/p/kiwix/discussion/604121/thread/7be499a745/ and remember me about this specific ticket.

The reason why it is like it is is that it as been done that way for a specific purpose/usage in a Californian prison. See https://github.com/openzim/mwoffliner/issues/58

@lowe are you still interested to keep that selection of articles in the next update of that ZIM file?

**Comment by kelson42** [comment]
This has been done for the https://github.com/thelastmile project which seems (on Github) to be quite calm... If no contradiction from @lowe I would probably recommend to base this file on https://download.openzim.org/wp1/enwiki/projects/Composers.tsv

**Comment by mbowie** [comment]
GitHub for The Last Mile is just legacy content at this stage... so it should be the very definition of calm. ;-)

Over time, we've found the filter for this set is pretty subjective. Although it's described as being CompSci based, the fact that it's generation was keyword driven, it does contain a LOT of pages which are tangentially related at best. For program purposes, there are some benefits to this, as it allows it's use as a sandboxed tool for research on general topics. (For project work, etc)

At this point, we actually run the `kiwix-serve` process behind a weighted keyword filter, which scores the markup as it would be returned to the user, and and can then decline (4xx) to serve the page if it reaches a score threshold. While on one hand it would be nice if any "unsuitable" content were not in the archive in the first place, the keyword scoring gives us some fluidity to handle problematic content, or re-weighting of false-positives, without rebuilding a large static archive.

Given that The Last Mile's use case is hyper specific, I'm not really sure how valuable these specific needs are in designing a package for a broader audience. I'm sure anyone looking at the zim in question under the lens of being strictly "computer" related would find themselves doing a bit of a head-scratch.

**Comment by kelson42** [comment]
@mbowie Thank you for your feedback. Do you use newly generated ZIM files we make periodically based on the article selection you have provided to us?... or you just keep an old one and are not interested in updated?

**Comment by mbowie** [comment]
The program doesn't have a strong motivation for updating... "currency" is not a heavy benefit for the environment, and there's a passive benefit from material being time-delayed. So for now, we continue to use the originally packaged file.

There is the possibility of looking to update the content again within the next year, but there isn't a heavy motivation to do so. If it does happen, I suspect we'd look closely at using an internally packed archive.

**Comment by Popolechien** [comment]
@kelson42 My 2 cents: let's generate a standard computing zim file. Now that we've expanded to subsets it is possible for someone interested in tangential topics to simply download/use the Pyhsics or Maths zim files. In the meantime, anyone interested in computing only will not be overburdened.

**Comment by kelson42** [comment]
@rgaudin Could you please use https://download.openzim.org/wp1/enwiki/projects/Computing.tsv (en similar list in other languages) in place of https://download.openzim.org/wp1/enwiki_2019-11/customs/computer.tsv ?

**Comment by rgaudin** [comment]
Sure could but given mwoffliner's behavior, we'd end up with files like `wikipedia_ar_computing_maxi_2019-08.zim`.

If that's fine, let me know and clarify whether we should rename the schedules to `wikipedia_xx_computing` as well.

**Comment by kelson42** [comment]
@rgaudin `--filenamePrefix` should do the job... but we can deal with `wikipedia_xx_computing`.. I will then rename the old files to `wikipedia_xx_computing`.

**Comment by rgaudin** [comment]
You're right, I forgot we fixed the prefix thing. Updated `wikipedia_xx_computer` to use the computing project list.
