### ISSUE TITLE
Wikimed First time opening blinds content

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#158]
The first thing one sees upon opening the app, is a welcoming and informative letter that pushes the primary content below the fold. 

If the primary reason people use the app is to get medical information, delivering that before anything else is important.

**Heuristics violated:**
Aesthetic and minimalist design
Dialogues should not contain information which is irrelevant or rarely needed. Every extra unit of information in a dialogue competes with the relevant units of information and diminishes their relative visibility. 

Little human/device interaction
Due to small size of mobile devices and the context of use (in motion, sometimes with one hand), it is important that the interaction effort is reduced…..Scrolling should be avoided especially for viewing links, and when the device is used in a horizontal position. Scrolling can be hidden and become visible only when there is interaction between the user and the device…. (see  more detail on page 8 )

**Recommendations:**
Move the welcome letter to make room for a table of contents above the fold. The letter could be below the table of contents, linked, or in a “see more” section, or a dismissible splash screen. 

Reorganize the information architecture of this page so users can get directly to the content they came for, and learn about details as needed.

Re-architect the information structure of this page.
Perhaps, move the sub topics from each section, and show only the highest level categories here, in a table of contents. 
Once category is tapped, take people to sub topics to navigate to the article they are looking for.

**Comment by Popolechien** [comment]
@kelson42 which Wikimed are you talking about? The english and arabic ones have been greatly simplified to accomodate what is described above.
Other languages should probably go this way as well, or use the tile layout or, better, use the tile layout with a sticky welcome message hidden in the first tile.

**Comment by kelson42** [comment]
@Popolechien This was a feedback from Wikimed mobile app Usability analysis by WMF. I don't know more.

**Comment by Popolechien** [comment]
Ok, this is indeed feedback from [April 2017](https://meta.wikimedia.org/wiki/File:Heuristic_Evaluation-_Wikimed_app.pdf) which has been taken into account for the English and Arabic versions. We probably should have a discussion as to what is best going forward : keep and expand the new layout to other languages or switch to tiles (or variation thereof).

**Comment by RavanJAltaie** [comment]
@Popolechien shall we close this issue?
