### ISSUE TITLE
Remove video/audio from wikipedia_en_100 / 1000 / 10000

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zim-requests#160]
I would like to ship Kiwix JS Windows with `wikipedia_en_100_xx-xx-xxx.zim` instead of with Ray Charles. However, it's currently 85MB, which would make the app much larger than it currently is (4.7MB). I find it hard to believe 100 pages need 85MB, when Ray Charles has 120 pages but only needs 2MB. The difference must be the videos (OK maybe quite a few more images too, but...). If these files are meant as sampler files, could we either remove the videos or else provide novid versions?

**Comment by Jaifroid** [comment]
I've been thinking about ways to increase retention of apps, which is something @Popolechien and I have been dicsussing with regard to the usage statistics of Kiwix JS Windows. I think having a really nice, attractive demo ZIM included with the app would help greatly. So I come back to this issue of providing a small but attractive `wikipedia_en_100`, with pictures but without video.

I've been looking at the new `wikipedia_en_top_mini_2019-08.zim` and its `maxi` equivalent, but they are still too large for distribution with an app. The mini is ~250MB, so I'm guessing it's either 1000 or 10000 (but it doesn't state the number) and of course has no pictures other than on the landing page.

As mentioned above, Kiwix JS Windows is currently just 4.7MB, including Ray Charles, and I can't justify increasing it to 250MB for the average user to download and try.

It should be possible to make a sample ZIM that is equivalent in size to Ray Charles, with some 100 pages with pictures (Ray Charles has 120 pages and is just 2MB).

**Comment by kelson42** [comment]
@Jaifroid I have create a recipe to create such a file https://farm.openzim.org/recipes/wikipedia_en_100

**Comment by Jaifroid** [comment]
@kelson42 Thank you, that would be wonderful!

**Comment by kelson42** [comment]
@Jaifroid First ZIM files have been released, see https://farm.openzim.org/pipeline/5ecf495153166de04f89c5fd. I'll close the ticket, let me know if any problem of course.

**Comment by Jaifroid** [comment]
Thank you @kelson42 , 32MB is much more reasonable and shouldn't be off-putting to users to download with the vanilla app. I think I'll package this with Version 1.0 of Kiwix JS, just one final push to get it out of Beta! (I'm on 0.9.9.99x.....)
