### ISSUE TITLE
wiki.opensourceecology.org

### ISSUE THREAD

**Issue by X-Ryl669** [openzim/zim-requests#162]
- Website URL: wiki.opensourceecology.org
- License: CC-by-sa
- Desired ZIM Title: osecology
- Desired ZIM Description: Open source Ecology
- Desired ZIM Icon –png (URL or attach one): https://wiki.opensourceecology.org/images/ose-logo.png?be82f
- Language (ISO 639-3): eng
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: yes 
- Articles List URL (mediawiki): **n/a**

It is very important to capture Youtube video from this site.

**Comment by WisdomCode** [comment]
The Zim file is now available on archive.org
https://archive.org/details/osewiki_en_all_2019-08

Its creation is documented on the wiki itself, see here:
https://wiki.opensourceecology.org/wiki/Create_ZIM_from_OSE_Wiki

Unfortunately, this makes the process currently only replicable for the OSE contributors themselves (I am one of them), however we would like to present an updated version on a regular basis. I'm right now working out an automated scraper that regularly puts out a new zim for kiwix.

Also, the videos (they are actually on vimeo) are important, but maybe even more so are the external files (that contain some software for the 3d Printer for instance) and the integrated google docs and presentations, presenting overviews, Bills of Materials and some other important stuff. At this moment, they are not integrated into the zim, as this is not possible by default. If someone knows how to do it, I'd be glad to adapt it. I am also willing to write some scripts around it if needed.

**Comment by X-Ryl669** [comment]
First, thank you for your work. Could you make a .tar or .zip archive of those ? How are they stored on the server initially ?

**Comment by WisdomCode** [comment]
Are you referring to the external files, like videos, docs? If so, they are partly on google drive (the google docs), partly on vimeo (under https://vimeo.com/opensourceecology, so youtube-dl can actually collect them pretty quick) and the files are hosted on the wiki, but sometimes also on github (for merging purposes) or archive.org (due to them being to big, like this zim for instance)

**Comment by X-Ryl669** [comment]
Do you have a manifest somewhere so we can automate the fetching of these documents ?
They are very important for understanding the concepts and being able to reproduce them.

**Comment by WisdomCode** [comment]
No I have not, that is what I am trying to say. I know of the importance, but I am not aware on how such a thing could be implemented best. I could write a bot scraping such things, but depending on what this would all include, it would be much work, so maybe we should look at whether this is worth it.

**Comment by WisdomCode** [comment]
This is something that I would like to know from the developer: Is it possible to add some external files to a zim? what structure do I have to put it in? As described in the deocumentation, I use zimwriterfs for getting it out of the folder structure into the zim, maybe it is possible to add something in between? One could convert the files maybe in pdf or something to embed them. 
About the external files, to add them as an external zip would probably be easiest.

**Comment by RavanJAltaie** [comment]
Zim File Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/osecology
