### ISSUE TITLE
English Wiktionary zim missing Thesaurus namespace

### ISSUE THREAD

**Issue by jberkel** [openzim/zim-requests#163]
Is this the right place to discuss issues with existing zim files?

I've just tried `wiktionary_en_all_novid_2018-06.zim` and noticed that it doesn't include the `Thesaurus:` namespace. More and more content is now shifted to this namespace so it would make sense to include it.

**Comment by kelson42** [comment]
@jberkel It is the right place, do you know the namespace id/number/code associated to the namesapce "thesaurus"?

**Comment by kelson42** [comment]
@jberkel May I ask the purpose of the "reconstruction" namespace? I'm willing to make things easier for ZIM users... but not to integrate meta pages.

**Comment by kelson42** [comment]
@rgaudin Would you be able to update the schedule?

**Comment by jberkel** [comment]
The reconstruction namespace contains hypothetical reconstruction of words. As an example, the word "house" is said to derive from a Proto-Germanic [*hūsą](https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/h%C5%ABs%C4%85) which is documented in that namespace. 

We don't include proto/hypothetical languages in the mainspace (per policy), but they are often linked to from etymologies. So not having them renders the etymologies fairly incomplete.

**Comment by kelson42** [comment]
@jberkel Thx, I agree, sounds legit.

**Comment by rgaudin** [comment]
OK, is this only for EN ?

**Comment by Popolechien** [comment]
@rgaudin Yes, I checked and other Wiktionaries either do not use Thesaurus or ahve a different namespace (106 for French)

**Comment by rgaudin** [comment]
Done. Next generation will include the Thesaurus NS.

**Comment by jberkel** [comment]
@rgaudin thanks! how often are these published? The most recent Wiktionary zim (en) I found is nearly a year old.

**Comment by kelson42** [comment]
@jberkel This summer for sure.
