### ISSUE TITLE
Add namespace Category to all Wikipedia ZIM files

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#166]
Was also requested here https://github.com/kiwix/kiwix-xulrunner/issues/496

**Comment by ghjm** [comment]
Similarly, it would be helpful to add Category: and Wikisource: namespaces to the Wikisource ZIM files.

Can I help somehow?  This issue just turned two years old.

cc @kelson42

**Comment by kelson42** [comment]
This ticket depends on https://github.com/openzim/mwoffliner/issues/829

**Comment by RavanJAltaie** [comment]
@kelson42 isn't this issue related more to the technical part in mwoffliner?
If confirmed, we can close this one.
