### ISSUE TITLE
New ZIM: for wiki.ubuntu.com

### ISSUE THREAD

**Issue by trappedinspacetime** [openzim/zim-requests#168]
*Please use the following format for a ZIM creation request…*

- Website URL:https://wiki.ubuntu.com
- License: **Copyrighted | CC-by-sa | Public domain | ...**
- Desired ZIM Title: **Wiki-Ubuntu**
- Desired ZIM Description: **Documentation**
- Desired ZIM Icon –png (URL or attach one): http://www.iconarchive.com/download/i94330/bokehlicia/captiva/launcher-bfb.ico
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **https://wiki.ubuntu.com/**
- Is this a MediaWiki?: **yes | no**
- Articles List URL (mediawiki): **n/a**

I requested it last year in the following issue https://github.com/openzim/mwoffliner/issues/177
I was told that it uses `moinmoin` engine and it's not supported. 
I hope it's possible this time.

**Comment by kelson42** [comment]
My comment last time: It looks like wiki.ubuntu.com uses https://moinmo.in wiki engine. MWoffliner is a solution for Mediawiki, an other wiki engine. There is nothing much we can do for now. A scrapper should be written for MoinMoin (and then use zimwriterfs to create the ZIM file).

**Comment by trappedinspacetime** [comment]
Just a desperate attempt; I found this https://github.com/jaap-karssenberg/zim-wiki/wiki/Moinmoin-import-script
May it help?

**Comment by kelson42** [comment]
@trappedinspacetime Not really :(
