### ISSUE TITLE
Feed the Beast Wiki

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#169]
OTRS request:
- Website URL: https://ftbwiki.org/Feed_The_Beast_Wiki
- License: CC-by-sa
- Desired ZIM Title: Feed the Beast
- Desired ZIM Description: Unofficial Feed the Beast wiki
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/feed_the_beast_wiki

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by Popolechien** [comment]
@ravan I can't see it in either library - do you have a link?

**Comment by RavanJAltaie** [comment]
No the same problem, we will discuss this. As I understand if the recipe succeeds then it should be reflected directly to the library
