### ISSUE TITLE
Infogalactic news

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#170]
OTRS suggestion:
- Website URL: https://infogalactic.com
- License: CC-by-sa
- Desired ZIM Title: Infogalactic
- Desired ZIM Description: The Planetary Knowledge Core
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: yes

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/infogalactic
