### ISSUE TITLE
New ZIM: wiki.evageeks.org

### ISSUE THREAD

**Issue by godane** [openzim/zim-requests#172]
*Please use the following format for a ZIM creation request…*

- Website URL: http://https://wiki.evageeks.org/Main_Page
- License: CC-by-sa
- Desired ZIM Title: EvaWiki
- Desired ZIM Description: An Encyclopedia of Evangelion Related Topics
- Desired ZIM Icon –png (URL or attach one): https://wiki.evageeks.org/skins/ngefgp/default-logo.jpg
- Language (ISO 639-3): eng
- Desired Main Page (homepage): https://wiki.evageeks.org/Main_Page
- Is this a MediaWiki?: yes
- Articles List URL (mediawiki): https://wiki.evageeks.org/Category:A_to_Z

I figure i add this one cause we have a game of thrones wiki so why not one on Evangelion.

**Comment by kelson42** [comment]
I have created a recipe to make it here, let see what it gives https://farm.openzim.org/recipes/evawiki

**Comment by kelson42** [comment]
done
