### ISSUE TITLE
Update EcuRed

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#173]
Our current version of EcuRed is from April 2018 whereas the generate a zim file pretty much every month. https://www.ecured.cu/EcuM%C3%B3vil#Enlaces_externos

@kelson42 Should I reach out to them and ask for a permalink? 
(the structure is otherwise pretty standard, e.g. http://descargas.jovenclub.cu/ecured/EcuMovil/EcuMovil_Imagenes_[month in Spanish]_[year]_Kiwix.zip)

**Comment by kelson42** [comment]
I'm not sure about an automatic solution... not sure this is really worth it. But If I have a way - automatically - to know about new version... I could build something automatically. For now I have uploaded the new version here https://download.kiwix.org/zim/other/ecured_es_all_2019-05.zim
