### ISSUE TITLE
MIT scratch

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#174]
*Please use the following format for a ZIM creation request…*

- Website URL: https://scratch.mit.edu/
- License:CC-SA
- Desired ZIM Title: Scratch
- Desired ZIM Description: Learn to code your own stories and games
- Desired ZIM Icon –png (URL or attach one): 
![scratch-logo-png-clip-art](https://user-images.githubusercontent.com/21675885/77339639-5deca580-6d2c-11ea-8cca-656c00ad01c3.png)

- Language (ISO 639-3): Looks like there are more than 60 languages available
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?:  no

**Comment by kelson42** [comment]
@Popolechien I think this request is invalid. Are you able to fix it?

**Comment by Popolechien** [comment]
Yeah don't know what happened but I updated the relevant fields

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/mitscratch

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by Popolechien** [comment]
Only picked up the front page. https://dev.library.kiwix.org/viewer#scratch_2022-12
