### ISSUE TITLE
Create TED-Ed category

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#176]
Much like we have a Wikipedia or StackExchange category if would be good to create a TED-Ed category and populate it with the playlists available by Subject
https://ed.ted.com/lessons?content_type=animations&direction=desc&sort=publish-date
There are currently 12 subjects which would form as many zim files: 
- [Teaching & Education](https://ed.ted.com/lessons?content_type=animations&category=teaching-education&direction=desc&sort=publish-date)
- [Literature & Language](https://ed.ted.com/lessons?content_type=animations&category=literature-language&direction=desc&sort=publish-date)
- [Philosophy & Religion](https://ed.ted.com/lessons?content_type=animations&category=philosophy-religion&direction=desc&sort=publish-date)
- [Mathematics](https://ed.ted.com/lessons?content_type=animations&category=mathematics&direction=desc&sort=publish-date)
- [Psychology](https://ed.ted.com/lessons?content_type=animations&category=psychology&direction=desc&sort=publish-date)
- [Design, Engineering & Tech](https://ed.ted.com/lessons?content_type=animations&category=design-engineering-technology&direction=desc&sort=publish-date)
- [Health](https://ed.ted.com/lessons?content_type=animations&category=health&direction=desc&sort=publish-date)
- [The Arts](https://ed.ted.com/lessons?category=the-arts&content_type=animations&direction=desc&sort=publish-date)
- [Thinking & Learning](https://ed.ted.com/lessons?content_type=animations&category=thinking-learning&direction=desc&sort=publish-date)
- [Science and Tech](https://ed.ted.com/lessons?content_type=animations&category=science-technology&direction=desc&sort=publish-date)
- [Social studies](https://ed.ted.com/lessons?content_type=animations&category=social-studies&direction=desc&sort=publish-date)
- [Business & Economics](https://ed.ted.com/lessons?content_type=animations&category=business-economics&direction=desc&sort=publish-date)

Each category seems to have 100-200 videos, so that should make for decent-sized files.

**Comment by kelson42** [comment]
@Popolechien @rgaudin Would be good to identify how we could scraper these videos. It seems for the moment that this is not doable either by the youtube scraper not by the TED scraper!

**Comment by rgaudin** [comment]
FYI, I think most of those videos (including very recent ones) are in the [TED ED youtube channel](https://www.youtube.com/user/TEDEducation) but playlists are not matching the website ones.

**Comment by Popolechien** [comment]
Well I would say that the topics are easier to understand than playlists named "The great Thanksgiving car ride", but at the end of the day which is easier to scrape?

**Comment by kelson42** [comment]
@Popolechien Youtube of course, but the playslist quality needs to be OK.

**Comment by rgaudin** [comment]
The playlists quality is very good, it's just that it's not structured (and thus not named) in the same way as on the TED website. The youtube ones looks more discovery-centric while the website ones are academic.

We should definitely revamp the ted scraper, sharing code with youtube one but until that happens, we could still create a TEDEd Channel youtube ZIM without any code…

**Comment by rgaudin** [comment]
After looking at the TED scraper, it's clear that TED-ED is very different from the rest. Actually, there's no duplicate in video files, those are all hosted on Youtube.

They do have two playlists systems: the one that you described and another one for youtube that is less convenient.

We'll have to wait for the revamp of the TED scraper and the move of most video features to the zimscraperlib to tackle this one.

In order to not complexify the ted scraper, we might end-up with a minimal ted-ed scraper.

**Comment by kelson42** [comment]
IMO the added value of ed.ted.com categories over teded youtube playlists is not obvious. Considering as well that this would need additional custom software solution to support it, I don't think this is the best move to do now.

I would propose to make one ZIM per youtube playlist instead. If we still see a need after that, we could reconsidering doing ZIM files for the ed.ted.com categories.

**Comment by RavanJAltaie** [comment]
@Popolechien I think this issue is outdated now as The website itself changed the way they categorize the subjects. What do you think?

**Comment by Popolechien** [comment]
Agree.
