### ISSUE TITLE
MDN web docs

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#180]
*Please use the following format for a ZIM creation request…*

- Website URL: https://developer.mozilla.org/en-US/
- License: CC-by-SA 2.5

**Comment by kelson42** [comment]
done https://farm.openzim.org/recipes/developer.mozilla.org_en

**Comment by thavelick** [comment]
This doesn't seem to work. When I try to view any page in this zim archive, I get "This page must be loaded via an HTTPS URL to support service workers.", then there's a link to the https version of the same page but that doesn't work. Is there any known workaround?

**Comment by thavelick** [comment]
I figured it out on my own. In order to make this work, start a local kiwix web server. You'll get the same error, but if you replace the ip of your computer with `localhost` it'll work in the web browser without ssl

**Comment by kelson42** [comment]
Yes, this ZIM file uses service-workers, whoch can run only in localhost or with proper HTTPS compnnection.
