### ISSUE TITLE
DevDocs

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#181]
*Please use the following format for a ZIM creation request…*

- Website URL: https://devdocs.io/
- License: Mozilla Public License v2.0
- Desired ZIM Title: DevDocs

**Comment by kelson42** [comment]
Should be easy with https://github.com/freeCodeCamp/devdocs

**Comment by kelson42** [comment]
Done https://farm.openzim.org/recipes/devdocs.io

**Comment by benoit74** [comment]
For the record, this request has never been fully completed, zimit is not working on devdocs.io ; we are now close to create one ZIM per slug with https://github.com/openzim/zim-requests/issues/1086
