### ISSUE TITLE
Mini offer should not include images

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#185]
The purpose of the nodet/mini selection is to save on space by restricting content to articles leads. But by leaving images the resulting file ends up being larger than the full wikipedia without picture (image shown: French)

![Capture d’écran 2019-08-23 à 08 44 10](https://user-images.githubusercontent.com/21675885/63572391-0bbf8800-c583-11e9-8958-ba3312d48f83.png)

**Comment by kelson42** [comment]
@Popolechien I guess you are talking about the "mini" offer, the "nodet" selection does not exist anymore in standard offering.

**Comment by Popolechien** [comment]
Yes. As long as every zim file hasn't been updated there still is a bit of overlap, but at the end of the day, same difference.

**Comment by rgaudin** [comment]
mini doesn't include pictures. This WP french mini is from before Wikimania.
