### ISSUE TITLE
new wiktionary zim files

### ISSUE THREAD

**Issue by amirh123123** [openzim/zim-requests#187]
i want just download english world of en wintionary not full of en wintionary 
this link
https://en.wiktionary.org/wiki/Category:English_lemmas

**Comment by RavanJAltaie** [comment]
@Popolechien shall we create a zim file for this link only: https://en.wiktionary.org/wiki/Category:English_lemmas?

**Comment by Popolechien** [comment]
@RavanJAltaie At this stage we can't parse categories, and there's another, easier way around OP's request.
