### ISSUE TITLE
Stacks project 

### ISSUE THREAD

**Issue by Pankratius** [openzim/zim-requests#189]
- Website URL: https://stacks.math.columbia.edu/
- License: GNU Free Documentation Licence
- Desired ZIM Title: Stacks Project
- Desired ZIM Description: A copy of the Stacks Project, a free online textbook on algebraic geometry
- Language (ISO 639-3): eng
- Desired Main Page (homepage): https://stacks.math.columbia.edu/browse
- Is this a MediaWiki?: no (?)

**Comment by kelson42** [comment]
Done https://farm.openzim.org/recipes/stacks.math.columbia.edu

**Comment by Pankratius** [comment]
Hi, I only now came around to accessing the file, but when I try to open it in kiwix (both on the phone and on the pc), it says 
```
Error
The requested URL can not be loaded because service workers are not supported here.

If you use Firefox in Private Mode, try regular mode instead.

If you use Kiwix-Serve locally, replace the IP in your browser address bar with localhost.
```
I can open other .zim files perfectly fine tho.
