### ISSUE TITLE
New ZIM: news.ycombinator.com (aka. HackerNews)

### ISSUE THREAD

**Issue by amirouche** [openzim/zim-requests#191]
*Please use the following format for a ZIM creation request…*

- Website URL: http://news.ycombinator.com
- License: **Copyrighted**, see https://news.ycombinator.com/item?id=10178971
- Desired ZIM Title: HackerNews
- Desired ZIM Description: Links for the intellectually curious, ranked by readers (mostly tech)
- Desired ZIM Icon –png (URL or attach one): FIXME
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **no**
- Articles List URL (mediawiki): **n/a**

**Comment by Popolechien** [comment]
Well I get the fair use thing for educational purposes, but that concept does not exist in Switzerland where Kiwix is based :-/
