### ISSUE TITLE
New ZIM: https://energypedia.info

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#192]
*Please use the following format for a ZIM creation request…*

- Website URL: https://energypedia.info
- License: * CC-by-sa 
- Desired ZIM Title: Energypedia
- Desired ZIM Icon –png (URL or attach one): http://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **yes | no**
- Articles List URL (mediawiki): **n/a**

**Comment by siemsie** [comment]
Comment to self: cloned "rationalwiki", https://farm.openzim.org/recipes/rationalwiki (with kelson's help!)

**Comment by siemsie** [comment]
Link here https://farm.openzim.org/recipes/energypedia. @kelson42 I hope I didn't miss anything???

**Comment by kelson42** [comment]
Yes, done
