### ISSUE TITLE
Scrape halachipedia.com

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#193]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.halachipedia.com
- License: **Copyrighted | CC-by-sa | Public domain | ...**
- Desired ZIM Title: **My title**
- Desired ZIM Description: **My description**
- Desired ZIM Icon –png (URL or attach one): **n/a**
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **yes | no**
- Articles List URL (mediawiki): **n/a**

**Comment by siemsie** [comment]
https://farm.openzim.org/recipes/halachipedia

**Comment by siemsie** [comment]
@kelson42 Hi :) this is failing – let me know if there is something I've done wrong! I have two open tickets which I updated the same day which are failing – so I'll wait on feedback before working on others in case it's something I'm going wrong?

**Comment by kelson42** [comment]
Works now, closing the ticket.
