### ISSUE TITLE
Incorrect landing page for wikipedia_en_all and similar custom landing pages

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#194]
The custom landing page has been moved and the zim file did not follow the redirect: see, e.g., [http://library.kiwix.org/wikipedia_en_all_mini_2019-09/A/User:Stephane_(Kiwix)/Landing](http://library.kiwix.org/wikipedia_en_all_mini_2019-09/A/User:Stephane_(Kiwix)/Landing)

zim files impacted are those with the ALL set, and presumably impacts other languages with custom landing pages, such as French, Spanish, German, etc.

The landing page should be https://en.wikipedia.org/wiki/User:The_other_Kiwix_guy/Landing

**Comment by kelson42** [comment]
@Popolechien Thx for reporting, this has been fixed a few days ago by @rgaudin
