### ISSUE TITLE
New ZIM: Wikipedia Vital (Level 3)

### ISSUE THREAD

**Issue by jncraton** [openzim/zim-requests#195]
I wanted a very small Wikipedia-based ZIM file to use on my phone, and this is what I came up with. It scrapes the ~1000 articles listed here:

https://en.wikipedia.org/wiki/Wikipedia:Vital_articles

It also scrapes the index page and uses that as the index for the ZIM file.

I didn't use mwoffliner, but instead wrote my own simple scraper in Python. In additional to grabbing pages, it also removes quite a bit of content (infoboxes, images, references, etc) and generally creates a simple chunk of text for each page. This allows the final ZIM file to be very tiny (current less than 24MB).

The scraper is on Github here:

https://github.com/jncraton/wikipedia-vital

An HTML preview of the content is here:

https://wikipedia-vital.netlify.com/articles/

The most recent ZIM file is here:

https://wikipedia-vital.netlify.com/wikipedia-vital.zim

- Website URL: en.wikipedia.org
- License: Creative Commons Attribution-ShareAlike 3.0
- Desired ZIM Title: Wikipedia Vital
- Desired ZIM Description:Wikipedia Vital
- Desired ZIM Icon –png (URL or attach one):
- Language (ISO 639-3): eng
- Desired Main Page (homepage):
- Is this a MediaWiki?: yes
- Articles List URL (mediawiki): https://en.wikipedia.org/wiki/Wikipedia:Vital_articles

**Comment by Popolechien** [comment]
@jncraton Quick question : since you removed a bunch of the clutter (infobox & al.), did you do some english-specific grep, or do you think this could work with other languages as well?

**Comment by kelson42** [comment]
@jncraton Thank you for your ticket. I'm not willing to publish this ZIM as it, but it would be easy for us to provide one following our standards using MWoffliner. That sounds to be a good idea to me. @Popolechien please open a new ticket if you agree, but please precise which kind of vital articles do you want: all of them ~10K or only the level3 like in this ticket (we publish the list here https://download.kiwix.org/wp1/enwiki/vital.lzma)

**Comment by jncraton** [comment]
@Popolechien It mostly filters by HTML tag attributes so should be language agnostic, e.g.:

```python
if tag in ['script','style','figure', 'map', 'figure-inline'] or \
       role == 'note' or \
       'pagelib_collapse_table_container' in cls or \
       'mw-ref' in  cls or \
       'thumb' in cls or \
       'gallery' in cls or \
       'ambox' in cls or \
       'noprint' in cls or \
       'flagicon' in cls:
```

But there are also some rules that are language specific that remove sections from the text:

```python
if self.is_in_heading and data.lower() in ['notes','references','bibliography','external links','further reading','see also','gallery', 'footnotes', 'sources']:
```

**Comment by Popolechien** [comment]
@jncraton Thanks a lot!
Based on #196 the immediate gain isn't huge, but I've followed up with [#24](https://github.com/openzim/wp1_selection_tools/issues/24) to make sure vitals are included in the selections.
