### ISSUE TITLE
Improper scraping of Mawsouaa

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#198]
When I click on one of the links listed in the bottom section, Kiwix either crashes (macOS) or tells me there is no such content (Kiwix-JS - screenshot below)
![Capture d’écran 2019-10-01 à 09 49 49](https://user-images.githubusercontent.com/21675885/65943910-da16c800-e430-11e9-9177-957034fec7b2.png)

**Comment by rgaudin** [comment]
Thanks, the links you mention are category links.

This ZIM is a test with `--getCategories` to test… the categories feature of mwoffliner. See [mwoffliner#829](/openzim/mwoffliner/issues/829#issuecomment-530330547).

I just relaunched it without that option. It usually takes 10mn to complete.
