### ISSUE TITLE
New ZIM: Wikipedia English

### ISSUE THREAD

**Issue by metal450** [openzim/zim-requests#199]
I'm not sure if this is the correct place to post this - but the English Wikipedia (all nopic & all novid) hasn't been updated in over a year.  Is there an expected update/release schedule somewhere?

**Comment by Popolechien** [comment]
@metal450 I can take that one - the last update for all_maxi failed, and I don't know when the next run is scheduled, But we did get all_nopic through last month: [http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_nopic_2019-10.zim](http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_nopic_2019-10.zim)
