### ISSUE TITLE
wikipedia_de_all_maxi_2019-08.zim doesn't have any coordinates anymore. 

### ISSUE THREAD

**Issue by Patrick023** [openzim/zim-requests#200]
**in german:**
die Koordinaten am Anfang (ganz oben in der ersten Zeile) eines Artikels sind nicht mehr enthalten.

**in english:**
the coordinates at the beginning (at the top of the first line) of an article no longer contain, an 
Example:
https://de.wikipedia.org/wiki/Kugelbake:
coordinates: 53° 53′ 30,6″ N, 8° 41′ 13,8″ O 
are no longer contain in the wikipedia_de_all_maxi_2019-08.zim:
http://library.kiwix.org/wikipedia_de_all_maxi_2019-08/A/Kugelbake

**Comment by kelson42** [comment]
@Patrick023 The mobile version does not: https://de.m.wikipedia.org/wiki/Kugelbake. And this ZIM file is based on the mobile version.
