### ISSUE TITLE
Tahrir Academy

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#201]
- Website URL: http://tahriracademy.org/
- License: CC-by-NC-ND
- Desired ZIM Title: أكاديمية التحرير
- Desired ZIM Description: نسخة عربية من أكاديمية خان العالمية 
- Desired ZIM Icon –png (URL or attach one): http://tahriracademy.org/uploads/TA_new_final%20-%20Copy.jpg
- Language (ISO 639-3): **ar**

**Comment by RavanJAltaie** [comment]
The website URL doesn't exist any more!
http://ww7.tahriracademy.org/
