### ISSUE TITLE
WikiSummaries

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#202]
- Website URL: http://www.wikisummaries.org/wiki/Main_Page
- License: GFDL 1.2
- Desired ZIM Title: WikiSummaries
- Desired ZIM Description: Where knowledge is free, and summarized for your convenience
- Desired ZIM Icon –png (URL or attach one): http://www.wikisummaries.org/w/images/a/a9/WikiSummaries.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes **

**Comment by Popolechien** [comment]
The summaries have a comment section at the bottom but we can probably live without them.

**Comment by siemsie** [comment]
https://farm.openzim.org/recipes/wikisummaries

**Comment by siemsie** [comment]
Marked as succeeded on March 19th. Closing ticket.

**Comment by Popolechien** [comment]
The zim file is empty.

**Comment by siemsie** [comment]
Oh ok, there is clearly stuff I'm not grasping here... I'll put all this on hold for now.

**Comment by Popolechien** [comment]
If you click on Succeeded in the recipe you will get the zim name: you can either download it and open it from your computer, or open it in the library (e.g. library.kiwix.org/zim-name-without-dot-zim, ie
https://library.kiwix.org/wikisummaries_en_all_maxi_2020-03 (but give it 24-48h to be uploaded. In the case at hand there's been a whole week so no problem).

Without doing any of the above one could already see that both `maxi` and `nopic` were 596kB, so clearly something went wrong there (no idea what).

**Comment by kelson42** [comment]
Job done, closing the ticket.
