### ISSUE TITLE
Refresh all youtube with last version of the scraper

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#205]
Here is the list to refresh:
* https://download.kiwix.org/zim/ted/teded_en_all_2017-10.zim
* https://download.kiwix.org/zim/ted/tedmed_en_all_2018-06.zim
* https://download.kiwix.org/zim/other/bil-tunisia_ar_all_2018-06.zim
* https://download.kiwix.org/zim/other/biologie-tout-compris_fr_all_2018-06.zim
* https://download.kiwix.org/zim/other/cest-pas-sorcier_fr_all_2018-06.zim
* https://download.kiwix.org/zim/other/crashcourse_en_all_2018-06.zim
* https://download.kiwix.org/zim/other/deus-ex-silicium_fr_all_2018-06.zim
* https://download.kiwix.org/zim/other/dirtybiology_fr_all_2018-06.zim
* https://download.kiwix.org/zim/other/e-penser_fr_all_2018-06.zim
* https://download.kiwix.org/zim/other/hygiene-mentale_fr_all_2018-06.zim
* https://download.kiwix.org/zim/other/la_chaine_de_maths_et_tiques_fr_all_2015-07.zim
* https://download.kiwix.org/zim/other/les-fondamentaux_fr_all_2016-05.zim
* https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2019-09.zim
* https://download.kiwix.org/zim/other/skin-of-color-society_en_all_2018-06.zim
* https://download.kiwix.org/zim/other/universcience-tv_fr_all_2015-03.zim
* https://download.kiwix.org/zim/other/vsauce-language_en_all_2019-10.zim
* https://download.kiwix.org/zim/other/wikistage_fr_all_2018-06.zim

**Comment by rgaudin** [comment]
Schedules created:


  * https://api.farm.openzim.org/schedules/teded_en_all
* https://api.farm.openzim.org/schedules/tedmed_en_all
* https://api.farm.openzim.org/schedules/bil-tunisia_ar_all
* https://api.farm.openzim.org/schedules/biologie-tout-compris_fr_all
* https://api.farm.openzim.org/schedules/cest-pas-sorcier_fr_all
* https://api.farm.openzim.org/schedules/crashcourse_en_all
* https://api.farm.openzim.org/schedules/deus-ex-silicium_fr_all
* https://api.farm.openzim.org/schedules/dirtybiology_fr_all
* https://api.farm.openzim.org/schedules/e-penser_fr_all
* https://api.farm.openzim.org/schedules/hygiene-mentale_fr_all
* https://api.farm.openzim.org/schedules/la_chaine_de_maths_et_tiques_fr_all
* https://api.farm.openzim.org/schedules/les-fondamentaux_fr_all
* https://api.farm.openzim.org/schedules/mali-pour-les-nuls_fr_all
* https://api.farm.openzim.org/schedules/skin-of-color-society_en_all
* https://api.farm.openzim.org/schedules/universcience-tv_fr_all
* https://api.farm.openzim.org/schedules/mindfield_en_all
* https://api.farm.openzim.org/schedules/wikistage_fr_all

@kelson42, I removed the vsauce language which was more for for demo purposes ; so please remove the ZIM file.
I've added a new Mind Field (from Vsauce) though.

Also, **wikistage_fr_all** is actually mostly English. I've changed it to `wikichange_multi_all`. Please confirm this is the right move.

**Comment by kelson42** [comment]
@rgaudin Thank you. I have removed vsauce ZIM file... but the ISO code for multilanguage is `mul` AFAIK, not `multi`. This should be fixed where the error has been introduced.

**Comment by rgaudin** [comment]
OK, fixing it in the following: `phet`, `gutenberg`, `litterature-audiobooks`, `wikistage`

**Comment by kelson42** [comment]
@rgaudin thx
