### ISSUE TITLE
New ZIM: Climate change

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#206]
*Please use the following format for a ZIM creation request…*

- Website URL: https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Climate_change
- License: CC-by-sa
- Desired ZIM Title: Climate change by Wikipedia
- Desired ZIM Description: A selection of Wikipedia articles on climate change
- Desired ZIM Icon –png (URL or attach one): https://commons.wikimedia.org/wiki/File:Change_in_Average_Temperature_(squared).png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): automatic
- Is this a MediaWiki?: yes
- Articles List URL (mediawiki): http://download.openzim.org/wp1/enwiki_2019-10/projects/Climate_change.tsv

Other versions should be done:
* German: Globale Erwärmung von Wikipedia / Eine Auswahl von Wikipedia Artikeln zum Thema Globale Erwärmung
* French: Réchauffement climatique par Wikipédia / Une sélection d'articles de Wikipédia sur le réchauffement climatique
* Spanish: Calentamiento global / Una selección de artículos de Wikipedia sobre el calentamiento global

**Comment by rgaudin** [comment]
Shouldn't the french version be named “Changement climatique” or “Dérèglement climatique” rather than _réchauffement_?

**Comment by Popolechien** [comment]
Likewise _Klimawandel_ in German and _Cambio climático_ in Spanish, cf. [Q125928](https://www.wikidata.org/wiki/Q125928)

**Comment by kelson42** [comment]
@rgaudin @Popolechien J'ai pris les nom des articles sur Wikipédia (en supposant) que toute cette discussion avait deja eu lieu dans ce cadre

**Comment by rgaudin** [comment]
Oui et les liens interwiki montre que tu t'es trompé :) Climate Change pointe vers Changement et pas réchauffement. J'ai créé avec les noms de @Popolechien.

**Comment by kelson42** [comment]
@rgaudin Thank you. I guess we can close the ticket?
