### ISSUE TITLE
New ZIM: Audiolivres littérature classique

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#208]
- License: Public domain
- Desired ZIM Title: Audiolivres littérature classique
- Desired ZIM Description: 120 romans et nouvelles en audiolivres
- Desired ZIM Icon –png:
![ebook](https://user-images.githubusercontent.com/21675885/69814489-8d632980-11f4-11ea-8419-99ab91c2a4b9.png)
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage): 
Based off what YouScribe currently offers, a list that offers the following fields
> **Titre** (bold, font size+1)
> Sous-thème
> Auteur
> A drop down/hide text part that includes the 100 first characters from the "description" field and expands when clicked on.

The final listing would look like this: on the left the regular view, on the right the expanded view:
![Capture d’écran 2019-11-28 à 16 09 59](https://user-images.githubusercontent.com/21675885/69816891-a15d5a00-11f9-11ea-8d6f-aec52198d925.png)

Here is the Youscribe screenshot
![Screenshot_20191218_144928_youscribe mobileapp](https://user-images.githubusercontent.com/21675885/71091675-d67c1d00-21a5-11ea-8e42-905ec994ff46.jpg)
- Based off YouScribe file list from Orange. These are the entries (all under `type=Audiobooks` in the excel table)
2902753
2902768
2909454
2909455
2909457
2909458
2909459
2909460
2909461
2909462
2909474
2909475
2909482
2909483
2909484
2909485
2917783
2917823
2917825
2917826
2917827
2917828
2917829
2917830
2917831
2917832
2917833
2917837
2917838
2917839
2917844
2917846
2917848
2917939
2917944
2917945
2917947
2917949
2917951
2917952
2917953
2917954
2917955
2917956
2917957
2917960
2917964
2917971
2917972
2917973
2917974
2917975
2917976
2917977
2917978
2917979
2917980
2917982
2917983
2917984
2917985
2917986
2917987
2917988
2917989
2917990
2917991
2917992
2917993
2917994
2917995
2918019
2918020
2918021
2918022
2918023
2918024
2918025
2918027
2918028
2918029
2918030
2918031
2918033
2918035
2918036
2918037
2918038
2918039
2918040
2918041
2918042
2918043
2918044
2918045
2918046
2918048
2918056
2918058
2918059
2918060
2918061
2918062
2918063
2918064
2918065
2918066
2918067
2918068
2918070
2918071
2918093
2918094
2918102
2918103
2918105
2918114
2918115
2918296

**Comment by kelson42** [comment]
@Popolechien After a discussion about the requirements with @rgaudin it is important to precise:
* Because most of the file are audio/word files, we won't be able to provide a nice cover picture
* We will make an effort to propose a basic filtering/search feature
* Most of the files (PDF/Word) won't be readable with the browser. End-user will need a PDF/Word document player to enjoy the content. They only will be able to download a file. For audio file, we will provide a reader within the browser.

**Comment by kelson42** [comment]
https://download.kiwix.org/zim/other/youscribe_fr_audiobooks_2020-01.zim
