### ISSUE TITLE
New ZIM: OpenEMR

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#209]
- Website URL: https://www.open-emr.org/wiki/index.php/OpenEMR_Downloads (git repo is here: https://github.com/openemr/openemr)
- License: GNU GPL
- Desired ZIM Title: [OpenEMR](https://github.com/openemr/openemr/blob/master/LICENSE)
- Desired ZIM Description: The popular electronic health records and medical practice management solution.
- Desired ZIM Icon : https://en.wikipedia.org/wiki/File:OpenEMR-Logo-Software-Project.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **no**

Question: does it make sense as a zim file, or should we simply add it as a static content available to install on the hotspot?

**Comment by RavanJAltaie** [comment]
@Popolechien shall I create this as a Zim warehouse path?

**Comment by Popolechien** [comment]
@RavanJAltaie No, come to think of it that's more probably a package for the Hotpot. I'll move it.
