### ISSUE TITLE
New ZIM: Wiki-Scratch

### ISSUE THREAD

**Issue by hsimon78** [openzim/zim-requests#210]
*Please use the following format for a ZIM creation request…*

- Website URL: https://fr.scratch-wiki.info/
- License: CC BY-SA 4.0 
- Desired ZIM Title: Wiki Scratch
- Desired ZIM Description: Wiki de Scratch en français
- Desired ZIM Icon –png (URL or attach one): https://fr.scratch-wiki.info/w/images/4/49/Scratch_Wiki_Fr_logo.svg
- Language (UTF-8): 
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **yes **
- Articles List URL (mediawiki): **n/a**

**Comment by siemsie** [comment]
https://farm.openzim.org/recipes/scratch_wiki_fr
@kelson42 let me know if there is something I'm doing wrong! I'll check in in the next few days to see if "succeeded".

**Comment by kelson42** [comment]
First version https://download.kiwix.org/zim/other/scratch-wiki_fr_all_maxi_2020-03.zim

**Comment by hsimon78** [comment]
Le 22/03/2020 à 11:00, Kelson a écrit :
    
    
      
      Closed #210.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openzim/zim-requests/issues/210#event-3152506971",
"url": "https://github.com/openzim/zim-requests/issues/210#event-3152506971",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    Hello,
    Thank you for doing the job.
    Some points can be improved :
    
      Size of the icons (warning, information...)
          too big.
      Bloc link not working (this is one of the most
          important)
      Tutoriels not available (also very useful)
        
    
    Don't hesitate to contact me...
    Best regards.
        Henri
