### ISSUE TITLE
November scraps seem to be twice as small (or more) as in October

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#213]
That's a random example but 
wikipedia_ar_mathematics_maxi_2019-10.zim -> 69 Mb
wikipedia_ar_mathematics_maxi_2019-11.zim -> 18 Mb

Any idea what happened?

**Comment by kelson42** [comment]
@Popolechien This is a bug, maybe a duplicate of #212... but first time is this is for non WPEN full ZIM file. Will have a look in detail.

**Comment by kelson42** [comment]
@Popolechien I have generated again and everything seems OK now. This is the same version of MWoffliner, so I'm a bit puzzled about the reasons of the problem. I'll close for now this ticket.
