### ISSUE TITLE
Ressources éducatives (ebooks) pour le Primaire

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#214]
Following up on #208 
Based off YouScribe file list from Orange. 
* License: PD
* Desired ZIM Title: Ressources éducative pour le Primaire
- Desired ZIM Description: Près de 1000 resources pédagogiques pour l'école primaire
- Desired ZIM Icon –png (URL or attach one): 
![elementary-school-icon-15](https://user-images.githubusercontent.com/21675885/71078191-2698b680-2189-11ea-8024-f6a2bc36f8f5.jpg)
* Language (ISO 639-3): **fr**
* Desired Main Page (homepage): 
A listing as follows.
> Title (bold, font size+1)
> Theme (column G)
User simply taps on title to get the corresponding content.
* Entry list (Classification (col. F)=primaire in the excel table):
431011
431014
431016
431017
431025
431424
431910
431915
432055
432336
433351
445351
508634
508635
508637
508638
511834
511835
546323
546324
546326
546327
546329
546478
546560
546561
546562
546564
546569
546575
1668428
1668429
1668430
1668431
1668432
1668433
1668434
1668435
1668437
1718997
1719031
1719033
1719034
1719035
1719037
1719038
1719039
1719040
1719041
1719042
1719043
1719044
1719045
1719046
1719047
1719048
1719049
1719050
1719051
1719052
1719053
1719054
1719055
1719056
1719057
1719058
1719059
1719060
1719061
1719062
1719063
1719064
1719065
1719066
1719067
1719068
1719069
1719070
1719071
1719072
1719073
1719074
1719075
1719076
1719077
1719078
1719079
1719080
1719081
1719082
1719083
1719084
1719085
1719086
1719087
1719088
1719089
1719090
1719091
1719092
1719093
1719094
1719095
1719096
1719098
1719099
2310974
2310978
2310980
2310983
2310986
2310987
2311587
2311588
2311589
2311593
2312008
2312010
2312011
2312012
2312013
2312029
2312030
2312031
2312032
2314927
2314928
2314929
2314931
2314933
2314935
2314937
2314939
2314942
2314944
2314945
2314947
2314948
2314951
2314952
2314955
2314957
2314959
2314961
2314965
2314966
2314967
2314970
2314971
2314972
2314975
2314976
2314978
2314980
2314981
2314983
2314984
2314987
2314988
2314990
2314991
2314992
2314995
2314996
2314998
2315000
2315002
2315004
2315005
2315007
2315008
2315010
2315011
2315012
2315013
2315014
2315015
2315016
2315017
2315019
2315020
2315021
2315022
2315024
2315025
2315026
2315028
2315029
2315030
2315031
2315033
2315034
2315035
2315036
2315038
2315039
2315040
2315042
2315043
2315044
2315045
2315047
2315048
2315050
2315051
2315053
2315054
2315055
2315056
2315058
2315059
2315060
2315062
2315063
2315064
2315065
2315067
2315069
2315070
2315071
2315072
2315073
2315075
2315076
2315077
2315079
2315080
2315081
2315083
2315084
2315086
2315087
2315088
2315089
2315091
2315092
2315093
2315094
2315096
2315097
2315098
2315100
2315101
2315102
2315104
2315105
2315106
2315108
2315109
2315110
2315112
2315113
2315114
2315116
2315117
2315119
2315120
2315121
2315123
2315124
2315125
2315126
2315128
2315129
2315131
2315132
2315134
2315136
2315137
2315139
2315140
2315141
2315142
2315144
2315145
2315146
2315147
2315149
2315150
2315151
2315152
2315154
2315155
2315156
2315158
2315159
2315160
2315162
2315163
2315164
2315166
2315167
2315169
2315170
2315172
2315173
2315174
2315175
2315177
2315178
2315179
2315180
2315182
2315183
2315184
2315185
2315186
2315188
2315189
2315190
2315191
2315193
2315194
2315195
2315198
2315199
2315200
2315201
2315202
2315204
2315205
2315206
2315208
2315209
2315211
2315212
2315213
2315215
2315216
2315217
2315218
2315219
2315220
2315221
2315222
2315223
2315224
2315225
2315226
2315227
2315228
2315229
2315230
2315231
2315233
2315234
2315235
2315237
2315238
2315239
2315241
2315242
2315243
2315244
2315246
2315247
2315248
2315249
2315250
2315251
2315253
2315254
2315255
2315256
2315257
2315259
2315260
2315261
2315262
2315265
2315266
2315267
2315268
2315269
2315271
2315272
2315273
2315275
2315276
2315277
2315278
2315279
2315281
2315282
2315283
2315284
2315285
2315287
2315288
2315289
2315290
2315292
2315293
2315294
2315295
2315296
2315298
2315299
2315300
2315301
2315303
2315304
2315305
2315306
2315308
2315309
2315310
2315311
2315313
2315314
2315315
2315316
2315318
2315319
2315320
2315321
2315323
2315324
2315325
2315326
2315328
2315329
2315330
2315332
2315333
2315334
2315335
2315336
2315337
2315338
2315340
2315341
2315342
2315344
2315345
2315346
2315347
2315349
2315350
2315351
2315352
2315353
2315355
2315356
2315357
2315358
2315359
2315360
2315361
2315363
2315364
2315365
2315366
2315368
2315369
2315370
2315372
2315373
2315374
2315376
2315377
2315378
2315379
2315381
2315382
2315383
2315384
2315386
2315387
2315388
2315389
2315390
2315391
2315392
2315393
2315395
2315396
2315397
2315398
2315399
2315401
2315402
2315403
2315405
2315406
2315407
2315408
2315410
2315411
2315412
2315413
2315415
2315416
2315417
2315418
2315421
2315422
2315423
2315424
2315425
2315426
2315428
2315430
2315432
2315433
2315434
2315436
2315437
2315438
2315439
2315440
2315441
2315442
2315444
2315445
2315446
2315448
2315449
2315451
2315452
2315453
2315455
2315456
2315457
2315458
2315459
2315461
2315462
2315464
2315465
2315466
2315467
2315468
2315469
2315470
2315472
2315473
2315474
2315476
2315477
2315478
2315479
2315480
2315482
2315483
2315484
2315485
2315486
2315488
2315489
2315490
2315491
2315492
2315494
2315495
2315496
2315497
2315498
2315500
2315501
2315502
2315503
2315505
2315506
2315507
2315508
2315510
2315512
2315513
2315514
2315515
2315517
2315518
2315519
2315520
2315522
2315523
2315524
2315526
2315527
2315528
2315529
2315531
2315532
2315533
2315534
2315535
2315537
2315538
2315539
2315540
2315541
2315543
2315545
2315546
2315548
2315549
2315550
2315551
2315552
2315553
2315554
2315555
2315557
2315559
2315560
2315562
2315565
2315566
2315568
2315570
2315571
2315573
2315574
2315577
2315578
2315579
2315582
2315583
2315585
2315587
2315588
2315590
2315591
2315593
2315595
2315597
2315600
2315601
2315602
2315604
2315605
2315607
2315609
2315610
2315611
2315614
2315615
2315618
2315620
2315621
2315626
2315628
2315629
2315630
2315633
2315635
2315637
2315638
2315639
2315640
2315643
2315644
2315645
2315648
2315649
2315650
2315653
2315654
2315655
2315657
2315658
2315661
2315662
2315663
2315665
2315667
2315668
2315669
2315672
2315673
2315674
2315675
2315678
2315679
2315682
2315683
2315684
2315686
2315687
2315689
2315691
2315692
2315693
2315695
2315697
2315698
2315700
2315702
2315703
2315705
2315706
2315707
2315709
2315711
2315712
2315713
2315715
2315717
2315718
2315720
2315722
2315723
2315724
2315726
2315728
2315730
2315731
2315733
2315735
2315737
2315740
2315741
2315743
2315744
2315746
2315747
2315751
2315752
2315756
2315757
2315759
2315760
2315762
2315764
2315765
2315767
2315768
2315770
2315771
2315772
2315775
2315776
2315778
2315779
2315781
2315783
2315784
2315786
2315788
2315789
2315790
2315792
2315795
2315796
2315799
2315803
2315804
2315807
2315808
2315811
2315813
2315814
2315815
2315816
2315820
2315821
2315822
2315824
2315825
2315827
2315829
2315830
2315831
2315834
2315835
2315836
2315839
2315840
2315844
2315845
2315846
2315849
2315850
2315851
2315853
2315854
2315855
2315858
2315859
2315861
2315863
2315864
2315867
2315868
2315870
2315872
2315873
2315876
2315877
2315878
2315881
2315882
2315883
2315885
2315887
2315888
2315890
2315892
2315893
2315896
2315898
2315899
2315902
2315905
2315906
2315908
2315911
2315914
2315918
2315922
2315930
2315934
2315943
2315944
2315945
2315946
2328044
2328048
2427974
2428010
2428073
2428096
2428097
2428098
2428099
2428101
2428102
2428103
2428104
2428105
2428106
2428108
2428109
2428119
2428121
2428123
2428128
2428131
2428132
2428198
2428202
2428736
2428738
2428739
2428753
2428754
2428755
2428756
2428781
2428782
2428785
2428788
2428789
2428791
2428793
2428795
2428796
2428797
2428798
2428801
2428802
2428803
2429557
2429559
2429560
2429561
2429563
2429564
2429565
2429566
2429568
2429569
2429582
2429585
2429588
2429589
2429590
2430072
2430073
2430076
2430077
2430080
2430081
2430082
2431495
2431496
2431497
2431499
2431500
2431510
2431540
2431541
2431542
2433482
2433484
2433486
2433487
2433488
2433489
2433491
2433493
2433494
2433496
2433497
2433500
3080069
3080070
3080071
3080073
3080074
3080075
3080076
3080177
3080363
3080364
3080365
3080366
3080367
3080368
3080369
3080370
3080371
3080372
3080373
3080374
3080375
3080376
3080377
3080378
3080379
3080380
3080381
3080382
3080383
3080384
3080385
3080386
3080387
3080388
3080389
3080390
3080391
3080392
3080393
3080394
3080395
3080396
3080397
3080398
333230
333326
333524
333660
1718998
1718999
1719000
1719001
1719002
1719003
1719004
1719005
1719006
1719007
1719008
1719009
1719010
1719011
1719012
1719013
1719014
1719015
1719016
1719017
1719018
1719019
1719020
1719021
1719022
1719023
1719024
1719025
1719026
1719027
1719028
1719029
1719030
1719032
1719036

**Comment by kelson42** [comment]
@Popolechien 
* Why a new ticket (why not reusing #208)?
* Where are all the content?
* Is that a one shot?
* Which metadata should be on the homepage
* Where are the metadata?
* Which one should be taken in account?
* Why we don't upload in the filebrowsing extension? Why a ZIM?

**Comment by kelson42** [comment]
https://download.kiwix.org/zim/other/youscribe_fr_primaire_2020-01.zim
