### ISSUE TITLE
Ressources éducatives (ebooks) pour le Collège

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#215]
Following up on #208 _et al._
Based off YouScribe file list from Orange. 
* License: PD
* Desired ZIM Title: Ressources éducative pour le Colège
*Desired ZIM Description: Près de 1400 resources pédagogiques pour le collège
* Desired logo:
![abc_backpack_elementary_school_education_icon-icons com_75499](https://user-images.githubusercontent.com/21675885/71080204-ffdc7f00-218c-11ea-8dbd-aca2276e54eb.png)

* Language (ISO 639-3): **fr**
* Desired Main Page (homepage): 
A listing as follows.
> Title (bold, font size+1)
> Theme (column G)
User simply taps on title to get the corresponding content.
* Entry list (Classification (col. F)=primaire in the excel table):
2435605
2435617
2435618
434983
333715
333725
333864
333872
333919
333926
333935
333959
333967
333972
333981
333997
334071
334096
334100
334105
334110
334111
334117
334149
334151
334166
334192
334202
334205
334206
334212
334219
334233
334245
334249
334252
334257
334293
334294
334307
334327
334342
334344
334378
334379
334386
334396
334400
334403
334407
334409
334419
334420
334433
334441
334445
334460
334471
334477
334484
334491
334498
334508
334510
334529
334543
335798
340945
340946
340947
340948
340949
340950
340951
340952
340953
340954
340955
340956
340957
340958
340959
340960
340961
340962
340963
340964
340965
340966
340967
340968
340969
340970
340971
340972
340973
340974
340975
340976
340977
340978
340979
340981
340982
340983
340984
340985
340986
340987
340988
340989
340990
340991
340992
340993
340994
340995
340996
340997
340998
340999
341000
341001
341005
341007
341008
341009
341010
341011
341012
341013
341014
341015
341016
341018
341019
341020
341021
341022
341023
341024
341025
341026
341027
341028
341029
341030
341031
341032
341033
341034
341035
341036
341037
341038
341039
341040
341041
341042
341043
341044
341045
341046
341047
341048
341049
341050
341051
341052
341053
341054
341055
341056
341057
341058
341059
341060
341061
341062
341063
341066
341069
341070
341074
341076
341079
341083
341084
341086
341089
341090
341091
341092
341093
341094
341095
341101
341102
341103
341105
341107
341109
341110
341111
341112
341113
341115
341116
341118
341119
341120
341121
341122
341123
341125
341126
341129
341130
341132
341136
341137
341138
341139
341140
341142
341143
341145
341146
341150
341151
341154
341160
341162
341165
341166
341167
341175
341177
351776
351777
351778
351779
351780
353563
353564
353565
353566
353567
353568
353569
353570
353571
353572
353573
353574
353575
353576
353577
353578
353579
353580
353581
353582
353583
353584
353585
353586
353587
353588
353589
353590
353591
353592
353593
353595
353596
353604
353607
353609
353610
353611
353612
353613
353614
353615
353616
353617
353618
353619
353620
353621
353622
353623
353624
353625
353626
353627
353628
353629
353630
353631
353632
353633
353634
353635
353636
353637
353638
353639
353640
353641
353642
353643
353644
353645
353646
353647
353648
353649
353650
353651
353652
353653
353654
353655
353656
353657
353658
353659
353660
353661
353662
353663
353664
353665
353666
353667
365774
430821
431491
431510
431514
431575
431577
431913
431914
434284
434286
434287
434288
434308
434309
445794
445981
446186
446373
447508
496504
505165
511830
511831
546473
546474
546475
546477
1413009
1654991
1654992
1654994
1654995
1654997
1655001
1655003
1655004
1655005
1655009
1655010
1655012
1655015
1655016
1655017
1655020
1655021
2236405
2263050
2304719
2304745
2304748
2304769
2304808
2304809
2304810
2304811
2305328
2305385
2306328
2306329
2306331
2306360
2306361
2306362
2306684
2306712
2306713
2306715
2306717
2306718
2306719
2306720
2306721
2306748
2306750
2306752
2307245
2307246
2307247
2307252
2307253
2307254
2307268
2307269
2307270
2307271
2307289
2307290
2307292
2307295
2307297
2307299
2307301
2307302
2307314
2307315
2307316
2307318
2307320
2307322
2307323
2307324
2307326
2307327
2307329
2307330
2307331
2307333
2310551
2310552
2310553
2310554
2310565
2310566
2310574
2310576
2310578
2310912
2310913
2310914
2310915
2310916
2310917
2310920
2310921
2310923
2310924
2310926
2310966
2310967
2310977
2311598
2311599
2313732
2315794
2315798
2315806
2315809
2315976
2320179
2320464
2320641
2320777
2321024
2321123
2321324
2321441
2323327
2323328
2323330
2323332
2323334
2323336
2323337
2324698
2324699
2324701
2324702
2324703
2324704
2324705
2324706
2324708
2325750
2325751
2325752
2325753
2325754
2325755
2325756
2325757
2325758
2325759
2326254
2326255
2326256
2326258
2326259
2326260
2326261
2326262
2326264
2326265
2326266
2326268
2326271
2326272
2326273
2326274
2326302
2326306
2326307
2326308
2328427
2328432
2328433
2328434
2328435
2328436
2328437
2328439
2328440
2328491
2328492
2328493
2328494
2328495
2328497
2328499
2328597
2328599
2328601
2328602
2328604
2328605
2328639
2328640
2328642
2328644
2328645
2328646
2328647
2328648
2328649
2328650
2328651
2328652
2328654
2332727
2332728
2332731
2336085
2336087
2336088
2336089
2336091
2336092
2336094
2336096
2336098
2336100
2336101
2336103
2336104
2336106
2336108
2336110
2336112
2336113
2336114
2336115
2336118
2336119
2336120
2336125
2336126
2336128
2336134
2336136
2336138
2336454
2336455
2348748
2348750
2348752
2348753
2348755
2348756
2348757
2348758
2348759
2348761
2348762
2348763
2348764
2348766
2348771
2348772
2348774
2348776
2348779
2348781
2348784
2351251
2351255
2351256
2351257
2351258
2351259
2351261
2353392
2353393
2353394
2353625
2353626
2353629
2353680
2353681
2353683
2353685
2353686
2353688
2353690
2353691
2353692
2353693
2353982
2353983
2353984
2353985
2353990
2353992
2353994
2354693
2354908
2354911
2354918
2354922
2354923
2355757
2355774
2355775
2355779
2355780
2355781
2355783
2355786
2355787
2355788
2355790
2364495
2364496
2370660
2370667
2370670
2371019
2371020
2371021
2371038
2371041
2371255
2371265
2371347
2371363
2371398
2371406
2371410
2371411
2371414
2371415
2371418
2371419
2371420
2371422
2371423
2371424
2371426
2371434
2371436
2371437
2371438
2371440
2371441
2371462
2371467
2371468
2371475
2371482
2371519
2371520
2371521
2371522
2371523
2371524
2371525
2371526
2371528
2371529
2371530
2371531
2371532
2371533
2371534
2371538
2371540
2371542
2371550
2371552
2371556
2371557
2371558
2371560
2371561
2371562
2371563
2371564
2371565
2371569
2371572
2371573
2371574
2371576
2371577
2371578
2371579
2371582
2371583
2371586
2371589
2371593
2371596
2371599
2371600
2371602
2371968
2371969
2371970
2371973
2371976
2371977
2371978
2371979
2371981
2372240
2372242
2372243
2372264
2372265
2372266
2372268
2372275
2372276
2372277
2373169
2373756
2373757
2373758
2373760
2373761
2373803
2373804
2373805
2373806
2373807
2373818
2373820
2373821
2373827
2374285
2374288
2374289
2374301
2374311
2374314
2374702
2374704
2374705
2374706
2374707
2374708
2375365
2375933
2375934
2375935
2375937
2375939
2375941
2375945
2375983
2376116
2376120
2377475
2377476
2377478
2377479
2377480
2377481
2377482
2377484
2377485
2377486
2377489
2377491
2377607
2377619
2378000
2378002
2378006
2378007
2378029
2378033
2378034
2378039
2378040
2378041
2378042
2378057
2378058
2378075
2378088
2378091
2378184
2378210
2378218
2378228
2378239
2378245
2378253
2378323
2378389
2378421
2378459
2382512
2382514
2382516
2382517
2382518
2382524
2382527
2382529
2382531
2382532
2382535
2382884
2382885
2382886
2382888
2382891
2382892
2382893
2382894
2382895
2382898
2382901
2382902
2382903
2382904
2382905
2382906
2382914
2382917
2383972
2383973
2383974
2383976
2383979
2383982
2383983
2383996
2384000
2384002
2384003
2384004
2384005
2384006
2384007
2384008
2384009
2384245
2384249
2384251
2384252
2384281
2384282
2384285
2384288
2384291
2384293
2384328
2384331
2384337
2384343
2384352
2384355
2384356
2384357
2384612
2385417
2385420
2385423
2385425
2385427
2385430
2385431
2385432
2385475
2385488
2385489
2385491
2385492
2385495
2385496
2385931
2385933
2385936
2385938
2385939
2385943
2386566
2386569
2386571
2386575
2386579
2386581
2386582
2388024
2388025
2388026
2388029
2388044
2388047
2388048
2388049
2388050
2388051
2388053
2389799
2389800
2389801
2389803
2389804
2389805
2389806
2389808
2390017
2390019
2390020
2390021
2390022
2390364
2390365
2390366
2390370
2390371
2390398
2390399
2390401
2390405
2390409
2390411
2390412
2392117
2392118
2392119
2392120
2392121
2392130
2392132
2392134
2392135
2392136
2392137
2392138
2392140
2392142
2392143
2392316
2392317
2392319
2392324
2392327
2392330
2392332
2392333
2392352
2392353
2392354
2392355
2392356
2392357
2392358
2392359
2392360
2392361
2394295
2394302
2398136
2398137
2398140
2400013
2400014
2400016
2400017
2402259
2402261
2402263
2402265
2402266
2402310
2402311
2402312
2402314
2402315
2402317
2402432
2402433
2402434
2402435
2402436
2402437
2402439
2402442
2402488
2402489
2402491
2402494
2404923
2404925
2404926
2404927
2404928
2404929
2404971
2404972
2404973
2404975
2425260
2425262
2425264
2425265
2425266
2425268
2425271
2425272
2425273
2425275
2425295
2425297
2425298
2425299
2425302
2425303
2425305
2425306
2425307
2425312
2425315
2425316
2425318
2425321
2425323
2425326
2425329
2427813
2427815
2427819
2427821
2427824
2427827
2427830
2427833
2428113
2428114
2428115
2428116
2428117
2428118
2433365
2433366
2433368
2433385
2433386
2433387
2433388
2433389
2433390
2433392
2433393
2433394
2433395
2433396
2433397
2433398
2433399
2433401
2433403
2433404
2433405
2433407
2433408
2433409
2433410
2433412
2433413
2433414
2433415
2433416
2433417
2433418
2433419
2433420
2433421
2433422
2433423
2433424
2433425
2433426
2433435
2433436
2433437
2433439
2433441
2433452
2433454
2433457
2433461
2433462
2433464
2433465
2433466
2433481
2433483
2433485
2435590
2435592
2435594
2435595
2435597
2435600
2435602
2435615
2435616
2435622
2435632
2435648
2435649
2437025
2437027
2437028
2437030
2437031
2437032
2437033
2437034
2437035
2437036
2437037
2437038
2437039
2437040
2437041
2437042
2437043
2437044
2437045
2437047
2437048
2437049
2437050
2437052
2437053
2437054
2437055
2437056
2437057
2437058
2437831
2447692
2462271
2462272
2462274
2462285
2462287
2462288
2462289
2462290
2462297
2462308
2462309
2462310
2462346
2462348
2462349
2462612
2462616
2462706
2462707
2462711
2462743
2462753
2462757
2462758
2463390
2483293
2586632
2586633
2586634
2586635
2586636
2586637
2586638
2586639
2586640
2586641
2586643
2586644
2586839
2586840
2586841
2586842
2587133
2587138
2587141
2587143
2587144
2587145
2587146
2587147
2587149
2587150
2587151
2587157
2587160
2587163
2587165
2587176
2587180
2587181
2587182
2587186
2587187
2587188
2587190
2587192
2587222
2587223
2587225
2587249
2587251
2587259
2587272
2587314
2587322
2587324
2587325
2587328
2587330
2587333
2587334
2587349
2587352
2587353
2587354
2660175
2741347
2741349
2741352
2741357
2741359
2741360
2741361
2741376
2741378
2741379
2741381
2741384
2741405
2741406
2741407
2741411
2741417
2741419
2741424
2741427
2741519
2741520
2741524
2741525
2741556
2741557
2741593
2741594
2741595
2741596
2741598
2844378
2844379
2844380
2844719
2844725
2844727
2844728
2844729
2844742
2844743
2845061
2845081
2845082
2845094
2845097
2845098
2845100
2845102
2845111
2845112
2845113
2845114
2964119
2964154
2964155
2964303
2964304
2964305
2964306
2964369
2964370
2964375
2964376
2964377
2964378
2964379
2964380
2964381
2964382
2964383
2964384
2964388
2964389
2964390
2964391
3060225
3060227
3060228
3060230
3060234
3060322
3060441
3060443
3062363
3062365
3062390
3064001
3064002

**Comment by kelson42** [comment]
https://download.kiwix.org/zim/other/youscribe_fr_college_2020-01.zim
