### ISSUE TITLE
Ressources éducatives (ebooks) pour le Lycée

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#216]
Following up on #208 _et al._
Based off YouScribe file list from Orange. 
* License: PD
* Desired ZIM Title: Ressources éducative pour le Lycée
*Desired ZIM Description: Plus de 1000 resources pédagogiques pour le collège
* Desired logo:
![high-school-icon-62](https://user-images.githubusercontent.com/21675885/71080060-b429d580-218c-11ea-852f-6c2d6893acad.png)
* Language (ISO 639-3): **fr**
* Desired Main Page (homepage): 
A listing as follows.
> Title (bold, font size+1)
> Theme (column G)
User simply taps on title to get the corresponding content.
* Entry list (Classification (col. F)=primaire in the excel table):
1657791
1657793
1657794
1657795
1659959
1996186
1996203
1996204
1996205
1996206
1996207
1996208
1996209
1996210
1996211
1996212
1996213
1996214
1996215
1996216
1996217
1996218
1996219
1996220
1996221
1996222
1996223
1996224
1996225
1996226
1996227
1996228
1996229
1996230
1996231
1996232
1996233
1996234
1996235
1996243
1996244
1996245
1996246
1996247
1996248
1996249
1996250
1996251
1996252
1996253
1996254
1996255
1996256
1996257
1996258
1996259
1996260
1996261
1996262
1996263
1996264
1996265
1996266
1996267
1996268
1996269
1996270
1996271
1996272
1996273
1996274
1996432
1996433
1996434
1996435
1996436
1996437
1996438
1996439
1996440
1996441
1996442
1996443
1996444
1996445
1996446
1996447
1996448
1996449
1996450
1996451
1996452
1996453
1996454
1996455
1996456
1996564
1996565
1996567
1996571
1996573
1996574
1996575
1996576
1996577
1996578
1996579
1996580
1996581
1996582
1996583
1996584
1996585
1996586
1996587
1996588
1996589
1996590
1996591
1996592
1996593
1996594
1996595
1996596
1996597
1996598
1996599
1996600
1996601
1996602
1996603
1996604
1996634
1996635
1996636
1996642
1996643
1996646
1996647
1996648
1996649
1996665
1996667
1996668
1996670
1996674
2170384
2170390
2170480
2170641
2170695
2170736
2170769
2170799
2170839
2170947
2171000
2171062
2222384
2222388
2222390
2222392
2222437
2222544
2222764
2222933
2222934
2222938
2222939
2222941
2222974
2222975
2222983
2223000
2223031
2223701
2223736
2223740
2224293
2224837
2225733
2234036
2234048
2234465
2234469
2234488
2234496
2234498
2234502
2234507
2234509
2234518
2234562
2234567
2234569
2235067
2235075
2235082
2235119
2235123
2235133
2235134
2235558
2235559
2313708
2313709
2313710
2313711
2313713
2313715
2313716
2313717
2313720
2313721
2313722
2313723
2313726
2313727
2313729
2313730
2313733
2313755
2313757
2313803
2313805
2313806
2313808
2326300
2326303
2326713
2327475
2327476
2327479
2327480
2327481
2327482
2327483
2327484
2327485
2327644
2327645
2327646
2327648
2327649
2328042
2328043
2337329
2337805
2337816
2337818
2337820
2337830
2337832
2337833
2337865
2337866
2337867
2337879
2337881
2337882
2337899
2337900
2338338
2338339
2338340
2338341
2338342
2338343
2338344
2338346
2338350
2338353
2338354
2338355
2338356
2338358
2338361
2338363
2338364
2338366
2338367
2338368
2338370
2338371
2338372
2338373
2338374
2338375
2338376
2338377
2338378
2338380
2338388
2339398
2339399
2339508
2349697
2349698
2349700
2349702
2349704
2350529
2350530
2350535
2350536
2350537
2350547
2350548
2350549
2350550
2350551
2350552
2350553
2351197
2351198
2351199
2351200
2351201
2351202
2351203
2351204
2351205
2351206
2353388
2353995
2354027
2354036
2355753
2355755
2355756
2355758
2355759
2355761
2355762
2369994
2370273
2370389
2370446
2370528
2370575
2370640
2370641
2370642
2370644
2370646
2370647
2370648
2370649
2370650
2370651
2370652
2370653
2370654
2370657
2370658
2370659
2370661
2370663
2370664
2370665
2370666
2370668
2370669
2370672
2370674
2370675
2370676
2370679
2370680
2370682
2370683
2370684
2370685
2370686
2370687
2370689
2370690
2370692
2370693
2370694
2370695
2370696
2370969
2370971
2370973
2370974
2370976
2370977
2370979
2370982
2370987
2370988
2370998
2371009
2371010
2371013
2371029
2371035
2371264
2371267
2371306
2371417
2371957
2371995
2371997
2372003
2372017
2372018
2372023
2372027
2372029
2372030
2372032
2372033
2372206
2372216
2372217
2372218
2372219
2372220
2372221
2372222
2372223
2372224
2372231
2372267
2372286
2372289
2373165
2373167
2373172
2373173
2373174
2373181
2373182
2373184
2373186
2373187
2373190
2373195
2373199
2373200
2373201
2373202
2373203
2373828
2373829
2373830
2373831
2373832
2373835
2374021
2374022
2374024
2374025
2374026
2374027
2374028
2374029
2374041
2374042
2374043
2374044
2374045
2374046
2374047
2374048
2374049
2374050
2374051
2374052
2374053
2374055
2374056
2374074
2374149
2374235
2374269
2374270
2374271
2374272
2374273
2374278
2374280
2374281
2374339
2374343
2374346
2374347
2374349
2374350
2374352
2374353
2374354
2374356
2374357
2374358
2375337
2375339
2375340
2375343
2375347
2375350
2375353
2375354
2375355
2375359
2375361
2375364
2375367
2375368
2375369
2375370
2375371
2375372
2375380
2375381
2375383
2375384
2375385
2375386
2375388
2375389
2375390
2375391
2375392
2375393
2375903
2375910
2375915
2375917
2375918
2375920
2375944
2375946
2375947
2375952
2375961
2375962
2375964
2375966
2375967
2375968
2375970
2375972
2375973
2375978
2375984
2375985
2375988
2375989
2375991
2375992
2375993
2376008
2376009
2376010
2376012
2376014
2376015
2376016
2376017
2376018
2376020
2376021
2376022
2376101
2376103
2376106
2376108
2376109
2376111
2376112
2376113
2376115
2376117
2376118
2376119
2376122
2376123
2376125
2376134
2376135
2376138
2376139
2376140
2376141
2376142
2376143
2376144
2376145
2376146
2376147
2376148
2376151
2376152
2376154
2376155
2376156
2376157
2376158
2376159
2382945
2382946
2382947
2382950
2382952
2382953
2382955
2382958
2382961
2382963
2382964
2382966
2382967
2383209
2383211
2383212
2383214
2383215
2383227
2383247
2383251
2383253
2383255
2383256
2383257
2383261
2383920
2383927
2383929
2383930
2413390
2413394
2413395
2413396
2413397
2413703
2413704
2413706
2413732
2413733
2413734
2413735
2414531
2414532
2414533
2423615
2423616
2423617
2423618
2423619
2423620
2423621
2423622
2423625
2423626
2431527
2431530
2431531
2431532
2431536
2431544
2431546
2431548
2431549
2431550
2431551
2431552
2431555
2431558
2431559
2431562
2431566
2431569
2431864
2431866
2431867
2431869
2431870
2431871
2431878
2431880
2431881
2431889
2431925
2431926
2431952
2431954
2431967
2431969
2431970
2431972
2431977
2432000
2440273
2440291
2440297
2444234
2444238
2444242
2444252
2459427
2459428
2459431
2459477
2459481
2459485
2459489
2459491
2459498
2459501
2459509
2459522
2459550
2459571
2459572
2459573
2459776
2459783
2459785
2459801
2459802
2459818
2459826
2459833
2459847
2459872
2459873
2459891
2459907
2459935
2459936
2460080
2460082
2460093
2460221
2460226
2460275
2460282
2460283
2460284
2460296
2460307
2460308
2460450
2460451
2460719
2460727
2460744
2460764
2460774
2460782
2460805
2460812
2460824
2461183
2461243
2461244
2461245
2461248
2461249
2461256
2461260
2461261
2461303
2461307
2461314
2461317
2461323
2461324
2461333
2461334
2461711
2461713
2461715
2461737
2461756
2461758
2461759
2461760
2483276
2483277
2483278
2483279
2483280
2483281
2483282
2483283
2483284
2483285
2483286
2483287
2483288
2483289
2483290
2483301
2483309
2483310
2483322
2483326
2483332
2483343
2483406
2483407
2483408
2483409
2584116
2584119
2584120
2584172
2584177
2584178
2584179
2584188
2584190
2584191
2584204
2584205
2584206
2584239
2584245
2584267
2584270
2584272
2584275
2584397
2584406
2584438
2584443
2584452
2584578
2584583
2584591
2584597
2584609
2584688
2584691
2584698
2584712
2584845
2584848
2584850
2584954
2584972
2584995
2585031
2585035
2585038
2585041
2585043
2585045
2585126
2585131
2585136
2585139
2585147
2585441
2585443
2585444
2585446
2585448
2585449
2585474
2585534
2585540
2585629
2585648
2585656
2585657
2585696
2585731
2585732
2585735
2585738
2585762
2585781
2585785
2585787
2585878
2585879
2585880
2586026
2586032
2586042
2586145
2586151
2586155
2586160
2586163
2586165
2586214
2586218
2586219
2586400
2586401
2586407
2586508
2586587
2586648
2586764
2586773
2586775
2586780
2586815
2586816
2586826
2586831
2737425
2738268
2738269
2738296
2738299
2738308
2738501
2738502
2738504
2738507
2738511
2738517
2738518
2738521
2738524
2738526
2738579
2738589
2738594
2738620
2738790
2738793
2738794
2738796
2738829
2738851
2738871
2738883
2738912
2738918
2738919
2738923
2738925
2738926
2738962
2738964
2738987
2739019
2739024
2739026
2739295
2739296
2739297
2739314
2739463
2739464
2739466
2739542
2739544
2739560
2739564
2739567
2739570
2739571
2739608
2739620
2739621
2739622
2739623
2739627
2739628
2739629
2739630
2739632
2739635
2739637
2739639
2739645
2739865
2739962
2739964
2739966
2739968
2739969
2739971
2739973
2739975
2739976
2739977
2739979
2739980
2739982
2739983
2739984
2739986
2739988
2739991
2739992
2739993
2740010
2740017
2740018
2740019
2740051
2740052
2740294
2740299
2740304
2740315
2740417
2740446
2740448
2740457
2740493
2740495
2740496
2740498
2740504
2740559
2740560
2740568
2740571
2740714
2740718
2740725
2740727
2740775
2740777
2740806
2740809
2740843
2740848
2740860
2740871
2740906
2740909
2740910
2740912
2740914
2740916
2740974
2740986
2740989
2741002
2741330
2741362

**Comment by kelson42** [comment]
https://download.kiwix.org/zim/other/youscribe_fr_lycee_2020-01.zim
