### ISSUE TITLE
Radiopaedia

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#217]
- Website URL: https://radiopaedia.org/
- License: cc-nc-sa
- Desired ZIM Title: Radiopaedia
- Desired ZIM Description: Radiopaedia is a radiology resource compiled by radiologists and other health professionals from across the globe.
- Desired ZIM Icon –png: https://en.wikipedia.org/wiki/File:Radiopaedia_org_logo_small.jpg
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by kelson42** [comment]
Ce n'est pas un Mediawiki
