### ISSUE TITLE
New ZIM: fountainpen.it

### ISSUE THREAD

**Issue by valholl** [openzim/zim-requests#218]
- Website URL: https://www.fountainpen.it/
- License: **GNU Free Documentation License 1.2**
- Desired ZIM Title: **FountainPen.it**
- Desired ZIM Description: **Un sito dedicato a storia e tecnica della stilografica**
- Desired ZIM Icon –png (URL or attach one): http://www.fountainpen.it/images/thumb/1/14/LogoFP.svg/219px-LogoFP.svg.png
- Language (ISO 639-3): **ita**
- Desired Main Page (homepage): **https://www.fountainpen.it/Pagina_principale**
- Is this a MediaWiki?: **yes**
- Articles List URL (mediawiki): **n/a**

Please note that the site is mostly in Italian, but a few pages have been translated to english (and will be served in english to browsers that accept that language by preference: is this a problem?

**Comment by Popolechien** [comment]
@kelson42 @rgaudin I've [cloned a recipe](https://farm.openzim.org/recipes/fountainpen_it_all) and requested the zim creation. Let me know if the parameters look ok.

**Comment by valholl** [comment]
To me it looks reasonable.

About the “failed“, is it because it hasn't run yet, or could there be something wrong on the wiki side?

**Comment by rgaudin** [comment]
No it’s actually a si farm bug copying the duration from the schedule it
was cloned from. will try to get it to run tomorrow but it looks good.

**Comment by rgaudin** [comment]
Looks like it succeeded: [fountainpen_it_all_maxi_2020-01.zim](https://download.kiwix.org/zim/other/fountainpen_it_all_maxi_2020-01.zim)

**Comment by Popolechien** [comment]
OK, the landing page is not what was specified (I get 1761 on macOS and a blank on Kiwix-JS). Also redirects are not taken (I tried with Cronologia on the 1761 article): I'll open tickets on /openzim/mwoffliner

**Comment by Popolechien** [comment]
Ah interestingly a bunch of text is also missing from Chronology itself.

**Comment by kelson42** [comment]
@Popolechien I fixed it, a title is expected there, not a URL
