### ISSUE TITLE
New ZIM: stupidedia.org

### ISSUE THREAD

**Issue by chjohn22** [openzim/zim-requests#219]
Since January 2018, Stupidedia is not actively maintained anymore. It is/was a big part of Austrian, Swiss and German (DACH) Internet culture and needs to be preserved, ideally in a ZIM-file.
- Website URL: https://www.stupidedia.org
- License: GNU Free Documentation License 1.2
- Desired ZIM Title: Stupidedia
- Desired ZIM Description: Stupidedia - Die sinnfreie Enzyklopädie
- Desired ZIM Icon –png (URL or attach one): https://www.stupidedia.org/stupi/Datei:Stupidedia_Stern.svg
- Language (ISO 639-3): deu
- Desired Main Page (homepage): https://www.stupidedia.org/stupi/Stupidedia:Hauptseite
- Is this a MediaWiki?: yes
- Articles List URL (mediawiki): https://www.stupidedia.org/stupi/Spezial:Alle_Seiten

**Comment by kelson42** [comment]
@chjohn22 I have created a recipe for it, we should get a first ZIM soon

**Comment by chjohn22** [comment]
Thanks, according to the pipeline the task was finished sucessfully! Do you know how long it takes until it will be available to download?
Additionally: I see you set the recipe to run monthly, this is not necessary as the whole project is in a frozen state and will not be updated with new content.

**Comment by chjohn22** [comment]
The [debug file](https://farm.openzim.org/pipeline/5e24803a9e9a48d7686528d4/debug) shows two errors:

> [2020-01-20 02:58:15,693: ERROR] ZIM Uploader:: b'[2020-01-20 02:57:30,671: INFO] Starting upload of /data/stupidedia_de_all_maxi_2020-01.zim to sftp://uploader@warehouse.farm.openzim.org:1522/zim/other/stupidedia_de_all_maxi_2020-01.zim\n[2020-01-20 02:57:30,672: INFO] Executing: /usr/bin/sftp -i /etc/ssh/keys/zimfarm -b /tmp/tmpdu0kqpa_.txt -o GlobalKnownHostsFile /etc/ssh/known_hosts -c aes128-ctr sftp://uploader@warehouse.farm.openzim.org:1522/zim/other/\n[2020-01-20 02:58:15,041: ERROR] sftp failed returning 1:: Warning: Permanently added the ECDSA host key for IP address \'[195.154.156.115]:1522\' to the list of known hosts.\nsftp> put /data/stupidedia_de_all_maxi_2020-01.zim stupidedia_de_all_maxi_2020-01.zim.tmp\nCouldn\'t write to remote file "/zim/other/stupidedia_de_all_maxi_2020-01.zim.tmp": Failure\n\n'
and

> [2020-01-20 02:58:18,117: ERROR] ZIM files exists ; __NOT__ removing: [('stupidedia_de_all_maxi_2020-01.zim', '614.51 MiB')]

**Comment by kelson42** [comment]
I reopen it, as long as the ZIM file is not online, so we can check it.

**Comment by rgaudin** [comment]
yes, it's uploaded but hasn't passed the quarantine yet.

```
615M Jan 22 17:55 /data/zimfarm-warehouse/zim/other/stupidedia_de_all_maxi_2020-01.zim
```

**Comment by chjohn22** [comment]
Quarantine?

**Comment by rgaudin** [comment]
ZIM files are checked once uploaded for conformity using a different tool (`zimcheck`). It's a long process and given the throughput of the zimfarm now, it's become a bottleneck.

**Comment by chjohn22** [comment]
Ok, is there a way to help? Does zimcheck run locally on the worker itself?

**Comment by kelson42** [comment]
@chjohn22 Being a bit patient or fixing https://github.com/openzim/zimfarm/issues/385

**Comment by kelson42** [comment]
http://download.kiwix.org/zim/stupidedia_de_all_maxi.zim

**Comment by kelson42** [comment]
http://download.kiwix.org/zim/other/stupidedia_de_all_maxi_2020-01.zim

**Comment by chjohn22** [comment]
Thanks!
I have one problem with the ZIM. It seems as if only hyperlinks on the start page will work, hyperlinks within articles simply do not load in Kiwix for Android 2.5.3.
On Kiwix Desktop on macOS 2.0.9 the click on a hyperlink within an article causes the crash of the application. I only have this problem with this ZIM so I thought I will post it in this Issue.

Reproduce:
1. Download stupidedia-ZIM
2. Open a random article
3. click a random hyperlink
4. nothing happens / app crashes

**Comment by Popolechien** [comment]
Same issue on Kiwix-JS 2.6.0 (Chrome), with this additional warning: 
"This ZIM is not fully supported in jQuery mode"

**Comment by kelson42** [comment]
@chjohn22 @Popolechien No need to keep that ticket open.
* URL problem is probably https://github.com/openzim/mwoffliner/issues/1017
* macOS crash is https://github.com/kiwix/apple/issues/157

**Comment by chjohn22** [comment]
@kelson42 Could we rerun the recipe, now that openzim/mwoffliner#1017 seems to be fixed?

**Comment by Popolechien** [comment]
@chjohn22 Just tested the [last version](https://farm.openzim.org/pipeline/5f00a723ebc9e0b38973f1d8) - Still not working but apparently a different issue ([#1202](../..//mwoffliner/issues/1202)).

**Comment by chjohn22** [comment]
Now that https://github.com/openzim/mwoffliner/issues/1203 is fixed and the monthly run of the recipe (https://farm.openzim.org/pipeline/5f7732a202bee71bcbdf1070) is finished, there is another problem. The .zim is less than 2 Megabytes in size and not working obviously.

**Comment by Popolechien** [comment]
Yeah apparently there's another fix coming.

**Comment by chjohn22** [comment]
The version from November works fine now. Thank you very much for all your efforts and hard work @rgaudin @kelson42 @Popolechien !

**Comment by kelson42** [comment]
@chjohn22 Thank you for the feedback(s)
