### ISSUE TITLE
Retire icd10_fr_all_2012-01

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#220]
The current revision is [ICD 11](https://icd.who.int/browse11/l-m/en) and it being medical I'd rather not have us distribute outdate material.
Also, and as importantly, the ZIM actually has a ton of empty fields: try clicking any of the entries here: http://library.kiwix.org/icd10_fr_all_2012-01/A/CIM-10:%20List%20des%20chapitres.html#f00

**Comment by kelson42** [comment]
Done
