### ISSUE TITLE
New ZIM: Pokewiki.de

### ISSUE THREAD

**Issue by Sofi204** [openzim/zim-requests#222]
I'm not sure I did that right.
My English is not so good.

Since there are already https://www.pokepedia.fr/Portail:Accueil and https://bulbagarden.net/ I wish for the German side.

I have already tried to download it myself, but it did not work.

I would be happy if it would work.

With kind regards

*Please use the following format for a ZIM creation request…*

- Website URL: https://pokewiki.de/
- License: Creative Commons
- Desired ZIM Title: PokeWiki
- Desired ZIM Description: PokeWiki - Die deutsche Pokemon-Enzyklopädie
- Desired ZIM Icon –png (URL or attach one): https://pbs.twimg.com/profile_images/876560637564002305/HBbDXTbd_400x400.jpg
- Language (ISO 639-3): deu
- Desired Main Page (homepage): https://pokewiki.de/
- Is this a MediaWiki?: yes
- Articles List URL (mediawiki): https://www.pokewiki.de/Spezial:Alle_Seiten

**Comment by Popolechien** [comment]
I've launched a receipe, let's wait and see.
https://farm.openzim.org/recipes/Pokewiki

**Comment by Sofi204** [comment]
ok many thanks

please let me know if there is any news.

**Comment by Popolechien** [comment]
It's a couple of days normally but we've had a few bugs lately with the interlinks so I'm not entirely confident it'll be consumption ready (but at least we'll know).

**Comment by Sofi204** [comment]
okay, then I hope it works out.

and it's okay if it takes longer.

**Comment by Sofi204** [comment]
hello

I wanted to ask what the current status is here?
but I don't want to seem annoying. 

Best regards
Sofi204

**Comment by rgaudin** [comment]
ZIM creation failed 3 times inside mwoffliner. Here's the [last attempt](https://farm.openzim.org/pipeline/5e30c5deba3b9910fb8613b0/debug)

@kelson42 can probably guess the problem from the log so we can fix the recipe.

**Comment by kelson42** [comment]
@rgaudin I'm clueless for the moment.

**Comment by Sofi204** [comment]
ok sehr schade das es nicht geklappt hat bisher.

trotzdem vielen Dank für die bisherige Mühe.

vielleicht klappt das ja eines Tages doch noch.

**Comment by kelson42** [comment]
@Sofi204 Yes, we will find find what goes wrong I guess, this will just take a bit of time.

**Comment by Sofi204** [comment]
it's not a problem that it takes a little longer.

the more I look forward to it when it's done.

**Comment by siemsie** [comment]
https://farm.openzim.org/recipes/pokewiki_de

**Comment by Sofi204** [comment]
I really hope it helps.

**Comment by kelson42** [comment]
New attempt https://farm.openzim.org/pipeline/5fc62bf786bd30ee81acc9a2

**Comment by kelson42** [comment]
Finaly got a zim https://farm.openzim.org/pipeline/afde7527958ff63cdd781ff5
