### ISSUE TITLE
Cheatography

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#223]
- Website URL: https://www.cheatography.com/
- License: CC-by-NC
- Desired ZIM Title: Cheatography
- Desired ZIM Description: Over 3,000 Free Cheat Sheets, Revision Aids and Quick References
- Desired ZIM Icon –png :
![cheatography](https://user-images.githubusercontent.com/21675885/73163020-5c697d00-40ef-11ea-986a-30ba1f1887da.png)

- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **no**

The landing page is cluttered with ads - is there a way a scraper could work with some sort of adblocker?

**Comment by kelson42** [comment]
Done https://farm.openzim.org/recipes/cheatography.com
