### ISSUE TITLE
GCF LearnFree 2020

### ISSUE THREAD

**Issue by ericnitschke** [openzim/zim-requests#225]
- Website URL: https://edu.gcfglobal.org/en/topics/
- License: Need consent, but OER2GO has a version from 2015: http://oer2go.org/viewmod/en-GCF2015, so it should be possible.

https://edu.gcfglobal.org/en/info/terms-of-use/1/

- Desired ZIM Title: GCF LearnFree 2020
- Desired ZIM Description: 200+ tutorials on digital and real world skills. 
- Desired ZIM Icon –png (URL or attach one): https://media.gcflearnfree.org/assets/logo/logo.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage): https://edu.gcfglobal.org/en/topics/
- Is this a MediaWiki?: No
- Articles List URL (mediawiki): **n/a**

**Comment by Popolechien** [comment]
> Need consent

They have a form, I just filled it and asked for it. Wait & see.

**Comment by Popolechien** [comment]
Got confirmation we're good to go (Freshdesk ticket #10388)

**Comment by kelson42** [comment]
Done https://farm.openzim.org/recipes/edu.gcfglobal.org

**Comment by holta** [comment]
FYI this was moved to:
https://farm.openzim.org/recipes/edu.gcfglobal.org_en

@kelson42 do you when a ZIM file might be available in coming weeks or coming months?

(Also for Spanish here, if possible?)
https://farm.openzim.org/recipes/edu.gcfglobal.org_es
