### ISSUE TITLE
Wiki yeshiva

### ISSUE THREAD

**Issue by davidshai** [openzim/zim-requests#226]
Hello friend, I am appealing to you to create a zim file from this site:

https://www.yeshiva.org.il/wiki/index.php?title=%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99

**Comment by Popolechien** [comment]
Hey no problem but please give us the info requested when opening a new ticket (particularly a link to the logo +description in Hebrew if the site is in Hebrew)

**Comment by davidshai** [comment]
ויקישיבה - פרוייקט האנציקלופדיה למושגי תורה ויהדות של אתר ישיבה

**Comment by davidshai** [comment]
ויקישיבה - פרוייקט האנציקלופדיה למושגי תורה ויהדות של אתר ישיבה
