### ISSUE TITLE
new zim ויקישיבה

### ISSUE THREAD

**Issue by davidshai** [openzim/zim-requests#227]
That's my request    
Website URL: http://www.yeshiva.org.il/wiki/
    Desired ZIM Title: wiki-yeshiva
    Desired ZIM Description: פרוייקט האנציקלופדיה למושגי תורה ויהדות
    Desired ZIM Icon –png (URL or attach one): 
![תמונה](https://user-images.githubusercontent.com/60844387/74107804-658d2c00-4b7c-11ea-811d-c081d2780ce8.png)

    Language: עברית hebrew
    Desired Main Page (homepage): http://www.yeshiva.org.il/wiki/
   Thank you

**Comment by davidshai** [comment]
@Popolechien

**Comment by Popolechien** [comment]
Let's wait until https://github.com/openzim/mwoffliner/issues/1017 is fixed.

**Comment by davidshai** [comment]
@Popolechien 
Is he doing problems?  Thank you

**Comment by Popolechien** [comment]
Basically we can generate the zim file already but as you can see for example with https://library.kiwix.org/stupidedia_de_all_maxi_2020-01 hyperlinks only work on the landing page.

**Comment by davidshai** [comment]
@Popolechien @kelson42 I will download the whole site ... Thanks again

**Comment by kelson42** [comment]
Recipe created https://farm.openzim.org/recipes/yeshiva

**Comment by davidshai** [comment]
@kelson42 @Popolechien Thanks for the investment, how do I download the file?

**Comment by davidshai** [comment]
http://www.yeshiva.org.il/wiki/
This is the address I gave ^
And this is the address you entered for download?
https://www.yeshiva.org.il/

Could it have failed because the repository address is different than what I saw you entered? (I don't get it)

**Comment by kelson42** [comment]
@davidshai Just wanted to update you here. We are stuck now with an other bug https://github.com/openzim/mwoffliner/issues/660. Really hope to get it fixed within a mont now, and finally release the ZIM of Yeshiva.

**Comment by davidshai** [comment]
I thank you very much Emanuel, you are doing an important job :)

**Comment by davidshai** [comment]
An update to the last file is incorrect

**Comment by Popolechien** [comment]
@davidshai Can you be more precise on what is the issue exactly (description or screenshot)?

**Comment by kelson42** [comment]
We had long difficulties to scrape properly this Mediawiki. Last run in october has generated an empty ZiM. I have launched a new scrape.

**Comment by davidshai** [comment]
Thank you very much ... you are great.

**Comment by kelson42** [comment]
@davidshai I will close this ticket as basically the ZIM is building at https://farm.openzim.org/pipeline/5fb6c6e1e6a71b3773ddbc7e and should be ready tomorrow. Thank you for your patience, and please open a new ticket if anything is wrong (again) with the ZIM file.

**Comment by davidshai** [comment]
Hi how are you?  Regarding the new site I requested, is it possible?

בתאריך יום ו׳, 20 בנוב׳ 2020, 9:40, מאת Kelson ‏<notifications@github.com>:

**Comment by 770asdfghjkl770-prog** [comment]
אפשר להכין קובץ חדש ומעודכן?

**Comment by Popolechien** [comment]
Looks like the last two runs have failed: https://farm.openzim.org/recipes/chabadtext_he_all 

I have opened #1931
