### ISSUE TITLE
New ZIM: World Digital Library

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#228]
- Website URL: https://www.wdl.org
- License: **Copyrighted** mostly. [Dependent on content](https://www.wdl.org/en/legal/).
- Is this a MediaWiki?: **no**
- Desired ZIM Icon –png (URL or attach one): https://www.wdl.org/static/img/logos/wdl-gray.4f4f4a504421.svg (to be converted to PNG)

Available in 7 languages:

**English**

- Desired ZIM Title: **World Digital Library**
- Desired ZIM Description: **The WDL makes available on the Internet, free of charge and in multilingual format, significant primary materials from all countries and cultures.**
- Language (ISO 639-3): **eng** 

**Español**

- Desired ZIM Title: **Biblioteca digital mundial**
- Desired ZIM Description: **La Biblioteca Digital Mundial pone a disposición en Internet, de manera gratuita y en formato multilingüe, importantes materiales fundamentales de culturas de todo el mundo.**
- Language (ISO 639-3): **spa** 

**Français**

- Desired ZIM Title: **Bibliothèque numérique mondiale**
- Desired ZIM Description: **La Bibliothèque numérique mondiale met à disposition sur Internet, gratuitement et en plusieurs langues, une documentation considérable en provenance des pays et des cultures du monde entier.**
- Language (ISO 639-3): **fra** 

**Português**

- Desired ZIM Title: **Biblioteca digital mundial**
- Desired ZIM Description: **A Biblioteca Digital Mundial disponibiliza na Internet, gratuitamente e em formato multilíngue, importantes fontes provenientes de países e culturas de todo o mundo.**
- Language (ISO 639-3): **por**

**русский**

- Desired ZIM Title: **Mировая цифровая библиотека**
- Desired ZIM Description: **Mировая цифровая библиотека (WDL) предоставляет бесплатный доступ в сети Интернет в многоязычном формате к большому количеству материалов, представляющих культуры разных стран мира.**
- Language (ISO 639-3): **rus**

**閩東語**

- Desired ZIM Title: **世界数字图书馆**
- Desired ZIM Description: **世界数字图书馆（ WDL ）在互联网上以多语种形式免费提供源于世界各地各文化的重要原始材料。**
- Language (ISO 639-3): **cdo**

**العربية**

- Desired ZIM Title: **المكتبة الرقمية العالمية**
- Desired ZIM Description: **تتيح المكتبة الرقمية العالمية على الإنترنت مجانًا وبعدة لغات مواد أساسية مهمة من دول وثقافات عديدة حول العالم**
- Language (ISO 639-3): **ara**

**Comment by Rexadev** [comment]
Also See https://github.com/openzim/zim-requests/issues/603

**Comment by RavanJAltaie** [comment]
@rgaudin if it's mostly copyrighted, do you suggest making a zim file for each collection?

**Comment by rgaudin** [comment]
It now redirects to the Library of Congress as indicated by @Rexadev ; closing as a duplicate.
