### ISSUE TITLE
47% size decrease on new wikipedia_de_all_maxi

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#230]
wikipedia_de_all_maxi_2020-02.zim was recently published and is 18 Gb
but the previous ZIM file (wikipedia_de_all_maxi_2019-08.zim) was 34 Gb (a 47% decrease in size).

Could it be that the scraping was done incompletely?

**Comment by kelson42** [comment]
J'ai viré les fichier, c'est le bug connu, que on a aussi sur WPEN.
