### ISSUE TITLE
Wikipedia in Mon

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#233]
- Website URL: https://mnw.wikipedia.org
- License: CC-by-SA
- Desired ZIM Title: ဝဳကဳပဳဒဳယာ
- Desired ZIM Description: ပြကိုဟ်ဗိသ္တာ မသက္ကုၚုဟ်မး ဝွံ ညးလဵုဟွံဟီု လုပ်ပလေဝ်ဒါန် ချူမာန် သီုညးဖအိုတ်ရ။
- Desired ZIM Icon –png (URL or attach one): same as other wikis 
- Language (ISO 639-3): **mnw**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **yes **
- Articles List URL (mediawiki): **n/a**

**Comment by siemsie** [comment]
I created a recipe https://farm.openzim.org/recipes/wikipedia_mnw_all. I'll check it in a few days to see if running properly.

**Comment by siemsie** [comment]
Just checked, https://mnw.wikipedia.org/wiki/မုက်လိက်တမ် is live, and it is a very pretty language! I'll close the ticket (unless @kelson42 you tell me otherwise?).

**Comment by Popolechien** [comment]
The place to check would be http://library.kiwix.org/wikipedia_mnw_all_nopic_2020-03 (you looked at the Wikimedia server, not our copy) - but yes it worked all the same :-)

**Comment by siemsie** [comment]
Ah, hmm... I just had EE on the phone – we're going to speak Wednesday to discuss all this further, there are still too may unknowns for me to do this right. Bon dimanche!
