### ISSUE TITLE
Postillon.de

### ISSUE THREAD

**Issue by JensKorte** [openzim/zim-requests#234]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.der-postillon.com/
- License: Alle Texte auf Der Postillon stehen unter CC BY-NC-SA 3.0 DE (nicht-kommerziell) 
- Desired ZIM Title: Der Postillon
- Desired ZIM Description: Der Postillon - Ehrliche Nachrichten - unabhängig, schnell, seit 1845
- Desired ZIM Icon –png (URL or attach one): https://1.bp.blogspot.com/-Kq3ywyddDEY/VLL_tKIUX-I/AAAAAAAAdHo/7FN9qWnXe2c/s1600/Logo.png
- Language (ISO 639-3): de
- Desired Main Page (homepage): 
- Is this a MediaWiki?: no
- Articles List URL (mediawiki): **n/a**
- Comment: I am not sure if the logo links works later. I could not upload a PNG. I thought of the main logo on the homepage.

**Comment by Popolechien** [comment]
Smaller (less horizontal) logo here: https://4.bp.blogspot.com/-46xU6sntzl4/UVHLh1NGfwI/AAAAAAAAUlY/RiARs4-toWk/s800/Logo.jpg
Turned into .PNG:
![postillon](https://user-images.githubusercontent.com/21675885/75657511-aef60600-5c66-11ea-8e2a-080b93f196d5.png)

**Comment by JensKorte** [comment]
Yes, that's the logo.

**Comment by kelson42** [comment]
Done, see https://farm.openzim.org/recipes/der-postillon.com

**Comment by JensKorte** [comment]
Thx
