### ISSUE TITLE
Ubongo Français Youtube Channel

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#235]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.youtube.com/channel/UC7tJK3LpcPrhsPRQ_nfTFAw/featured
- License: **Copyrighted**
- Desired ZIM Title: **Ubongo Kids - Français**
- Desired ZIM Description: **P'tits Ubongo est un dessin animé éducatif pour enfants, qui suivent les aventures des P'tits Ubongo : cinq amis qui aiment apprendre les sciences, la technologie, l’ingénierie, les mathématiques et les compétences de vie. Ils utilisent leurs nouvelles connaissances pour résoudre des problèmes et mystères dans le village de Kokotoa.**
- Desired ZIM Icon –png (URL or attach one): https://yt3.ggpht.com/a/AATXAJxyDt4Y1fTqgONPjCXiQXWhKLVMEwuAJw4_aQ=s288-c-k-c0xffffffff-no-rj-mo- Language (ISO 639-3): **fra**
- Desired Main Page (homepage): **https://www.youtube.com/channel/UC7tJK3LpcPrhsPRQ_nfTFAw/featured**
- Is this a MediaWiki?: **no**
- Articles List URL (mediawiki): **n/a**

**Comment by kelson42** [comment]
Recipe created https://farm.openzim.org/recipes/ubungo_fr

**Comment by kelson42** [comment]
First version done https://download.kiwix.org/zim/other/ubongo_fr_all_2020-03.zim
