### ISSUE TITLE
New ZIM: Mondial tissus

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#236]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.youtube.com/user/YMONKA
- License: **Youtube**
- Desired ZIM Title: ** Maths et tiques**
- Desired ZIM Description: **m@ths et tiques est une chaîne YouTube : des cours de maths en vidéo pour t'aider à mieux comprendre. **
- Desired ZIM Icon –png (URL or attach one): https://yt3.ggpht.com/a/AATXAJw0gdHmC4CN82h2QgYPbVkaefSsXMkn3c9hOA=s288-c-k-c0xffffffff-no-rj-mo- Language (ISO 639-3): **fra**
- Desired Main Page (homepage): **https://www.youtube.com/user/YMONKA**
- Is this a MediaWiki?: **no**
- Articles List URL (mediawiki): **n/a**

**Comment by rgaudin** [comment]
We already have this one

**Comment by barbayellow** [comment]
Did not know that. We can close this issue.

**Comment by kelson42** [comment]
The ZIM file is quite old... but will make a new version soon.

**Comment by kelson42** [comment]
Here is the recipe https://farm.openzim.org/recipes/la_chaine_de_maths_et_tiques_fr_all

**Comment by kelson42** [comment]
New version available https://download.kiwix.org/zim/other/la_chaine_de_maths_et_tiques_fr_all_2020-03.zim
