### ISSUE TITLE
Micmaths Youtube channel

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#237]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.youtube.com/user/Micmaths
- License: **Youtube**
- Desired ZIM Title: **Mic Maths**
- Desired ZIM Description: **La chaîne Micmaths vous propose diverses vidéos autour des mathématiques. Vous y trouverez des cours de maths, des jeux de logique, des chroniques ou encore des manipulations autour des mathématiques.**
- Desired ZIM Icon –png (URL or attach one): https://yt3.ggpht.com/a/AATXAJwTeSsCLzdRmjdL-iMP00ndr-WHb7fMvBzqdQ=s288-c-k-c0xffffffff-no-rj-mo
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage): **https://www.youtube.com/user/Micmaths**
- Is this a MediaWiki?: **no**
- Articles List URL (mediawiki): **n/a**

**Comment by kelson42** [comment]
Recipe https://farm.openzim.org/recipes/micmaths

**Comment by kelson42** [comment]
Done https://download.kiwix.org/zim/other/micmaths_fr_all_2020-03.zim
