### ISSUE TITLE
Nota bene Youtube Channel

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#238]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.youtube.com/user/notabenemovies
- License: **Youtube**
- Desired ZIM Title: **Nota Bene**
- Desired ZIM Description: **Nota Bene est une émission qui vous fait comprendre l'Histoire avec un grand H. Le but est de faire découvrir de nombreux sujets en rapport avec l'histoire de façon légère et compréhensible, autrement qu'avec des énumérations de dates ! **
- Desired ZIM Icon –png (URL or attach one): https://yt3.ggpht.com/a/AATXAJzilcmC-OiWwMG76scOHNtD7kkmTlhlyc-yag=s288-c-k-c0xffffffff-no-rj-mo
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage): **https://www.youtube.com/user/notabenemovies**
- Is this a MediaWiki?: **no**
- Articles List URL (mediawiki): **n/a**

**Comment by kelson42** [comment]
Recipe https://farm.openzim.org/recipes/nota_bene

**Comment by kelson42** [comment]
Done https://download.kiwix.org/zim/other/nota-bene_fr_all_2020-04.zim
