### ISSUE TITLE
New ZIM: Chaîne Youtube couture (Mondial tissus)

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#240]
*Please use the following format for a ZIM creation request…*

- Website URL: https://www.youtube.com/user/MondialTissusfrance
- License: **Youtube**
- Desired ZIM Title: **Mondial Tissus**
- Desired ZIM Description: **Comment coudre une nappe ? Commment utiliser une surjeteuse ? La chaîne de Mondial tissus donne de nombreuses astuces pour la couture. **
- Desired ZIM Icon –png (URL or attach one): https://yt3.ggpht.com/a/AATXAJz8YC7khyApaBx5UJtoRmZrXURURfbmFYFtnA=s288-c-k-c0xffffffff-no-rj-mo
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage): **https://www.youtube.com/user/MondialTissusfrance**
- Is this a MediaWiki?: ** no**
- Articles List URL (mediawiki): **n/a**

**Comment by kelson42** [comment]
Recipe https://farm.openzim.org/recipes/mondial_tissus

**Comment by kelson42** [comment]
First version https://download.kiwix.org/zim/other/mondial-tissus_fr_all_2020-03.zim
