### ISSUE TITLE
covid19relay.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#243]
URL is http://covid19.popup.wiki/ - site is still under construction but managed by our friend @harej who should ping us when ready.

**Comment by harej** [comment]
Domain is now covid19relay.org (and the site is up)

**Comment by kelson42** [comment]
Recipe https://farm.openzim.org/recipes/covid19relay

**Comment by kelson42** [comment]
Site seems down since many days, i have disabled the recipe.
