### ISSUE TITLE
New ZIM:  whitewolf wikia ( would you guys be so kindly as to make this into a ZIM file?)

### ISSUE THREAD

**Issue by aban930** [openzim/zim-requests#244]
*Please use the following format for a ZIM creation request…*

- Website URL: https://whitewolf.fandom.com/wiki/Main_Page
- License: **Copyrighted | CC-by-sa | Public domain | ...** i dont know
- Desired ZIM Title: **whitewolf wikia** 
- Desired ZIM Description: ** a wiki about all the white wolf settings**
- Desired ZIM Icon –png (URL or attach one): http://abc.com/icon.png  - doesnt matter
 - Language (ISO 639-3): **eng** 
- Desired Main Page (homepage): **n/a** - doesnt matter
- Is this a MediaWiki?: **yes | no** - i dont know
- Articles List URL (mediawiki): **n/a** - i dont know

**Comment by kelson42** [comment]
@RavanJAltaie @aban930 Should be doable now, take example on the Minecraft recipes

**Comment by RavanJAltaie** [comment]
Recipe requested
https://farm.openzim.org/recipes/whitewolf_wikia

**Comment by RavanJAltaie** [comment]
Recipe succeeded but a big is there when the maxi version doesn't show any pictures.
A technical issue is placed 
https://github.com/openzim/mwoffliner/issues/1735
