### ISSUE TITLE
SMBC covid pack

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#245]
- Website URL: https://www.smbc-comics.com/covid/
- License: CC-by-NC
- Desired ZIM Title: Saturday Morning Breakfast Cereals Book Pack
- Desired ZIM Description: Fun reads by the author of SMBC
- Desired ZIM Icon –png (URL or attach one): 
![smbc](https://user-images.githubusercontent.com/21675885/76985114-07542580-6940-11ea-8c63-007c3c3049aa.png)
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/smbc-comics.com_en

**Comment by RavanJAltaie** [comment]
File is ready in the library
https://library.kiwix.org/viewer#smbc-comics.com_en_2024-04
