### ISSUE TITLE
Videos "Les fondamentaux"

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#246]
400 high quality pedagocical videos in French by the network "Réseau Canopé":
https://lesfondamentaux.reseau-canope.fr/accueil.html

We have the ones from the Youtube channel, but this is only a part small part of them:
https://download.kiwix.org/zim/other/les-fondamentaux_fr_all.zim

**Comment by kelson42** [comment]
@barbayellow Would you be interested? Would you be able here to get an access to the data in a ZIP/... any machine readable format so we can easily create ZIM file(s).

**Comment by barbayellow** [comment]
Clearly interested! However I don't really understand your resquest " Would you be able here to get an access to the data in a ZIP/... any machine readable format so we can easily create ZIM file(s)."

**Comment by kelson42** [comment]
@barbayellow For now, for us, there is no way to provide *all* videos of "Les fondamentaux". If you have through BSF access to them in a machine readble format, we would be able to do it.

**Comment by kelson42** [comment]
Done, see https://farm.openzim.org/recipes/lesfondamentaux
