### ISSUE TITLE
ETH Core MOOCs

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#248]
- Website URL: https://mooc.phzh.ch/
- License: [CC-by-NC 4.0](https://mooc.phzh.ch/courses/course-v1:PHZH+W-IB+2019_E/about)
- Desired ZIM Title: Core MOOC
- Desired ZIM Description: A step-by-step programme for the development of life skills
- Desired ZIM Icon –png (URL or attach one):
![CORE Arab](https://user-images.githubusercontent.com/21675885/80596161-37561480-8a26-11ea-848b-5067c0b0ba1d.png)
![CORE Engl](https://user-images.githubusercontent.com/21675885/80596164-391fd800-8a26-11ea-80fc-b33d7e138081.png)

- Language (ISO 639-3): en / ar (el/fa to follow)
- Desired Main Page (homepage):
(arabic)  https://mooc.phzh.ch/courses/course-v1:PHZH+W-IB-CORE+2019_A_01/course/ 
and 
(english) https://mooc.phzh.ch/courses/course-v1:PHZH+W-IB+2019_E/course/

Not a mediawiki. Needs registration. ETH will follow up so putting On Hold tag for the time being

**Comment by kelson42** [comment]
@rgaudin It seems we need (at least) to add support of openedx scraper in zimfarm https://github.com/openzim/zimfarm/issues/473

**Comment by Popolechien** [comment]
Ok, I've added the logos for en/ar, but does it make more sense to open one ticket per language?

**Comment by kelson42** [comment]
@Popolechien Done
