### ISSUE TITLE
New ZIM: Wikipedia Engineering 

### ISSUE THREAD

**Issue by shockergit** [openzim/zim-requests#250]
- Website URL: https://en.m.wikipedia.org/wiki/Engineering 
- License: **CC BY-SA 3.0 **
- Desired ZIM Title: **Wikipedia Engineering **
- Desired ZIM Description: **This article is about the general field called "Engineering**
- Desired ZIM Icon –png (URL or attach one): https://en.m.wikipedia.org/wiki/Engineering#/media/File%3AMaquina_vapor_Watt_ETSIIM.jpg 
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **https://en.m.wikipedia.org/wiki/Engineering**
- Is this a MediaWiki?: **yes | no**
- Articles List URL (mediawiki): **n/a**

**Comment by RavanJAltaie** [comment]
@Popolechien Please inform if we shall have a zim file for this page only? https://en.m.wikipedia.org/wiki/Engineering

**Comment by RavanJAltaie** [comment]
@shockergit We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
