### ISSUE TITLE
Bayard books

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#251]
- Content provided by Orange
- License: available until March 2024
- Desired ZIM Title: Bayard Jeunesse
- Desired ZIM Description: Une collection de livres et audiolivres pour apprendre et se détendre
- Desired ZIM Icon –png (URL or attach one): https://www.bayard-jeunesse.com/static/version1584441951/frontend/Bayard/jeunesse/fr_FR/images/logo.svg or https://www.ricochet-jeunes.org/sites/default/files/styles/300_x_400/public/2017-09/18882306_1440019806019483_6439973503445352727_n.jpg
- Language (ISO 639-3): **fr**

**Comment by rgaudin** [comment]
@Popolechien here's a list of the _packages_ (folders) in which came the files.

The sizes are the compressed one so it's approx. equivalent to what it will be in the ZIM file.

```
# following two are the same
29M     [PDF  ] Bayard Afrique/PDF (12)
35M     [AUDIO] Bayard Afrique/AUDIOS (12)

24M     [VIDEO] Bayard Afrique/Dis le dans ma langue
101M    [VIDEO] Bayard Afrique/Expériences Scientifiques
46M     [VIDEO] Bayard Afrique/Poésies
409M    [VIDEO] Bayard Afrique/Recettes de cuisines

322M    [EPUB,PDF,AUDIO] Bayard France/Ebooks/J'aime lire
103M    [EPUB,PDF,AUDIO] Bayard France/Ebooks/J'apprends à lire

# same stories
150M    [EPUB,PDF,AUDIO] [EN] Bayard France/Ebooks/les belles histoires
187M    [EPUB,PDF,AUDIO] [FR] Bayard France/Ebooks/les belles histoires

109M    [EPUB,PDF] Bayard France/Ebooks/Mes p'tites questions
156M    [VIDEO] Bayard France/Lab'Oh
143M    [VIDEO] Bayard France/Les P'tits philosphes
29M     [VIDEO] [EN] Bayard France/MesP'titsPourquoi (10)
84M     [VIDEO] [FR] Bayard France/MesP'titsPourquoi (26)
119M    [VIDEO] Bayard France/Scoopy, en direct du corps humain
```

Important informations:

* EPUB usually includes audio and are quite large.
* Even if the package is `PDF,EPUB,AUDIO`, we can still separate them and create a ZIM with just PDF or just a couple of those formats.
* the target audience is **very wide** for those. it would be good to group them by age-target. Unfortunately, this information is not in the metadata and the _collections_ (J'aime lire, J'apprends à lire, Les belles histoires, Lab'Oh, etc) are not directly visible on their websites ([1](https://www.bayard-editions.com) and [2](https://bayard-rights.com/)) so it might take some work to get that information.

Please, **give me a list of ZIM files** to create with the list of content/content-type to include in each. We'll sort out the metadata (title, desc, icon) after.

**Comment by Popolechien** [comment]
Right. What is the content of these two? Anywhere I can check these?
I would bundle them and base the zim title on what's in it.

```
29M     [PDF  ] Bayard Afrique/PDF (12)
35M     [AUDIO] Bayard Afrique/AUDIOS (12)
```

As for the rest:

Bayard cuisine
```
409M    [VIDEO] Bayard Afrique/Recettes de cuisines
```
Beautiful stories
```
150M    [EPUB,PDF,AUDIO] [EN] Bayard France/Ebooks/les belles histoires
```
Tell me why
```
29M     [VIDEO] [EN] Bayard France/MesP'titsPourquoi (10)
```
Then one for each of these with the same title (Mes p'tites questions, Lab'Oh, etc.
```
322M    [EPUB,PDF,AUDIO] Bayard France/Ebooks/J'aime lire
103M    [EPUB,PDF,AUDIO] Bayard France/Ebooks/J'apprends à lire
24M     [VIDEO] Bayard Afrique/Dis le dans ma langue
101M    [VIDEO] Bayard Afrique/Expériences Scientifiques
46M     [VIDEO] Bayard Afrique/Poésies
187M    [EPUB,PDF,AUDIO] [FR] Bayard France/Ebooks/les belles histoires
109M    [EPUB,PDF] Bayard France/Ebooks/Mes p'tites questions
156M    [VIDEO] Bayard France/Lab'Oh
143M    [VIDEO] Bayard France/Les P'tits philosphes
84M     [VIDEO] [FR] Bayard France/MesP'titsPourquoi (26)
119M    [VIDEO] Bayard France/Scoopy, en direct du corps humain
```

So 15 files in total. Considering their number and size, it wouldn't be a bad idea to have some sort of `Bayard` tag or even repository.

**Comment by rgaudin** [comment]
@Popolechien please go to https://farm.openzim.org/recipes and filter on `bayard` tag to see the list of recipes.

Edit as you please. We'll discuss how we should handle the branding/logo stuff

**Comment by Popolechien** [comment]
> Edit as you please.

If you refer to the content descriptions they all look good to me. Ditto for the logos. Let's run a couple and see what they look like.

As a side note, why is the warehouse `Others` rather than `Bayard` (I would expect that deleting Bayard when the license expires in 3 years would be marginally faster)?

**Comment by rgaudin** [comment]
Regarding warehouse, that's for @kelson42 to answer.

I'm fixing some stuff in nautilus so we can release and create those ZIMs.

**Comment by kelson42** [comment]
I'm not really in favour to keep it in an other place than `others`. Make things more comple, without clear added value.

**Comment by Popolechien** [comment]
Good point. Shouldn't we rather create an `ebooks` directory then and add youscribe + gutenberg in it?

**Comment by kelson42** [comment]
> Good point. Shouldn't we rather create an `ebooks` directory then and add youscribe + gutenberg in it? Or more generally, does this folder structure have any use outside of people looking directly at download.kiwix.org/zim ?

This sounds a better idea even if I’m not sre to see all the implications... @rgaudin your opinion?

**Comment by rgaudin** [comment]
I don't really care about the folder. I think people looking for a ZIM **file** (not a content) can easily find it now because the hierarchy is small and explicit.

The thing is we currently have a 1:1 relationship between this folder tree and the `category`. I am more concerned about the explosion of the `others` category because it makes the library unbrowsable (but searchable). The folder is storage, it doesn't matter much but the category is a metadata and that is more sensitive. But it's a higher-level discussion…

**Comment by kelson42** [comment]
OK, lets leave it for the moment.

**Comment by rgaudin** [comment]
- https://download.kiwix.org/zim/other/lesbelleshistoires_fr_2020-05.zim
- https://download.kiwix.org/zim/other/alittlequestionaday_fr_2020-05.zim
- https://download.kiwix.org/zim/other/bayardcuisine_fr_2020-05.zim
- https://download.kiwix.org/zim/other/disledansmalangue_fr_2020-05.zim
- https://download.kiwix.org/zim/other/experiencesscientifiques_fr_2020-05.zim
- https://download.kiwix.org/zim/other/jaimelire_fr_2020-05.zim
- https://download.kiwix.org/zim/other/japprendsalire_fr_2020-05.zim
- https://download.kiwix.org/zim/other/laboh_fr_2020-05.zim
- https://download.kiwix.org/zim/other/lesptitsphilosophes_fr_2020-05.zim
- https://download.kiwix.org/zim/other/mesptitesquestions_fr_2020-05.zim
- https://download.kiwix.org/zim/other/mesptitspourquoi_fr_2020-05.zim
- https://download.kiwix.org/zim/other/poesies_fr_2020-05.zim
- https://download.kiwix.org/zim/other/scoopyendirectducorpshumain_fr_2020-05.zim
- https://download.kiwix.org/zim/other/storybox_fr_2020-05.zim

As I write this, belles histoires is done, others in the pipe. Haven't tested, downloading…

**Comment by rgaudin** [comment]
Belles histoires looks OK. @Popolechien please report any issue with those ZIMs and close this ticket should it be OK.

**Comment by rgaudin** [comment]
Actually the UI is not set to french. Will edit recipes and relaunch it all.

**Comment by Popolechien** [comment]
Uh I can't seem to be able to read more than the first story in Les belles Histoires

**Comment by rgaudin** [comment]
Downloaded it again, have no problem using kiwix macOS and kiwix-serve.

**Comment by Popolechien** [comment]
I was going to flag that videos don't fit the screen, but am I right to understand from [this comment of yours](https://github.com/kiwix/apple/issues/80#issuecomment-626126240) that it's not really an option anyway?

**Comment by rgaudin** [comment]
on apple readers yes.

**Comment by Popolechien** [comment]
Ah ok my issue was in fact on android. Should I mention it here or open a ticket there?

**Comment by Popolechien** [comment]
Alles gut. Closing ticket.
