### ISSUE TITLE
New ZIM: 

### ISSUE THREAD

**Issue by DSMishler** [openzim/zim-requests#252]
*PhysiCell ZIM*

- Website URL: http://physicell.org/wiki/Main_Page
- License: **CC-by-sa **
- Desired ZIM Title: **Physicell Wiki**
- Desired ZIM Description: **A Mediawiki that is to replace the PhysiCell user manual**
- Desired ZIM Icon –png https://i0.wp.com/physicell.org/wp-content/uploads/2019/11/cropped-cropped-physicell-logov0.0.3-100dpi-2.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **yes**
- Articles List URL (mediawiki): **n/a**

In general, I am seeking a way to transform this MediaWiki into a local pdf, preferably with LaTEX syntax. I can do text processing to get it there, if need be. But for now I'm trying to figure out how to grab all ~20 pages and compile them. If this is not the place for this task, please let me know!

**Comment by Popolechien** [comment]
I created the recipe here: https://farm.openzim.org/recipes/PhysiCell%20Wiki 
Let's see what that first run looks like.

**Comment by kelson42** [comment]
First version released https://download.kiwix.org/zim/other/physicell_en_all_maxi_2020-04.zim
