### ISSUE TITLE
New ZIM: Stardew Valley Wiki

### ISSUE THREAD

**Issue by PaulB03** [openzim/zim-requests#255]
*Please use the following format for a ZIM creation request…*

- Website URL: https://stardewvalleywiki.com/Stardew_Valley_Wiki
- License: CC
- Desired ZIM Title: Stardew Valley Wiki
- Desired ZIM Description: Official Stardew Valley Wiki
- Desired ZIM Icon –png (URL or attach one): https://stardewvalleywiki.com/mediawiki/images/6/68/Main_Logo.png
- Language (ISO 639-3): EN, GER
- Desired Main Page (homepage): https://stardewvalleywiki.com/Stardew_Valley_Wiki
- Is this a MediaWiki?: Yes
- Articles List URL (mediawiki): https://stardewvalleywiki.com/Special:AllPages

**Comment by RavanJAltaie** [comment]
recipe created
https://farm.openzim.org/recipes/stardewvalleywiki_en_all

**Comment by flossgeek** [comment]
The build appears to have failed:
![image](https://user-images.githubusercontent.com/83112921/235352052-6292c7e0-77e1-4fdb-9498-f10381e1934e.png)

**Comment by Popolechien** [comment]
@flossgeek Yep, we'll have to wait until the next mwoffliner update/upgrade.

**Comment by outusuke** [comment]
some update on this?
