### ISSUE TITLE
New ZIM: OFPRA

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#256]
- Website URL: https://www.ofpra.gouv.fr/
- License:  CC-by-sa
- Desired ZIM Title: OFPRA
- Desired ZIM Description: L'Office français de protection des réfugiés et apatrides est un établissement public doté d'une indépendance fonctionnelle, chargé de l'application des textes relatifs à la reconnaissance de la qualité de réfugié, d'apatride et à l'admission à la protection subsidiaire.
- Desired ZIM Icon –png (URL or attach one): ![image](https://user-images.githubusercontent.com/4816690/81576636-cb21cc00-93a8-11ea-8598-24b8cadf8d92.png)
- Language (ISO 639-3): fra
- Desired Main Page (homepage): n/a
- Is this a MediaWiki?: no
- Articles List URL (mediawiki): n/a

**Comment by kelson42** [comment]
@barbayellow @Popolechien Si is a bit too sensitive too me. This is not only copyrighted, but I see potential problems if we present outdated or even not-complete content.

**Comment by Popolechien** [comment]
@kelson42 I think that zimfarm would reasonably deal with the outdated concern, but I do not think this is CC-by-SA content.
I see the value in sharing this content though: @barbayellow Do you have contacts there that could grant us a license of sorts?

**Comment by barbayellow** [comment]
It is not uner cc by SA however I consider it as outrageous since OFPRA is a French public service. This content has been created with taxes from French citizens and should be available to all. 
Still, we're going to try to find a contact at the OFPRA to open negotiations.

**Comment by RavanJAltaie** [comment]
@barbayellow we didn't hear back from you, so I'm closing the ticket for now.
Feel free to re-open once you have the requirements.
