### ISSUE TITLE
New ZIM: OFII

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#257]
*Please use the following format for a ZIM creation request…*

- Website URL: http://www.ofii.fr/
- License: CC BY-NC-ND
- Desired ZIM Title: OFII
- Desired ZIM Description: Site Internet de l'Office Français de l'Immigration et de l'Intégration
- Desired ZIM Icon –png: 
![image](https://user-images.githubusercontent.com/4816690/81576866-11772b00-93a9-11ea-9daf-d07639327f2c.png)
- Language (ISO 639-3): fra
- Desired Main Page (homepage): n/a
- Is this a MediaWiki?: no
- Articles List URL (mediawiki): n/a

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/ofii.fr_fr_all
I'll update the library file link once ready

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#ofii.fr_fr_all_2024-08
