### ISSUE TITLE
Update ZIM: ubuntudoc.fr

### ISSUE THREAD

**Issue by letompouce** [openzim/zim-requests#261]
Long story short, a GDPR-like request pointed me at th ubuntudoc-fr ZIM, which latest version is from 2015-12-15.

 5 years in computer science shall be counted as dog-years, this is pretty outdated documentation. This package should be updated.

- Website URL: https://doc.ubuntu-fr.org/
- License: CC-by-sa 3.0
- Desired ZIM Title: Documentation Ubuntu ~~Française~~ Francophone
- Desired ZIM Description: Version hors ligne du wiki doc.ubuntu-fr.org
- Desired ZIM Icon –png (URL or attach one): https://commons.wikimedia.org/wiki/File:Logo-ubuntu_cof-orange-hex.svg (Public Domain) (PNG versions available)
- Language (ISO 639-3): fra
- Desired Main Page (homepage): https://doc.ubuntu-fr.org/
- Is this a MediaWiki?: no
- Articles List URL (mediawiki): n/a

Thanks!

**Comment by kelson42** [comment]
Yes our current doc is far too old.

**Comment by kelson42** [comment]
We should create a script (and put it in Dockerfile) which would download the tarball, optimize the pictures and create the ZIM file using `zimwriterfs`.

**Comment by letompouce** [comment]
> Yes our current doc is far too old.

I hope you're not talking about *your* (Kiwix/openZIM) doc ; I was pointing at this offline Ubuntu doc, which is 20 dog-years old :-)

**Comment by kelson42** [comment]
I will give a try with ZIMit 2.0

**Comment by kelson42** [comment]
Here is the recipe https://farm.openzim.org/recipes/doc.ubuntu-fr.org, in testing

**Comment by benoit74** [comment]
I've added an exclusion rule and requested recipe again

**Comment by benoit74** [comment]
Exclusion rule was not correct, fixed and requested again. I've also updated/moved the custom CSS and favicon

**Comment by benoit74** [comment]
ZIM file is ready in dev: https://dev.library.kiwix.org/#lang=fra&q=ubuntu

OK for me, @Popolechien can you please review it as well? Thanks

**Comment by benoit74** [comment]
We can hide them easily yes. But there are plenty, and hiding them is going to hide all of them, and in some cases this is going to be ugly.

See e.g. section 4 of https://dev.library.kiwix.org/content/doc.ubuntu-fr.org_fr_all_2024-11/doc.ubuntu-fr.org/debutant

![Image](https://github.com/user-attachments/assets/24d41ef5-ac65-4332-8566-a4483ded95fe)

If we hide those links, then the phrase loose all its meaning.

This works "as designed at the source".

**Comment by Popolechien** [comment]
Yeah, will get better if/when external links are flagged one way or the other following https://github.com/openzim/zimit/issues/374

In the meantime, let's roll.

**Comment by Popolechien** [comment]
Ah, task failed 🤨 
https://farm.openzim.org/pipeline/688ffb13-4b3f-454e-8160-6e6dff2f5e39/debug

**Comment by benoit74** [comment]
Probably only intermittent issue on upstream, requested again.

**Comment by benoit74** [comment]
New ZIM is ready online: https://library.kiwix.org/#q=documentation+ubuntu

Nota: I've removed `ubuntudoc_fr_all_2015-12` from the library since ZIM name is different and 9 years is ... a lot !

Recipe set to quarterly update.
