### ISSUE TITLE
New ZIM: Astronomy (from each Wikipedia)

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/zim-requests#264]
Please create a **ZIM** file about **Astronomy** from the English (and not only) Wikipedia.
After all, there are ZIM files about **computer**, **cricket**, **history**, etc.
But there is no ZIM file about **Astronomy**!

PS: please update **[Wikipedia English all_maxi_2018-10.zim](https://github.com/openzim/zim-requests/issues/199)** 2018-11-06 **78G**

**Comment by kelson42** [comment]
@Ubuntu-2020 WPEN all maxi has been updated

**Comment by kelson42** [comment]
@Ubuntu-2020 I have created a version for English https://farm.openzim.org/recipes/wikipedia_en_astronomy. The ZIM file should be available in the next hours. We don't do all languages for selection. If you need an other language, please open an other ticket.
