### ISSUE TITLE
New ZIM: РадиоВики

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/zim-requests#265]
- Website URL: http://radiowiki.ru/wiki/Заглавная_страница
- License: **CC-by-4.0**
- Desired ZIM Title: **Радио (wiki)**
- Desired ZIM Description: **РадиоВики - энциклопедия радио и электроники**
- Desired ZIM Icon –png (URL or attach one): http://radiowiki.ru/logo/rev_1.png
- Language: **ru**
- Desired Main Page (homepage): **http://radiowiki.ru/wiki/Заглавная_страница**
- Is this a MediaWiki?: **yes**
- Articles List URL (mediawiki): **http://radiowiki.ru/wiki/Служебная:Все_страницы**

**Comment by Ubuntu-2020** [comment]
@kelson42 @Popolechien I understand that the developers are very busy but it has already been almost a year since the application was submitted!
I have some suggestions about this application:
1. since you have too many requests to create ZIM files for a specific site in a only one language, I suggest that if you create a ZIM file, update them not every month but **once a quarter** or **once every half a year**!
2. if you create a ZIM file for **[radiowiki.ru](http://radiowiki.ru/wiki/Заглавная_страница)** then it **popularizes** the Kiwix program on the territory of the former USSR. After all **[radiowiki.ru](http://radiowiki.ru/wiki/Заглавная_страница)** this is a popular site for Russian-speaking radio amateurs.

**Comment by Popolechien** [comment]
@Ubuntu-2020 I've created the recipe here: https://farm.openzim.org/recipes/radiowiki

**Comment by Popolechien** [comment]
Downloaded 1804 articles but crashed with `unable to hack startup module`. @rgaudin is this a zimfarm issue?

**Comment by RavanJAltaie** [comment]
@rgaudin any update of this ticket so we can close it?

**Comment by rgaudin** [comment]
> @rgaudin any update of this ticket so we can close it?

I'm not involved in this ticket but I found the recipe on zimfarm: https://farm.openzim.org/recipes/radiowiki Looks like it's still failing.

**Comment by rgaudin** [comment]
I see @Popolechien's question above now ; answer is no. It's failing inside mwoffliner. Scaper or Website issue

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/radiowiki
