### ISSUE TITLE
Update ZIM: 

### ISSUE THREAD

**Issue by ry362** [openzim/zim-requests#267]
*Please use the following format for a ZIM creation request…*

- Website URL: http://en.wikipedia.com/
- License: Public domain
- Desired ZIM Title: Wikipedia All Maxi
- Desired ZIM Description: The full version of the English Wikipedia
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/7/77/Wikipedia_svg_logo.svg
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): **n/a**
- Is this a MediaWiki?: **yes**
- Articles List URL (mediawiki): **n/a**

**Comment by Popolechien** [comment]
@ry362 Yeah we are well aware that this is past due 
https://www.kiwix.org/en/whats-wrong-with-the-english-wikipedia/

You can also check our tries on the zimfarm: https://farm.openzim.org/recipes/wikipedia_en_all
