### ISSUE TITLE
AimHi

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#271]
- Website URL: https://www.youtube.com/watch?v=Y8SLX4wyIgU&list=PLr5n3ojAJWjTkqDW49ew1u7vsbVzM5Uub and PLr5n3ojAJWjRiuPrUAAveWrrqnNPPNzYK (several playlists but we'll start with Geography and Philosophy)
- License: **CC BY-NC-ND**
- Desired ZIM Title: **AimHi Geography** / **AimHi Philosophy**
- Desired ZIM Description: 

`Curriculum linked lessons for ages 8-18`

or

`Who will be underwater in 100 years? Should we pay trees more than footballers?  - AimHi is an online school that is bringing together educators with outstanding knowledge and enthusiasm for their subjects to inspire and captivate students, using provoking questions to construct a curriculum-linked learning adventure and providing alternative role models for a generation immersed in online culture.`
- Desired ZIM Icon –png (URL or attach one): 
![Logo With Volcano](https://user-images.githubusercontent.com/21675885/83773255-9988e180-a684-11ea-9a0b-f76c19bd596e.jpg)
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/aimhi_en_geography_all

**Comment by kelson42** [comment]
@Popolechien Should we close this ticket?

**Comment by Popolechien** [comment]
Yeah the playlists run failed but that's probably a youtube2zim issue.

**Comment by kelson42** [comment]
@Popolechien Both recipes are successfull, not sure what you mean with "failed".

**Comment by Popolechien** [comment]
The playlist one : https://farm.openzim.org/pipeline/5efa0c699ec57a81057740c3

**Comment by rgaudin** [comment]
It hasn't failed, it's running.  Those take time as there's a lot of videos.

**Comment by Popolechien** [comment]
Then there is a problem with the log:
[youtube2zim::2020-07-01 04:38:57,468] ERROR:FAILED. An error occurred: Too much videos failed to download

**Comment by kelson42** [comment]
Done
