### ISSUE TITLE
New ZIM request: Selections for Endless OS encyclopedia apps

### ISSUE THREAD

**Issue by dnohales** [openzim/zim-requests#273]
In [Endless](https://endlessos.com/) we have desktop encyclopedia apps (they look like [this](https://endlessos.com/wp-content/uploads/2016/06/encyclopidia.png)) for a variety of languages. Recently we opted to stop using our Mediawiki scrapers and start using OpenZIM, we adapted our systems and desktop SDK to take the content from .zim files in contrary to our zim-like (eos-shard) format.

The only obstacle we face is that our encyclopedias have a blacklist of content not suitable for children and also adds content requested by customers that are not necessarily in the lists of more "pagecounted" articles.

So the selection for each language would be: `topN articles - blacklist + whitelist`

For this I share [this ZIP](https://drive.google.com/file/d/1Slj2OvMtCanfKs8ba1HFnOEFkZdGLeSd/view?usp=sharing) with the blacklist, whitelist and the base selection (basically, top50000) to use for each language.

- Website URL: https://{langcode}.wikipedia.org/
- License: CC-by-sa
- Desired ZIM Title: EndlessOS selection for {language readable name} encyclopedia app
- Desired ZIM Description: EndlessOS selection for {language readable name} encyclopedia app
- Desired ZIM Icon: https://pbs.twimg.com/profile_images/738495472843796480/IqJu16RE_400x400.jpg
- Language (ISO 639-3): ara, eng, spa, fra, ind, por
- Desired Main Page: default
- Is this a MediaWiki?: yes

Thanks!

**Comment by kelson42** [comment]
@dnohales Sounds doable but what is exactly the white list, does this contain article titles which might not be in the base_selection but have to be in the final ZIM?

**Comment by dnohales** [comment]
@kelson42 yes, the whitelist should be in no matter what: if they are already in `base_selection`, then nothing is added; if it's missing in `base_selection`, then it's added.

**Comment by kelson42** [comment]
@dnohales Would you be able please to provide a PNG version of https://pbs.twimg.com/profile_images/738495472843796480/IqJu16RE_400x400.jpg. Would be good to not depends on a Twitter temporary file as well.

**Comment by kelson42** [comment]
@dnohales I have generated a first version in Indonesian with the Zimfarm:
* https://farm.openzim.org/recipes/wikipedia_id_endless
* https://download.kiwix.org/zim/.hidden/endless/wikipedia_id_endless_maxi_2020-06.zim

I have already remarked that I made a regression by "killing" the sorting of articles which makes the first page with not top importance articles. I will fix that.

But otherwise it looks "normal", please let me know if this is OK for you so I can prepare the other recipes/zim files.

**Comment by dnohales** [comment]
> @dnohales Would you be able please to provide a PNG version of https://pbs.twimg.com/profile_images/738495472843796480/IqJu16RE_400x400.jpg. Would be good to not depends on a Twitter temporary file as well. Having the propoer logo on Wikipedia article is probably the best approach https://en.wikipedia.org/wiki/Endless_Computers

We've better use the logo from the `endlessm` GitHub organization, this is a transparent PNG: https://avatars3.githubusercontent.com/u/1930958

> @dnohales I have generated a first version in Indonesian with the Zimfarm:

Outstanding! I'm gonna work on the Indonesian Encyclopedia app right now!

**Comment by kelson42** [comment]
> We've better use the logo from the `endlessm` GitHub organization, this is a transparent PNG: https://avatars3.githubusercontent.com/u/1930958

Fixed in the recipe.

**Comment by dnohales** [comment]
Sorry for the delay, some stuff had to be fixed in our infrastructure and got delayed, the ZIM file looks perfect and it works as intended in our app.

**Comment by kelson42** [comment]
All recipes have been created at https://farm.openzim.org/recipes with the tag "endless".
