### ISSUE TITLE
PLIX

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#279]
- Website URL: https://interactives.ck12.org/plix/measurement/
- License: **CC-by-NC**
- Desired ZIM Title: **PLIX interactive simulations**
- Desired ZIM Description: Play, Learn, Interact & eXplore math & science concepts
- Desired ZIM Icon : https://www.ck12.org/media/common/images/logo_ck12.svg
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
@rgaudin the first page of this website is interactive, it acts like a search engine which filters the courses for you as per your interest.
I wanted to confirm that zimit offliner cant scrape this, right?

**Comment by rgaudin** [comment]
Indeed, zimit being unattended, I don't think the result is going to be much useful:

We can hide the initial popup **in the resulting ZIM** which only filters the results AFAICT but the list of cards already loaded on the page is limited and the rest loads on scroll… after passing the popup. So the ZIM would only have the first ones.

More importantly, each activity is actually just a tutorial and one has to sign in to access the actual activity.

**Comment by RavanJAltaie** [comment]
Thank you
