### ISSUE TITLE
rugby

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#28]
_From @amirh123123 on April 10, 2018 8:4_

all wikipedia articles about rugby

_Copied from original issue: openzim/mwoffliner#296_

**Comment by RavanJAltaie** [comment]
@amirh123123 We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
