### ISSUE TITLE
A large number of articles are missing in the "wikipedia_ru_movies_maxi_2020-05.zim"

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/zim-requests#280]
A large number of articles are missing in the **wikipedia_ru_movies_maxi_2020-05.zim**
Many articles about **movies**, **actors**, and even **movie studios** are missing!
Here is just a small list of missing articles.

**Movies**:
- [Матч-пойнт (фильм)](https://ru.wikipedia.org/wiki/Матч-пойнт_(фильм))
- [Человек, которого не было](https://ru.wikipedia.org/wiki/Человек,_которого_не_было)
- [Заклинатель лошадей](https://ru.wikipedia.org/wiki/Заклинатель_лошадей)
- [Чёрная вдова (фильм, 2020)](https://ru.wikipedia.org/wiki/Чёрная_вдова_(фильм,_2020))
- [Парк юрского периода: Затерянный мир](https://ru.wikipedia.org/wiki/Парк_юрского_периода:_Затерянный_мир)
- [Сердца трёх (фильм, 1992)](https://ru.wikipedia.org/wiki/Сердца_трёх_(фильм,_1992))
- [Бегущий человек (фильм)](https://ru.wikipedia.org/wiki/Бегущий_человек_(фильм))
- [Водный мир](https://ru.wikipedia.org/wiki/Водный_мир)
- [Пираты XX века](https://ru.wikipedia.org/wiki/Пираты_XX_века)
- [Экипаж (фильм, 1979)](https://ru.wikipedia.org/wiki/Экипаж_(фильм,_1979))
- [Экипаж (фильм, 1994)](https://ru.wikipedia.org/wiki/Экипаж_(фильм,_1994))
- [Экипаж (фильм, 2016)](https://ru.wikipedia.org/wiki/Экипаж_(фильм,_2016))
- [Грань будущего](https://ru.wikipedia.org/wiki/Грань_будущего)
- [Побег (фильм, 2005, Россия)](https://ru.wikipedia.org/wiki/Побег_(фильм,_2005,_Россия))
- [Терминатор: Да придёт спаситель](https://ru.wikipedia.org/wiki/Терминатор:_Да_придёт_спаситель)
- [Корона Российской империи, или Снова неуловимые](https://ru.wikipedia.org/wiki/Корона_Российской_империи,_или_Снова_неуловимые)
- [Освобождение (киноэпопея)](https://ru.wikipedia.org/wiki/Освобождение_(киноэпопея))
- [Трактир на Пятницкой](https://ru.wikipedia.org/wiki/Трактир_на_Пятницкой)
- [Прибытие (фильм, 1996)](https://ru.wikipedia.org/wiki/Прибытие_(фильм,_1996))
- [Туман (фильм)](https://ru.wikipedia.org/wiki/Туман_(фильм))
- [Туман (фильм, 2005)](https://ru.wikipedia.org/wiki/Туман_(фильм,_2005))
- [Туман (фильм, 2010)](https://ru.wikipedia.org/wiki/Туман_(фильм,_2010))
- [Хроники Риддика](https://ru.wikipedia.org/wiki/Хроники_Риддика)
- [Добро пожаловать к Райли](https://ru.wikipedia.org/wiki/Добро_пожаловать_к_Райли)
- [Идеальный побег](https://ru.wikipedia.org/wiki/Идеальный_побег)
- [Пробуждение (фильм, 1990)](https://ru.wikipedia.org/wiki/Пробуждение_(фильм,_1990))
- [Чёрная дыра (фильм, 2000)](https://ru.wikipedia.org/wiki/Чёрная_дыра_(фильм,_2000))
- [Хроники Риддика: Тёмная ярость](https://ru.wikipedia.org/wiki/Хроники_Риддика:_Тёмная_ярость)
- [Бандиты (фильм, 2009)](Бандиты (фильм, 2009))
- [Бриллиантовый полицейский](https://ru.wikipedia.org/wiki/Бриллиантовый_полицейский)
- [Пляжный бездельник](https://ru.wikipedia.org/wiki/Пляжный_бездельник)
- [127 часов](https://ru.wikipedia.org/wiki/127_часов)
- [Петровка, 38 (фильм)](https://ru.wikipedia.org/wiki/Петровка,_38_(фильм))
- [Золото Маккенны](https://ru.wikipedia.org/wiki/Золото_Маккенны)
- [Лучший фильм года (Советский экран)](https://ru.wikipedia.org/wiki/Лучший_фильм_года_(Советский_экран))
- [Четвёртый вид](https://ru.wikipedia.org/wiki/Четвёртый_вид)
- [Обитель зла 3](https://ru.wikipedia.org/wiki/Обитель_зла_3)
- [Коллектор (фильм)](https://ru.wikipedia.org/wiki/Коллектор_(фильм))
- [Три мушкетёра (значения)](https://ru.wikipedia.org/wiki/Три_мушкетёра_(значения))
- [Гостья из будущего](https://ru.wikipedia.org/wiki/Гостья_из_будущего)
- [Район № 9](https://ru.wikipedia.org/wiki/Район_№_9)
- [Возвращение Робокопа](https://ru.wikipedia.org/wiki/Робокоп_(франшиза)#Возвращение_Робокопа_(TBA))
- [Найти Форрестера](https://ru.wikipedia.org/wiki/Найти_Форрестера)
- [Легенда Багера Ванса](https://ru.wikipedia.org/wiki/Легенда_Багера_Ванса)
- [Идентификация Борна (фильм)](https://ru.wikipedia.org/wiki/Идентификация_Борна_(фильм))
- [Че (фильм)](https://ru.wikipedia.org/wiki/Че_(фильм))
- [Студия 30](https://ru.wikipedia.org/wiki/Студия_30)
- [Заражение (фильм, 2011)](https://ru.wikipedia.org/wiki/Заражение_(фильм,_2011))

**Actors**:
- [Батлер, Джерард](https://ru.wikipedia.org/wiki/Батлер,_Джерард)
- [Бин, Майкл](https://ru.wikipedia.org/wiki/Бин,_Майкл)
- [Кёртис, Клифф](https://ru.wikipedia.org/wiki/Кёртис,_Клифф)
- [Никулин, Юрий Вениаминович](https://ru.wikipedia.org/wiki/Никулин,_Юрий_Вениаминович)
- [Лукин, Виталий Валентинович](https://ru.wikipedia.org/wiki/Лукин,_Виталий_Валентинович)
- [Светличная, Светлана Афанасьевна](https://ru.wikipedia.org/wiki/Светличная,_Светлана_Афанасьевна)
- [Уивер, Сигурни](https://ru.wikipedia.org/wiki/Уивер,_Сигурни)
- [Круз, Том](https://ru.wikipedia.org/wiki/Круз,_Том)
- [Кэмерон, Джеймс](https://ru.wikipedia.org/wiki/Кэмерон,_Джеймс)
- [Миронов, Андрей Александрович](https://ru.wikipedia.org/wiki/Миронов,_Андрей_Александрович)
- [Леонов, Евгений Павлович](https://ru.wikipedia.org/wiki/Леонов,_Евгений_Павлович)
- [Ливанов, Василий Борисович](https://ru.wikipedia.org/wiki/Ливанов,_Василий_Борисович)
- [Румянцева, Надежда Васильевна](https://ru.wikipedia.org/wiki/Румянцева,_Надежда_Васильевна)
- [Боярский, Михаил Сергеевич](https://ru.wikipedia.org/wiki/Боярский,_Михаил_Сергеевич)
- [Зельдин, Владимир Михайлович](https://ru.wikipedia.org/wiki/Зельдин,_Владимир_Михайлович)
- [Жигунов, Сергей Викторович](https://ru.wikipedia.org/wiki/Жигунов,_Сергей_Викторович)
- [Серебряков, Алексей Валерьевич](https://ru.wikipedia.org/wiki/Серебряков,_Алексей_Валерьевич)
- [Хоффман, Дастин](https://ru.wikipedia.org/wiki/Хоффман,_Дастин)
- [Папанов, Анатолий Дмитриевич](https://ru.wikipedia.org/wiki/Папанов,_Анатолий_Дмитриевич)

**Movie studios**:
- [Pixar](https://ru.wikipedia.org/wiki/Pixar)
- [Одесская киностудия](https://ru.wikipedia.org/wiki/Одесская_киностудия)

**Others**:
- [КиноПоиск](https://ru.wikipedia.org/wiki/КиноПоиск)
- [Hollywood Forever](https://ru.wikipedia.org/wiki/Hollywood_Forever)

**Comment by kelson42** [comment]
@Ubuntu-2020 This ZIM file is build of the selection of articles available http://download.openzim.org/wp1/ruwiki/customs/movies.tsv. This selection is build based on the [Wikipedia in English Wikiprojects](https://en.wikipedia.org/wiki/Wikipedia:WikiProject) evaluations. The article titles are then through the interwiki links translated to create this list of article titles in the Wikipedia in Russian. We have to do so because the Wikipedia in Russian does not make evaluation/gathering of its articles which make the creation of such a list impossible. So here what probably happen is that (1) These articles don't exist in the Wikipedia in English (2) article evaluated by a Wikiproject (3) Don' have a proper interwiki link to the Wikipedia in Russian.

**Comment by kelson42** [comment]
@Ubuntu-2020 BTW BTW "Pixar" is there http://library.kiwix.org/wikipedia_ru_movies_maxi/A/Pixar

**Comment by Ubuntu-2020** [comment]
A large number of articles are missing in the **wikipedia_ru_movies_maxi_2020-06.zim**
Many articles about **movies**, **actors**, and even **movie studios** are missing!
Here is just a small list of missing articles.

**Movies**:
- [Вычислитель (фильм)](https://ru.wikipedia.org/wiki/Вычислитель_(фильм))
- [Гостья из будущего](https://ru.wikipedia.org/wiki/Гостья_из_будущего)
- [Лучший фильм года (Советский экран)](https://ru.wikipedia.org/wiki/Лучший_фильм_года_(Советский_экран))
- [Менялы (фильм)](https://ru.wikipedia.org/wiki/Менялы_(фильм))
- [На игре 2. Новый уровень](https://ru.wikipedia.org/wiki/На_игре_2._Новый_уровень)
- [Он, она и я](https://ru.wikipedia.org/wiki/Он,_она_и_я)
- [Петровка, 38 (фильм)](https://ru.wikipedia.org/wiki/Петровка,_38_(фильм))
- [Побег (фильм, 2005, Россия)](https://ru.wikipedia.org/wiki/Побег_(фильм,_2005,_Россия))
- [Семнадцать мгновений весны (телефильм)](https://ru.wikipedia.org/wiki/Семнадцать_мгновений_весны_(телефильм))
- [Сердца трёх (фильм, 1992)](https://ru.wikipedia.org/wiki/Сердца_трёх_(фильм,_1992))
- [Студия 30](https://ru.wikipedia.org/wiki/Студия_30)
- [Трактир на Пятницкой](https://ru.wikipedia.org/wiki/Трактир_на_Пятницкой)
- [Туман (фильм)](https://ru.wikipedia.org/wiki/Туман_(фильм))
- [Туман (фильм, 2010)](https://ru.wikipedia.org/wiki/Туман_(фильм,_2010))
- [Три мушкетёра (значения)](https://ru.wikipedia.org/wiki/Три_мушкетёра_(значения))
- [Экипаж (фильм, 1994)](https://ru.wikipedia.org/wiki/Экипаж_(фильм,_1994))

**Actors**:
- [Боярский, Михаил Сергеевич](https://ru.wikipedia.org/wiki/Боярский,_Михаил_Сергеевич)
- [Жигунов, Сергей Викторович](https://ru.wikipedia.org/wiki/Жигунов,_Сергей_Викторович)
- [Зельдин, Владимир Михайлович](https://ru.wikipedia.org/wiki/Зельдин,_Владимир_Михайлович)
- [Леонов, Евгений Павлович](https://ru.wikipedia.org/wiki/Леонов,_Евгений_Павлович)
- [Лукин, Виталий Валентинович](https://ru.wikipedia.org/wiki/Лукин,_Виталий_Валентинович)
- [Лучко, Клара Степановна](https://ru.wikipedia.org/wiki/Лучко,_Клара_Степановна)
- [Миронов, Андрей Александрович](https://ru.wikipedia.org/wiki/Миронов,_Андрей_Александрович)
- [Никулин, Юрий Вениаминович](https://ru.wikipedia.org/wiki/Никулин,_Юрий_Вениаминович)
- [Папанов, Анатолий Дмитриевич](https://ru.wikipedia.org/wiki/Папанов,_Анатолий_Дмитриевич)
- [Румянцева, Надежда Васильевна](https://ru.wikipedia.org/wiki/Румянцева,_Надежда_Васильевна)
- [Светличная, Светлана Афанасьевна](https://ru.wikipedia.org/wiki/Светличная,_Светлана_Афанасьевна)
- [Серебряков, Алексей Валерьевич](https://ru.wikipedia.org/wiki/Серебряков,_Алексей_Валерьевич)
- [Яковлев, Юрий Васильевич](https://ru.wikipedia.org/wiki/Яковлев,_Юрий_Васильевич)

**Movie studios**:
- [Одесская киностудия](https://ru.wikipedia.org/wiki/Одесская_киностудия)

**Others**:
- [КиноПоиск](https://ru.wikipedia.org/wiki/КиноПоиск)
- [Hollywood Forever](https://ru.wikipedia.org/wiki/Hollywood_Forever)

**Comment by Popolechien** [comment]
@Ubuntu-2020 As indicated previously the articles you point to, when they do have an enwp equivalent, are not listed as part of the Wikiproject Film (likely an oversight from the community). That's one of the shortcomings of the selection system but nothing we can really do anything about (unless you do tag them properly on-wiki; then they'll be included in the next round).

**Comment by Ubuntu-2020** [comment]
@Popolechien OK. You mean [Wikipedia:WikiProject](https://en.wikipedia.org/wiki/Wikipedia:WikiProject)? Please explain in detail on the example of some of the above articles where it should be added so that it appears in the **ZIM** file.

**Comment by Popolechien** [comment]
@Ubuntu-2020 Here is [an example](https://en.wikipedia.org/w/index.php?title=Talk%3ATwo_Captains_%28film%29&type=revision&diff=967827971&oldid=856663882) with a movie

**Comment by Ubuntu-2020** [comment]
@Popolechien Thank you very much!
I understood. I need to add the appropriate tag on the **discussion page** for a **article**. Specifically about the **movie** this code is: `{{WikiProject Film}}`
What should I do if the article doesn't exist in the **English Wikipedia**?
I can't create so many articles! This will take a very long time.

**Comment by Popolechien** [comment]
@Ubuntu-2020 Yes, adding this template on the talk page does the trick.
If the article does not exist and you cannot create one in English (a short, one-line stub is enough for us to make the connection to the Russian one) then it is a net loss :-(

**Comment by Ubuntu-2020** [comment]
@Popolechien I have an idea. If there is an article in the English Wikipedia, then there is no problem. And if there is no article in the English Wikipedia, but there is an article in the German or French Wikipedia. Can I then add the code `{{WikiProject Film}}` to the discussion page of a specific article? In other words, will the German, French, Spanish, and Italian Wikipedia be suitable, or should there be an article in the English Wiki?

**Comment by Popolechien** [comment]
@Ubuntu-2020 As far as I know we only identify articles based on the English wiki tags (for consistency).
