### ISSUE TITLE
Frequency of updating ZIM files

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/zim-requests#284]
Already there are many **ZIM** files and over time their number will **only increase**!
There are a lot of outstanding requests on **[this page](https://github.com/openzim/zim-requests/issues)**.
In addition there are large **ZIM** files with a size of **30 GB**.
And if the user have a **low download speed** or a **limited Internet package** they may not be able to download such a file even in one month! But the largest **ZIM** file (**wikipedia_en_all_maxi_2020-06.zim**) weighs **89 GB**!

Based on the above I would suggest the following frequency of updates to ZIM files:
- every month (for ZIM files less than 10 GB)
- every two months (for ZIM files from 10 to 20 GB)
- every three months (for ZIM files from 20 to 30 GB)
- every four months (for ZIM files larger than 30 GB)
- every six months (for ZIM files larger than 70 GB)(en-wiki-all-maxi)

You can use the saved time to create ZIM files **better** and **fix errors** in existing ZIM files.

**Comment by kelson42** [comment]
If people can not afford to download a new version of a content each month, then they should not and download when they can every N months. We won't schedule our updated based on people with low bandwidth. To get details about how often the ZIM are scheduled, look at https://farm.openzim.org/recipes.

**Comment by Popolechien** [comment]
@Ubuntu-2020 I won't get much into details but individual users downloading content onto their personal phone or computer are only a fraction of our base - a lot come from organizations like schools and libraries who then act as local distributors, in which case it makes a lot of sense for them to have recent updates.
Also, once a recipe is ready the cost associated with running it once a month or once a year is marginal, so spacing out updates wouldn't allow us to assign more money to code.
