### ISSUE TITLE
Wikisummaries repeatedly fails

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#285]
See https://farm.openzim.org/recipes/wikisummaries

It did work once a couple of months ago but not really: http://library.kiwix.org/wikisummaries_en_all_maxi_2020-04/

**Comment by kelson42** [comment]
Looks like the configuration has changed then. I have fixed it.

**Comment by Popolechien** [comment]
https://farm.openzim.org/pipeline/5fc4e05abadfb69c5bab4e87 failed

**Comment by kelson42** [comment]
No, it succeeded https://farm.openzim.org/pipeline/5fc4e15486bd30ee81abfab5
