### ISSUE TITLE
Differnce in number of headwords between mini and maxi

### ISSUE THREAD

**Issue by sobaee** [openzim/zim-requests#288]
I read about this in readme.md file of yours, but the thing that I want to be sure about it, is there any difference in numbers of articles between (all mini) and (all maxi).
And I didn't understand what do you mean by "subset text" in the description of "mini"?
Does it mean that all articles is contained but no details, no audio, no video, no pictures?

N.B: I know what "top" means, so please don't include it in your response here 🙏

Many thanks.

**Comment by kelson42** [comment]
Yes, this is the same number of articles. Like written at http://download.kiwix.org/zim/README, this is the first section of any article, and not the whole article.
