### ISSUE TITLE
New ZIM request: TEALS CS curriculum

### ISSUE THREAD

**Issue by madhadron** [openzim/zim-requests#289]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://tealsk12.gitbook.io/intro-cs/
- License: Creative Commons Attribution Non-Commercial Share-alike License
- Desired ZIM Title: TEALS Introduction to Computer Science
- Desired ZIM Description: The Introduction to Computer Science curriculum is a flexible and approachable course adapted from the UC Berkeley CS 10, and is course for a wide range of high school students from diverse backgrounds.
- Desired ZIM Icon –png (URL or attach one): https://gblobscdn.gitbook.com/spaces%2F-LCzJq41PFoS--jMTTuQ%2Favatar.png?alt=media
- Language (ISO 639-3): English
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
URL is not valid
