### ISSUE TITLE
New ZIM request: Cours de français #1

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#292]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://www.youtube.com/watch?v=B4OxXFm_BqQ&list=PLcoQWyFpRIxjqHAr-WgPu6C0whuKH8tk7
- License: **Public domain**
- Desired ZIM Title: **Cours de français - La grammaire française**
- Desired ZIM Description: **70 Vidéos de Français avec Pierre pour découvrir et apprendre les subtilités de la grammaire française et ne plus faire d'erreurs !**
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
@barbayellow They seem to be selling to very classes, if I am to believe the pinned top comment. How certain are you that this is public domain (an option that is not available as a default license on YT if I'm not mistaken)?

**Comment by barbayellow** [comment]
Hi @Popolechien let me double check this with our content team. Thx for the warning.

**Comment by barbayellow** [comment]
Ok, it's tricky but we should not take any risks: the content on the website is published under copyright as stated in [their legal mentions](https://www.francaisavecpierre.com/mentions-legales/), however, the youtube channel is not sot clear about its licence. We're contacting us and we'll come back here as soon as we got the answer.

**Comment by kelson42** [comment]
@barbayellow Any update here?

**Comment by barbayellow** [comment]
Hi Kelson, no news from our content team yet. I will ask them again if they have any more information.

**Comment by kelson42** [comment]
@barbayellow No feedback, closing for the moment.

**Comment by JulienMoraliBSF** [comment]
@kelson42, update from our content team, they confirmed that every content reachable in the public part is in public domain
Can we re-open this request ?

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/francais-avec-pierre_fr_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
The file is ready at the library
https://library.kiwix.org/viewer#francais-avec-pierre_fr_all_2024-08
