### ISSUE TITLE
New ZIM request: Cours de français #2

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#293]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://www.youtube.com/watch?v=YsvOIi1AlPA&list=PLcoQWyFpRIxj6J0PAo_3SAJkCInMsoRoC
- License: **Public domain**
- Desired ZIM Title: **Cours de français - Vocabulaire et Expressions**
- Desired ZIM Description: **74 Vidéos de Français avec Pierre pour découvrir et enrichir son vocabulaire et répertoire d'expressions en langue française**
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by kelson42** [comment]
@barbayellow Te given link points to a specific video, you want the whole channel https://www.youtube.com/channel/UCVgW9ZQaGBk6fsiPgE2mYDg ?

**Comment by barbayellow** [comment]
Yes, sorry, my mistake. We need the whole playlist and not just one video. However, as @Popolechien stated in #292 we must first double check be sure the content is under public licence. We're contacting the website to check the content licence and if it's copyrighted we'll ask if they would allow potential bypass for humanitarian projects.

**Comment by kelson42** [comment]
@barbayellow playlists and channels are not the same. Do you want the whole channel? All playlists separatly? A specific playlist? Any update otherwise on the legal point?

**Comment by kelson42** [comment]
@barbayellow No feedback, closing for the moment.
