### ISSUE TITLE
New ZIM request: Dark Souls

### ISSUE THREAD

**Issue by Destroyer5150** [openzim/zim-requests#298]
The "Soul's" game's have a massive amount of lore and story. So much so even G.R.R.M. has joined the developers in creating a new game. It actually rivals the Ice and Fire books. Creating an available zim with all the pictures and lore from all of the game's would be great.

**Comment by Popolechien** [comment]
Hello @Destroyer5150 Destroy thanks for this (and no problem in principle) but we need the informations that are asked in the editing window when you opened this ticket (starting with the URL and licensing status). Closing for now but feel free to reopen when you can provide the relevant info.
