### ISSUE TITLE
Kata Biblon lexicon of the greek new testament

### ISSUE THREAD

**Issue by arnoulfos** [openzim/zim-requests#299]
- Website URL: https://lexicon.katabiblon.com
- License: CC-BY-NC-ND
- Desired ZIM Title: Kata Biblon lexicon of the greek new testament
- Desired ZIM Description: The Kata Biblon Wiki Lexicon of the Greek New Testament is a publicly editable dictionary of the Greek New Testament and Septuagint.
www.katabiblon.com
- Desired ZIM Icon –png (URL or attach one): https://www.katabiblon.com/common/favicon.png
- Language (ISO 639-3): eng, grc
- Desired Main Page (homepage, if different from website URL): n/a
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
Interesting. I don't think MWoffliner would be able to accomodate the "fetch verses" function (at least not out-of-the-box) but I'll try a first run to see where that takes us.

**Comment by arnoulfos** [comment]
Thanks a lot!

**Comment by RavanJAltaie** [comment]
The website says at bottom:
Copyright 2007-2022 Thomas Moore
Rejected
