### ISSUE TITLE
zim of glosbe

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#3]
_From @amirh123123 on September 14, 2018 8:50_

glosbe.com

_Copied from original issue: openzim/mwoffliner#374_

**Comment by RavanJAltaie** [comment]
Rejected
Looks hard to distinguish data
License and download
Some of data we present is licensed with CC-BY-SA, some is FDL, some comes with custom license. Data source is always indicated next to data if it is needed due to the license. "Download section" would be enabled when it is ready.
