### ISSUE TITLE
New ZIM request: finiki, the financial wiki

### ISSUE THREAD

**Issue by fux0r2009** [openzim/zim-requests#300]
Hi, please make this wonderful wiki available as a zim thank you very much!

- Website URL: https://www.finiki.org/
- License: CC-by-sa 4.0
- Desired ZIM Title: Finiki
- Desired ZIM Description: the Canadian financial wik
- Desired ZIM Icon –png (URL or attach one): https://www.finiki-org.financialwisdomforum.org/wiki/finiki:Logo#/media/File%3AFiniki_logo-verdana.png
- Language (ISO 639-3): ENG
- Desired Main Page (homepage, if different from website URL): https://www.finiki.org/wiki/Main_Page
- Is this a MediaWiki?: yes

**Comment by kelson42** [comment]
Done https://farm.openzim.org/recipes/finiki
