### ISSUE TITLE
Project Fuel (YT playlist)

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#305]
- Website URL: https://www.youtube.com/c/ProjectFUELlifelessons/playlists
- License: **CC-by-sa**
- Desired ZIM Title: Project FUEL
- Desired ZIM Description: Project FUEL collects life lessons from people all over the world and turns them into interactive and performance activities, to pass on the learnings
- Desired ZIM Icon –png (URL or attach one): https://d33wubrfki0l68.cloudfront.net/854058894535c00686ca936d7a9a491f4de42cb0/32e7b/img/logo.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#project-fuel_en_2024-08
