### ISSUE TITLE
New ZIM request: termux wiki

### ISSUE THREAD

**Issue by SHMAUS-Carter** [openzim/zim-requests#307]
- Website URL: https://wiki.termux.com/wiki/
- License: **CC BY 4.0**
- Desired ZIM Title: **Termux wiki**
- Desired ZIM Description: **offline Termux wiki backup**
- Desired ZIM Icon –png (URL or attach one): https://store.nethunter.com/repo/com.termux/en-US/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Done https://farm.openzim.org/recipes/termux_wiki
