### ISSUE TITLE
New ZIM request: UNF3S Cours medecine

### ISSUE THREAD

**Issue by Mitia99** [openzim/zim-requests#308]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://archives.uness.fr/sites/campus-unf3s-2014/
- License: CC-by-sa
- Desired ZIM Description: Cours de médecine humaine
- Desired ZIM Icon –png (URL or attach one): https://campus.cerimes.fr/image/logo-unf3s-noir.png
- Language (ISO 639-3): fra

**Comment by Popolechien** [comment]
@Mitia99 http://www.unf3s.org/ (the parent website) states "Copyright UNF3S tous droits réservés"
Are you sure about this website's CC-by-SA's licensing?

**Comment by Mitia99** [comment]
@Popolechien Oh,I didin't notice the parent site.So creating the zim won't be possible?

**Comment by Popolechien** [comment]
@Mitia99 Is there any way you can contact these guys so they give us email permission?

**Comment by Mitia99** [comment]
@Popolechien I found a contact.I'll contact them and keep you in touch![AddText_11-11-01.33.51.jpg](https://user-images.githubusercontent.com/56766778/98801270-a58e8180-2422-11eb-92c8-b7ed9db7a6e7.jpg)

**Comment by Popolechien** [comment]
Great, you can include `contact at kiwix.org`in your email (and French is fine, we're in Switzerland)

**Comment by RavanJAltaie** [comment]
@Mitia99 any update here?

**Comment by Mitia99** [comment]
> @Mitia99 any update here?

No news.

**Comment by RavanJAltaie** [comment]
I'll close the issue for now, feel free to re open it once you have news @Mitia99
