### ISSUE TITLE
New ZIM request: המכלול

### ISSUE THREAD

**Issue by davidshai** [openzim/zim-requests#309]
https://www.hamichlol.org.il/

- Website URL: https://www.hamichlol.org.il/
- Desired ZIM Title: ‏hamichlol
- Desired ZIM Description: האנציקלופדיה היהודית
- Desired ZIM Icon : https://www.hamichlol.org.il/w/upload/michlol/8/80/%D7%A1%D7%9E%D7%9C_%D7%94%D7%9E%D7%9B%D7%9C%D7%95%D7%9C_%D7%92%D7%9E%D7%A8%D7%90_2.PNG
- Language (ISO 639-3): עברית hebrew
- Desired Main Page : https://www.hamichlol.org.il/
- Is this a MediaWiki?: yes

**Comment by kelson42** [comment]
I have created a recipe here https://farm.openzim.org/recipes/hamichlol/, hopefully getting a ZIM soon.
