### ISSUE TITLE
Allow to scrape Twitter

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#312]
Looks at https://www.docnow.io/

**Comment by Popolechien** [comment]
@kelson42 What's the educational use case and what would be the scope (e.g. all of Twitter vs. select users or threads, à la https://awesomethread.com/ )?

**Comment by kelson42** [comment]
This ticket cames out a call I had we a few universities. This would be useful in academic research context to have large collection of Twitter accounts/threads to be able to run social studies.

**Comment by RavanJAltaie** [comment]
@Popolechien @kelson42 any update for this issue?

**Comment by Popolechien** [comment]
As far as I am concerned this is neither a priority nor something that is being funded. @kelson42 can we close it (and reopen if things change?)

**Comment by kelson42** [comment]
Twitter has lost anyway all its interest. Closing
