### ISSUE TITLE
New ZIM request:  AviSynth Wiki

### ISSUE THREAD

**Issue by kodxana** [openzim/zim-requests#314]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: http://avisynth.nl/index.php/Main_Page
- License: **Creative Commons Attribution-ShareAlike 3.0 License (CC BY-SA 3.0)**
- Desired ZIM Title: **AviSynth Wiki**
- Desired ZIM Description: **AviSynth is a powerful tool for video post-production. It provides ways of editing and processing videos. AviSynth works as a frameserver**
- Desired ZIM Icon –png (URL or attach one): http://avisynth.nl/skins/common/images/avisynth-logo-gears-mod.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by kelson42** [comment]
done https://farm.openzim.org/recipes/avisynth

**Comment by Popolechien** [comment]
@kelson42 @rgaudin Sounds like an interesting tool to add to future iterations of the Hotspot, no?

Created https://farm.openzim.org/recipes/avisynth_en - I see that there are language versions but not as subdomain (see, e.g., http://avisynth.nl/index.php/Main_Page/fr). Do we have a way to split them?

**Comment by rgaudin** [comment]
I don't see the connection with the hotspot…

Regarding zim, it could be named multi as it's a single Wiki with articles in multiple languages organized freely (categories, etc). Splitting it could be done just by changing the main page.

**Comment by Popolechien** [comment]
> I don't see the connection with the hotspot…

Simply as a tool that could be run off it, much like moodle, wikifundi, etc.?

**Comment by rgaudin** [comment]
> Simply as a tool that could be run off it, much like moodle, wikifundi, etc.?

I'm lost. I don't know this tool but main page says:

> AviSynth is a powerful tool for video post-production. It provides ways of editing and processing videos. AviSynth works as a frameserver, providing instant editing without the need for temporary files

And it seems to be a windows binary…

**Comment by kelson42** [comment]
MWoffliner fails to scrape this wiki properly. The reason is that this is a super old (10+ years) version of Mediawiki. See https://github.com/openzim/mwoffliner/issues/1366

**Comment by kodxana** [comment]
@kelson42 any way I could scrap it manually?

**Comment by kelson42** [comment]
I don't know, the best thing to do is to upgrade the version of Mediawiki used by this web site.
