### ISSUE TITLE
New ZIM request: Neos Wiki

### ISSUE THREAD

**Issue by kodxana** [openzim/zim-requests#315]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://wiki.neos.com
- License: **general information purposes**
- Desired ZIM Title: **Neos Wiki**
- Desired ZIM Description: **Neos is an innovative metaverse engine designed to accelerate the development of social VR applications.**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Neos_VR_Logo.png/596px-Neos_VR_Logo.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **https://wiki.neos.com/Main_Page**
- Is this a MediaWiki?: **yes**

**Comment by kelson42** [comment]
Recipe  is here https://farm.openzim.org/recipes/neos_wiki

**Comment by kodxana** [comment]
Thank you :)
