### ISSUE TITLE
https://oer.suny.edu/

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#320]
Please use the following format for a ZIM creation request (and delete unnecessary information)

Website URL: https://oer.suny.edu/ 
License: Creative Commons | Public domain | 
Desired ZIM Title: SUNY OER Services
Desired ZIM Description: SUNY campuses and faculty to provide assistance and knowledge
Desired ZIM Icon –png (URL or attach one): 
Language (ISO 639-3): eng
Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/oer.suny.edu_en_all
I'll update the library file once ready

**Comment by Popolechien** [comment]
Looks to me like this is only a list of description of courses and actual access is reserved to SUNY students
![Screenshot 2024-08-13 at 14 19 36](https://github.com/user-attachments/assets/21d9ac88-f398-45ef-99b8-e6ed2e6c391a)

They have, however, links to other open educational resources that look more promising.

@RavanJAltaie Can you please delete this recipe and close it when done?

**Comment by RavanJAltaie** [comment]
Recipe deleted.
