### ISSUE TITLE
Koch-Wiki ZIMs are broken

### ISSUE THREAD

**Issue by chjohn22** [openzim/zim-requests#324]
All ZIMs from Koch-Wiki are broken since last autumn. They had a size of about 40-50 Megabytes each, but now they only weigh 4-5 Megabytes. So all new versions which are available for download are totally broken. Each article just shows: `[object Object]`

Maybe you can publish an old one in working condition until a fix is available? I could send you `kochwiki_de_all_maxi_2020-07.zim`if you do not have it anymore.

**Comment by kelson42** [comment]
@chjohn22 Thank you for your bug report, I believe this ticket to be a duplicate of https://github.com/openzim/mwoffliner/issues/1363. Therefore, closing.

**Comment by kelson42** [comment]
New *proper* ZIM files should be available online in the next hours, see https://farm.openzim.org/pipeline/976994088c589d106213d106
