### ISSUE TITLE
openlibrary.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#326]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://openlibrary.org/
- License: Public domain
- Desired ZIM Title: Open Library
- Desired ZIM Description: 1.7 M public domain books
- Desired ZIM Icon –png (URL or attach one): https://openlibrary.org/static/images/openlibrary-logo-tighter.svg
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
The recipe succeeded but the zim file opens nothing beyond the main page.
Placed a ticket to investigate more
#https://github.com/openzim/zimit/issues/203

**Comment by benoit74** [comment]
Reopening since recipe needs to be fixed, as mentioned in upstream ticket.

Current dev ZIM seems promising, I fixed the recipe by adding the `autoscroll` behavior since the website seems to load assets dynamically as the user scroll: `autoplay,autofetch,autoscroll` and requested it again with Zimit2

**Comment by benoit74** [comment]
I did not realized this was THE openlibrary.org

This is not something we can scrape with Zimit. This needs a custom scraper.

**Comment by benoit74** [comment]
Oh, and do we really want the books in the ZIM? Because AFAIK, the books themselves are not free at all, registered users can allow borrow some ebooks for a given amount of time.

**Comment by Popolechien** [comment]
Ah well if it is not free then it's out of bounds for us. Not sure how I could get this request so wrong.

**Comment by benoit74** [comment]
@Popolechien did you really checked that I'm right about the license? I might be wrong as well, it is just based on my rather very limited experience with the website.

**Comment by Popolechien** [comment]
Yep you were right
