### ISSUE TITLE
New ZIM request: https://www.feynmanlectures.caltech.edu/

### ISSUE THREAD

**Issue by Aang488** [openzim/zim-requests#328]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://xxx
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **My title**
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no**

**Comment by Aang488** [comment]
Kindly make a zim of feynman Lectures, I'll be indebted to you

**Comment by Popolechien** [comment]
@Aang488 Hey no problem, but we need you to put in a minimum of effort and fill out the fields above (license, titie, description, etc.)

**Comment by eshellman** [comment]
it's copyrighted; publisher is zealous about takedowns.

**Comment by Aang488** [comment]
You asked them?, I guess it creative commons 😑

**Comment by Aang488** [comment]
> it's copyrighted; publisher is zealous about takedowns.

I guess it's creative commons 😑

**Comment by eshellman** [comment]
yes, I have corresponded with the publisher

**Comment by Popolechien** [comment]
@eshellman Thanks!

@Aang488 give it a try with [zimit](https://www.youzim.it) (there's a cutoff at 1'000 pages and the corresponding zim files can only be read on Kiwix-serve and Kiwix-Android atm). We may eventually do private copy.

**Comment by Aang488** [comment]
I did that but it didn't open any subtopic with a topic 😐
And i badly need it

**Comment by Aang488** [comment]
> yes, I have corresponded with the publisher

thank you 🙂

**Comment by eshellman** [comment]
relatively easy to scrape. This has some backstory, but I contacted them again in September. https://go-to-hellman.blogspot.com/2014/03/the-dmca-takedown-of-feynman-lectures.html

**Comment by Aang488** [comment]
> relatively easy to scrape. This has some backstory, but I contacted them again in September. https://go-to-hellman.blogspot.com/2014/03/the-dmca-takedown-of-feynman-lectures.html

Thank you so much for sharing, i don't understand a word of that, am using github for the first time 😊, but your enthusiasm to help me out made me very happy! ❤️

**Comment by Popolechien** [comment]
Ok, I guess we can close this ticket then (commenting remains open).
