### ISSUE TITLE
New ZIM request: Le droit d’auteur pour les jeunes

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#329]
Nautilus-compatible content:

- Website URL: https://www.dropbox.com/sh/eaao3vcp5jg08dx/AAACOn2NoPML0p1W1lV2GsiHa?dl=0
- List of files with parameters: https://docs.google.com/spreadsheets/d/1cCY6c6YrpA6RQ7hhBtWbE_ssPKYf2EdMQtdRys3OZI8/edit?usp=sharing
- License: CC-by-sa 
- Desired ZIM Title: Le droit d’auteur pour les jeunes
- Desired ZIM Description: Un ensemble de ressources destinées aux enseignants pour la
sensibilisation des 9-14 ans au droit d'auteur et licences Creative Commons
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/8/86/Wiki_In_Africa_full_colour_logo_02.png
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
@Popolechien shall I create the recipe for this issue?

**Comment by Popolechien** [comment]
I think we have it already https://library.kiwix.org/#lang=fra&q=droit+d%27auteur and I forgot to close it ¯\_(ツ)_/¯
