### ISSUE TITLE
Single bundle for StackExchange 

### ISSUE THREAD

**Issue by zkosk** [openzim/zim-requests#330]
Is there a single bundle of all StackExchange sites? Can't find it here https://wiki.kiwix.org/wiki/Content_in_all_languages, there are only zims for each sub sites.

**Comment by kelson42** [comment]
@zkosk no, what woukd be the value of it?

**Comment by kelson42** [comment]
Closing, we are not doing to do that. To the contrary, we try to publish smaller subsets.
