### ISSUE TITLE
New ZIM request: boobpedia

### ISSUE THREAD

**Issue by slavamargez** [openzim/zim-requests#346]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://boobpedia.com/
- License:  Public domain 
- Desired ZIM Title: Boobpedia: Encyclopedia of Big Tits
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png https://boobpedia.com/bp.gif
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: yes

**Comment by RavanJAltaie** [comment]
The URL is not valid.

**Comment by Popolechien** [comment]
@RavanJAltaie The URL is valid here (maybe it's blocked on your end because of the sensitive nature?)

This being said I'm all for free knowledge broadly construed but _that one particular site_ may be a bit much... So yeah, let's leave it there.
