### ISSUE TITLE
Chabadpedia

### ISSUE THREAD

**Issue by simchafisch** [openzim/zim-requests#348]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: http://chabadpedia.co.il/
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **חברפדיה**
- Desired ZIM Description: **גרסה לא מקוונת של חברפדיה**
- Desired ZIM Icon –png (URL or attach one): https://images.app.goo.gl/GKiQ6JwQsMJtJhg96
- Language (ISO 639-3): **עבר**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Ok I've launched https://farm.openzim.org/recipes/chabadpedia

Job ran fine but only picked up the front page. I've [opened a ticket](../../mwoffliner/issues/1461)

**Comment by Popolechien** [comment]
Bug has been fixed, moving recipe away from dev. Should show up in the library in the next 24hrs.
