### ISSUE TITLE
New ZIM request: Wikipedia for Schools

### ISSUE THREAD

**Issue by SolarSPELL-Main** [openzim/zim-requests#350]
- Website URL: 
https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome
- License: **CC-by-sa 
- Desired ZIM Title: Wikipedia for Schools
- Desired ZIM Description: Wikipedia for Schools (WfS), is a curated selection of Wikipedia articles targeted for use in offline primary and secondary classrooms. It has been curated to be an educational resource that promotes information literacy, digital, and research skills in remote, rural, offline communities globally. This version of Wikipedia for Schools was curated by SolarSPELL, an educational initiative at Arizona State University.
- Desired ZIM Icon –png (URL or attach one): ![wikipedia](https://user-images.githubusercontent.com/57197808/118203396-d458d500-b410-11eb-95e1-a88339f4e035.png)
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a** - same as websiteURL
[Landing page + History.xlsx](https://github.com/openzim/zim-requests/files/6475657/Landing.page.%2B.History.xlsx)

The attached excel sheet has one page [titled Landing page and subpages] with the links for the main landing page (Website URL); one page with the links/articles to be listed in the History subpage (excel sheet titled History page articles); and one page [titled History articles] with all of the articles that won't be listed on the landing page or subpage, but should be within the Wikipedia for Schools application to be searched by users.

**Comment by SolarSPELL-Main** [comment]
New ZIM description: A selection of student-friendly Wikipedia articles for teachers and students in primary and secondary schools around the world. Curated by SolarSPELL, an educational initiative at Arizona State University.

New Zim icon (-png) 
![wikipedia-for-schools](https://user-images.githubusercontent.com/57197808/120034190-88319700-bfb1-11eb-9080-b5b22ee84672.png)

**Comment by SolarSPELL-Main** [comment]
New excel sheet of articles to include in Wikipedia for Schools (the rest of the submitted information -- URL, description, logo, etc.) is the same)

[Final_SU21_Kiwix_format_Working Document - Articles List.xlsx](https://github.com/openzim/zim-requests/files/6934123/Final_SU21_Kiwix_format_Working.Document.-.Articles.List.xlsx)

**Comment by kelson42** [comment]
@SolarSPELL-Main Ok, will do a new scrape based on it. If you could next time export this XLS in a one column CSV, that would be helpful.

**Comment by kelson42** [comment]
Latest version has been made https://farm.openzim.org/pipeline/06c74eb3b2f47b15ba5a3116. A few articles can not be downloaded properly, so far I can see they are wrong (they don't exist).

**Comment by Popolechien** [comment]
@kelson42 I spotted a couple of images in gallery whose name is not properly displayed ([source is ok](https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome/Natural_Science) though)
![Screenshot_20210811-141007](https://user-images.githubusercontent.com/21675885/129026718-512491b2-7383-470e-8a31-862504b414a2.png)
Could this be an MWoffliner issue?

**Comment by kelson42** [comment]
@Popolechien Not sure, but please open a ticket at openzim/mwoffliner yes.
