### ISSUE TITLE
New ZIM request: Wikimedica

### ISSUE THREAD

**Issue by Mitia99** [openzim/zim-requests#353]
- Website URL: https://wikimedi.ca/
- License: CC-by-sa 
- Desired ZIM Title: Wikimedica
- Desired ZIM Description: Plateforme collaborative permettant l'accès et l'amélioration des ressources utiles aux professionnels de santé/étudiants

- Desired ZIM Icon –png : https://images.app.goo.gl/mfjy9vQGNyPF6MwN9

- Language (ISO 639-3): fra

**Comment by Popolechien** [comment]
https://farm.openzim.org/recipes/wikimedica
Let's check in a few hours if it worked or is like many other wikis.

**Comment by Mitia99** [comment]
@Popolechien Okey.Thanks a lot and kindly keep me updated please.
