### ISSUE TITLE
Update ZIM: English and German Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/zim-requests#354]
The latest ZIM file of German Wikipedia is from 2021-03, exactly 3 months from today. English Wikipedia is also almost 3 months old (10 days from today). 

Could someone, if time is available, update and upload these two Wikipedias? Man, that would be excellent. Everyone loves to be up to date. 👍🏽

**Comment by kelson42** [comment]
We are aware of the problem. This is an upstream problem at Wikimedia to a large extend. We do our best to make new versions of the zim regularly.

**Comment by Inbefortus** [comment]
@kelson42 @Popolechien 


Just so you know, if there is anything I can assist you with, such as examining new releases (or anything you think will help), let me know. I would love to help you guys fix all these issues. I assure you that I greatly acknowledge Kiwix and the point that you can carry the whole damn Wikipedia in your pocket. I use your app all the time. It is the best app for offline purposes. That's what technology is earnestly made for.

**Comment by Popolechien** [comment]
@Inbefortus Thanks for the offer - we might actually take you up on that. We're soon to roll out a Content Manager and the plan is to open it to volunteers. Details remain to be discussed, but if that's something you'd be interested in helping out with do drop an email at contact@kiwix.org (subject: CRM)

**Comment by kelson42** [comment]
@Inbefortus I can only emphasis what @Popolechien has written last month. You have provided many helpful feedbacks about both content and software. We value that, in particular in the field of content, where we really miss people like you, who look to things in detail. If you are interested to know more about Kiwix, beein better integrated within the team, have more impact... then I can only reiterate the invitation: write us an email so we can better know each other.

**Comment by Inbefortus** [comment]
@kelson42 Thank you, I am glad to hear that. I'm obliged to say that I greatly enjoy supporting Kiwix. After all, our greatest aspiration is to make the use of Kiwix by its users as fantastic as possible. 👍🏽


FYI: I have already written and sent an email with reference to the CRM a month ago. As soon as the whole thing starts, I will be notified. You guys can also email me at any time if I can be of assistance in a particular category!

**Comment by Popolechien** [comment]
@Inbefortus Yep, thanks. The CMS has been delayed but it's still on the table. We'll reach out eventually, but you can already keep an eye on [openzim/cms](../../../../openzim/cms/issues) to see when things will be moving.
