### ISSUE TITLE
New ZIM request: Minecraft Wiki

### ISSUE THREAD

**Issue by ElonSatoshi** [openzim/zim-requests#357]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://minecraft.fandom.com/
- License: **CC BY-NC-SA 3.0**
- Desired ZIM Title: **Minecraft Wiki**
- Desired ZIM Description: **Minecraft is a sandbox construction video game developed by Mojang Studios where players interact with a fully modifiable three-dimensional environment made of blocks and entities. Its diverse gameplay lets players choose the way they play, allowing for countless possibilities.**
- Desired ZIM Icon –png (URL or attach one): https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/93/Grass_Block_JE7_BE6.png/revision/latest?cb=20200830143209&format=original
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/minecraft_fandom_all 
[Failed](https://farm.openzim.org/pipeline/1bee49e1dbb27558d714cd06/debug) with `"code": "apierror-visualeditor-docserver-http", "info": "HTTP 503"`

Error seems to be on fandom end, will retry later.

**Comment by Popolechien** [comment]
Failed again. @kelson42 am I right to think that we need to reach out to Wikia to figure this out?

**Comment by kelson42** [comment]
There is a working recipe at https://farm.openzim.org/recipes/minecraft_de_all/

**Comment by kelson42** [comment]
My bad, there is one in German and one in English. Will recreate the one in English and get it working.

**Comment by kelson42** [comment]
[Done https://farm.openzim.org/recipes/minecraft_de_alll](https://farm.openzim.org/recipes/minecraft_fandom_en_all)
