### ISSUE TITLE
new zim request tor.stackexchange.com

### ISSUE THREAD

**Issue by PhiDi3di** [openzim/zim-requests#358]
Website URL: https://tor.stackexchange.com/
License: site design / logo © 2021 Stack Exchange Inc; user contributions licensed under cc by-sa. rev 2021.7.13.39733
Desired ZIM Title: tor.stackexchange.com_en
Desired ZIM Description: Stack Exchange Inc is Q&A community containing this sublet for information on Tor. Tor is free software and an open network that helps you defend against traffic analysis, a form of network surveillance that threatens personal freedom and privacy, confidential business activities and relationships, and state security. 
Desired ZIM Icon –png (URL or attach one): "https://icons.iconarchive.com/icons/blackvariant/button-ui-requests-8/256/Tor-icon.png" or any similar relating to SE or TOR, the color alone 
Language (ISO 639-3): eng
Desired Main Page (homepage, if different from website URL): n/a
Is this a MediaWiki?: no

**Comment by rgaudin** [comment]
Thanks @PhiDi3di, it's about to be build soon.

**Comment by Popolechien** [comment]
We already have tor.stackexchange ([see here](https://farm.openzim.org/pipeline/843de8564d13328dbeade806)), and StackOverflow to Kiwix (see openzim/sotoki) is currently being revamped.
