### ISSUE TITLE
mdwiki.tsv

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-requests#359]
@kelson42 To create a tsv for mdwiki I merged the medicine.tsv that you produce with the result of 

'https://mdwiki.org/w/api.php?action=query&apnamespace=' + namesp + '&format=json&list=allpages&aplimit=max&apcontinue='

where namespace is 0 and 3000.

I was wrong to say that this does not include redirects, which at the time I thought were required. The authors of mwoffliner may know an optimal way to exclude redirects.

A newly generated version of this file without the medicine merge is available at http://iiab.me/downloads/mdwiki.tsv.

**Comment by kelson42** [comment]
@tim-moody Thx for the TSV, I have test with it many times, but the process always die, see latest attempt https://farm.openzim.org/pipeline/69c54ea67e2721a40aabfe06/debug. It is always the same article causing problems: `List_of_skin_conditions`.

**Comment by tim-moody** [comment]
@kelson42 if an article such as List_of_skin_conditions were to occur twice in the tsv would it get tried twice?

**Comment by kelson42** [comment]
@tim-moody no, i don't think do

**Comment by tim-moody** [comment]
@kelson42 you reported that the process dies when encountering List_of_skin_conditions, the relevant part of the log being:

```
[error] [2021-07-15T05:32:34.087Z] Error downloading article List_of_skin_conditions
Failed to run mwoffliner after [3520s]: {
	"code": "apierror-visualeditor-docserver-http-error",
	"info": "Error contacting the Parsoid/RESTBase server: (curl error: 28) Timeout was reached",
	"*": "See https://mdwiki.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."
}
[log] [2021-07-15T05:32:34.090Z] Exiting with code [2]
```

I ran a more limited test with only that article, see https://github.com/openzim/mwoffliner/issues/1505

But in my case the article was skipped and the process continued. It was run on the latest docker image with the command:

```
# mwoffliner only command
# use S3
S3URL="http://iiab-content:9000/?bucketName=mwobucket&keyId=AKIAIOSFODNN7EXAMPLE&secretAccessKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  mwoffliner \
  --adminEmail="info@iiab.me" \
  --articleList="/lists/skin.tsv" \
  --customMainPage="WikiProjectMed:App/IntroPage" \
  --customZimTitle="MDWiki" \
  --customZimDescription="MDWiki is a collection of healthcare content developed from Wikipedia specifically for offline use." \
  --customZimFavicon="https://en.wikipedia.org/static/images/project-logos/enwiki.png" \
  --filenamePrefix="skin" \
  --mwUrl="https://mdwiki.org/" \
  --osTmpDir="/dev/shm" \
  --outputDirectory="/output" \
  --optimisationCacheUrl=$S3URL \
  --zstd \
  --requestTimeout=120000 \
  --speed="0.1" \
  --webp \
  --verbose

```
I should also mention that I reran this command immediately afterwards and the article did not time out, presumably because the server had it in cache.

**Comment by kelson42** [comment]
@tim-moody Lots of interesting findings... for the moment I would like to focus on fixing the following points:
* Timeout is given in seconds (not milliseconds)
* Timeout is respected

**Comment by tim-moody** [comment]
@kelson42 I would add to that the following:

- Timeout causes some number of retries before giving up
- Timeout behaves consistently, either the process is terminated or the article is skipped.

**Comment by kelson42** [comment]
@tim-moody BTW, we might start to consider to use the new Mediawiki REST API https://www.mediawiki.org/wiki/API:REST_API .... but somehow it seems to not work at all on mdwiki, see https://mdwiki.org/w/rest.php/v1/page/Earth

**Comment by kelson42** [comment]
I thin we can close this
