### ISSUE TITLE
New ZIM request: Stackoverflow 2021

### ISSUE THREAD

**Issue by MichaMan93** [openzim/zim-requests#361]
- Website URL: https://stackoverflow.com/

- Desired ZIM Title: Stackoverflow zim file
- Desired ZIM Description: A working and some what updated SOF zim file
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

If the file exists please inform me with the download link path please.
Thanks a lot

**Comment by kelson42** [comment]
See https://github.com/openzim/zim-requests/issues/358#issuecomment-879762182, a new version will be released in the next weeks. You will need a bit of patience.
