### ISSUE TITLE
New ZIM request: Mashruteh

### ISSUE THREAD

**Issue by gitigohar** [openzim/zim-requests#363]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://mashruteh.org
- License: **CC-by-sa
- Desired ZIM Title: **Mashruteh**
- Desired ZIM Description: **Persian database of history about Iran and Middle East (این پایگاه یک کتابخانه پژوهشی دیجیتال تاریخ معاصر ایران است)**
- Desired ZIM Icon –png (URL or attach one): https://ibb.co/wRVKxvC
- Language (ISO 639-3): **Farsi**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/mashruteh but two successive runs returned a 404 error. 

@rgaudin any idea what went wrong there?

**Comment by kelson42** [comment]
@Popolechien The recipe misconfiguration you had is fixed, let see if no other problem appears.

**Comment by gitigohar** [comment]
hello friends
is there any other problem?
can you zim the website now?

**Comment by Popolechien** [comment]
It looks like it [crashed ](https://farm.openzim.org/pipeline/ad564e3d60f566c74be21016/debug)after a timeout somewhere mid-way into the process (so it's probably on their side). I'm attaching the log and I've restarted the recipe to see if we get any better luck.
[ad564e3d60f566c74be21016_mwoffliner.log](https://github.com/openzim/zim-requests/files/6912282/ad564e3d60f566c74be21016_mwoffliner.log)

**Comment by Popolechien** [comment]
Failed [after 9 hours](https://farm.openzim.org/pipeline/ea684ed30929548978946016) :-(

**Comment by Popolechien** [comment]
Ok, tried and failed again with `504 Gateway timeout` this time. Nothing more that we can do on our side, sorry :-(
