### ISSUE TITLE
New ZIM request: 

### ISSUE THREAD

**Issue by Soufileaks** [openzim/zim-requests#364]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://www.youtube.com/c/Mentalit%C3%A9Ing%C3%A9nieur
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **MentalitéIngénieur**
- Desired ZIM Description: **ingenieurie, tutos techniques**
- Desired ZIM Icon –png (URL or attach one): https://yt3.ggpht.com/ytc/AKedOLTSl-H0KJMjfnw3ajFJL9qOB9Rk69jlQfPYR5ZU=s88-c-k-c0x00ffffff-no-rj
- Language (ISO 639-3): **fr**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
@soufileaks I've [pinged them on Twitter](https://twitter.com/KiwixOffline/status/1419567930757586944) to confirm the licensing status but should they fail to respond we'll go ahead with the scraping.

**Comment by Soufileaks** [comment]
Hi, thank you for your work and reactivity, I stay tunned if I an help

**Comment by Popolechien** [comment]
They have responded via email (ticket 23312)

> Thanks for getting in touch with us. I can confirm that our content is not under a CC-licence. 
> Kiwix sounds like a fantastic cause to help many people but it's not something we wish to participate in at this point in time. Thank you nonetheless for reaching out and we wish you all the best. 
> Thanks
> Tash
