### ISSUE TITLE
New ZIM request:SKYbrary

### ISSUE THREAD

**Issue by gordonlgy** [openzim/zim-requests#365]
Please use the following format for a ZIM creation request

Website URL: https://skybrary.aero/
License: Public domain
Desired ZIM Title: SKYbrary
Desired ZIM Description: SKYbrary Aviation Safety
Desired ZIM Icon –svg (URL or attach one): https://flightsafety.org/wp-content/uploads/2016/07/Skybrary-logo-824-e1475698650414.png
Language (ISO 639-3): eng
Desired Main Page (homepage, if different from website URL): https://www.skybrary.aero/index.php/Main_Page
Is this a MediaWiki?: yes

**Comment by gordonlgy** [comment]
- the Web site  is Powered by MediaWiki <https://www.mediawiki.org/> Powered
   by Semantic MediaWiki
   <https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki>


Popo le Chien ***@***.***> 于 2021年7月27日周二 上午2:32写道：

**Comment by kelson42** [comment]
> Ran recipe here: https://farm.openzim.org/pipeline/6f864e88bc16dd5704f8df06
> Failed with `Cannot read property 'modules' of undefined` error message.
> 
> @kelson42 Is this an mwoffliner issue or from the target wiki?

Bug in MWoffliner, see https://github.com/openzim/mwoffliner/issues/1456

**Comment by gordonlgy** [comment]
will it be fixed? when shall we expect to have this website zim file?

**Comment by Popolechien** [comment]
@gordonlgy It's been assigned to the next maintenance milestone, but we have no release date for it at the moment.

**Comment by gordonlgy** [comment]
> @gordonlgy It's been assigned to the next maintenance milestone, but we have no release date for it at the moment.

thanks, waiting for the good news.

**Comment by gordonlgy** [comment]
@Popolechien hi, how is it right now?

**Comment by Popolechien** [comment]
Nothing to report. We've started pitching grant requests to get mwoffliner revamped, until then we'll have to hope for an ambitious volunteer developer to help with the most obvious bugs.

**Comment by RavanJAltaie** [comment]
@Popolechien Is this ticket's status still the same?

**Comment by Popolechien** [comment]
@RavanJAltaie I can't find the recipe anymore. Check the website still exists, that they haven't modified their licensing, and create a new recipe (and then close the ticket).

**Comment by RavanJAltaie** [comment]
They've changed the License 
Copyright © SKYbrary Aviation Safety, 2021-2022. All rights reserved
Rejected
