### ISSUE TITLE
New ZIM request: Stanford Encyclopedia of Philosophy

### ISSUE THREAD

**Issue by drgonzo31** [openzim/zim-requests#366]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://plato.stanford.edu/
- License: ??
- Desired ZIM Title: SEP
- Desired ZIM Description: Stanford Encyclopedia of Philosophy
- Desired ZIM Icon –png (URL or attach one): https://plato.stanford.edu/symbols/sep-man-red.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): https://plato.stanford.edu/index.html
- Is this a MediaWiki?: no.

**Comment by Popolechien** [comment]
_The Stanford Encyclopedia of Philosophy is copyright © 2021 by The Metaphysics Research Lab,_
