### ISSUE TITLE
New ZIM request: Internet Encyclopedia of Philosophy 

### ISSUE THREAD

**Issue by drgonzo31** [openzim/zim-requests#367]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://iep.utm.edu/
- License: ??
- Desired ZIM Title: IEP
- Desired ZIM Description: Internet Encyclopedia of Philosophy 
- Desired ZIM Icon –png (URL or attach one): https://en.wiktionary.org/wiki/%CE%A6#/media/File:Greek_letter_uppercase_Phi.svg
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): https://iep.utm.edu/
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
_"All articles are copyrighted by The IEP and the authors of the original articles; accordingly, our articles are not open source or in the public domain."_

**Comment by Popolechien** [comment]
Authorization granted - see ticket 23474.

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/internet-encyclopedia-philosophy_en
Zim file should be available in a day or so. 

@drgonzo31 just so you know, we've used zimit for this one which therefore uses service workers. This means that the only versions of Kiwix able to read it for the time being will be Kiwix-android and Kiwix-serve (on Raspberry Hotspots). Kiwix desktop and iOS/macOS will eventually catch up, but later.

**Comment by Popolechien** [comment]
Note: the search box and the category selector do not work, so finding articles will have to be done through the alphabetical ledger on top of the page.
