### ISSUE TITLE
New ZIM request: Lesswrong

### ISSUE THREAD

**Issue by drgonzo31** [openzim/zim-requests#368]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://www.lesswrong.com
- License: ??
- Desired ZIM Title: LessWrong
- Desired ZIM Description: LessWrong is a community dedicated to improving our reasoning and decision-making. We seek to hold true beliefs and to be effective at accomplishing our goals. More generally, we work to develop and practice the art of human rationality.
- Desired ZIM Icon –png (URL or attach: https://en.m.wikipedia.org/wiki/File:LessWrong_logo.svg
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
I've sent a note to clarify their licensing conditions.

**Comment by Popolechien** [comment]
Reply from LessWrong.com:
_"Alas, LessWrong used to have an option to publish some posts under a CC-license, but many of our authors actually cared about retaining their copyright, so we only have permission to use it."_
