### ISSUE TITLE
tvtropes.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#369]
- Website URL: https://tvtropes.org
- License: **CC-by-NC-sa**
- Desired ZIM Title: TV Tropes
- Desired ZIM Description: The pop-culture wiki
- Desired ZIM Icon –png (URL or attach one):https://tvtropes.org/images/logo-white-big.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no** (pmwiki)

**Comment by Popolechien** [comment]
I created a recipe but after 8 days it's only covered 4% of it. 
https://farm.openzim.org/pipeline/08c53829a73b1d04311a9416/debug

@rgaudin Any idea of how we could speed this up?

**Comment by malicious** [comment]
Hi, I've downloaded some recent ZIM files from https://mirror.download.kiwix.org/zim/.hidden/dev/, and it looks like TVTropes is throttling the downloader. Specifically:

- in `tvtropes_en_all_2022-07.zim`, I noticed the "Chuunibyou" page shows a 403 page that says "We're sorry, but we're receiving too many requests from you. / Please wait a few minutes before trying again."
- the other archives, June/August, are a fraction of the size (150 MB vs 1 GB)

Perhaps contacting TVTropes would help?

**Comment by RavanJAltaie** [comment]
@Popolechien @rgaudin any update on this? 
This is what I'm getting when opening the zim file.
![image](https://github.com/openzim/zim-requests/assets/116940574/8fad04b3-3155-4b46-8668-b55e2eb3a9b0)

**Comment by rgaudin** [comment]
Changed recipe and recreated. New one is 380MB and [dev](https://dev.library.kiwix.org/viewer#tvtropes_en_all_2023-07) looks usable. Please check

**Comment by RavanJAltaie** [comment]
Checked & moved to main library
