### ISSUE TITLE
New ZIM request: Lurkmore

### ISSUE THREAD

**Issue by sunsh1newarrior** [openzim/zim-requests#370]
- Website URL: https://lurkmore.to
- License: CC BY 3.0
- Desired ZIM Title: Lurkmore
- Desired ZIM Description: An informal Russian-language online encyclopedia focusing on Internet subcultures, folklore and memes.
- Desired ZIM Icon –png (URL or attach one): https://lurkmore.to/skins/common/favicon.png
- Language (ISO 639-3): ru
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/lurkmore_ru/edit 
Let's see if it works or is also plagued by the latest regression.

@sunsh1newarrior I've translated your ZIM description to _Неофициальная русскоязычная онлайн-энциклопедия, посвященная интернет-субкультурам, фольклору и мемам._ Correct?

**Comment by sunsh1newarrior** [comment]
@Popolechien Okay, thanks. 
Yep, translation is correct.

**Comment by Popolechien** [comment]
Ah, it failed with error message `Mediawiki version 1.19.24 not supported should be >=1.27`
(current MW version is 1.36.0, so it's not like we are very strict, eh)

@sunsh1newarrior if you feel like sending them an email recommending an update. I will close the request but feel free to reopen it if they respond.
