### ISSUE TITLE
New ZIM request: Appropedia

### ISSUE THREAD

**Issue by Sophivorus** [openzim/zim-requests#371]
- Website URL: https://www.appropedia.org
- License: CC-BY-SA
- Desired ZIM Title: Appropedia
- Desired ZIM Description: Shared knowledge to build rich, sustainable lives.
- Desired ZIM Icon –png (URL or attach one): https://www.appropedia.org/logo-poncho.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): https://www.appropedia.org/Welcome_to_Appropedia
- Is this a MediaWiki?: yes

If the entire wiki is too much, then I'd like to request a ZIM file for https://www.appropedia.org/Practical_Action_Technical_Briefs and the pages linked therein. Our immediate goal is to able to see for ourselves how Appropedia looks on Kiwix so as to better understand the potential. Thanks!!

**Comment by kelson42** [comment]
@Popolechien So could we close this as duplicate?

**Comment by Popolechien** [comment]
Seems like it to me

**Comment by Sophivorus** [comment]
Hi! I'm reopening this issue because https://github.com/openzim/mwoffliner/issues/1456 fixed the error with Appropedia runs (thanks!) but it seems like now there's a NEW issue preventing the run from completing. I'm not sure exactly what's the issue but https://farm.openzim.org/pipeline/020ccb7605803f00747fc216/debug logs the following warning:

Unable to retrieve js/css dependencies for article 'GSTC1 test page': permissiondenied

Warnings are not errors so I'm not sure if this is actually the problem, but just in case I temporarily deleted the problematic page (the only one of its kind with weird permissions). Can I ask for a re-run of the script to see if it goes through now? Thanks!

**Comment by kelson42** [comment]
@Sophivorus I have open a ticket at https://github.com/openzim/mwoffliner/issues/1534 related to this. No clue why MWoffliner still tries to scrape this deleted article.
