### ISSUE TITLE
New ZIM request: Computer History Wiki

### ISSUE THREAD

**Issue by sunsh1newarrior** [openzim/zim-requests#374]
- Website URL: https://gunkies.org/wiki
- License: GNU-FDL
- Desired ZIM Title: Computer History Wiki
- Desired ZIM Description: A knowledge base about historic computers.
- Desired ZIM Icon –png (URL or attach one): https://gunkies.org/w/icon.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/gunkies
Let's see how that pans out.

**Comment by Popolechien** [comment]
`Request failed with status code 404`

@kelson42 if the website does, in fact, exist and does not return a 404 when visiting, do you know what the reason for this could be ?
