### ISSUE TITLE
New ZIM request: Wookieepedia

### ISSUE THREAD

**Issue by Booyahhayoob** [openzim/zim-requests#375]
- Website URL: https://starwars.fandom.com/wiki/Main_Page
- License: **CC-BY-SA**
- Desired ZIM Title: **Wookieepedia**
- Desired ZIM Description: **Wookieepedia is a wiki-based online encyclopedia that contains detailed information about the Star Wars universe, including movies, books, video games, characters, locations, technology, weapons, vehicles, and everything in between.**
- Desired ZIM Icon –png (URL or attach one): https://static.wikia.nocookie.net/starwars/images/e/e6/Site-logo.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/wookieepedia/
Let's check back in a couple of hours, but as with #376 I think this may have to wait until some issues are fixed.

**Comment by Booyahhayoob** [comment]
Yeah, it looks like it got about a third of the way before crapping out.
