### ISSUE TITLE
New ZIM request: The Infosphere

### ISSUE THREAD

**Issue by Booyahhayoob** [openzim/zim-requests#376]
- Website URL: https://theinfosphere.org/Main_Page
- License: **CC-by-sa**
- Desired ZIM Title: **The Infosphere**
- Desired ZIM Description: **The Futurama memory bank that anyone can edit**
- Desired ZIM Icon –png (URL or attach one): http://theinfosphere.org/skins/common/images/infosphere.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/the_infosphere 
I don't think it'll work as MWoffliner is being antsy these days, but once it's fixed it'll be there.

**Comment by Rexadev** [comment]
Edit description: Futurama animated TV series WiKi
@Popolechien
