### ISSUE TITLE
Standard Ebooks

### ISSUE THREAD

**Issue by vivadavid** [openzim/zim-requests#378]
Hi!

- Website URL: https://standardebooks.org/
- License: Public domain.
- Desired ZIM Title: Standard Ebooks.
- Desired ZIM Description: Free & Liberated Ebooks.
- Desired ZIM Icon –png (URL or attach one):
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: no.

This is the generated ZIM file: https://youzim.it/c2a682224c210fffd9185516

Unfortunately, the information doesn't seem to be accessible (typing space doesn't do anything). The closest thing to this type of content should be Project Gutenberg, as it's a collection of ebooks in different formats.

![Kiwix Standard Ebooks](https://user-images.githubusercontent.com/9334287/135594082-25b8cfb2-aa90-4061-9858-8dc32f18275d.png)

**Comment by Popolechien** [comment]
@vivadavid Zim files that have been generated via zimit can not (yet) be browsed with Kiwix-JS or Kiwix-desktop as the technology requires service workers.

Android is fine though, at least in theory: I downloaded the 386.2 MB zim file and can't go further than the first page (it also picked none of the design layout). I suspect this is an edge case of zimit simply not being able to scrape, though I did not see anything funky that should/could have made it fail :-(

**Comment by vivadavid** [comment]
Hi, @Popolechien! Thank you for having a look at it anyway!

**Comment by eshellman** [comment]
I know the guy who runs the site if there's anything you need him to do.

**Comment by Popolechien** [comment]
@eshellman Thanks but the issue is more scraper-side.
