### ISSUE TITLE
Remove zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#379]
https://covid19relay.org/ has been deprecated but we kept on serving zim files that are corrupted and should be removed:
https://download.kiwix.org/zim/other/covid19relay_en_all_nopic_2020-08.zim
https://download.kiwix.org/zim/other/covid19relay_en_all_nopic_2020-09.zim
https://download.kiwix.org/zim/other/covid19relay_en_all_maxi_2020-08.zim
https://download.kiwix.org/zim/other/covid19relay_en_all_maxi_2020-09.zim

**Comment by kelson42** [comment]
Do we have an older version we would like to keep? We should identify why mwoffliner does not stop if the web site is not reachable.
