### ISSUE TITLE
Investigate replacing Wikipedia _mini_ with summarized content

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#380]
We could use this summarizer here https://github.com/claudelkros/WATS-SMS-Model.git who according to [this paper](https://www.mdpi.com/1999-5903/13/9/238/htm) performs better than purely extractive methods.

**Comment by kelson42** [comment]
This seems to work only in French... which sounds like a blocker to me.

**Comment by Popolechien** [comment]
Author [confirmed](https://twitter.com/lfendji/status/1445838413102555138) it was geared towards French :-/
