### ISSUE TITLE
https://glossaries.translatorswb.org/bangladesh/

### ISSUE THREAD

**Issue by barbayellow** [openzim/zim-requests#385]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://glossaries.translatorswb.org/bangladesh/
- License: CC by NC SA. Also, we have an agreement with TWB for the free use of this 'application
- Desired ZIM Title: **TWB Bangladesh Glossary**
- Desired ZIM Description: **Translators Without Borders Glossary includes translations for vocabulary in Rohingya, Chittagonian, Bangla, Burmese and English**
- Desired ZIM Icon –png (URL or attach one): https://glossaries.translatorswb.org/bangladesh/
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
Tested with zimit https://youzim.it/a3f8829c513cc27bf3669616 and got a 1Mb file that Kiwix would not even recognize :-/
