### ISSUE TITLE
Receipt for le Dico des Ados isn't working anymore 

### ISSUE THREAD

**Issue by DSwissK** [openzim/zim-requests#388]
Hello,

https://farm.openzim.org/pipeline/6eaa130510654d364ee45616 isn't working anymore. I guess it's because we are preparing for multilingual. Therefore the URL isn't dicoado.org anymore but fr.dicoado.org for the French version. 

Also it should be noted that visual editor is now usable (we use it to edit part of the form) and I remember in the the last issue we had that it might be something useful for you.

Thank you for your time.

**Comment by RavanJAltaie** [comment]
@Popolechien is this closed for now?
