### ISSUE TITLE
Meta section on zh.wikipedia

### ISSUE THREAD

**Issue by ssj10ssj** [openzim/zim-requests#392]
- Website URL: https://zh.m.wikipedia.org/wiki/Wikipedia:RD
- License: CC-by-sa | GFDL
- Desired ZIM Title: 维基百科知识问答
- Desired ZIM Description:
- Desired ZIM Icon –png (URL or attach one):
- Language (ISO 639-3): zh
- Desired Main Page (homepage, if different from website URL): n/a
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
We don't generally scrape meta on Wikipedia, unless there's a use case being explained for it. I'll close the ticket for now but feel free to explain the purpose of your request.
