### ISSUE TITLE
thwiki.cc

### ISSUE THREAD

**Issue by ssj10ssj** [openzim/zim-requests#393]
- Website URL: https://thwiki.cc/
- License: CC-by-nc-sa
- Desired ZIM Title: THBWiki
- Desired ZIM Description: 以专业性为目标的东方Project维基百科
- Desired ZIM Icon –png (URL or attach one): https://thwiki.cc/banner/banner_r0.png
- Language (ISO 639-3): zh
- Desired Main Page (homepage, if different from website URL): n/a
- Is this a MediaWiki?: yes

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/thbwiki

**Comment by ssj10ssj** [comment]
false

**Comment by Popolechien** [comment]
Restarted https://farm.openzim.org/recipes/thbwiki_zh_all

**Comment by Popolechien** [comment]
Run failed https://farm.openzim.org/pipeline/d35e8cf5-718e-4021-89ce-408b439aab14/debug

**Comment by benoit74** [comment]
Website is protected by a very offensive WAF. No chance we can proceed ATM.
