### ISSUE TITLE
Issues with ALL Chinese zim files from Wiki* sites

### ISSUE THREAD

**Issue by kiyospace** [openzim/zim-requests#396]
Hi there, I am neither sure whether this is the proper place for this question/request, nor sure whether this has been mentioned before, but currently the Simplified-Chinese-and-Traditional-Chinese-mixing issue seems happening in all zim files from Wiki* sites (Wikipedia, Wikibooks... etc)

The situation (with some of my assumptions) is for Chinese version of Wikipedia, there are editors are from Mainland China, as well as Hong Kong, Taiwan, Singapore, Malaysia, etc. Some editors use **Simplified Chinese** (`zh-hans` (OR `zh-cn`, `zh-sg`, `zh-my`)) and some use **Traditional Chinese** (`zh-hant` (OR `zh-tw`, `zh-hk`, `zh-mo`)), which leads to the mix of both writing in the sources of almost all Chinese Wikipedia articles/pages. And the same situation happens to Wikibooks, etc.

The differences between Simplified Chinese and Traditional Chinese not only include the individual characters' structure, but also include the way of using certain terms (esp. for some academic and technology terms). So the mixing of both writing in one article/page kinda like mixing Italian and Spanish in one article/page...

Wikipedia (as well as Wikibooks) has provided good transformation to solve this problem (not only replacing differently written characters, but also adapting different words for the same term), so for users you can switch among the locale variants in the same page, like

**_For the same Wikipedia page_**
- Source contents without transformation (mixed): https://zh.wikipedia.org/zh/%E6%97%A5%E6%9C%AC
- Transformed to Simplified Chinese: https://zh.wikipedia.org/zh-cn/%E6%97%A5%E6%9C%AC
- Transformed to Traditional Chinese: https://zh.wikipedia.org/zh-tw/%E6%97%A5%E6%9C%AC

**_For the same Wikibooks page_**
- Source contents without transformation (mixed): https://zh.wikibooks.org/zh/Wikibooks:%E5%85%B3%E4%BA%8E
- Transformed to Simplified Chinese: https://zh.wikibooks.org/w/index.php?title=Wikibooks%3A%E5%85%B3%E4%BA%8E&variant=zh-hans
- Transformed to Traditional Chinese: https://zh.wikibooks.org/w/index.php?title=Wikibooks%3A%E5%85%B3%E4%BA%8E&variant=zh-hant

So I am not sure whether for the next update of Chinese zim files, it would be possible to generate either one "unified-writing" version (either Simplified Chinese or Traditional Chinese is OK) to just make the pages more "cleared" instead of like reading the mixture of Italian and Spanish

e.g. to just generate the zim file from  https://zh.wikipedia.org/zh-cn/*** OR https://zh.wikipedia.org/zh-tw/***

Thanks very much!

**Comment by Popolechien** [comment]
Hello @kiyospace - yes this is a known (and old, annoying) issue, see this comment in [#940](https://github.com/openzim/mwoffliner/issues/840#issuecomment-631453395). We do not have a fix yet.
