### ISSUE TITLE
Link feature for the same Wikipedia term among languages

### ISSUE THREAD

**Issue by kiyospace** [openzim/zim-requests#397]
Hi there, is there a way to realize the link feature for the same term among different languages in the Wikipedia zim data like how it is working on Wikipedia?

One of the very good feature of Wikipedia for me (and I guess for a lot of bi-/tri-/multi-lingual speakers) is that I can quickly and easily find out the very precise translation of certain term in language B by inputting its word in language A, by simply clicking "language B" link at the left-nav-panel in its language A page. This is much more than a simple dictionary, as Wikipedia comes with (detailed) explanation for the terms in all languages when available (this is very important for distinguishing esp. scientific/tech terms with close meanings), and also you can get different stories and opinions for the same term in different languages, especially for terms related to society/politics/history issues, etc. Also this is helpful when the term's contents in language A are not detailed enough you can check it in language B (if available). Thanks!

**Comment by RavanJAltaie** [comment]
@kelson42

**Comment by Popolechien** [comment]
I think this is an mwoffliner limitation that prevents this (managing interwikis). Sorry.
