### ISSUE TITLE
New ZIM request: 

### ISSUE THREAD

**Issue by EMN308** [openzim/zim-requests#399]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://gadial.net/
- License: **CC-by-sa**
- Desired ZIM Title: **gadial**
- Desired ZIM Description: **Mathematics Blog in Hebrew**
- Desired ZIM Icon –png (URL or attach one): https://gadial.net/favicon.ico
- Language (ISO 639-3): **heb**
- Desired Main Page (homepage, if different from website URL): **[n]**
- Is this a MediaWiki?: *no**

**Comment by Popolechien** [comment]
@EMN308 I read  כל הזכויות שמורות לגדי אלכסנדרוביץ'©
Not very CC-by-SA. Can you point me to where alternative licensing would be mentioned?

Feel free to message the author and point him here (I'll close the ticket until then).
