### ISSUE TITLE
New ZIM request: OpenSynth wiki

### ISSUE THREAD

**Issue by oxygen-dioxide** [openzim/zim-requests#403]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://opensynth.miraheze.org
- License: **CC-by-sa**
- Desired ZIM Title: **OpenSynthWiki**
- Desired ZIM Description: **自制歌声合成引擎wiki**
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **zh**
- Desired Main Page (homepage, if different from website URL): **https://opensynth.miraheze.org/wiki/%E9%A6%96%E9%A1%B5**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/opensynth-wiki

this should not work as MWoffliner is still pending rework, but once it is fixed then the recipe will be ready to run.
