### ISSUE TITLE
New ZIM request: C++ Reference

### ISSUE THREAD

**Issue by pan-sveta** [openzim/zim-requests#405]
Hello team,

I would like to ask for a zim of a C++ reference guide. I think it is permanent enough and might be helpful not only for me.

- Website URL: https://en.cppreference.com
- License: CC-BY-SA
- Desired ZIM Title: C and C++ reference
- Desired ZIM Description: Whole C and C++ reference
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
I have created https://farm.openzim.org/recipes/cppreference_en 
The job failed but in a way that was expected (it does this on a lot of non-wikimedia Wikis) and will hopefully be fixed next year if/when we can revamp mwoffliner. In the meantime the recipe is here, so there is that.

**Comment by kelson42** [comment]
@Popolechien @pan-sveta I have fixed the recipe which was incorrect, but the problem with this Web site is that their Mediawiki is really old and not supported anymore by MWoffliner.

**Comment by ford-jones** [comment]
Hiya! Is there anything happening with this? I would love to browse cppreference locally. 
I can see this has been marked as closed, but the last job listed on [zimfarm](https://farm.openzim.org/recipes/cppreference_en) failed two years ago. What would be required to reopen and progress this ticket forward? 

Happy to help however I can!

**Comment by Popolechien** [comment]
Thanks for the ping. I see they've updated their Mediawiki instance. I have restarted the recipe, let us see what happens.

**Comment by Popolechien** [comment]
Ah well [it failed](https://farm.openzim.org/pipeline/d73c8bd9-b0b5-43a4-8ca9-95265b575ab8/debug). We'll look into it a bit more to see if the recipe can be fixed or if the issue is still upstream.

**Comment by benoit74** [comment]
I've fixed recipe configuration and requested again (paths were wrong)

**Comment by Popolechien** [comment]
Failed again as to many files failed to download apparently (https://farm.openzim.org/pipeline/7e22c4c0-e8fe-4ddb-a1e6-0c835f32df45/debug)

**Comment by benoit74** [comment]
Yes, yet another occurrence of https://github.com/openzim/mwoffliner/issues/2679
