### ISSUE TITLE
Changes to mdwiki zim creation parameters

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-requests#407]
Please make the following changes to the mdwiki recipe:

--articleList="http://offline.mdwiki.org/nonwiki/lists/mdwikimed.tsv"
--customMainPage="App/IntroPage"
--customZimTitle="MDWiki Medical Encyclopedia" 
--customZimDescription="MDWiki is a collection of healthcare content curated by WikiProjectMed including material from Wikipedia specifically for offline use."
--filenamePrefix="mdwiki_en_all"
--mwUrl="http://offline.mdwiki.org/"
--speed="1"

If possible can you please give this a try. I have successfully run video and novid versions of this resulting in 

1666496317 Jan 10 23:16 mdwiki_en_all_maxi_2022-01.zim
8706199816 Jan 11 01:54 mdwiki_en_all_2022-01.zim

**Comment by kelson42** [comment]
We should have a shorter description, a few words, a motto.

**Comment by Popolechien** [comment]
Made the changes, would suggest `MDWiki is a collection of healthcare content for offline use.`

@tim-moody ok?

**Comment by tim-moody** [comment]
MDWiki is a collection of healthcare content curated by WikiProjectMed.

**Comment by Popolechien** [comment]
Done. Task [#8bbd0](https://farm.openzim.org/pipeline/8bbd0554f580d6f87b08dd16) requested.
