### ISSUE TITLE
mdwiki formats and other params

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-requests#409]
I forgot to include

`--format="novid:maxi" --format=""
`

Please confirm the syntax. We would like both a video and a non-video version. The video version was produced.

Also the home page in https://farm.openzim.org/recipes/mdwiki/config is WikiProjectMed:App/IntroPage. It should be just

` -customMainPage="App/IntroPage"
`

Can Creator be WikiProjectMed instead of offline?

**Comment by kelson42** [comment]
Syntax is OK. I have already fixed the problem yesterday.
