### ISSUE TITLE
Configuration change request: wikihow_en_endless_personal-care-and-style

### ISSUE THREAD

**Issue by dylanmccall** [openzim/zim-requests#412]
For the existing [`wikihow_en_endless_personal-care-and-style`](https://farm.openzim.org/recipes/wikihow_en_endless_personal-care-and-style/config) recipe, the zim-file property is incorrectly set to `"wikihow_en_endless_sports-and-fitness_{period}.zim"`. That is the same as a different recipe, so the two end up writing to the smae place.

We should change this property to `"wikihow_en_endless_personal-care-and-style_{period}.zim"`.

**Comment by kelson42** [comment]
Fixed and scrape relaunched
