### ISSUE TITLE
Please enable skip-relateds for WikiHow + Endless zim files

### ISSUE THREAD

**Issue by dylanmccall** [openzim/zim-requests#415]
For the WikiHow + Endless zim files, we are finding that many articles are unexpectedly included as a result of being in the "related articles" sections for other articles, even though they aren't in any of the category listing pages. (I even made a fun little tool to explore that problem: https://github.com/dylanmccall/zim-explorer).

To solve this, we would like to change the following recipes so that the wikihow scraper is run with its [`--skip-relateds`](https://github.com/openzim/wikihow/blob/main/wikihow2zim/entrypoint.py#L183-L189) option.

 * [wikihow_en_endless_arts-and-entertainment](https://farm.openzim.org/recipes/wikihow_en_endless_arts-and-entertainment/config)
 * [wikihow_en_endless_hobbies-and-crafts](https://farm.openzim.org/recipes/wikihow_en_endless_hobbies-and-crafts/config)
 * [wikihow_en_endless_cars-and-other-vehicles](https://farm.openzim.org/recipes/wikihow_en_endless_cars-and-other-vehicles/config)
 * [wikihow_en_endless_holidays-and-traditions](https://farm.openzim.org/recipes/wikihow_en_endless_holidays-and-traditions/config)
 * [wikihow_en_endless_work-world](https://farm.openzim.org/recipes/wikihow_en_endless_work-world/config)
 * [wikihow_en_endless_computers-and-electronics](https://farm.openzim.org/recipes/wikihow_en_endless_computers-and-electronics/config)
 * [wikihow_en_endless_food-and-entertaining](https://farm.openzim.org/recipes/wikihow_en_endless_food-and-entertaining/config)
 * [wikihow_en_endless_home-and-garden](https://farm.openzim.org/recipes/wikihow_en_endless_home-and-garden/config)
 * [wikihow_en_endless_youth](https://farm.openzim.org/recipes/wikihow_en_endless_youth/config)
 * [wikihow_en_endless_education-and-communications](https://farm.openzim.org/recipes/wikihow_en_endless_education-and-communications/config)
 * [wikihow_en_endless_personal-care-and-style](https://farm.openzim.org/recipes/wikihow_en_endless_personal-care-and-style/config)
 * [wikihow_en_endless_sports-and-fitness](https://farm.openzim.org/recipes/wikihow_en_endless_sports-and-fitness/config)

**Comment by kelson42** [comment]
Sounds prinary like a bug in the scraper, ahoukd be IMO reported as such as well. But nice if there is a workaround for the meantime.

**Comment by kelson42** [comment]
@rgaudin Any comment on this?

**Comment by rgaudin** [comment]
Not a bug. WH do include a (actually 2) block of related articles to each article. At the bottom and in the sidebar.
It's an important browsing feature so it is kept in the ZIM.

Because those can be from anywhere in the website and can introduce a long list of additional articles (it's recursive), we have a dedicated --skip-related param that prevent the scraper from including them.

**Comment by rgaudin** [comment]
Done
