### ISSUE TITLE
New ZIM request: https://www.banrepcultural.org/

### ISSUE THREAD

**Issue by aquilu** [openzim/zim-requests#416]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.banrepcultural.org/
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **Red Cultural del Banco de la República**
- Desired ZIM Description: **Red de Bibliotecas y Portal Cultural del Banco de la República**
- Desired ZIM Icon –png (URL or attach one): https://www.banrepcultural.org/favicon.ico
- Language (ISO 639-3): **esp**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no** some site into

**Comment by Popolechien** [comment]
© 2021 Banco de la República, Colombia. Todos los derechos reservados. ->not freely licensed content, sorry.

On a side note, this seems like a generic portal, if you are interested in the book database itself I'm not sure we could capture it without working on a dedicated scraper.

**Comment by aquilu** [comment]
> © 2021 Banco de la República, Colombia. Todos los derechos reservados. ->not freely licensed content, sorry.
> 
> On a side note, this seems like a generic portal, if you are interested in the book database itself I'm not sure we could capture it without working on a dedicated scraper.

It is not just any page. It is a portal of Colombian Cultural Heritage. It contains museums, libraries nationwide in Colombia. The internet penetration rate is very low in Colombia, a large population would benefit from having this page on sites without internet.
