### ISSUE TITLE
Create Russian Wikimed subset

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#419]
Russian is a fairly large Wiki so there should be enough material to start with.

**Comment by kelson42** [comment]
@Popolechien We need first the welcome (pages)

**Comment by Popolechien** [comment]
@kelson42 Can't we use the default pagination like for the basketball, history, etc. subsets?

**Comment by kelson42** [comment]
yes

**Comment by kelson42** [comment]
@Popolechien You can make a recipe based on https://download.openzim.org/wp1/ruwiki/customs/medicine.tsv
