### ISSUE TITLE
Betmidrash.org.il

### ISSUE THREAD

**Issue by zevisvei** [openzim/zim-requests#421]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.betmidrash.org.il/
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **ויקיסוגיה*
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **HE**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **YES**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/*%D7%95%D7%99%D7%A7%D7%99%D7%A1%D7%95%D7%92%D7%99%D7%94

**Comment by zevisvei** [comment]
"after the mediawiki mwoffliner be updated "
And when will it happen?

**Comment by Popolechien** [comment]
@zevisvei So there's a new dev contractor that started working on minor fixes this week, if all works out then we'll get going and the revamp will take place over the next few months (Q1-2/2023)
Then when it works, the recipe has been created already so it'll just pop out the zim files.
