### ISSUE TITLE
betmidrash

### ISSUE THREAD

**Issue by ShiraCM** [openzim/zim-requests#422]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.betmidrash.org.il
- License: **CC-by-sa** 
- Desired ZIM Title: **ויקיסוגיה**
- Desired ZIM Description: **יצירת תורנית שיתופית**
- Desired ZIM Icon –https://upload.wikimedia.org/wikipedia/he/e/ee/WikiSugia.png
- Language (ISO 8859-8): **heb**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/%D7%95%D7%99%D7%A7%D7%99%D7%A1%D7%95%D7%92%D7%99%D7%94
