### ISSUE TITLE
wiki.jewishbooks.org.il/mediawiki/wiki/

### ISSUE THREAD

**Issue by ShiraCM** [openzim/zim-requests#423]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://wiki.jewishbooks.org.il/mediawiki/wiki/
- License: **CC-by-sa** 
- Desired ZIM Title: **אוצר הספרים היהודי השיתופי**
- Desired ZIM Description: **ספרי קודש בפורמט ויקי**
- Desired ZIM Icon –https://upload.wikimedia.org/wikipedia/commons/9/9c/JewishBook-logo-clear.png
- Language (ISO 8859-8): **heb**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes **

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/%D7%90%D7%95%D7%A6%D7%A8%20%D7%94%D7%A1%D7%A4%D7%A8%D7%99%D7%9D%20%D7%94%D7%99%D7%94%D7%95%D7%93%D7%99%20%D7%94%D7%A9%D7%99%D7%AA%D7%95%D7%A4%D7%99
