### ISSUE TITLE
iFixit 

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#425]
- Website URL: **https://www.ifixit.com/**
- License: **CC-by-sa** 
- Desired ZIM Title: **iFixit**
- Desired ZIM Description: **Repair guides for every thing, written by everyone.**a
- Desired ZIM Icon –png (URL or attach one): **cf. attachment**
- Language (ISO 639-3): **eng** to start, with fallback to other languages, then probably fr, de, ...
- Is this a MediaWiki?: **no**

**Comment by benoit74** [comment]
Source code (work in progress): https://gitlab.com/benoit74/ifixit2zim/

**Comment by benoit74** [comment]
@kelson42 I'm definitely open to host this under the openZIM org umbrella. Feel free to fork the git repo I mentioned above under your org, and just give my user some rights on it ^^ (at least Write I would say, preferably Maintain).

I started this scraper by looking at the gutemberg2zim repo, and I'm using the same kind of libraries for easier maintenance. Is it the right project to mimic ? Do you have any other hint about tools I should have a look after ?

**Comment by benoit74** [comment]
Btw, I'm not sure it's easy to fork a gitlab repo to a github one ; you could as well just create an empty repo and I will take care of the migration

**Comment by rgaudin** [comment]
@benoit74 I've created opezim/ifixit repository and gave you maintain access to it.

**Comment by rgaudin** [comment]
gutenberg scraper is from a very long time ago and it's considered *unmaintainable* at this point. There a list of our scrapers at [openzim/overview](https://github.com/openzim/overview/wiki/Scrapers-list) that I suggest you look at.

Every scraper is kinda unique but you'll notice we have a consistent structure accross all *recent* scrapers. Things you should consider:
- use [zimscraperlib](https://github.com/openzim/python-scraperlib)
- use it's `zim` module to instantiate a ZIM Creator and add your content to it.
- don't store your content to filesystem and then build the ZIM: as you fetch it, just add it to the ZIM.
- optimize images: that's a later-step optimization but you'll see it in scrapers
- publish on PyPi (we'll had the credentials to the `kiwix` account on the repo once we're at this stage)
- make it docker-friendly. We run all scrapers monthly on our [Zimfarm](https://farm.openzim.org) and it uses docker
- use exit codes properly: if something's wrong and we don't end up building the ZIM, we want a non-zero return code so the farm categorizes the task accordingly
- print logs on stdout/stderr so docker can report it to the farm and we can track what's happening.

I think that's mostly it. Open tickets on the repo and join us on Slack. I'll be happy to give you a hand and answer your questions.

[openZIM-workflow](https://github.com/openzim/overview/wiki/openZIM-workflow) might be a good read as well

**Comment by benoit74** [comment]
Code is now hosted under openzim umbrella: https://github.com/openzim/ifixit/
It has been released on Docker Hub + PyPi with regular tooling.
First version is running on the ZimFarm: https://farm.openzim.org/recipes?name=ifixit
@kelson42 @rgaudin I would suggest to close this issue, ok for you?

**Comment by rgaudin** [comment]
yes ; congratulations 🎉
