### ISSUE TITLE
New ZIM request: Penser Critique [BSF]

### ISSUE THREAD

**Issue by JulienMoraliBSF** [openzim/zim-requests#427]
- Website URL: https://www.penser-critique.be/
- License: **CC** 
- Desired ZIM Title: **Penser critique**
- Desired ZIM Description: **Ce site offre une sélection de ressources destinées à servir les membres du monde éducatif désireux d’aider les jeunes à aiguiser leur esprit critique et se protéger de la désinformation. La curation de contenu s’adresse a priori aux enseignants, animateurs en maison de jeunes, etc., tout en restant suffisamment généraliste pour être ouverte à tous. L’objectif du site est de présenter ces ressources classées par thématique de façon à ce que d’une part la communauté éducative (mais pas que) puisse y trouver des sources d’inspiration pour des activités pédagogiques et, d’autre part, que les étudiants puissent y trouver des ressources pour leurs travaux. Sans oublier les citoyens lambda qui ont simplement envie de développer leurs compétences en auto-défense intellectuelle.**
- Desired ZIM Icon –png (URL or attach one): https://www.penser-critique.be
- Language (ISO 639-3): **fra**
- Desired Main Page (homepage, if different from website URL): **[n/a](https://www.penser-critique.be/trouver-une-ressource/)**
- Is this a MediaWiki?: **yes | no**

**Comment by Popolechien** [comment]
Licence: CC-by-NC https://www.penser-critique.be/droits-dauteur/
This being said, a lot of resources are hosted on external sites and would fail to be retrieve (besides not really belonging to Penser Critique). The site owner deprecated the site in 2021 and while it does have value as archive the lack of maintenance on external content kind of defeats the purpose.
