### ISSUE TITLE
Delete Wikisummaries zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#429]
Scraping went wrong and content is missing

* https://download.kiwix.org/zim/other/wikisummaries_en_all_maxi_2021-03.zim
* https://download.kiwix.org/zim/other/wikisummaries_en_all_maxi_2021-04.zim
* https://download.kiwix.org/zim/other/wikisummaries_en_all_nopic_2021-03.zim
* https://download.kiwix.org/zim/other/wikisummaries_en_all_nopic_2021-04.zim

**Comment by benoit74** [comment]
ZIM are still there and not getting updated, I will remove them.

**Comment by benoit74** [comment]
Marked for deletion

**Comment by benoit74** [comment]
Files deleted
