### ISSUE TITLE
Update Stackexchange ZIMs?

### ISSUE THREAD

**Issue by garywhite208** [openzim/zim-requests#430]
This isn't really a request as much as it is a question, I just wanted to find out if there's any plan to update the Stack Exchange ZIMs sometime soon? Most of them are about a year old, but some go back as far as 18 months. I know it's a huge hassle to update them, but it'd be great to get the new information available.

**Comment by Popolechien** [comment]
So there is a new SE scraper that has been in the works for some time now. Not sure about the release schedule but _soonish_ (i.e., before Summer) seems a reasonable expectation. @rgaudin would know more.

**Comment by kelson42** [comment]
We should indeed start to use new scraper to make new SE ZIM files.

**Comment by Jaifroid** [comment]
It looks like these ZIMs are now updating (bar occasional failures), and this issue could be closed.

**Comment by kelson42** [comment]
Indeed!
