### ISSUE TITLE
wikipedia_ru_astronomy_maxi

### ISSUE THREAD

**Issue by DmitriyAvdeev** [openzim/zim-requests#437]
Please  make  wikipedia_ru_astronomy_maxi.zim   or make howto

- Website URL: https://ru.wikipedia.org
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **Ru Wikipedia Astro**
- Desired ZIM Description: **Astropedia**
- Desired ZIM Icon –png (URL or attach one): https://ru.wikipedia.org/static/favicon/wikipedia.ico
- Language (ISO 639-3): **rus**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by DmitriyAvdeev** [comment]
> Agree on the principle, actually we have one in English

How to make a zim-file with astronomy content from  Wikipedia? Mfoffliner +option?

**Comment by RavanJAltaie** [comment]
The links for the website is for a general Ru Wikipedia which it has a zim file already
if you have another specific astronomy wiki website, please re open a new request.
