### ISSUE TITLE
wiki.jewishbooks.org.il

### ISSUE THREAD

**Issue by EEEWWWEEE** [openzim/zim-requests#439]
- Website URL: https://wiki.jewishbooks.org.il/
- License: CC-by-nc-sa
- Desired ZIM Title: אוצר הספרים היהודי השיתופי
- Desired ZIM Description: ספרי קודש
- Desired ZIM Icon –png (URL or attach one): https://wiki.jewishbooks.org.il/mediawiki/images/8/80/JewishBook-logo-%D7%A9%D7%A7%D7%95%D7%A3.png
- Language (ISO 639-3): heb
- Desired Main Page (homepage, if different from website URL): https://wiki.jewishbooks.org.il/mediawiki/wiki/%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99
- Is this a MediaWiki?: yes

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/%D7%90%D7%95%D7%A6%D7%A8%20%D7%94%D7%A1%D7%A4%D7%A8%D7%99%D7%9D%20%D7%94%D7%99%D7%94%D7%95%D7%93%D7%99%20%D7%94%D7%A9%D7%99%D7%AA%D7%95%D7%A4%D7%99
