### ISSUE TITLE
Wikipedia for schools in Arabic

### ISSUE THREAD

**Issue by SolarSPELL-Main** [openzim/zim-requests#444]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: [https://ar.wikipedia.org/wiki/ويكيبيديا:ويكيبيديا_للمدارس/مرحبا](https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7_%D9%84%D9%84%D9%85%D8%AF%D8%A7%D8%B1%D8%B3/%D9%85%D8%B1%D8%AD%D8%A8%D8%A7)
- License: CC-by-sa 
- Desired ZIM Title: Wikipedia for Schools - Arabic
- Desired ZIM Description: Wikipedia for Schools (WfS), is a curated selection of Wikipedia articles targeted for use in offline primary and secondary classrooms. It has been curated to be an educational resource that promotes information literacy, digital, and research skills in remote, rural, offline communities globally. This version of Wikipedia for Schools contains articles in Arabic and was curated by SolarSPELL, an educational initiative at Arizona State University.
- Desired ZIM Icon –png (URL or attach one): 
![wikipedia-ar](https://user-images.githubusercontent.com/57197808/167954597-ab56e5ad-3c3d-4133-8e59-9d767016390e.png)

- Language (ISO 639-3): **arabic**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**
[Final_Arabic_Wikipedia_for_Schools_(Kiwix_Format)_v01 - Final_Arabic_WfS_v01.csv](https://github.com/openzim/zim-requests/files/8673672/Final_Arabic_Wikipedia_for_Schools_.Kiwix_Format._v01.-.Final_Arabic_WfS_v01.csv)

The attached file contains all of the Arabic WFS articles to include, including landing page and categories.

**Comment by Popolechien** [comment]
@SolarSPELL-Main Can you please provide the title and description in Arabic?

**Comment by kelson42** [comment]
@Popolechien List to be used in Zimfarm recipe is available at https://raw.githubusercontent.com/openzim/wp1_selection_tools/master/customs/solarspell/wikipedia-for-schools_ar.tsv

**Comment by admiral12** [comment]
Hello all, 

**For the title:** 
ويكيبيديا للمدارس - العربية

**As for the Arabic description**>> the comment section in GitHub doesn't support (from-right-to-left) writing format so when pasting the Arabic description here, it will be shown in the wrong format. Please go to this Google Doc and copy the correct description for it. 
[https://docs.google.com/document/d/19CVWytSa50q4pv97lIDXm3N9TIJjfXWJdzdkhOtlyOI/edit?usp=sharing](url)

Let me know if you need anything else. 
Rashad

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/wikipedia_for_schools_ar - Let's see what happens.
