### ISSUE TITLE
New ZIM request: roguebasin.com

### ISSUE THREAD

**Issue by Des-Nerger** [openzim/zim-requests#445]
- Website URL: http://roguebasin.com/index.php/Main_Page
- License: CC-by-sa | GFDL
- Desired ZIM Title: RogueBasin
- Desired ZIM Description: The Roguelike information resource that you can edit.
- Desired ZIM Icon –png: ![RogueBasin_logo](https://user-images.githubusercontent.com/7359990/168621115-a704d12c-5497-48f0-97e4-4fd24896ba9e.png)
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): n/a
- Is this a MediaWiki?: yes

**Comment by Des-Nerger** [comment]
In the meanwhile, is it trivial to determine parameters to the mwoffliner utility to grab this kind of wiki? @Popolechien, could you please help me to come up with those?

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/roguebasin

Not sure about the parameters for this as I suspect that MWoffliner can handle it. We'll see how it goes

**Comment by Popolechien** [comment]
Request failed with status code 404 :-/
Let's park this for the time being, at least now we have the recipe logged.
