### ISSUE TITLE
Update Wikibooks (en) ZIM

### ISSUE THREAD

**Issue by ghost** [openzim/zim-requests#449]
The wikibooks_en_all (specifically [wikibooks_en_all_maxi_2021-03.zim](https://download.kiwix.org/zim/wikibooks/wikibooks_en_all_maxi_2021-03.zim) ) hasn't been updated since 2021-03-04. 

Is it possible for it to be updated here: https://download.kiwix.org/zim/wikibooks/ ?

I tried running mwoffliner myself but couldn't get it to work.

**URL**: https://en.wikibooks.org/
**Name**: WikiBooks

**Comment by Popolechien** [comment]
I've requested the zimfarm to re-run the scraper but it seems to have failed repeatedly over the past six months: https://farm.openzim.org/recipes/wikibooks_en

I've increased memory and RAM, we'll see what gives.

**Comment by RavanJAltaie** [comment]
@rgaudin @Popolechien is that solved or not yet?

**Comment by RavanJAltaie** [comment]
The recipe is failing since 8 months ago, apparently as @rgaudin mentioned, it's a foundation issue.
