### ISSUE TITLE
Premiers pas avec python

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#454]
- Website URL: https://www.youtube.com/watch?v=Nceby1byNrs&list=PLJuLuvqQa2aTJtmmK4VRuK4RR7I0iFuV1
- License: CC-by-sa (currently confirming with UniNE)
- Desired ZIM Title: Premiers pas avec Python
- Desired ZIM Description: Des capsules vidéos à utiliser sans modération pour faire ses premiers pas en python
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **fra**

**Comment by Popolechien** [comment]
Pinged them today again.

**Comment by Popolechien** [comment]
Cleared and good to go via ticket [63788](https://kiwix.freshdesk.com/a/tickets/63788)

**Comment by RavanJAltaie** [comment]
File is ready in the library
https://library.kiwix.org/viewer#premiers_pas_avec_python_fr_2024-02
