### ISSUE TITLE
New ZIM request: 

### ISSUE THREAD

**Issue by jurok04** [openzim/zim-requests#455]
- Website URL: https://lurkmore.rip/
- License: CC BY 3.0
- Desired ZIM Title: lurkmore.to_2022_frozen_RiP
- Desired ZIM Description: Последняя копия почившей в 2022 году энциклопедии современной культуры, фольклора и субкультур 20ХХ годов.
- Desired ZIM Icon –png (URL or attach one): https://lurkmore.rip/images/d/da/Sculpture-drawing.png
- Language (ISO 639-3): rus
- Desired Main Page (homepage, if different from website URL): https://lurkmore.rip/%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0
- Is this a MediaWiki?: yes

**Comment by jurok04** [comment]
Hello to everyone!  
In the past I have tried to request .zim from the main mediawiki site (lurkmore.org), but unfortunately mediawiki was too old for it ( https://github.com/openzim/zim-requests/issues/413   -  Mediawiki version 1.19.24 not supported should be >=1.27 )
Could this mirror site (because main site is down forever) be able to be offlined to zim?
I'm kindly asking someone to check, if it's possible.
Thank you in advance.

**Comment by Popolechien** [comment]
See #413 for the initial request.

**Comment by Popolechien** [comment]
Updated and restarted the recipe. Let's wait and see.

**Comment by Popolechien** [comment]
[Failed again](https://farm.openzim.org/pipeline/d7f0588ead8d37d3bb888b26/debug), though this time at least there is a different error message :-/
I'll park this one until we get a revamp of mwoffliner.
