### ISSUE TITLE
Request: www.wikicorps.org

### ISSUE THREAD

**Issue by nickmalerba** [openzim/zim-requests#456]
Website URL: https://www.wikicorps.org/
License: CC-by-sa (i am also the owner)
Desired ZIM Title: WikiCorps
Desired ZIM Description: The Marine Corps Encyclopedia
Desired ZIM Icon –attached
![F2CC08A3-9DEB-4CFF-8E4B-D9833AF68435](https://user-images.githubusercontent.com/87617150/177156851-19ca3c2b-92c7-40da-bbb0-77e5f84c9ac3.jpeg)

Language (ISO 639-3): eng
Desired Main Page
: n/a
Is this a MediaWiki?: yes

**Comment by nickmalerba** [comment]
Hello @Popolechien i edited it. Thank you for letting me know

**Comment by Popolechien** [comment]
@nickmalerba Thanks. I have created https://farm.openzim.org/recipes/wikicorps_en and started a run... which predicably failed with some sort of docker error. 

We'll need to wait until MWoffliner has been revamped, but the recipe is there at least. Closing for now.
