### ISSUE TITLE
Audiopedia

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#457]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.audiopedia.org/
- License: **CC-by-sa **
- Desired ZIM Title: **Audiopedia**
- Desired ZIM Description: **Fair access to vital knowledge for all**
- Desired ZIM Icon –png (URL or attach one): https://www.audiopedia.org/assets/Audiopedia-Logo.png
- Language (ISO 639-3): multiple languages
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes **

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/audiopedia
