### ISSUE TITLE
New ZIM request: etymonline-online etymology dictionary

### ISSUE THREAD

**Issue by omersc1** [openzim/zim-requests#458]
etymonline-online etymology dictionary
(https://www.etymonline.com)
public domain, made from these sources https://www.etymonline.com/columns/post/sources
comprehensive online etymological dictionary
https://cdn.etymonline.com/web/logo.png
eng
www.etymonline.com
no

**Comment by Popolechien** [comment]
@omersc1 From the [Terms of service](https://www.etymonline.com/legal/terms): "_The Service and its original content, features and functionality are and will remain the exclusive property of Etymonline and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries_."

Are you sure about the public domain part? The list of sources includes quite a few non-public domain resources...
