### ISSUE TITLE
Delete / deprecate cyclowiki_ru_all*

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#459]
Scraper has failed for the past few months already and the currently available zim files (https://library.kiwix.org/cyclowiki_ru_all_maxi_2020-11 and https://library.kiwix.org/cyclowiki_ru_all_nopic_2020-11) only return the first page - all others only have `[object Object]` as text

files to remove:
https://download.kiwix.org/zim/other/cyclowiki_ru_all_maxi_2020-10.zim
https://download.kiwix.org/zim/other/cyclowiki_ru_all_maxi_2020-11.zim
https://download.kiwix.org/zim/other/cyclowiki_ru_all_nopic_2020-10.zim
https://download.kiwix.org/zim/other/cyclowiki_ru_all_nopic_2020-11.zim

**Comment by kelson42** [comment]
yes for disable, no for delete. At éeast not for this sole reason.

**Comment by Popolechien** [comment]
@kelson42 Yes the recipe is only disabled - I'm asking for the zim files to be deleted however, people download them and then complain they are useless.

**Comment by kelson42** [comment]
@rgaudin This is for you
