### ISSUE TITLE
Coding for Tomorrow

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#460]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://coding-for-tomorrow.de/downloads/
- License: **CC-by-sa**
- Desired ZIM Title: **Coding for tomorrow**
- Desired ZIM Description: **Digitale Bildung**
- Desired ZIM Icon –png (URL or attach one): https://coding-for-tomorrow.de/wp-content/uploads/2018/08/klammer-rechts-171x300.png
- Language (ISO 639-3): **deu**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/codingfortomorrow_de_all
Will update the library file once ready

**Comment by RavanJAltaie** [comment]
The file is ready in the library
https://library.kiwix.org/viewer#codingfortomorrow_de_all_2023-11

**Comment by RavanJAltaie** [comment]
File is marked for deletion, I reopened the troubleshooting issue [here](https://github.com/openzim/zimit/issues/215) to investigate more
