### ISSUE TITLE
Remove old files in wrong directory

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#461]
Pursuant to zimit issue [#156](../../zimit/issues/156) the Internet Encyclopedia of Philosophy zim file has been made public again but in the zimit folder.  Hence the following files can / should be deleted:
* https://download.kiwix.org/zim/other/internet-encyclopedia-philosophy_en_all_2021-08.zim
* https://download.kiwix.org/zim/other/internet-encyclopedia-philosophy_en_all_2022-02.zim

As well as the /dev versions no longer needed
* https://download.kiwix.org/zim/.hidden/dev/internet-encyclopedia-philosophy_en_all_2022-06.zim
* https://download.kiwix.org/zim/.hidden/dev/internet-encyclopedia-philosophy_en_all_2022-07.zim

**Comment by rgaudin** [comment]
Done ; thank you. As you know, updates in different subdirectories is causing trouble to the library-update mechanism so it's good to know when it happens 👍
