### ISSUE TITLE
Remove Nomadic Changthang

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#462]
Source website has moved to birdsofladakh.org (or somesuch) and the recipe changed accordingly, which now gives us 
https://library.kiwix.org/birds-of-ladakh_en_all_2022-08

Hence 
https://download.kiwix.org/zim/zimit/nomadic-changthang_en_all_2011-12.zim and
https://download.kiwix.org/zim/zimit/nomadic-changthang_en_all_2022-06.zim

Can now be deleted.

**Comment by rgaudin** [comment]
Why is birds-of-ladakh in `other` ???

**Comment by rgaudin** [comment]
moved birds-of-ladakh ZIM to zimit and removed the other two. Please change recipe.

**Comment by kelson42** [comment]
https://library.kiwix.org/birds-of-ladakh_en_all_2022-08/ displays only an error page, wonder why this is public.

**Comment by rgaudin** [comment]
Fresh browser issue :/
<img width="920" alt="Screen Shot 2022-08-17 at 17 01 20" src="https://user-images.githubusercontent.com/57929/185199445-33c80ad1-bb86-4cdd-a0c4-67d3e2cae229.png">
