### ISSUE TITLE
New ZIM request: namu.wiki

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#466]
- Website URL: https://namu.wiki
- License: **CC BY-NC-SA 2.0**
- Desired ZIM Title: **나무위키**
- Desired ZIM Description: **여러분이 가꾸어 나가는 지식의 나무
나무위키에 오신 것을 환영합니다!**
- Desired ZIM Icon –png (URL or attach one): https://namu.wiki/img/apple_icon.png
- Language (ISO 639-3): **kor**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **No**(?)

https://en.wikipedia.org/wiki/Namuwiki

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4

**Comment by tim78245** [comment]
I don't think it's a mediawiki...

**Comment by RavanJAltaie** [comment]
<img width="788" alt="1" src="https://user-images.githubusercontent.com/116940574/204344565-cb3c7ab4-b9a7-4c1f-96b9-38770a54bdcc.png">
The Wikipedia article about the project says it's a mediawiki
Check the snapshot

**Comment by tim78245** [comment]
> <img alt="1" width="788" src="https://user-images.githubusercontent.com/116940574/204344565-cb3c7ab4-b9a7-4c1f-96b9-38770a54bdcc.png">
> 
> The Wikipedia article about the project says it's a mediawiki Check the snapshot

It does not? I'm reading "powered by the proprietary wiki software The Seed"

It is a wiki, but I believe it is not a mediawiki. If it is a mediawiki I can't find the various API's mwoffliner needs.
