### ISSUE TITLE
New ZIM request: jewishbooks

### ISSUE THREAD

**Issue by zevisvei** [openzim/zim-requests#470]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://wiki.jewishbooks.org.il/mediawiki/
- License: **CC-by-sa | Public domain | ...** (do NOT request  material)
- Desired ZIM Title: **אוצר הספרים היהודי השיתופי**
- Desired ZIM Description: **אוצר ספרי יהדות**
- Desired ZIM Icon –https://he.m.wikipedia.org/wiki/%D7%A7%D7%95%D7%91%D7%A5:JewishBook-logo-clear.png
- Language (ISO 8859): **heb**
- Desired Main Page (https://wiki.jewishbooks.org.il/mediawiki/wiki/%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/%D7%90%D7%95%D7%A6%D7%A8%20%D7%94%D7%A1%D7%A4%D7%A8%D7%99%D7%9D%20%D7%94%D7%99%D7%94%D7%95%D7%93%D7%99%20%D7%94%D7%A9%D7%99%D7%AA%D7%95%D7%A4%D7%99

**Comment by zevisvei** [comment]
Thank you very much, what exactly does this mean? By the way I saw that the same site also appears in [this ](https://github.com/openzim/zim-requests/issues/439)request

**Comment by RavanJAltaie** [comment]
That means we are running an update for mediawiki mwoffliner, once the update is complete, your zim file will be ready and operational
