### ISSUE TITLE
New ZIM request: mainlynorfolk.info

### ISSUE THREAD

**Issue by deedeenelson994** [openzim/zim-requests#471]
- Website URL: https://www.mainlynorfolk.info
- License: **Public domain** (do NOT request copyrighted material)
- Desired ZIM Title: Mainly Norfolk
- Desired ZIM Description: English Folk and Other Good Music
- Desired ZIM Icon –png (URL or attach one): ![mainlynorfolk_xtra1060](https://user-images.githubusercontent.com/112797951/188302279-e8b82742-1d7c-4ce3-9c0d-2c219790f0a6.png)
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): https://www.mainlynorfolk.info/folk/
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
@deedeenelson994 Please put the link where it mentions that the website content is under public domain

**Comment by RavanJAltaie** [comment]
No Clear License Info.
