### ISSUE TITLE
Please create a zim of the tardis wiki

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#472]
Please create a zim of the Tardis wiki would be hours of useful reading for Doctor Who fans.

tardis.wikia.com

From https://sourceforge.net/p/kiwix/feature-requests/1022/

**Comment by RavanJAltaie** [comment]
The website doesn't mention any free license.
@kelson42 Please inform if otherwise.

**Comment by RavanJAltaie** [comment]
Closed for wrong license.
