### ISSUE TITLE
New ZIM request: StrategyWiki

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#475]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://strategywiki.org/wiki/Main_Page
- License: **CC-by-sa** (do NOT request copyrighted material)
- Desired ZIM Title: **StrategyWiki**
- Desired ZIM Description: **a collaborative and freely-licensed wiki for all your video game strategy guide and walkthrough needs!**
- Desired ZIM Icon –png (URL or attach one): https://cdn.wikimg.net/en/strategywiki/favicon.ico
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **Yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/strategywiki
