### ISSUE TITLE
New ZIM request: SourceWatch

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#476]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.sourcewatch.org/index.php?title=SourceWatch
- License: **CC-by-sa**
- Desired ZIM Title: **SourceWatch**
- Desired ZIM Description: **The Center for Media and Democracy publishes SourceWatch to track corporations.**
- Desired ZIM Icon –png (URL or attach one): https://www.sourcewatch.org/resources/assets/wiki.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): https://www.sourcewatch.org/index.php?title=SourceWatch
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
@tim78245 The website is not opening
We get this message: The server is temporarily unable to service your request due to maintenance downtime or capacity problems
Please once it's fixed, place another request

**Comment by tim78245** [comment]
> @tim78245 The website is not opening We get this message: The server is temporarily unable to service your request due to maintenance downtime or capacity problems Please once it's fixed, place another request

I know you said to open another request but every link I posted works on my end, including simply going to sourcewatch.org.

If you still want me to open another request I can, but considering it's been less than 24 hours I think simply reopening the issue would be better.

**Comment by Popolechien** [comment]
Service is back online. Reopening ticket.

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/sourcewatch
