### ISSUE TITLE
New ZIM request: wikirefua

### ISSUE THREAD

**Issue by zevisvei** [openzim/zim-requests#479]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.wikirefua.org.il/
- License: **CC-by-sa | Public domain | ...** (do NOT request  material)
- Desired ZIM Title: **ויקירפואה**
- Desired ZIM Description: **איגוד רופאי המשפחה בישראל**
- Desired ZIM Icon –https://he.wikipedia.org/wiki/%D7%A7%D7%95%D7%91%D7%A5:%D7%95%D7%99%D7%A7%D7%99%D7%A8%D7%A4%D7%95%D7%90%D7%94.jpg
- Language (ISO 8859): **heb**
- Desired Main Page (https://www.wikirefua.org.il/w/index.php?title=%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by tim78245** [comment]
You didn't fill out the License part. It appears to me the Zim project can't use this. The website states:

> כל זכויות היוצרים של התכנים המופיעים באתר הינן של מערכת ויקירפואה. אין לעשות שימוש בכל תוכן המופיע באתר בלא קבלת הסכמה בכתב ומראש ממערכת ויקירפואה ו/או מבעלי הזכויות האחרים פרט לפעילות לימודית כמתואר להלן.
> אנו מתירים את כל השימושים שהותרו בחוק זכויות יוצרים התשס"ח-2007.
> בנוסף לכך, אנו מתירים כל שימוש לצרכים לימודיים, אקדמיים ורפואיים, באקדמיה, בקופות החולים ובמוסדות ציבור, שאינו נועד למטרות מסחריות, הגם שנועד לרווח אישי, ובלבד שלא יהווה אלטרנטיבה לויקירפואה. בכל מקרה של שימוש מותר בחומר, אפשר לפרסם אותו תחת אותו רישיון בדיוק בו הוא מפורסם בויקירפואה בתנאי שמשתמש מציין במפורש כי מקור המאמר הוא בויקירפואה.

Translated by Google:

> All copyrights of the contents appearing on the site belong to the Wikimedicine system. Any content appearing on the website may not be used without prior written consent from the Wikimedicine system and/or the other rights holders, except for educational activities as described below.
> We permit all uses permitted by the 2007 Copyright Law.
> In addition, we permit any use for educational, academic and medical needs, in academia, health funds and public institutions, which is not intended for commercial purposes, even if intended for personal profit, provided that it does not constitute an alternative to Wikimedicine. In any case of permitted use of the material, it is possible to publish it under the exact same license under which it is published in Wikimedicine, provided that the user explicitly states that the source of the article is in Wikimedicine.

https://www.wikirefua.org.il/w/index.php?title=%D7%95%D7%99%D7%A7%D7%99%D7%A8%D7%A4%D7%95%D7%90%D7%94:%D7%90%D7%95%D7%93%D7%95%D7%AA_%D7%95%D7%99%D7%A7%D7%99%D7%A8%D7%A4%D7%95%D7%90%D7%94#%D7%A9%D7%99%D7%9E%D7%95%D7%A9_%D7%91%D7%AA%D7%9B%D7%A0%D7%99_%D7%94%D7%90%D7%AA%D7%A8

One could argue this is educational and non-commercial, but it could also be argued that by creating an offline mirror file it is constituting an alternative to wikirefua. It seems to me the openzim project would need to explicitly get permission from wikirefua.

**Comment by zevisvei** [comment]
I asked them just to be sure, we'll see what they answer

**Comment by RavanJAltaie** [comment]
@zevisvei do you have an answer ?

**Comment by zevisvei** [comment]
No ,They didn't answer me

**Comment by Popolechien** [comment]
Closing for the time being, feel free to reopen if you hear back from them and they are willing to send us a note authorizing offline distribution. They can write directly to contact _at_ kiwix.org
