### ISSUE TITLE
New ZIM request: MediaWiki.org

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#480]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.mediawiki.org/wiki/MediaWiki
- License: **CC-by-sa**
- Desired ZIM Title: **MediaWiki**
- Desired ZIM Description: **MediaWiki is a collaboration and documentation platform brought to you by a vibrant community.**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/MediaWiki-2020-logo.svg/1843px-MediaWiki-2020-logo.svg.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **https://www.mediawiki.org/wiki/MediaWiki**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/mediawiki
