### ISSUE TITLE
New ZIM request: OpenZim

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#481]
- Website URL: https://wiki.openzim.org/wiki/OpenZIM
- License: **CC-by-sa**
- Desired ZIM Title: **OpenZim**
- Desired ZIM Description: **The openZIM project proposes offline storage solutions for content coming from the Web.**
- Desired ZIM Icon –png (URL or attach one): https://wiki.openzim.org/w/images/logo.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **https://wiki.openzim.org/wiki/OpenZIM**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
Not sure what the plan is for that one. @kelson42 Wasn't there a plan to move this content somewhere else and/or deprecate it, or is it just wishful thinking on my part?

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/openzim
