### ISSUE TITLE
New ZIM request: Ballotpedia

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#482]
- Website URL: https://ballotpedia.org/Main_Page
- License: **GFDL** (source: https://ballotpedia.org/Ballotpedia:Copyrights)
- Desired ZIM Title: **Ballotpedia**
- Desired ZIM Description: **The Encyclopedia of American Politics**
- Desired ZIM Icon –png (URL or attach one): https://pbs.twimg.com/profile_images/518120305290530816/Wa2H2RxF_400x400.jpeg
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/ballotpedia
