### ISSUE TITLE
blockly games

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#486]
- Website URL: https://github.com/google/blockly-games/wiki/Offline
- License: **CC-by-sa ** 
- Desired ZIM Title: **Blockly Games**
- Desired ZIM Description: _Blockly Games is a series of educational games that teach programming. It is designed for children who have not had prior experience with computer programming. By the end of these games, one is ready to use conventional text-based languages._
- Desired ZIM Icon –png (URL or attach one): https://blockly.games/index/title-beta.png
- Language (ISO 639-3): **multiple**

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/blockly_games

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by Popolechien** [comment]
It has not moved to the library yet, and I can't find in in the dev library either. Do you have a link?

**Comment by RavanJAltaie** [comment]
No, I checked again it not there, yet the recipe succeeded twice
https://farm.openzim.org/recipes/blockly_games
