### ISSUE TITLE
New ZIM request: based.cooking

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#490]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://based.cooking/
- License: **Public domain** https://github.com/LukeSmithxyz/based.cooking/blob/master/LICENSE.md
- Desired ZIM Title: **based.cooking LukeSmith **
- Desired ZIM Description: **Recipes summited by computer savvy cooks*
- Desired ZIM Icon –png (URL or attach one): 🍲 Based Cooking 🍳
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/based.cooking_lukesmith

**Comment by RavanJAltaie** [comment]
Recipe Failed,
Labeled as bug in order to follow up

**Comment by Rexadev** [comment]
@RavanJAltaie Updates ?

**Comment by Rexadev** [comment]
@RavanJAltaie Also might want to put this on https://github.com/LukeSmithxyz/based.cooking

**Comment by Rexadev** [comment]
Icon
![image](https://github.com/openzim/zim-requests/assets/62152714/0e5db8d6-468d-4f21-bade-b2ef64610084)
