### ISSUE TITLE
New ZIM request: Dolphin Emulator Wiki

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#491]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://wiki.dolphin-emu.org
- License: **CC-by-sa**
- Desired ZIM Title: **Dolphin Emulator Wiki**
- Desired ZIM Description: **Dolphin is an open-source emulator for the Nintendo GameCube and Wii with support for Microsoft Windows, Linux, Mac OS X, and Android.**
- Desired ZIM Icon –png (URL or attach one): https://wiki.dolphin-emu.org/images/dolphin.40.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **https://wiki.dolphin-emu.org/index.php?title=Main_Page**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/dolphin_emulator_wiki
