### ISSUE TITLE
New ZIM request: ThinkWiki

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#492]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.thinkwiki.org/wiki/ThinkWiki
- License: **GFDL** (source: https://www.thinkwiki.org/wiki/ThinkWiki:About)
- Desired ZIM Title: **ThinkWiki - Linux ThinkPad Wiki**
- Desired ZIM Description: **This is ThinkWiki, the Wikipedia for IBM and Lenovo ThinkPad users. In here, you can find anything you need to install your favourite Linux distribution on your ThinkPad. Windows users shouldn't run away, there's a lot of useful information for them as well. Some Linux information for Mac users also can be found here.**
- Desired ZIM Icon –png (URL or attach one): https://www.thinkwiki.org/w/skins/thinkwiki/thinkwiki-logo.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL):  https://www.thinkwiki.org/wiki/ThinkWiki
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/thinkwiki/edit
