### ISSUE TITLE
Wikidata

### ISSUE THREAD

**Issue by deedeenelson994** [openzim/zim-requests#493]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.wikidata.org/
- License: Public domain
- Desired ZIM Title: Wikidata
- Desired ZIM Description: Wikidata is a free and open knowledge base that can be read and edited by both humans and machines.
- Language (ISO 639-3): English
- Desired Main Page (homepage, if different from website URL): [**n/a**](https://www.wikidata.org/wiki/Wikidata:Main_Page)
- Is this a MediaWiki?: Yes

**Comment by Popolechien** [comment]
Hi @deedeenelson994 this is a legitimate request but we have no scraper for Wikidata nor any short/medium term plans to build one. I'm going to close the ticket.
Just out of curiosity, what kind of use case did you have in mind?
