### ISSUE TITLE
New ZIM request: britannica.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#495]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.britannica.com/
- License: **royalty-free**  https://corporate.britannica.com/termsofuse.html
- Desired ZIM Title: **britannica**
- Desired ZIM Description: **Encyclopaedia**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no**

**Comment by Popolechien** [comment]
> "_You may not use data mining, robots, screen scraping, or similar data gathering and extraction tools on the Services, except with our express written permission._"

As a matter of fact, Britannica started engaging a couple of years ago about getting a dedicated scraper and then the person in charge simply disappeared. I would put it "on hold", but that's rather charitable.

**Comment by Rexadev** [comment]
> > "_You may not use data mining, robots, screen scraping, or similar data gathering and extraction tools on the Services, except with our express written permission._"
> 
> As a matter of fact, Britannica started engaging a couple of years ago about getting a dedicated scraper and then the person in charge simply disappeared. I would put it "on hold", but that's rather charitable.

Can kiwix make a special request

**Comment by Popolechien** [comment]
No answer from them. Dead end at the moment I'm afraid.

**Comment by Rexadev** [comment]
@Popolechien we should it another try and ask them ?
