### ISSUE TITLE
New ZIM request: repair.wiki

### ISSUE THREAD

**Issue by thatsitipl** [openzim/zim-requests#497]
- Website URL: https://[Repair Wiki](https://repair.wiki)
- License: GFDL 1.3 or later
- Desired ZIM Title: Repair Wiki
- Desired ZIM Description: A Wiki about repairs.
- Desired ZIM Icon –png (URL or attach one): https://repair.wiki/images/b/bc/Wiki.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **/w/Repair_Wiki**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/repair_wiki
