### ISSUE TITLE
New ZIM request: What to do if a nuclear Disaster is imminent

### ISSUE THREAD

**Issue by TheWanderer1983** [openzim/zim-requests#498]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: http://ki4u.com/guide.htm
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
Everyone is invited to copy, post, print, and distribute this 'WHAT TO DO IF A NUCLEAR DISASTER IS IMMINENT!' guide anywhere, as long as they do so without charging anything for it. It must be reproduced in entirety, including this notice, and not be altered or edited. To contact the author with comments, e-mail: Shane Connor at [webmaster@ki4u.com](mailto:webmaster@ki4u.com). This guide will be continually 'fine-tuned' so, before distributing it, download it fresh from http://www.ki4u.com/guide.htm or to print out, use this PDF version here [http://www.ki4u.com/guide.pdf](http://1683196019.rsc.cdn77.org/guide.pdf)

- Desired ZIM Title: ki4u
- Desired ZIM Description: Nuclear Disaster survival guide.
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
Site seems down.

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/ki4u/edit

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by Popolechien** [comment]
It only picked up the front page https://dev.library.kiwix.org/viewer#ki4u_2022-11 
But then most of the info is there and the other couple internal links (to ki4u.com) seem rather benign.

**Comment by RavanJAltaie** [comment]
I've updated some parameters here, I'll review it in 24 hour, if still picking only the front page them will add it to the failed files to be deleted.
