### ISSUE TITLE
New ZIM request: SCP Survival guides

### ISSUE THREAD

**Issue by TheWanderer1983** [openzim/zim-requests#499]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://seasonedcitizenprepper.com/preparedness-downloads/
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
Free Survival PDFs, Manuals, and Downloads
- Desired ZIM Title: SCP Survival guides
- Desired ZIM Description: Various free survival guides
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/scp_survival_guides

**Comment by samuk** [comment]
As an alternative you could use this: https://survivalmanual.github.io/home

**Comment by Popolechien** [comment]
FWIW there's already a request for the app to be ported [as a downloadable apk](../../../offspot/package-requests/issues/2) on the Hotspot

**Comment by Popolechien** [comment]
How about the Github site?

**Comment by benoit74** [comment]
Github site is a totally different content. Still about survival manuals, but for me this is a different ZIM request. I just opened https://github.com/openzim/zim-requests/issues/1049 

I propose to close this issue since upstream site is not really usable for now and delete corresponding Zimfarm recipe.

**Comment by benoit74** [comment]
Recipe deleted
