### ISSUE TITLE
New ZIM request: openwrt.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#500]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://openwrt.org
- License: [CC Attribution-Share Alike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/deed.en) 
- Desired ZIM Title: **openwrt.org**
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no**

**Comment by RavanJAltaie** [comment]
@Popolechien it looks like a mediawiki but not labeled as one.
Shall I make the recipe as a mediawiki?

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/openwrt.org

**Comment by Rexadev** [comment]
@RavanJAltaie updates ?

**Comment by RavanJAltaie** [comment]
The mediawiki mwoffliner still not updated completely, the recipe is there but it's failing until the update is fully working.

**Comment by Rexadev** [comment]
@RavanJAltaie updates ?

**Comment by RavanJAltaie** [comment]
Same issue still exists.
Here is an updated recipe, waiting for the new update to be ready
https://farm.openzim.org/recipes/openwrt.org_en

**Comment by benoit74** [comment]
See https://github.com/openzim/zim-requests/issues/1583 for current problem we have

**Comment by Popolechien** [comment]
@benoit74 Considering the last run we attempted was over 2 years ago and 1.17 has since rolled out, shouldn't we give it a fist shot already?

**Comment by benoit74** [comment]
Nope, this is useless, with Anubis in front of the website we have 0 chance to succeed. We need to request website owners if they are open to whitelist our Zimfarm worker IP(s).

**Comment by roblinksdata** [comment]
Setting the `--userAgent` property to something non-browsery like `curl/8.14.1` seems to do the trick of skipping anubis. I'm not sure if it is possible to configure this with Zimfarm?

See https://github.com/openwrt/openwrt/issues/20814#issuecomment-3590215977

**Comment by Popolechien** [comment]
@benoit74 WDYT?

**Comment by benoit74** [comment]
Good insight, thank you very much!

- mwoffliner user-agent does not like a browser at all
- but this is not a mediawiki, so we have to use zimit
- zimit default user-agent looks a bit like a browser but is "customized" to indicate there is "something" on top of the browser
- I don't know how anubis will consider this user-agent
- If needed, we have the whole freedom to customize zimit user-agent
- I would prefer we do not fake the user-agent but indicate we are "zimit", since it is supposed to be the same

@Popolechien I recommend that you reconfigure the recipe to use zimit and launch a first attempt without any special user-agent, should it work this would be the least effort path.

**Comment by Popolechien** [comment]
Recipe updated and started

**Comment by Popolechien** [comment]
Oh Noes!
<img width="530" height="577" alt="Image" src="https://github.com/user-attachments/assets/103fce54-77e3-4d94-b3ff-2ed7b0892413" />

**Comment by roblinksdata** [comment]
For the purposes of debugging, I can tell you that I acquire some of the site myself using zimit with the curl user agent: 

<img width="863" height="604" alt="Image" src="https://github.com/user-attachments/assets/aaa15644-129b-43d6-9001-9be8228bd721" />

**Comment by benoit74** [comment]
Reconfigured with curl UA and requested again

**Comment by benoit74** [comment]
It worked. I cancelled the task to reconfigure the scope exclude rule to exclude non-english pages + editing pages + I added a custom CSS to hide irrelevant stuff

Task requested again with new config

**Comment by Popolechien** [comment]
Task failed https://farm.openzim.org/pipeline/26daa9d9-fcd6-44af-ba9d-701b3df2b3fa/debug

**Comment by benoit74** [comment]
It was an out of memory error, but it processed way too many useless pages.

Config updated to ignore these pages and requested.

Sample new pages to ignore:
- https://openwrt.org/_detail/media/doc/walkthrough-login-screen-1.png?id=docs:guide-quick-start:walkthrough_login
- https://openwrt.org/_media/media/doc/howtos/buzzer-mod-high.png
- https://openwrt.org/_export/code/docs/guide-user/services/honeypots?codeblock=1
- https://openwrt.org/lib/exe/fetch.php?media=http://nottheoilrig.com/openwrt/201212090/index_files/graph_image_003.png&tok=a59450
- https://openwrt.org/packages/table/start?dataofs=50&datasrt=categories

**Comment by roblinksdata** [comment]
It's completed. I've downloaded it, and it seems to contain most of the important stuff. I've just done a cursory check of what's in it — the only thing I think it could use in addition is content on the `forum.openwrt.org` subdomain. Parts of the wiki do link to issues therein. 

Thanks for the work! It's always helpful to have OpenWrt content offline for when I break my router configuration and need to check something.

**Comment by hms0411rt** [comment]
Thanks for the work :)
Any chances to get the Table of Hardware into the zim? The legacy ToH only shows "Loading data...", and the new ToH only links to [the web](https://toh.openwrt.org/)

**Comment by benoit74** [comment]
The legacy toh is working fine on my end:

<img width="875" height="858" alt="Image" src="https://github.com/user-attachments/assets/7aee01aa-3e98-42a2-a97b-d8181ae01183" />

Adding the new toh.openwrt.org is probably technically feasible (besides a bit complex), but is there any (visible) link to this new toh? I'm kinda concerned it will be hard to find in the ZIM

**Comment by benoit74** [comment]
Adding forum.openwrt.org is probably not realistic, in general we end up with way too many pages (1 page per topic + subpages when there has been many answers). I would recommend to start with a new recipe on Zimfarm trying to make a ZIM of only the forum, and if it goes well then we can consider to merge the two.

**Comment by roblinksdata** [comment]
> Adding forum.openwrt.org is probably not realistic, in general we end up with way too many pages (1 page per topic + subpages when there has been many answers).

Fair enough, I won't push it. As it stands I'm pretty happy with what's in there already — and I don't want to trigger another OOM error.

**Comment by Popolechien** [comment]
Thank you for your comments. Moving to production, then

**Comment by Popolechien** [comment]
- [x] Available at https://browse.library.kiwix.org/#lang=eng&q=openWRT
- [x] announced on Mastodon
- [x] added to newsletter announcement list

**Comment by hms0411rt** [comment]
> The legacy toh is working fine on my end

@benoit74 How long did it take on your end for the data to load? What client are you using?

**Comment by benoit74** [comment]
It was kiwix-serve and took 2 secs or something like this

**Comment by hms0411rt** [comment]
@benoit74 So its probably an issue with Kiwix-Desktop? I had it open for days and it wont load with kiwix-desktop, neither on linux nor on windows. 

On linux using debian stable Version 2.3.0 I get
```
js: 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
js: Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
js: Fetch API cannot load zim://c4f0b1f5-acd6-e50b-f04e-2da11e0f7ad6.zim/openwrt.org/toh.json. URL scheme "zim" is not supported.
js: Uncaught (in promise) TypeError: Failed to fetch
```

It this the same as in https://github.com/kiwix/kiwix-desktop/issues/1476?

**Comment by benoit74** [comment]
Yes it is the same indeed. Thank you for make the connection, didn't realized about it.
