### ISSUE TITLE
New ZIM request: geeksforgeeks.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#501]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.geeksforgeeks.org/
- License: CCBY-SA https://www.geeksforgeeks.org/copyright-information/
- Desired ZIM Title: *GeeksForGeeks**
- Desired ZIM Description: **Computer science, Concepts, Programming**
- Desired ZIM Icon –png (URL or attach one): https://media.geeksforgeeks.org/gfg-gg-logo.svg
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **no**

It also has non-programming articles that only interests indian people may not include that in zim.

**Comment by Popolechien** [comment]
From https://www.geeksforgeeks.org/copyright-information/

_You should Refrain from using images, photos, and videos as these are the sole property of GeeksforGeeks and do not fall under the CC license, and that usage of the same shall be treated as Infringement._

**Comment by Rexadev** [comment]
> From https://www.geeksforgeeks.org/copyright-information/
> 
> _You should Refrain from using images, photos, and videos as these are the sole property of GeeksforGeeks and do not fall under the CC license, and that usage of the same shall be treated as Infringement._

Exclude media text is very good

**Comment by Popolechien** [comment]
@Rexadev Unfortunately we only have this level of granularity for wikis.

**Comment by Rexadev** [comment]
> @Rexadev Unfortunately we only have this level of granularity for wikis.

How that be possible in future ?
