### ISSUE TITLE
Prunelle

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#502]
- Website URL: https://drive.farm.openzim.org/_admin/#/prunelle

- Desired ZIM Title: there are actually six sets of ebooks (French/English) Auteurs en herbe/Budding authors ; contes africains à illustrer / draw your african stories; livres interactifs / interactive books
- Desired ZIM Description: 

`Contes africains à illustrer `
Français : Viens lire et illustrer ces contes issus du folklore africain !
Anglais : Read and illustrate these African tales !

`Livres interactifs`
Français : Des livres à l’image de la vie des enfants, qui en reflètent la richesse et la complexité grâce à des personnages attachants.
Anglais : Books depicting and reflecting children’ life complexity and richness thanks to adorable characters.

`Auteurs en herbe` 
Français : Livres d'évasion ou livres d'activité, les albums des collections « Sans Mots » et « Auteurs en herbe » transporteront les enfants dans un univers où ils sont les auteurs de leur histoire. Les livres sont spécialement conçus pour stimuler leur imagination et leur écriture.
Anglais : Activity or Picture books, the collections “Write your own story” and “Imagine your own story” take the children in a universe where they are the authors of their own story. Books are specially designed to spark creativity through writing.

- Desired ZIM Icon –png (URL or attach one): https://drive.farm.openzim.org/book%20prunelle/book%20prunelle%20square.png
- Language (ISO 639-3): **eng** / **fra**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: ** no**

**Comment by RavanJAltaie** [comment]
@Popolechien isn't this issue a duplicate of #625 ?

**Comment by Popolechien** [comment]
Correct.
