### ISSUE TITLE
New ZIM request: fandom.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#503]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.fandom.com/
- License: CC-by-sa for most of it https://community.fandom.com/wiki/Copyright
- Desired ZIM Title: **Fandom**
- Desired ZIM Description: **Wikipedia of normies**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no**

**Comment by Popolechien** [comment]
I think it's a good idea and I've had this one in my crosshairs for a while, but I would advise we get individual requests for fandom microsites (e.g. gta.fandom, witcher.fandom, etc.). 

I don't think anyone (except r/datahoarders folks) would ever look forward to downloading a terabyte-size zim file.

**Comment by Rexadev** [comment]
Is it possible to do it by Topic.
Example - https://ibanez.fandom.com/wiki/Ibanez_Wiki a Guitar Brand wiki. It doesn't show Music as topic but https://www.fandom.com/?s=ibanez does

Also there is things to find first like - 
1. Does fandom does topics properly. 
2. Does music c

They also got [Hubs ](https://community.fandom.com/wiki/Category:Hubs). Example - music.fandom.com/wiki/Music_Hub
https://community.fandom.com/wiki/Hub:Big_wikis



They also got a github https://github.com/Wikia

**Comment by Popolechien** [comment]
@Rexadev Topics would probably be ideal. We handle them on Wikipedia but there's a consistent use of Wikiprojects there. Not sure fandom does that, we'd need to look into it. Hubs might be it.

Can you please open a ticket with this exact title (e.g. "_Music-themed fandom hub" or along those lines) to we can keep track of the issue? and please also link to their repo, should we need to build a dedicated scraper.
