### ISSUE TITLE
New ZIM request: prlib.ru

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#504]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.prlib.ru/en
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **Boris Yeltsin Presdidential Library**
- Desired ZIM Description: **Encyclopedia from RUSSIA in English and Russian**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no**

**Comment by Popolechien** [comment]
_©  Presidential Library, 2022 All rights reserved._

**Comment by Rexadev** [comment]
@Popolechien Would you still respect copyright if you are not of it's jurisdiction
