### ISSUE TITLE
New ZIM request: Fandom Music_Hub

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#505]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL:  https://music.fandom.com/wiki/Music_Hub
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **Fandom Music_Hub**
- Desired ZIM Description: **Fandom Music_Hub**
- Desired ZIM Icon –png (URL or attach one): https://abc.com/icon.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes | no**

They also got a github https://github.com/Wikia

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/fandom_music_hub

**Comment by Rexadev** [comment]
@RavanJAltaie update ?

**Comment by RavanJAltaie** [comment]
Recipe is failing, the file will be ready once the mwoffliner update is done which is expected in about 2 months minimum.

**Comment by Rexadev** [comment]
Updates ?

**Comment by RavanJAltaie** [comment]
@Rexadev Nothing yet

**Comment by Rexadev** [comment]
> @Rexadev Nothing yet

Ibanez wiki the supported why not Music

**Comment by RavanJAltaie** [comment]
@Rexadev because of the same reason of mwoffliner update.
