### ISSUE TITLE
Broken Cyclowiki Archives

### ISSUE THREAD

**Issue by Artem13327** [openzim/zim-requests#506]
In these archives [1](https://library.kiwix.org/cyclowiki_ru_all_maxi_2020-11) [2](https://library.kiwix.org/cyclowiki_ru_all_nopic_2020-11) all pages except the main page are broken

**Comment by RavanJAltaie** [comment]
@Popolechien who is following up on this?

**Comment by Popolechien** [comment]
Looks like a duplicate of #459.

@rgaudin Can you please delete all four cyclowiki files?

https://download.kiwix.org/zim/other/cyclowiki_ru_all_maxi_2020-10.zim
https://download.kiwix.org/zim/other/cyclowiki_ru_all_maxi_2020-11.zim
https://download.kiwix.org/zim/other/cyclowiki_ru_all_nopic_2020-10.zim
https://download.kiwix.org/zim/other/cyclowiki_ru_all_nopic_2020-11.zim

**Comment by rgaudin** [comment]
Done
