### ISSUE TITLE
New ZIM Request for osdev.org

### ISSUE THREAD

**Issue by helloray** [openzim/zim-requests#509]
- Website URL: https://wiki.osdev.org/
- License: Public domain
- Desired ZIM Title: osdev.org
- Desired ZIM Description: About the creation of operating systems
- Desired ZIM Icon –png (URL or attach one): https://wiki.osdev.org/skins/common/images/osdev.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): n/a
- Is this a MediaWiki?: yes

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/pipeline/18dac99e1c7aad427466b636
