### ISSUE TITLE
New ZIM request: openSUSE Wiki

### ISSUE THREAD

**Issue by blurredbeeble** [openzim/zim-requests#512]
- Website URL: https://en.opensuse.org/Main_Page
- License: GNU Free Documentation License 1.2
- Desired ZIM Title: openSUSE Wiki
- Desired ZIM Description: The openSUSE Wiki offers information about the openSUSE project and distribution. The goal is to provide high quality documentation and a place for collaboration on all parts of the project.
- Desired ZIM Icon –png: 
![button-filled-colour](https://user-images.githubusercontent.com/114100745/198589534-f4ca79b3-f2be-4c72-a520-4f4e3057f36d.png)
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/opensuse_en_all

Might not work until next mwoffliner update but at least it is there now.

**Comment by Rexadev** [comment]
@Popolechien duplicate https://github.com/openzim/zim-requests/issues/511
