### ISSUE TITLE
New ZIM request: ReactOS Wiki

### ISSUE THREAD

**Issue by Artem13327** [openzim/zim-requests#513]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://reactos.org/wiki/
- License: GNU Free Documentation License 1.3 or later
- Desired ZIM Title: ReactOS Wiki
- Desired ZIM Description: Official ReactOS wiki
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: yes

**Comment by RavanJAltaie** [comment]
@Artem13327 
The recipe has been updated
https://farm.openzim.org/recipes/reactos_wiki

However, it's failing as we wait for mwoffliner update to be implemented successfully to see these recipes work.
This is expected to be done before the end of this year
