### ISSUE TITLE
New ZIM request: WineHQ Wiki

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-requests#516]
- Website URL: https://wiki.winehq.org/Main_Page
- License: **LGPL 2.1** (source: https://wiki.winehq.org/Licensing#Wiki_Content)
- Desired ZIM Title: **WineHQ Wiki**
- Desired ZIM Description: **The WineHQ Wiki is a repository of both end-user and developer documentation for the Open-Source Wine Project.**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/e/ed/WINE-logo.png
- Language (ISO 639-3): **eng,deu,kor,fra,zho,nld**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/winehq_wiki
