### ISSUE TITLE
New  request: Scaleway webinars

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#517]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.youtube.com/playlist?list=PL8WjEBDU6iMKe9vav-yYXqU7q5PN2X70G
- License: **Creative Commons ** 
- Desired ZIM Title: **Webinaires cloud**
- Desired ZIM Description: **Une série de webinaires de formation au cloud / kubernetes**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Cib-scaleway_%28CoreUI_Icons_v1.0.0%29.svg/240px-Cib-scaleway_%28CoreUI_Icons_v1.0.0%29.svg.png
- Language (ISO 639-3): **fra**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
The License on all videos in the playlist says © 2020 - Scaleway
No mention of CC license anywhere

**Comment by Popolechien** [comment]
@RavanJAltaie We did get permission from them.

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/scalewaywebinars_fr_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
https://dev.library.kiwix.org/viewer#paulgraham.com_en_all_2024-08
The file is not complete, I've tried to change the scope type but same result.
Could you please check? @benoit74

**Comment by benoit74** [comment]
@RavanJAltaie I imagine your last comment has nothing to do in this issue but is related to https://github.com/openzim/zim-requests/issues/1143
