### ISSUE TITLE
Latest 100r.co Off the Grid wiki is broken

### ISSUE THREAD

**Issue by jmontleon** [openzim/zim-requests#519]
https://library.kiwix.org/100r-off-the-grid_en_2022-06/A/100r.co/site/off_the_grid.html

Every page returns, "Sorry, the URL https://100r.co/site/off_the_grid.html is not in this archive."

The same happens if I download it and try it locally.

**Comment by RavanJAltaie** [comment]
It works perfectly with us
The main page and every single link to internal pages
Check the snapshots
<img width="779" alt="2" src="https://user-images.githubusercontent.com/116940574/204209119-8e4da90b-dd34-43ab-a98d-417e81d1f6b3.png">
<img width="730" alt="1" src="https://user-images.githubusercontent.com/116940574/204209127-2df1055c-3ec2-4f4f-9614-a014dc343660.png">

**Comment by Popolechien** [comment]
@jmontleon i've seen this issue before, try to clear your cache or visit the page from a private window.

**Comment by jmontleon** [comment]
Thank you @Popolechien that worked. It works locally and on the kiwix library site now.

**Comment by RavanJAltaie** [comment]
https://library.kiwix.org/viewer#100r-off-the-grid_en_2023-05
