### ISSUE TITLE
wikipedia cooking

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#52]
_From @amirh123123 on April 3, 2018 12:20_

hi please make wikipedia articles about cooking foods can cuisine of countries and more

_Copied from original issue: openzim/mwoffliner#272_

**Comment by Popolechien** [comment]
See [wikibooks](https://en.wikibooks.org/wiki/Category:Recipes) preferably

**Comment by RavanJAltaie** [comment]
@Popolechien  There is no website mentioned or any files
If we don't have any, let's close this ticket for now.
