### ISSUE TITLE
Cannot click links on Arabic wikimed

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#522]
The issue appearshttps://library.kiwix.org/viewer#wikipedia_ar_medicine_maxi (and variants): links are shown in blue except that they cannot be clicked on.

The issue seems limited to the landing page as going to a random article (e.g. https://library.kiwix.org/viewer#wikipedia_ar_medicine_maxi/A/%D8%AF%D8%A7%D9%8A_%D9%86%D8%B3%D8%AA%D9%8A%D8%B1%D9%88%D9%84) all internal links function

@RavanJAltaie Can you go and check out the wikicode at 
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Medicine/Open_Textbook_of_Medicine2
and compare to what is at 
https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D9%85%D8%B4%D8%B1%D9%88%D8%B9_%D9%88%D9%8A%D9%83%D9%8A_%D8%B7%D8%A8/%D9%85%D8%B1%D8%AC%D8%B9_%D8%A8%D8%AF%D8%A7%D9%8A%D8%A9_%D8%A7%D9%84%D8%AA%D8%B7%D8%A8%D9%8A%D9%82_%D8%A7%D9%84%D8%B7%D8%A8%D9%8A2

**Comment by RavanJAltaie** [comment]
All links in the landing page are checked and working properly.
All links in the sub-pages are check and working properly.
