### ISSUE TITLE
Delete incomplete files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#525]
A couple of zim files were created but the scraping was incomplete (300ko files or so). Please delete:

- https://download.kiwix.org/zim/zimit/ManKier_2022-12.zim
- https://download.kiwix.org/zim/zimit/Coopmaths_2022-12.zim
- https://download.kiwix.org/zim/zimit/Fipeco_2022-12.zim
- https://download.kiwix.org/zim/zimit/Scratch_2022-12.zim
- https://download.kiwix.org/zim/zimit/OWASP_2022-12.zim
- https://download.kiwix.org/zim/zimit/footballdatabase.com_2022-12.zim

@rgaudin I'm assigning the ticket to you, but I'm adding @RavanJAltaie so she sees how file removal works (until we have a CMS)

**Comment by rgaudin** [comment]
@Popolechien I've deleted them all but **Coopmaths** was 707MiB.

I'd like to stress that none of those files respect the [Naming Convention](https://github.com/openzim/overview/wiki/Naming-Convention). Those are **new files**, we should not create improperly named ones. Haven't checked the `Name` tag of those but I suppose it matches the filenames.

@RavanJAltaie indeed, I only can delete files at the moment.

**Comment by Popolechien** [comment]
@rgaudin Thanks! You've been too fast - I also added 

https://download.kiwix.org/zim/zimit/OWASP_2022-12.zim

and 

https://download.kiwix.org/zim/zimit/footballdatabase.com_2022-12.zim

and that should be all for me for now.

**Comment by rgaudin** [comment]
Done

**Comment by RavanJAltaie** [comment]
This is a list of current zimit files which their recipes needed fixings:
1- https://farm.openzim.org/recipes/mankier (The file name has no spaces but I removed the capital letter and requested it again)
2- https://farm.openzim.org/recipes/ki4u  (The file name has no spaces or capital letters)
3- https://farm.openzim.org/recipes/coopmaths (The file name has no spaces but I removed the capital letter and requested it again)
4- https://farm.openzim.org/recipes/blockly_games (I've removed the spaces in the file name and requested again)
5- https://farm.openzim.org/recipes/rapsberry_pi_docs  (I've removed the spaces in the file name and requested again)
6- https://farm.openzim.org/recipes/fipeco/ (The file name has no spaces but I removed the capital letter and requested it again)
7- https://farm.openzim.org/recipes/mitscratch (The file name has no spaces but I removed the capital letter and requested it again)
8- https://farm.openzim.org/recipes/feed_the_beast_wiki  (I've removed the spaces in the file name and requested again)
9- https://farm.openzim.org/recipes/modern_philosophy (I've removed the spaces in the file name and requested again)
10- https://farm.openzim.org/recipes/core_knowledge (I've removed the spaces in the file name and requested again)
11- https://farm.openzim.org/recipes/openstreet_map (I've removed the spaces in the file name and requested again)
12- https://farm.openzim.org/recipes/owasp (The file name has no spaces but I removed the capital letter and requested it again)
13- https://farm.openzim.org/recipes/footballdatabase.com (The file name has no spaces or capital letters but I removed a dot and requested it again)

**Comment by rgaudin** [comment]
Could you please provide a list of files instead? This is a list of recipes

**Comment by RavanJAltaie** [comment]
I will put the files which are created, but most of the recipes above didn't reflect in the library in the first place.
Tomorrow will double check if the recipes fixings made any change in the files and will update you here.

**Comment by RavanJAltaie** [comment]
The Files which exists in the library but not full or not correct (Even after correcting the zim file naming):
1- https://library.kiwix.org/viewer#ki4u_2022-12
2- https://library.kiwix.org/viewer#mankier_2022-12
3- https://library.kiwix.org/viewer#fipeco_2022-12
4- https://library.kiwix.org/viewer#scratch_2022-12
5- https://library.kiwix.org/viewer#feed_the_beast_2022-12
6- https://library.kiwix.org/viewer#modern_philosophy_2022-12
7- https://library.kiwix.org/viewer#core_knowledge_2022-12
8- https://library.kiwix.org/viewer#open_street_maps_2022-12
9- https://library.kiwix.org/viewer#owsap_2022-12
10- https://library.kiwix.org/viewer#footballdatabase_2022-12

It's been almost 15 hours since I re-requested the recipes after correcting the zim file names, does it take more time for the changes to be reflected?
@rgaudin

**Comment by rgaudin** [comment]
@RavanJAltaie I don't understand what you are asking for.
This (closed) ticket is about removing some files. If you have additional files to have removed from the server, use the same formatting as @Popolechien did in this ticket: actual links to files.
That would be in a separate ticket anyway.

Now regarding the duration, you have access to the zimfarm so you can check there whether the process is awaiting to be started, running, or completed (either successfully or failed).
