### ISSUE TITLE
Remove volapük top selection

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#532]
Namely:
https://download.kiwix.org/zim/wikipedia/wikipedia_vo_top_maxi_2022-06.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_vo_top_maxi_2022-07.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_vo_top_mini_2022-06.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_vo_top_mini_2022-07.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_vo_top_nopic_2022-06.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_vo_top_nopic_2022-07.zim

**Comment by rgaudin** [comment]
Done. I think we should include the reason those are deleted in the ticket otherwise that information will be lost.
