### ISSUE TITLE
[Copyrighted] thetubestore.com/guitar-amp-schematics

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#533]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.thetubestore.com/guitar-amp-schematics
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: thetubestore.com Guitar Amp Schematics
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
We don't create Zim files for copyrighted materials
