### ISSUE TITLE
[Copyrighted] tonepad.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#534]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: http://tonepad.com/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: tonepad.com Guitar Amp and Pedal Circuits
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes | no**

**Comment by RavanJAltaie** [comment]
We don't create Zim files for copyrighted materials.
