### ISSUE TITLE
[Copyrighted] guitarelectronics.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#536]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://guitarelectronics.com
- License: 
- Desired ZIM Title: Guitar Parts Info and Electronics Circuits
- Desired ZIM Description: 
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
We don't create Zim files for copyrighted materials.
