### ISSUE TITLE
New  request: ibanez.fandom.com/wiki/Ibanez_Wiki

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#537]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://ibanez.fandom.com/wiki/Ibanez_Wiki
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: Ibanez Guitars Fandom Wiki
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Recipe requested
https://farm.openzim.org/recipes/ibanez_guitars

**Comment by RavanJAltaie** [comment]
recipe failed
technical ticket has been issued
https://github.com/openzim/mwoffliner/issues/1727

**Comment by Rexadev** [comment]
@RavanJAltaie It is not available in library.kiwix.org

**Comment by RavanJAltaie** [comment]
@Rexadev The recipe succeeded, the file location has been updated to library.kiwix.org, it will appear in max. couple of days

**Comment by RavanJAltaie** [comment]
@Rexadev Here is the file
https://library.kiwix.org/viewer#ibanezwiki_en_all_maxi_2023-04

**Comment by Rexadev** [comment]
> Here is the file
> https://library.kiwix.org/viewer#ibanezwiki_en_all_maxi_2023-04

❤️‍🔥 Thanks alot
@RavanJAltaie @kelson42

**Comment by Rexadev** [comment]
@RavanJAltaie images are low res compared to images on the site

**Comment by Rexadev** [comment]
@RavanJAltaie @kelson42
images are low res compared to images on the site

**Comment by kelson42** [comment]
> @RavanJAltaie @kelson42
> images are low res compared to images on the site

yes, we slightly reduce the qiality of pictures so tge zim file can be smaller. Should not be tfat visible.

**Comment by Rexadev** [comment]
You can use better compression formats like WebP because the current ZIM image quality is very low
@kelson42 @RavanJAltaie

**Comment by kelson42** [comment]
We already use wepb excep if this scrape is wrongly configured.

**Comment by Rexadev** [comment]
> We already use wepb.

Bump up the resolution a little

**Comment by Rexadev** [comment]
@RavanJAltaie Bump up the resolution a little

**Comment by Popolechien** [comment]
@Rexadev all fandom-related sites are tied to the upgrade of MWoffliner. Work is still ongoing so unlikely to see any resolution anytime soon.

**Comment by Rexadev** [comment]
@RavanJAltaie Bump up the resolution a little

**Comment by Rexadev** [comment]
![image](https://github.com/user-attachments/assets/2895d6ba-c56e-4589-ae51-a8399080c5ab)
@kelson42 little broken

**Comment by Rexadev** [comment]
@kelson42 Will converting every file to AVIF save space ?

**Comment by kelson42** [comment]
@Rexadev No clue. Not part of the roadmap. Large support of AVIF is pretty recent and we focus on Webp.
