### ISSUE TITLE
[Copyrighted] dimarzio.com/support/wiring-diagrams

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#538]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.dimarzio.com/support/wiring-diagrams
- License: 
- Desired ZIM Title: dimarzio.com wiring-diagrams
- Desired ZIM Description: 
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
We don't create Zim files for copyrighted materials.
