### ISSUE TITLE
[Copyrighted] 1728.org/guitar.htm

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#539]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.1728.org/guitar.htm
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: 1728.org Guitar Wiring Diagrams
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes | no**

**Comment by RavanJAltaie** [comment]
We don't create Zim files for copyrighted materials.
