### ISSUE TITLE
Fix minecraftwiki_de

### ISSUE THREAD

**Issue by uriesk** [openzim/zim-requests#543]
https://farm.openzim.org/recipes/minecraftwiki_de/config

Those paramaters need to be different, here the correct ones:
```
--mwUrl=https://minecraft.fandom.com/de --mwApiPath api.php --mwModulePath load.php
```
And the favicon is at
```
https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/93/Grass_Block_JE7_BE6.png
```

thanks

**Comment by uriesk** [comment]
Thanks a lot.

If possible, maybe also change the name to `minecraft_fandom_de_all` to be consistent with [minecraft_fandom_all](https://farm.openzim.org/recipes/minecraft_fandom_all)

**Comment by kelson42** [comment]
> Thanks a lot.
> 
> If possible, maybe also change the name to `minecraft_fandom_de_all` to be consistent with [minecraft_fandom_all](https://farm.openzim.org/recipes/minecraft_fandom_all)

Does not have to, they follow slightly different naming conventions.

**Comment by kelson42** [comment]
I have fixed it slightly differently, but it should be fixed now.
