### ISSUE TITLE
Make a ZIM of ManualLibs

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#546]
- Website URL: https://www.manualslib.com
- License: Not clear, but situation is a bit special
- Desired ZIM Title: manuallibs
- Desired ZIM Description: The ultimate manuals library
- Desired ZIM Icon –png (URL or attach one): https://static.manualslib.com/public/img/manuallib_logo_large_en.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
@kelson "situation is bit special"?

**Comment by kelson42** [comment]
Basically, the manuals are copyrighted, but the goal of the authors is to distribute them as much as possible. So wonder if there is really a concrete problem here.

**Comment by benjaoming** [comment]
I'm not a "Right to Repair" expert, but I believe that this legislation, proposed or implemented, is going to be about legally obligating manufacturers to make manuals and repair instructions available.

So indeed, the situation is special.

**Comment by benjaoming** [comment]
> The current focus of Right to Repair has three main tenets: parts should be available at reasonable prices, **service manuals should be free and public**, and repair information like software tools and schematics should be available. 

See: https://www.ifixit.com/News/61178/what-right-to-repair-compliance-looks-like-for-manufacturers

**Comment by Popolechien** [comment]
I agree as far as manuals are concerned, but the website and it's design are proprietary

**Comment by Popolechien** [comment]
@RavanJAltaie Can you please drop them a note and seek permission to share their website offline? Ping me with a draft when ready.

**Comment by RavanJAltaie** [comment]
Draft sent to be checked.

**Comment by RavanJAltaie** [comment]
No response even with following up more than once.
