### ISSUE TITLE
Archive WP for Schools (old)

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#549]
The old Wikipedia for Schools selection from SOS Children's villages has not been updated since 2013. I am told that folks at Labdoo are still uploading it on their computer because they weren't aware of the new ASU version.

We need to move 
https://download.kiwix.org/zim/wikipedia/wikipedia_en_for-schools_2013-01.zim
and 
https://download.kiwix.org/zim/wikipedia/wikipedia_en_for-schools_2018-09.zim

To https://download.kiwix.org/archive/zim/wikipedia/ so as to avoid confusion.

**Comment by rgaudin** [comment]
done

**Comment by kelson42** [comment]
@rgaudin Please archive both versions in https://download.kiwix.org/archive/zim/wikipedia/.

**Comment by rgaudin** [comment]
> @rgaudin Please archive both versions in https://download.kiwix.org/archive/zim/wikipedia/.

How is this different from the request ?

**Comment by kelson42** [comment]
Ooops
