### ISSUE TITLE
Create Astronomy zim file

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#55]
_From @Popolechien on April 9, 2018 9:57_

Based on Wikipedia:WikiProject_Astronomy 

_Copied from original issue: openzim/mwoffliner#286_

**Comment by kelson42** [comment]
Duplicate of #264

**Comment by Ubuntu-2020** [comment]
May be it will be better increase ZIM file **wikipedia_physics**?
Especially since the file **wikipedia_physics** already has some articles about astronomical observatories!

**Comment by Popolechien** [comment]
@Ubuntu-2020 I understand your rationale but I'd rather want to keep specific thematic zim files - nothing prevents people from downloading both, and they would remain at a decent size which is always important in most of our use cases.
