### ISSUE TITLE
Two bibnum recipes

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#560]
There are currently two recipes for [bibnum](https://journals.openedition.org/bibnum/) using the same URL

- one has an `exclude` param configured
- both target `dev/`
- both use the same `Name` so **they would override each other!!!**
- both have recent runs…
- both are enabled
- one is `monthly` other one is `biannually`

that's a recipe for failure (pun intended 😅)

**Comment by Popolechien** [comment]
Since they're identical and the site is somewhat dormant, I guess the bi-annual one will do and the monthly one can be deleted.

I'm assigning @RavanJAltaie to make this easy fix for when she'll be back.

**Comment by rgaudin** [comment]
It's difficult to define what a duplicate is. In this case, it's not exactly a duplicate because the config are differents and there might be reasons to…

I imagine the ZF could ask for confirmation on clone and list the other ones with similar names. But that in this case I am pretty sure the original one was cloned into the new one so it was probably done on purpose but without follow up.

**Comment by kelson42** [comment]
We could make IMO a good enough system, pretty simple, just based on the upstream URL and warn that we might have a duplicate.

**Comment by rgaudin** [comment]
I don't think it can work alone because url is scraper specific and many scrapers don't use URL. Also, because we only ever create by cloning, we will obviously have a duplicate at creation (where we only specify the name).

URL checking would thus have to be done in Edit mode. I don't think upon save would be much useful but it could be a _live_ check when modifying the URL/ident field

**Comment by RavanJAltaie** [comment]
Fixed.
