### ISSUE TITLE
Move `booksdash_en_all_2023-01.zim` from `dev` to `zimit`

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zim-requests#561]
@rgaudin I have tested `booksdash_en_all_2023-01.zim` in Kiwix JS PWA (left) and via Kiwix Serve (right), and all seems fine. The UI is responsive and the books load correctly. I think it's safe for the archive to be permanently moved to to `zimit` and the recipe modified so that future scrapes go straight there.

![image](https://user-images.githubusercontent.com/4304337/216025431-e1458ffa-9e90-42bb-981c-3f9a0c286945.png)

**Comment by rgaudin** [comment]
👍  done
