### ISSUE TITLE
Delete unnecessary nopic files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#563]
We've built https://download.kiwix.org/zim/wikipedia/wikipedia_guw_all_nopic_2023-02.zim and https://download.kiwix.org/zim/wikipedia/wikipedia_pcm_all_nopic_2023-02.zim but these are small wikis and there is little to no added value to building a `nopic` version at this stage and the corresponding zim files should be deleted to minimize confusion.

I've already modified the recipes so as to only generate `maxi`.

**Comment by Popolechien** [comment]
adding https://download.kiwix.org/zim/wikipedia/wikiquote_guw_all_nopic_2023-02.zim

**Comment by rgaudin** [comment]
done
