### ISSUE TITLE
New  request: Madrasa Videos

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#572]
- Website URL: https://www.youtube.com/@Madrasa
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **فيديوهات مدرسة** (please correct)
- Desired ZIM Description: **محتوى تعليمياً متميزاً باللغة العربية في كافة مواد العلوم** (please correct)
- Desired ZIM Icon –png (URL or attach one): https://yt3.googleusercontent.com/ytc/AL5GRJXF48kJD4WNkXJ8HqwQvAGt3mcTWyiLn--vGtD9=s176-c-k-c0x00ffffff-no-rj but YT scraper handles this automatically
- Language (ISO 639-3): **ara**
- Is this a MediaWiki?: **no**

I didn't create a recipe directly because we need an Arabic-speaker to look closely at this channel (5,600 videos) and decide what to do with it. It probably makes little sense to create a huge, complete ZIM but playlists-based ones might be very useful.

This content is supposed to be of high quality and could replace the Khan Academy AR that we are missing

**Comment by RavanJAltaie** [comment]
Pending

**Comment by RavanJAltaie** [comment]
@rgaudin I've changed already 3 or 4 different APIs in the recipe and it's still failing, any idea?

**Comment by rgaudin** [comment]
Debug log says `Invalid channelId `Madrasa`: Not Found`

**Comment by Popolechien** [comment]
well that's not really helpful because Madrasa does exist. Should the Channel Id be `@madrasa`?

**Comment by rgaudin** [comment]
I believe it's a _User_ then and not a _Channel_ (distinction kinda blurred by YT now with this @ prefix).

**Comment by RavanJAltaie** [comment]
I've changed the parameter from Channel to User, requested again and will monitor

**Comment by RavanJAltaie** [comment]
@rgaudin the recipe is still failing, I'll place a ticket for troubleshooting.
https://github.com/openzim/youtube/issues/176
