### ISSUE TITLE
Delete 2019 mwoffliner ZIMs

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#573]
The following ZIM files have all been created at a time `mwoffliner` set the Publisher in the `Name`. There are no updates for those ZIMs.

Most of them dont have recipes. Some have different lang codes: `nan` -> `zh` and `no` -> `nb`.

| Lang | ZIM | Size | Preview |
| ---- | --- | ---- | ------- |
| Chinese (`nan`) | wikiquote/wikiquote_nan_all_nopic_2019-04.zim  | 170K | https://library.kiwix.org/content/wikiquote_nan_all_nopic_2019-04/A/Th%C3%A2u-ia%CC%8Dh |
| Haitian (`ht`) | wikisource/wikisource_ht_all_nopic_2019-04.zim | 477K | https://library.kiwix.org/content/wikisource_ht_all_nopic_2019-04/A/Paj_Prensipal |
| Haitian (`ht`) | wikisource/wikisource_ht_all_maxi_2019-04.zim | 5.9M | https://library.kiwix.org/content/wikisource_ht_all_maxi_2019-04/A/Paj_Prensipal |
| Irish (`ga`) | wikiquote/wikiquote_ga_all_maxi_2019-04.zim | 127K | https://library.kiwix.org/content/wikiquote_ga_all_maxi_2019-04/A/Pr%C3%ADomh%C2%ADleathanach |
| Irish (`ga`) | wikiquote/wikiquote_ga_all_nopic_2019-04.zim  | 142K | https://library.kiwix.org/content/wikiquote_ga_all_nopic_2019-04/A/Pr%C3%ADomh%C2%ADleathanach |
| Simple English | wikiquote/wikiquote_en_simple_all_maxi_2019-04.zim | 5.1M | https://library.kiwix.org/content/wikiquote_en_simple_all_maxi_2019-04/A/Main_Page |
| Simple English | wikiquote/wikiquote_en_simple_all_nopic_2019-04.zim | 1.8M | https://library.kiwix.org/content/wikiquote_en_simple_all_nopic_2019-04/A/Main_Page |
| Kazakh (`kk`) | wikiquote/wikiquote_kk_all_maxi_2019-04.zim | 166K | https://library.kiwix.org/content/wikiquote_kk_all_maxi_2019-04/A/%D0%91%D0%B0%D1%81%D1%82%D1%8B_%D0%B1%D0%B5%D1%82 |
| Kazakh (`kk`) | wikiquote/wikiquote_kk_all_nopic_2019-04.zim | 166K | https://library.kiwix.org/content/wikiquote_kk_all_nopic_2019-04/A/%D0%91%D0%B0%D1%81%D1%82%D1%8B_%D0%B1%D0%B5%D1%82 |
| Luxembourgish (`lb`) | wikiquote/wikiquote_lb_all_nopic_2019-04.zim | 246K | https://library.kiwix.org/content/wikiquote_lb_all_nopic_2019-04/A/Haapts%C3%A4it |
| Luxembourgish (`lb`) | wikiquote/wikiquote_lb_all_maxi_2019-04.zim | 253K | https://library.kiwix.org/content/wikiquote_lb_all_maxi_2019-04/A/Haapts%C3%A4it |
| Old English (`ang`) | wikisource/wikisource_ang_all_nopic_2019-04.zim | 166K | https://library.kiwix.org/content/wikisource_ang_all_nopic_2019-04/A/H%C4%93afodtramet |
| Old English (`ang`) | wikisource/wikisource_ang_all_maxi_2019-04.zim | 155K | https://library.kiwix.org/content/wikisource_ang_all_maxi_2019-04/A/H%C4%93afodtramet |
| Norwegian (`no`) | wikinews/wikinews_no_all_nopic_2016-12.zim | 1.9M | No link ; probably broken |
| Norwegian (`no`) | wikibooks/wikibooks_no_all_nopic_2016-12.zim | 2.5M | No link ; probably broken |
| Norwegian (`no`) | wikiquote/wikiquote_no_all_nopic_2016-12.zim | 743K | No link ; probably broken |
| Norwegian (`no`) | wikisource/wikisource_no_all_nopic_2016-12.zim | 61M | No link ; probably broken |

@Popolechien or @kelson42 please confirm i can **DELETE all those files**

**Comment by Popolechien** [comment]
@rgaudin Yes please do.

**Comment by rgaudin** [comment]
Done
