### ISSUE TITLE
Remove Wikiwel

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#574]
What is the status of [WikiWel](https://library.kiwix.org/viewer#wikiwel_en_all_maxi_2018-10/A/Wikiwel.html) for which we have a single ZIM (nopic, maxi) from `2018-10` with a recipe disabled for 2 years.

Should we keep the ZIM file?

**Comment by kelson42** [comment]
No clue why the recipe was deactivated.

**Comment by rgaudin** [comment]
[The recipe](https://farm.openzim.org/recipes/wikiwel.org/config) was using custom paths for mediawiki

**Comment by Popolechien** [comment]
Let's reactivate the recipe and see if the latest fixes to MWoffliner changed anything.

**Comment by Popolechien** [comment]
Of so that [last one](https://farm.openzim.org/pipeline/b6c39c744ee94c5325170046/debug) failed with a 403.

The website's main author also seems to have greatly reduced their activity since late last year.

At this stage I would opt to remove both file and recipe.

**Comment by Popolechien** [comment]
@benoit74 Can you please delete https://download.kiwix.org/zim/other/wikiwel_en_all_nopic_2018-10.zim and https://download.kiwix.org/zim/other/wikiwel_en_all_maxi_2018-10.zim

**Comment by benoit74** [comment]
Done, files have been removed, library will update soon.

I however don't get why:
- we delete ZIMs with content which is almost "always-green" (the knowledge embedded is not much changing) ; even if the content cannot be updated anymore, I don't feel like this is a valid reason to delete the ZIMs
- we do not have a ticket on mwoffliner asking for help about the 403 error (it does not look like it was a usual error)

**Comment by Popolechien** [comment]
I think the word is "evergreen". Generally speaking I'd agree with you (and I think we do, in fact, have a bunch of evergreen content), but in the case at hand if you clicked around there were a bunch of pages missing so the zim file wasn't really fit for consumption.
