### ISSUE TITLE
AimHi playlists recipe

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#575]
[the recipe](https://farm.openzim.org/recipes/aimhi_playlists/config) for the `AimHi` youtube playlists is incorrect:

Meta | Value
-- | --
playlists-description | `The nature-first, curiosity-powered online school for ages 8-18`
playlists-name | `aimhi_en_-{title}`
playlists-title | `AimHi`
playlists-zim-file | `aimhi_en_{slug}_{period}`

- All ZIM files (one for each playlist) will have the very same Title and Description. [pretty useless](https://library.kiwix.org/?lang=&category=&q=AimHi)
- Filenames are good 👍 
- `Name` metadata is wrong. It should use the `{slug}` as well.

**Comment by Popolechien** [comment]
@rgaudin So wat should the fix be? Create a recipe for each separate playlist? Or simply add the `{slug}` to the `Playlist Name` field (ie from `aimhi_en_-{title}` to `aimhi_en_-{title}-{slug}` or.. ?)

**Comment by rgaudin** [comment]
Well, for title and description, I'd go with the obvious `{title}` and `{description}`. But maybe you want a prefix or something else.

For the name, you need to figure out a format that is both compliant with our convention and easy to infer for all the YT playlists recipes you have.

`aimhi-playlists_en_{slug}` could work for instance but is this channel popular enough to deserve an `aimhi` identifier? For instance, you Khan videos have names like `khan-academy-videos_en_playlist-PL301908982CBFE20D`

Please figure something out and document it somewhere… then maybe open a ticket to update all such recipes.

**Comment by rgaudin** [comment]
Maybe we should schedule a call with @kelson42 about that and rediscuss maybe a Tag for video-based ZIM files: at least for YT and TED.

**Comment by RavanJAltaie** [comment]
The Playlists don't exist anymore on youtube, recipe deleted as per https://github.com/openzim/zim-requests/issues/770
