### ISSUE TITLE
Youscribe recipes

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#577]
Youscribe ZIMs have incorrect `Name` that lacks the language code.

[recipes](https://farm.openzim.org/recipes?name=youscribe)

I checked _college recipe and the name is fixed in recipe. Probably fixed after ZIM was created (and later renamed). Can someone verify that all 4 recipes have correct name and relaunch them?

**Comment by RavanJAltaie** [comment]
Checked, all names has language in the recipes.
Relaunched as well.
