### ISSUE TITLE
Text of links on ArchWiki max is not shown

### ISSUE THREAD

**Issue by materia-nigra** [openzim/zim-requests#580]
The text of (packages AFAIK) links are missing. Example on iOS: 
[https://wiki.archlinux.org/title/Security#File_encryption](https://wiki.archlinux.org/title/Security#File_encryption)
The words `p7zip`, `zip`, and `age` are not shown. Even though external URL redirection might not be an expected functionality of Kiwix, the simple absence of important words inside text cripple the reading experience.

**Comment by RavanJAltaie** [comment]
@materia-nigra I've tested the link and all the text in packages and other sections are working fine.
Could you please confirm if the issue still exist at your side?
