### ISSUE TITLE
New  request: Free Software Directory

### ISSUE THREAD

**Issue by ToeushiMWYKaesai** [openzim/zim-requests#581]
- Website URL: https://directory.fsf.org
- License: **[GFDL](https://static.fsf.org/nosvn/directory/fdl-1.3-standalone.html)** 
- Desired ZIM Title: **Free Software Directory**
- Desired ZIM Description: **Directory of Free Software**
- Desired ZIM Icon –png (URL or attach one): https://directory.fsf.org/favicon.ico
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by tim78245** [comment]
duplicate #473

**Comment by RavanJAltaie** [comment]
Duplicate of #473
