### ISSUE TITLE
Failed wikivoyage (English) run - please restart

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zim-requests#585]
The `wikivoyage_en` run failed after 14 mins on 21/03. Debug log is here: https://farm.openzim.org/pipeline/c1bb61950ab575c9568b9146/debug

Could the run be re-started, please, so that the Wikivoyage packaged apps can be updated this month?

**Comment by Popolechien** [comment]
Requested

**Comment by Jaifroid** [comment]
Oops, failed again after two minutes in pipe: https://farm.openzim.org/pipeline/ad8c211235f7a2285ef7d146. Maybe there is a bigger issue? @kelson42 are you aware of anything?

**Comment by Jaifroid** [comment]
@Popolechien We still don't have a full English Wikivoyage for March 2023 due to the recipe having failed twice. Third time lucky?

**Comment by Jaifroid** [comment]
You were right... Failed again. @kelson42 Any idea why Wikivoyage English is failing (three times in a row after a short time in the pipe), whereas Wikivoyage Italian succeeded 3 hours ago? Latest debug log is here: https://farm.openzim.org/pipeline/ba5731f000770990da771246/debug. I took a look at the downloadable log, and all I could find was as follows (and I don't know whether that is informative):
```
Failed to run mwoffliner after [1522s]: {
	"message": "Request failed with status code 403",
	"name": "AxiosError",
	"stack": "AxiosError: Request failed with status code 403\n    at settle (file:///tmp/mwoffliner/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:548:11)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1344:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
```
