### ISSUE TITLE
Creating a Zim file for FreeCodeCamp

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#589]
Could you please create the zim file for FreeCodeCamp, the information are mentioned below?

Website URL: https://www.freecodecamp.org/
License: Free & Open source - (501(c)(3) public charity
Desired ZIM Title: freecodecamp
Desired ZIM Description: Learn to code for free, Build projects, Earn certifications.
Desired ZIM Icon –png (URL or attach one): 
Language (ISO 639-3): eng
Is this a MediaWiki?: no

**Comment by Rexadev** [comment]
@Popolechien updates ?

**Comment by Popolechien** [comment]
@Rexadev See repo I pointed at earlier. One PR being reviewed I see.

**Comment by Rexadev** [comment]
@Popolechien why this site needs dedicated repo
