### ISSUE TITLE
Add "Survivor Library" to the Kiwix Library

### ISSUE THREAD

**Issue by gordon-matt** [openzim/zim-requests#590]
- Website URL: http://www.survivorlibrary.com/library-download.html
- License: Public domain (As noted in their [FAQs page](http://www.survivorlibrary.com/faqs.html))
- Desired ZIM Title: Survivor Library
- Desired ZIM Description:

The Library in it’s entirety is a compendium of the Technological and Industrial Knowledge of the 1800s through early 1900s. It is the knowledge needed to rebuild a technological and industrial infrastructure from scratch when the modern infrastructure ceases to function.

- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
A recipe has been created and discussed in #1130 - closing this one as duplicate.
