### ISSUE TITLE
New  request: CIA the-world-factbook

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#592]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.cia.gov/the-world-factbook/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **My title**
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes | no**

**Comment by RavanJAltaie** [comment]
Recipe created, however in your upcoming requests please fill up the required information
Logo: https://commons.wikimedia.org/wiki/File:The_World_Factbook_emblema.svg
Title: CIA The World Factbook

**Comment by RavanJAltaie** [comment]
Here is the recipe
https://farm.openzim.org/recipes/theworldfactbook_en_all

**Comment by Rexadev** [comment]
@RavanJAltaie  Not in library yet https://library.kiwix.org/?lang=&q=CIA

**Comment by RavanJAltaie** [comment]
The recipe succeeded and the file is ready in the library
https://library.kiwix.org/viewer#theworldfactbook_en_all_2023-05
