### ISSUE TITLE
New request: mutopiaproject.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#598]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.mutopiaproject.org/
- License: **Public domain**
- Desired ZIM Title: **Mutopia Project**
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Rexadev** [comment]
https://farm.openzim.org/recipes/mutopiaproject.org_en

**Comment by RavanJAltaie** [comment]
I've placed a ticket to investigate the failure
https://github.com/openzim/zimit/issues/200
