### ISSUE TITLE
[Recipe created] openscore.cc

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#599]
- Website URL: https://openscore.cc/
- License: **Public domain**
- Desired ZIM Title: **OpenScore**
- Desired ZIM Description: Sheet Music
- Desired ZIM Icon –png (URL or attach one): 
![image](https://github.com/openzim/zim-requests/assets/62152714/a3e2eeb9-6e02-4bdd-bfdb-56a7230e5118)
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Rexadev** [comment]
@RavanJAltaie updates ?

**Comment by Rexadev** [comment]
@RavanJAltaie updates ?

**Comment by Rexadev** [comment]
@RavanJAltaie fixed the request

**Comment by Rexadev** [comment]
@RavanJAltaie fixed it

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/openscore.cc_en_all

**Comment by Popolechien** [comment]
yeah it look like this is just a generic information website and the actual sheet music is at [musescore.com](https://musescore.com/OpenScore)

**Comment by Rexadev** [comment]
@Popolechien you may close this request
