### ISSUE TITLE
make zim of catalogueoflife.org

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#60]
_From @amirh123123 on March 6, 2018 5:9_

hi please make zim file for catalogueoflife.org

_Copied from original issue: openzim/mwoffliner#207_

**Comment by RavanJAltaie** [comment]
Rejected
The License: COL Checklist 2022-11-14 [doi:10.48580/dfqj](https://doi.org/10.48580/dfqj)
© 2020, Species 2000. This online database is copyrighted by Species 2000 on behalf of the Catalogue of Life partners.

**Comment by ssj10ssj** [comment]
似乎是Creative Commons Attribution 4.0 International License在网页底下。

除了 https://www.catalogueoflife.org/ ，”物种2000”（ http://www.sp2000.org.cn/ ）的其他内容也值得kiwix确认一下，似乎有给申请途径的。
