### ISSUE TITLE
New request: cpdl.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#601]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.cpdl.org/wiki/index.php/Main_Page
- License: **Public domain**
- Desired ZIM Title: **ChoralWiki**
- Desired ZIM Description: **Choral Public Domain Library**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/choral_wiki_en
I'll update the library file once ready
