### ISSUE TITLE
New request: Library of Congress (USA) loc.gov

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#603]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.loc.gov/
- License: **Public domain**
- Desired ZIM Title: **Library of Congress (USA)**
- Desired ZIM Description: ****
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

Can also do parts like
https://www.loc.gov/notated-music/
http://memory.loc.gov/ammem/index.html
https://www.loc.gov/collections/american-sheet-music-1870-to-1885/about-this-collection/

**Comment by Rexadev** [comment]
@RavanJAltaie ping

**Comment by RavanJAltaie** [comment]
it involves a big search engine, it will fail and needs a dedicated scrapper to be built
