### ISSUE TITLE
[Completed] MusicEditions by ChristophDalitz

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#606]
- Website URL: http://music.dalitio.de/
- License: Public domain
- Desired ZIM Title: Music Editions by Christoph Dalitz
- Desired ZIM Description: Sheet Music
- Desired ZIM Icon –png (URL or attach one): 
![image](https://github.com/openzim/zim-requests/assets/62152714/16ee66eb-cc2d-4c35-9267-02738c6d45bf)
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
@Rexadev please add the description and title

**Comment by Rexadev** [comment]
@RavanJAltaie fixed it

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/music.dalitio.de_en_all
I'll update the library link once ready

**Comment by Rexadev** [comment]
@RavanJAltaie You may close this, file in library now

**Comment by Rexadev** [comment]
@RavanJAltaie Edit title to `music.dalitio.de Music Editions by Christoph Dalitz - ShhetMusic for Intruments (Lute,Guitar,Recorder,violin,Oboe,basso continuo with basso continuo without etc.) and Voice (Two part mixed choir, 3 part mixed choir, 4 part mixed choir, 5 part mixed choir, Women's choir, Men's choir, 1 solo voice, 2 solo voices Mass settings and individual mass parts) in Genres (Psalms and canticles, Passions, Hymns, Motets, Prayers, Chorale settings, Secular songs and madrigals)`

**Comment by RavanJAltaie** [comment]
Library Link
https://library.kiwix.org/viewer#music.dalitio.de_en_all_2024-08
@Rexadev title can't be more than 30 characters.

**Comment by Rexadev** [comment]
@RavanJAltaie Edit description to `Sheet Music for Instruments (Lute,Guitar,Recorder,violin,Oboe,basso continuo with basso continuo without etc.) and Voice (Two part mixed choir, 3 part mixed choir, 4 part mixed choir, 5 part mixed choir, Women's choir, Men's choir, 1 solo voice, 2 solo voices Mass settings and individual mass parts) in Genres (Psalms and canticles, Passions, Hymns, Motets, Prayers, Chorale settings, Secular songs and madrigals)`

**Comment by RavanJAltaie** [comment]
@Rexadev Description can't be more than 80 characters.
