### ISSUE TITLE
New  request: golden.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#614]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://golden.com
- License:  [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)
- Desired ZIM Title: **Golden.com**
- Desired ZIM Description: **Golden uses machine intelligence to build a self-constructing knowledge base. The platform contains canonical information describing entities (sometimes referred to as topic pages) and allows users to create, contribute, and compare knowledge by utilizing a set of AI-based tools. AI-assisted editing allows users to automatically extract summaries and infobox data from external web-based sources, and AI-based suggestions enable users to make quick, modular updates to topics. Golden uses clusters to group related topics. Clusters include [Blockchain & cryptocurrency](https://golden.com/wiki/Blockchain_and_cryptocurrency-8AR86E6), [Cell-based and plant-based meat](https://golden.com/wiki/Cell-based_and_plant-based_meat-EAVZ5V8), [Synthetic biology](https://golden.com/wiki/Synthetic_biology-8AR8ZAX), [Stem cell technology](https://golden.com/wiki/Stem_cell_technology-JNZXAA6), [COVID-19](https://golden.com/wiki/COVID-19-ZXJX9AR), and [Biotechnology](https://golden.com/wiki/Biotechnology-39P6B95). Each cluster contains links to hundreds of topic pages.**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: No

**Comment by RavanJAltaie** [comment]
Websites with search engines are failing in the offliner scrapper.
This is invalid.
