### ISSUE TITLE
New  request: https://en.everybodywiki.com/Everybodywiki:Welcome

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#617]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.everybodywiki.com/Everybodywiki:Welcome
- License: **Creative Commons | Public domain | ...**
- Desired ZIM Title: **EverybodyWiki **
- Desired ZIM Description: **Everybodywiki tries to save articles which are currently marked for deletion on [Wikipedia](https://en.wikipedia.org/). We have many of the same features, such as [VisualEditor](https://en.wikipedia.org/wiki/VisualEditor) and we are optimized for viewing from mobile devices.**
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/everybodywiki_en_all

Will update the library link once succeeded

**Comment by Rexadev** [comment]
Not here https://library.kiwix.org/?q=everybodywiki.com
