### ISSUE TITLE
New request: Wikipedia without trash

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#618]
Wikipedia without low importance articles like 

1. Without articles about specific films but still having articles like https://en.wikipedia.org/wiki/Film. Some films maybe be more important if they are related to another Topic of greater importance like War movies, history, documentary , etc
Also See - 
https://en.wikipedia.org/wiki/Category:Hindi_cinema
https://en.wikipedia.org/wiki/Category:Cinema_of_the_United_States

2. Without articles about specific songs or albums or artists but still having articles about genres

3.  Without articles about specific Video games

**Comment by Popolechien** [comment]
@Rexadev Hmm, there's a granularity of curation here that we cannot provide. Best we (or you) could do would be to try the Wikipedia on demand tool: http://wp1.openzim.org/ ([documentation here](https://wp1.readthedocs.io/en/latest/))
