### ISSUE TITLE
Create Zim File for Barmaga.io

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#620]
Please create a zim file for barmaga.io

- Website URL: https://barmaga.io/
- License: Open source
- Desired ZIM Title: barmaga.io
- Desired ZIM Description: برمجة بالعربي (والأمهري والسواحيلي)
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): multiple languages (Arabic, Swahili & Amharic)
- Is this a MediaWiki?:  no

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/barmaga.io

**Comment by rgaudin** [comment]
@RavanJAltaie makes no sense to create a single recipe for this if it offers multiple languages…
Also, most of the content is not publicly available and requires to be logged-in.
Last, I see an `exclude` option in the recipe and a `behaviorTimeout`. Are those set on purpose ? If not, don't set it.

**Comment by RavanJAltaie** [comment]
@rgaudin noted.
Contacted the website owners, will update it here once having a response.

**Comment by RavanJAltaie** [comment]
@rgaudin I've sent your the account credentials in slack

**Comment by rgaudin** [comment]
Why is this not in dev? Has this been successfully tested in dev first? I doubt it as I can't seen videos.

We currently don't support website behind a login wall but the crawler supports it (to some extent). We could add support for this into zimit/zimfarm but:
- are we sure we are allowed to publish a ZIM file with this content?
- Is is worth it? Most of the courses are video playlists. Most of them are on YT so we could create YT recipes (a few are on vimeo though).

**Comment by RavanJAltaie** [comment]
Yes, the content is good for Arabic speakers, agreed by @Popolechien that's why recipe moved to main library.
Can we do the Crawler support?

**Comment by RavanJAltaie** [comment]
Moved to hidden/dev library, and recipe disabled
