### ISSUE TITLE
Recipes with too-long descriptions

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#621]
The following recipes have descriptions over the recommended 80 chars length.

Please note that this does not include the dynamic descriptions we have for individual ZIMs in _multi_ ted and youtube recipes

| Schedule | Field name | Length | Value |
| --- | --- | --- | --- |
| [`wikiversity_fr`](https://farm.openzim.org/recipes/wikiversity_fr) | `customZimDescription` | 201 | Wikiversité est un projet visant à produire et diffuser des documents pédagogiques (cours, exercices, travaux dirigés, etc.) pour à chacun d'apprendre ou réapprendre de façon la plus autonome possible. |
phet
| [`mawsouaa_ar_all`](https://farm.openzim.org/recipes/mawsouaa_ar_all) | `customZimDescription` | 133 | الموسوعة التونسية المفتوحة التي وإلى الإحاطة بكل روافد الثقافة والحضارة التونسيين تاريخا وجغرافيَا، فنّا وأدبا وعلما، شخصيات ومؤسسات. |
| [`scoopyendirectducorpshumain`](https://farm.openzim.org/recipes/scoopyendirectducorpshumain) | `description` | 84 | Scoopy, la première bactérie reporter, enquête sur le fonctionnement du corps humain |
| [`jaimelire`](https://farm.openzim.org/recipes/jaimelire) | `description` | 92 | 12 histoires à lire et/ou écouter depuis les collections J'aime lire et Planète J'aime lire. |
| [`mesptitspourquoi`](https://farm.openzim.org/recipes/mesptitspourquoi) | `description` | 88 | 26 vidéos pour répondre simplement aux questions des 4-6 ans sous forme de dessin animé. |
| [`poesies`](https://farm.openzim.org/recipes/poesies) | `description` | 91 | Apprendre à lire c’est aussi apprendre à jouer avec les mots, leur consonance, les lettres… |
| [`laboh`](https://farm.openzim.org/recipes/laboh) | `description` | 111 | Rendre les sciences à portée de tous, grâce à des expériences engageantes et faciles à faire chez soi. (Bayard) |
| [`disledansmalangue`](https://farm.openzim.org/recipes/disledansmalangue) | `description` | 114 | Sur la base d'un mot-clé, l’enfant découvre une langue africaine et ouvre son esprit à d’autres cultures. (Bayard) |
| [`experiencesscientifiques`](https://farm.openzim.org/recipes/experiencesscientifiques) | `description` | 85 | Expliquer de façon ludique les phénomènes naturels par le biais d’expériences simples |
| [`bayardcuisine`](https://farm.openzim.org/recipes/bayardcuisine) | `description` | 104 | Dans ces vidéos à visionner en famille, garçons et filles, préparent des recettes d’Afrique et du monde. |
| [`lesptitsphilosophes`](https://farm.openzim.org/recipes/lesptitsphilosophes) | `description` | 164 | Les aventures des « p’tits philos » qui accompagnent les enfants de maternelle dans leurs toutes premières interrogations existentielles et philosophiques. (Bayard) |
| [`zaya-english-duniya-marathi`](https://farm.openzim.org/recipes/zaya-english-duniya-marathi) | `description` | 87 | ज़ाया इंग्लिश दुनिया मराठी - हा मराठी भाषिकांसाठी इंग्रजी शिकण्याचा एक मजेदार मार्ग आहे |
| [`mooc-energie-climat`](https://farm.openzim.org/recipes/mooc-energie-climat) | `description` | 88 | Donner à tout le monde le moyen de s'emparer de ces enjeux pour en parler autour de soi. |
| [`phzh_core-dari-one`](https://farm.openzim.org/recipes/phzh_core-dari-one) | `description` | 111 |  این کرس قدم به قدم یک برنامه ارتقا مهارت های زندگی ارائه میدهد برای افراد بی جا شده و همچنین برای باقی افراد.  |
| [`minecraft_fandom_de_all`](https://farm.openzim.org/recipes/minecraft_fandom_de_all) | `customZimDescription` | 111 | Das offizielle Minecraft Wiki mit hilfreichen und ausführlichen Informationen zu dem Open-World-Spiel Minecraft |
| [`wikihow_fr_maxi`](https://farm.openzim.org/recipes/wikihow_fr_maxi) | `description` | 91 | wikiHow est un recueil universel de guides simples, aussi appelés How-to («Comment faire»). |
| [`pink_pookie`](https://farm.openzim.org/recipes/pink_pookie) | `description` | 135 | Un ensemble de ressources destinées aux enseignants pour la sensibilisation des 9-14 ans au droit d'auteur et licences Creative Commons |
| [`zimgit-post-disaster_en`](https://farm.openzim.org/recipes/zimgit-post-disaster_en) | `description` | 116 | A collection of post-disaster resources (Food, water, shelter, medicine, etc.). Order a preloaded card at zimgit.com |
| [`deployed-medicine`](https://farm.openzim.org/recipes/deployed-medicine) | `description` | 141 | Deployed Medicine is a platform used by the Defense Health Agency aimed at improving readiness and performance of deployed medical personnel. |
| [`zimgit-food-preparation_en`](https://farm.openzim.org/recipes/zimgit-food-preparation_en) | `description` | 97 | A collection of recipes and techniques for preparing food with limited equipment or in the field. |
| [`penser-critique`](https://farm.openzim.org/recipes/penser-critique) | `description` | 781 | Ce site offre une sélection de ressources destinées à servir les membres du monde éducatif désireux d’aider les jeunes à aiguiser leur esprit critique et se protéger de la désinformation. La curation de contenu s’adresse a priori aux enseignants, animateurs en maison de jeunes, etc., tout en restant suffisamment généraliste pour être ouverte à tous. L’objectif du site est de présenter ces ressources classées par thématique de façon à ce que d’une part la communauté éducative (mais pas que) puisse y trouver des sources d’inspiration pour des activités pédagogiques et, d’autre part, que les étudiants puissent y trouver des ressources pour leurs travaux. Sans oublier les citoyens lambda qui ont simplement envie de développer leurs compétences en auto-défense intellectuelle. |
| [`maison-des-maternelles`](https://farm.openzim.org/recipes/maison-des-maternelles) | `description` | 136 | Du test de grossesse à la première rentrée des classes, La Maison Des Maternelles accompagne les parents avec un site dédié 100% vidéo ! |
| [`wikipedia_for_schools_ar`](https://farm.openzim.org/recipes/wikipedia_for_schools_ar) | `customZimDescription` | 446 | ويكيبيديا للمدارس: هي عبارة عن مجموعة منتقاة من مقالات ويكيبيديا موجهة للاستخدام في الفصول الدراسية الابتدائية والثانوية غير المتصلة بالإنترنت. لقد تم تنسيقها لتكون مصدراً تعليمياً تعزز المعرفة المعلوماتية والمهارات الرقمية والبحثية في المجتمعات النائية والريفية وغير المتصلة بالإنترنت على مستوى العالم. يحتوي هذا الإصدار من ويكيبيديا للمدارس على مقالات باللغة العربية والذي تم تنسيقه بواسطة سولارسبيل، وهي مبادرة تعليمية في جامعة ولاية أريزونا . |
| [`ncatlab`](https://farm.openzim.org/recipes/ncatlab) | `description` | 255 | A wiki on Mathematics, Physics, and Philosophy — especially, but far from exclusively, from the n-point of view: with a sympathy towards the tools and perspective of higher algebra, homotopy theory, type theory, category theory and higher category theory. |
| [`us_code`](https://farm.openzim.org/recipes/us_code) | `description` | 236 | The United States Code is a consolidation and codification by subject matter of the general and permanent laws of the United States. It is prepared by the Office of the Law Revision Counsel of the United States House of Representatives. |
| [`bookdash_en_all`](https://farm.openzim.org/recipes/bookdash_en_all) | `description` | 209 | Library of 150+ free picturebooks for read-aloud to young children, or early readers featuring diverse characters, available in a variety of South African languages including English and wordless picturebooks. |
| [`oer4schools`](https://farm.openzim.org/recipes/oer4schools) | `description` | 160 | The OER4Schools programme is a teacher professional development programme utilizing information and communication technologies, focussing on sub-Saharan Africa. |
| [`opensuse_documentation`](https://farm.openzim.org/recipes/opensuse_documentation) | `customZimDescription` | 99 | Documentation for the openSUSE Linux distribution for both system administrators and desktop users. |
| [`openzim`](https://farm.openzim.org/recipes/openzim) | `customZimDescription` | 88 |  The openZIM project proposes offline storage solutions for content coming from the Web. |
| [`mediawiki`](https://farm.openzim.org/recipes/mediawiki) | `customZimDescription` | 94 | MediaWiki is a collaboration and documentation platform brought to you by a vibrant community. |
| [`music_fandom_en_all`](https://farm.openzim.org/recipes/music_fandom_en_all) | `customZimDescription` | 81 | Definitive music encyclopedia, encompassing all aspects music and related topics. |
| [`strategywiki`](https://farm.openzim.org/recipes/strategywiki) | `customZimDescription` | 102 | A collaborative and freely-licensed wiki for all your video game strategy guide and walkthrough needs! |
| [`military_wiki`](https://farm.openzim.org/recipes/military_wiki) | `customZimDescription` | 82 | Military Wiki, the World's largest, free, interactive online Military encyclopedia |
| [`encyclopediaofmath`](https://farm.openzim.org/recipes/encyclopediaofmath) | `customZimDescription` | 115 | The Encyclopedia of Mathematics wiki is an open access resource designed specifically for the mathematics community |
| [`the_cutting_room_floor`](https://farm.openzim.org/recipes/the_cutting_room_floor) | `customZimDescription` | 326 | The Cutting Room Floor is a site dedicated to unearthing and researching unused and cut content from video games. From debug menus, to unused music, graphics, enemies, or levels, many games have content never meant to be seen by anybody but the developers — or even meant for everybody, but cut due to time/budget constraints. |
| [`dolphin_emulator_wiki`](https://farm.openzim.org/recipes/dolphin_emulator_wiki) | `customZimDescription` | 134 | Dolphin is an open-source emulator for the Nintendo GameCube and Wii with support for Microsoft Windows, Linux, Mac OS X, and Android. |
| [`winehq_wiki`](https://farm.openzim.org/recipes/winehq_wiki) | `customZimDescription` | 110 | The WineHQ Wiki is a repository of both end-user and developer documentation for the Open-Source Wine Project. |
| [`imslp`](https://farm.openzim.org/recipes/imslp) | `customZimDescription` | 134 | International Music Score Library Project (IMSLP) also called Petrucci Music Library, is digital library of public-domain music scores |
| [`blockly_games`](https://farm.openzim.org/recipes/blockly_games) | `description` | 241 | Blockly Games is a series of educational games that teach programming. It is designed for children who have not had prior experience with computer programming. By the end of these games, one is ready to use conventional text-based languages. |
| [`core_knowledge`](https://farm.openzim.org/recipes/core_knowledge) | `description` | 125 | Core Knowledge Foundation publishes educational books and materials and supports a growing network of Core Knowledge schools. |
| [`openlibrary.org`](https://farm.openzim.org/recipes/openlibrary.org) | `description` | 109 | Open Library is an open, editable library catalog, building towards a web page for every book ever published. |
| [`globalnames.org_en`](https://farm.openzim.org/recipes/globalnames.org_en) | `description` | 207 | The Global Names Architecture (GNA) is a system of web-services which helps people to register, find, index, check and organize biological scientific names and interconnect on-line information about species. |
| [`websters1913`](https://farm.openzim.org/recipes/websters1913) | `description` | 85 | Connoisseur's reference to American English - a dictionary for writers and wordsmiths |
| [`mitscratch`](https://farm.openzim.org/recipes/mitscratch) | `description` | 95 | Scratch is the world's largest free coding community for kids. Your support makes a difference. |
| [`mankier`](https://farm.openzim.org/recipes/mankier) | `description` | 97 | ManKier is a collection of man pages, translated from the their original troff to semantic HTML5. |
| [`practical_action`](https://farm.openzim.org/recipes/practical_action) | `description` | 103 | Practical Action with access to the right technical knowledge, people in poverty can change their world |
| [`minecraft_fandom_en_all`](https://farm.openzim.org/recipes/minecraft_fandom_en_all) | `customZimDescription` | 278 | Minecraft is a sandbox construction video game developed by Mojang Studios where players interact with a fully modifiable three-dimensional environment made of blocks and entities. Its diverse gameplay lets players choose the way they play, allowing for countless possibilities. |
| [`memory_alpha_fandom_en_all`](https://farm.openzim.org/recipes/memory_alpha_fandom_en_all) | `customZimDescription` | 91 | Memory Alpha is a free Star Trek reference database written collaboratively by its readers. |
| [`madrasa`](https://farm.openzim.org/recipes/madrasa) | `description` | 156 | منصّة تعليمية إلكترونية وتوفِّر محتوى تعليمياً متميزاً باللغة العربية في كافة مواد العلوم والرياضيات، ومتاحة مجاناً لأكثر من 50 مليون طالب عربي أينما كانوا. |
| [`prunelle_contes_africains`](https://farm.openzim.org/recipes/prunelle_contes_africains) | `description` | 104 | Dans ces vidéos à visionner en famille, garçons et filles, préparent des recettes d’Afrique et du monde. |
| [`wordnet_en_all`](https://farm.openzim.org/recipes/wordnet_en_all) | `description` | 710 | WordNet® is a large lexical database of English. Nouns, verbs, adjectives and adverbs are grouped into sets of cognitive synonyms (synsets), each expressing a distinct concept. Synsets are interlinked by means of conceptual-semantic and lexical relations. The resulting network of meaningfully related words and concepts can be navigated with the browser. WordNet is also freely and publicly available for download. WordNet's structure makes it a useful tool for computational linguistics and natural language processing.When writing a paper or producing a software application, tool, or interface based on WordNet, it is necessary to properly cite the source. Citation figures are critical to WordNet funding. |

**Comment by RavanJAltaie** [comment]
All fixed!
