### ISSUE TITLE
Delete Fipeco zim file

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#623]
https://download.kiwix.org/zim/zimit/fipeco_2023-03.zim

Just tested it and only the front page is available (I've restarted the recipe under dev.library)

**Comment by rgaudin** [comment]
Recipe is wrong. It uses a `custom` value for `scopeType` but doesn't specify the include/exclude…

**Comment by rgaudin** [comment]
> @rgaudin should I change to `not set`?

Yes ; at least unless you know why you want to change it

**Comment by rgaudin** [comment]
Removed

**Comment by rgaudin** [comment]
Also, the `Name` metadata is incorrect. It has no language nor period. This is **a lot of errors for a single recipe**

**Comment by Popolechien** [comment]
I think it's fixed now (I copied from the Postillon and Manioc recipes, which weren't mine). I've restarted the run.
