### ISSUE TITLE
Prunelle

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#625]
Files in repo https://drive.farm.openzim.org/_admin/#/prunelle
There are six .zip files will all epubs and pdf, and six xlsx files

Not sure if this has an impact but when I unpack the zip files they take on another name (usually `français` or `english`)

**For all files:**
Banner: [book_prunelle_long_logo_black.png](https://drive.farm.openzim.org/prunelle/book%20prunelle%20long%20logo%20black.png)
Logo: [book_prunelle_square.png](https://drive.farm.openzim.org/prunelle/book%20prunelle%20square.png)

**Book title :** Auteurs en herbe (Prunelle)
**Description:** Imprimez et écrivez votre histoire!
**language:** fra
**.xls:** [auteurs_en_herbe.xlsx](https://drive.farm.openzim.org/prunelle/auteurs%20en%20herbe.xlsx)
**files:** [auteurs_en_herbe.zip](https://drive.farm.openzim.org/prunelle/auteurs%20en%20herbe.zip)

**Book title :** Contes africains à illustrer (Prunelle)
**Description:** Imprimez et racontez vos propres histoires
**language:** fra
**.xls:** [contes_africains_a_illustrer.xslx](https://drive.farm.openzim.org/prunelle/contes%20africains%20%C3%A0%20illustrer.xlsx)
**files:** [contes_africains_a_illustrer.zip](https://drive.farm.openzim.org/prunelle/contes_africains_a_illustrer.zip)

**Book title :** Prunelle
**Description:** Histoires pour enfants
**language:** fra
**.xls:** [livres_interactifs_prunelle.xlsx](https://drive.farm.openzim.org/prunelle/livres_interactifs_prunelle.xlsx)
**files:** [livres_interactifs_prunelle.zip](https://drive.farm.openzim.org/prunelle/livres_interactifs_prunelle.zip)

**Book title :** Budding authors
**Description:** Interactive books by Prunelle. Print and write your own story!
**language:** eng
**.xls:** [auteurs_en_herbe.xlsx](https://drive.farm.openzim.org/prunelle/auteurs%20en%20herbe.xlsx)
**files:** [auteurs_en_herbe.zip](https://drive.farm.openzim.org/prunelle/auteurs%20en%20herbe.zip)

**Book title :** Draw your African story
**language:** eng
**description:** Interactive books by Prunelle. Print and write your own story!
**xlsx:** [draw_your_african_story.xlsx](https://drive.farm.openzim.org/prunelle/draw%20your%20african%20story.xlsx)
**files:** [draw_your_african_story.zip](https://drive.farm.openzim.org/prunelle/draw%20your%20african%20story.zip)

**Book title:** Prunelle books
**language:** eng
**description:** Books for children
**.xls:** [prunelle_interactive_books.xlsx](https://drive.farm.openzim.org/prunelle/prunelle%20interactive%20books.xlsx)
**files:** [prunelle_interactive_books.zip](https://drive.farm.openzim.org/prunelle/prunelle%20Interactive%20books.zip)

**Comment by rgaudin** [comment]
I've uploaded all the JSON collections alongside. I suggest you look at them and maybe fix them as I've seen one with the same description for every entry

**Comment by Popolechien** [comment]
@rgaudin All descriptions were provided by the Prunelle folks, so it's their choice in the end. Question: will the special characters (e.g. `Diassigue le ca\u00efman et Gon\u00e9 l\u2019enfant`) will appear normally, or is this an artifact from the viewer or export?

**Comment by rgaudin** [comment]
Well, the Publisher of those ZIM is Kiwix… 

As for the characters, yes, this is the JSON encoding. There may be tools for that but you can use this shortcut in your terminal to check

```sh
alias jsonpp='python -c "import json; import pprint; import sys ; pprint.pprint(json.load(open(sys.argv[1], \"r\")))"'
jsonpp auteurs_en_herbe.json
```

**Comment by Popolechien** [comment]
@rgaudin Ok something is off, see https://dev.library.kiwix.org/viewer#prunelle_auteurs_en_herbe_fr_2023-05 where all PDF files return as `not found`
The description field is also absent, so I suspect something to do with special characters.

**Comment by rgaudin** [comment]
It is indeed an encoding problem: the `ç` passed to kiwix-serve when we click the link ends up being different than the one stored in the ZIM path. It's a nautilus issue now.

```diff
3c3
< full_url  : /content/prunelle_auteurs_en_herbe_fr_2023-05/files/Français (37)/Annabelle une fille a fleur de coeur .pdf
---
> full_url  : /content/prunelle_auteurs_en_herbe_fr_2023-05/files/Français (37)/Annabelle une fille a fleur de coeur .pdf
6c6
< request#  : 4
---
> request#  : 5
15d14
<  - referer : 'http://localhost:8080/content/prunelle_auteurs_en_herbe_fr_2023-05/home.html'
18c17
<  - sec-fetch-site : 'same-origin'
---
>  - sec-fetch-site : 'none'
24,25c23,24
< full_url: /content/prunelle_auteurs_en_herbe_fr_2023-05/files/Français (37)/Annabelle une fille a fleur de coeur .pdf
< url   : /content/prunelle_auteurs_en_herbe_fr_2023-05/files/Français (37)/Annabelle une fille a fleur de coeur .pdf
---
> full_url: /content/prunelle_auteurs_en_herbe_fr_2023-05/files/Français (37)/Annabelle une fille a fleur de coeur .pdf
> url   : /content/prunelle_auteurs_en_herbe_fr_2023-05/files/Français (37)/Annabelle une fille a fleur de coeur .pdf
31c30,31
< Failed to find files/Français (37)/Annabelle une fille a fleur de coeur .pdf
---
> Found files/Français (37)/Annabelle une fille a fleur de coeur .pdf
> mimeType: application/pdf
33c33
< httpResponseCode : 404
---
> httpResponseCode : 200
```

**Comment by rgaudin** [comment]
@Popolechien please redo the ZIMs. JSON files have been updated (normalized) and nautilus version bumped.

Regarding the _missing_ description ; use the `--show-description` option.
