### ISSUE TITLE
Recent Wiktionary ZIM files don't show a search bar

### ISSUE THREAD

**Issue by ghjm** [openzim/zim-requests#628]
I recently updated my offline copy of Wiktionary and found that it no longer offers a home button and search bar at the top of the page. This happens both in kiwix-serve and in Kiwix Desktop. I notice that the same problem exists at the hosted copy at [library.kiwix.org](https://library.kiwix.org/content/wiktionary_en_all_maxi_2023-02/A/Wiktionary:Offline). However, an older copy at [iiab.me](https://iiab.me/kiwix/wiktionary_en_all_maxi_2022-09/A/Wiktionary:Offline) doesn't have the issue. Other ZIM files don't have the issue, like the [Simple English Wiktionary at library.kiwix.org](https://library.kiwix.org/viewer#wiktionary_en_simple_all_maxi_2023-04/A/Wiktionary:Main_Page).

**Comment by kelson42** [comment]
@ghjm IMO, you are impacted by a double known weaknesses which are https://github.com/openzim/mwoffliner/issues/1803 and https://github.com/kiwix/kiwix-tools/issues/604. Both bugs have needed quite a bit of work and are fixed... bit none otpf them still officially released. Hopefully in the few next weeks. Thx for reporting and your patience.

**Comment by Jaifroid** [comment]
I think this is actually https://github.com/openzim/mwoffliner/issues/1803: the latest Wiktionary contains a script that breaks out of the iframe and overwrites the top page. This has been fixed in the dev version, and should roll out to Kiwix Serve soonish.
