### ISSUE TITLE
niwanetwork

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#63]
_From @amirh123123 on March 4, 2018 12:26_

hi please make zim files for niwanetwork.org

_Copied from original issue: openzim/mwoffliner#194_

**Comment by kelson42** [comment]
That might be doable... I should try. Licence seems OK. But I can not give a timeline.

**Comment by RavanJAltaie** [comment]
Rejected
The License: All original content found throughout this website is copyright © Nintendo Independent Wiki Alliance (NIWA) 2010-2022.
NIWA is in no way associated with Nintendo. In places where copyrighted Nintendo content is presented we do so with fair terms of use, whereby it is not used commercially for gain and where it does not impede Nintendo's right to sell the depicted material.
Furthermore the member wikis of NIWA are not bound by a single license. Therefore please refer to the individual wikis for their licensing and content duplication policies.
