### ISSUE TITLE
New  request: en.uesp.net

### ISSUE THREAD

**Issue by wolfweim** [openzim/zim-requests#630]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.uesp.net/
- License: Attribution-ShareAlike 2.5 License
- Desired ZIM Title: En_Uesp.zim
- Desired ZIM Description: "A collaborative source for all knowledge on the Elder Scrolls series since 1995"
- Desired ZIM Icon –png (URL or attach one): https://en.uesp.net/favicon.ico
- Language (ISO 639-3): eng
- Is this a MediaWiki?: Yes

**Comment by Popolechien** [comment]
duplicate of #595
