### ISSUE TITLE
ZIM wikipedia_de_all_maxi_2023-02 wrong link: Buch -> Books

### ISSUE THREAD

**Issue by JensKorte** [openzim/zim-requests#631]
In the ZIM file [wikipedia_de_all_maxi_2023-02](https://library.kiwix.org/viewer#wikipedia_de_all_maxi_2023-02/A/Benutzer:The_other_Kiwix_guy/Landing) the link "Buch" links to [Books](https://library.kiwix.org/content/wikipedia_de_all_maxi_2023-02/A/Books). I guess, the target should be Buch.

**Comment by RavanJAltaie** [comment]
@Popolechien any idea?

**Comment by kelson42** [comment]
I'm not even sure to understand the bug report!

Which link exactly? In which article?

**Comment by kelson42** [comment]
@Popolechien Please fix upstream on WPDE

**Comment by Popolechien** [comment]
Done.
