### ISSUE TITLE
Creating new Zim file for Boundless Courses 

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#642]
As a part of scouting Grey Box content, we need to create zim file for the details below:

Website URL: https://courses.lumenlearning.com/catalog/boundlesscourses
License: Creative Commons
Desired ZIM Title: Boundless Courses
Desired ZIM Description: Free educational content originally curated by Boundless.
Desired ZIM Icon –png (URL or attach one):
Language (ISO 639-3): eng
Is this a MediaWiki?: no

**Comment by kelson42** [comment]
In 2021, we already created a ZIM of Boundless, see https://library.kiwix.org/?lang=eng&category=&q=boundless. Wonder where is the recipe we used at that time!

**Comment by RavanJAltaie** [comment]
@kelson42 you are right.
I'm reviewing now against duplication.
I fixed the duplication for boundless content.

**Comment by kelson42** [comment]
> I fixed the duplication for boundless content.

How? I seems to me you have removed the two recipes.

**Comment by RavanJAltaie** [comment]
Re-created 
https://farm.openzim.org/recipes/boundless_courses_en_all

**Comment by kelson42** [comment]
@RavanJAltaie What happened? Recreated from which recipe? How do you secure it the same as the old recipe?

**Comment by RavanJAltaie** [comment]
@kelson42 I opened a new ticket to fix this #657
