### ISSUE TITLE
New  request: https://m.mediawiki.org

### ISSUE THREAD

**Issue by Bola197** [openzim/zim-requests#646]
- Website URL: https://m.mediawiki.org
- License: Creative Commons | Public domain 
- Desired ZIM Title: Library Education 
- Desired ZIM Description: Library studies 
- Desired ZIM Icon png:bfadeleye@gmail.com 
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
@Bola197 Mediawiki.org please remove your email address, point to the correct logo, and give a correct descriptor.

**Comment by Popolechien** [comment]
Recipe already exists (but has crashed). https://farm.openzim.org/recipes/mediawiki
