### ISSUE TITLE
New request: Tyap Wikipedia

### ISSUE THREAD

**Issue by amire80** [openzim/zim-requests#654]
- Website URL: https://kcg.wikipedia.org
- License: CC-BY-SA 3.0
- Desired ZIM Icon –png (URL or attach one): https://drive.farm.openzim.org/wikipedia_all/favicon-48x48.png
- Language (ISO 639-3): kcg
- Is this a MediaWiki?: yes

(Get the title and the description automatically from the Wikipedia metadata.)

[Comment: Created this at the Wikimedia Hackathon 2023 in Greece. I am testing how the adding of one new language works. IF this request works well, I'll make a proper procedure for all the future languages. I'll also add more languages in which Wikipedias already exist.]

**Comment by kelson42** [comment]
Recipe done at https://farm.openzim.org/recipes/wikipedia_kcg_all. We still need to update the Zimfarm for that language and then we should be good.
