### ISSUE TITLE
Boundless Courses missing recipe issue

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#657]
A while ago, I've created a duplicate zim file for Boundless courses with no attention to the existing file in the library.
When I noticed that, I tried to delete the new recipe in zimfarm but instead I've deleted the old recipe which lead to this file.
(https://dev.library.kiwix.org/viewer#courses.lumenlearning.com_en_all_2022-07/A/courses.lumenlearning.com/catalog/boundlesscourses)
The new recipe failed and resulted in a small size file.
I've learned from @Popolechien that there is a back up for deleted recipes.
So we need now to delete the duplicate file from the library (link is below)
(https://library.kiwix.org/viewer#boundless_courses_en_all_2023-05)
and bring back the old recipe.

The new failed recipe is still in the zimfarm but I disabled it.
https://farm.openzim.org/recipes/boundless_courses_en_all

I apologize for the inconvenience caused by this mistake.

**Comment by RavanJAltaie** [comment]
1- https://master.download.kiwix.org/zim/zimit/boundless_courses_en_all_2023-05.zim
2- May 11 2023
3- courses.lumenlearning.com_en_all

**Comment by rgaudin** [comment]
https://farm.openzim.org/recipes/courses.lumenlearning.com_en_all
