### ISSUE TITLE
Explain XKCD failing recipe

### ISSUE THREAD

**Issue by akshatj27** [openzim/zim-requests#658]
recipe exists, but is failing with error "Unable to find appropriate API end-point to retrieve article HTML"
Recipe link: https://farm.openzim.org/recipes/explain-xkcd
latest run: https://farm.openzim.org/pipeline/dbe67bc5-a69b-49b6-94be-08111f774d89

**Comment by Popolechien** [comment]
Confirm it only picks up the first page and not the images: https://library.kiwix.org/viewer#explainxkcd_en_all_maxi_2021-03/A/Main_Page

https://www.explainxkcd.com/wiki/index.php/Main_Page for reference.

**Comment by kelson42** [comment]
The remote wiki does not provide any API end-points to download (semantic) HTML. As a conseqeunce MWoffliner can not work. I will deactivate the recipe.
