### ISSUE TITLE
Best Educational Lessons

### ISSUE THREAD

**Issue by sgpopovich** [openzim/zim-requests#660]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://bestedlessons.org/
- License: **Creative Commons | Public domain |**
- Desired ZIM Title: **Best Ed Lessons for Primary, Middle, and High School Students **
- Desired ZIM Description: **All the best freely accessible learning and educational lessons, worksheets, activities, and textbooks are at your fingertips for easy viewing and downloading – for students, teachers, and homeschools.**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**
![Screenshot 2023-05-24 at 3 05 13 PM](https://github.com/openzim/zim-requests/assets/101420446/dd800d1f-033a-417b-b974-619891ab606a)

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/bestedlessons.org_en_all
Will update the library file link once ready
