### ISSUE TITLE
Best Education Lessons 

### ISSUE THREAD

**Issue by sgpopovich** [openzim/zim-requests#662]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://bestedlessons.org/
- License: **Creative Commons | Public domain | **
- Desired ZIM Title: **Best Ed Lessons**
- Desired ZIM Description: **Best Ed Lessons for Primary, Middle, and High School Students and Teachers**
- Desired ZIM Icon –png (URL or attach one): https://bestedlessons.org/
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by sgpopovich** [comment]
Sorry this may be a duplicate of issue 660 :( my bad

**Comment by kelson42** [comment]
Closing...
