### ISSUE TITLE
Various issues with GCF Global_en_all_2023-05

### ISSUE THREAD

**Issue by sgpopovich** [openzim/zim-requests#663]
When off-line, I am getting inconsistencies:

1) When I open the zim file in Kiwix sometime it views like a webpage and sometimes its format in a list on the left-hand side of the page.

2) When I open the zim file, on the main page I am getting a spinning wheel. I also get three spinning dots on the top right-hand side of the page

3) I am not able to view/play any of the videos - then after a while, they start playing - not sure why

4) I sometimes get the message "This page is not responding"

5) Main page - The Search and Topics button on top does not work

6) I select "Get Started with Computers", then "What is a computer", It asks me "What do I want to do with Downloadfile.jpeg" I download and place it in the same folder as the zim. It asks me this over and over again.

7) I always get splash screens that say "Opening External link" and "Downloads". Sometime I can not get them to close.

8) TOC at the bottom does not take you to the selected location. Then the TOC panel will not close.

**Comment by Popolechien** [comment]
@sgpopovich It would have been better to reopen the previous ticket (or comment in it anyway.

This being said, I suspect some of the issues you flag are reader rather than zim-specific. Can you please re-test on this version here: https://library.kiwix.org/viewer#edu.gcfglobal.org_en_all_2023-05/A/edu.gcfglobal.org/en/topics/ 

(and then if behaviour is indeed different, indicate which reader you were initially testing on, including version, OS, etc. etc.)

**Comment by sgpopovich** [comment]
> @sgpopovich It would have been better to reopen the previous ticket (or comment on it anyway).
> 
> This being said, I suspect some of the issues you flag are reader rather than Zim-specific. Can you please re-test this version here: https://library.kiwix.org/viewer#edu.gcfglobal.org_en_all_2023-05/A/edu.gcfglobal.org/en/topics/
> 
> (and then if the behavior is indeed different, indicate which reader you were initially testing on, including version, OS, etc., etc.)

@Popolechien, Sorry the link above does not lead to a new version. Am I missing something?

**Comment by Popolechien** [comment]
Zim Files served via Kiwix-server are considered as the benchmark. 
Having an issue here means there is a file-specific issue, whereas having it here fine and not on another platform means there is a platform-related issue.
I could not reproduce what you described on kiwix server, but then I don't know which pages you looked at. The key here is to be consistently able to reproduce problematic behaviour (and then figure out what went wrong)

**Comment by sgpopovich** [comment]
@Popolechien help me understand - what am I supposed to do with this link? It is not a ZIM file so I can not download it. Please explain. https://library.kiwix.org/viewer#edu.gcfglobal.org_en_all_2023-05/A/edu.gcfglobal.org/en/topics/

**Comment by Popolechien** [comment]
Kiwix-server is installed at library.kiwix.org and so reads and displays zim files (the better link could be https://library.kiwix.org/?lang=eng&q=gcf so you can see that this is the file ready for download). 

Eventhough you are browsing this online, it is for all intent and purpose the offline version that is being displayed (or if this is too confusing replace _offline_ with _archived_)
