### ISSUE TITLE
New request: update ויקישיבה

### ISSUE THREAD

**Issue by zevisvei** [openzim/zim-requests#664]
That's my request
Website URL: http://www.yeshiva.org.il/wiki/
Desired ZIM Title: wiki-yeshiva
Desired ZIM Description: פרוייקט האנציקלופדיה למושגי תורה ויהדות
Desired ZIM Icon –png (URL or attach one):
![image](https://github.com/openzim/zim-requests/assets/101482799/ae4aa90c-38bb-4ab4-b4eb-31d1ef3a22a5)

Language: עברית hebrew
Desired Main Page (homepage): http://www.yeshiva.org.il/wiki/
Thank you
[The original post of the request to prepare the zim file](https://github.com/openzim/zim-requests/issues/227)

**Comment by kelson42** [comment]
We already have a recipe to do this Web site at https://farm.openzim.org/recipes/yeshiva. But th upstream Website does not use Visual Editor, therefore we have no API end-point we can use to make the scraping. For the moment the recipe is disabled.
