### ISSUE TITLE
New request: https://en.wikipedia.org/wiki/History_of_Uganda

### ISSUE THREAD

**Issue by TitusSmiles** [openzim/zim-requests#665]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://xxx
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **My title**
- Desired ZIM Description: **Short description (80 characters or less)**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **abc**
- Is this a MediaWiki?: **yes | no**

**Comment by Popolechien** [comment]
We don't do Zim files of single articles and most if not all of the requested information is missing
