### ISSUE TITLE
Request: freestompboxes.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#668]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.freestompboxes.org/
- License: Can't find
- Desired ZIM Title: freestompboxes.org
- Desired ZIM Description: Guitar/Bass Amp & Pedal Circuits
- Desired ZIM Icon –png (URL or attach one): 
![image](https://github.com/openzim/zim-requests/assets/62152714/7d92910a-c671-47fb-bfdd-000b4edd4499)
![image](https://github.com/openzim/zim-requests/assets/62152714/daaee33e-6ee8-4230-bdb6-78cd341323bf)
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

**Comment by Rexadev** [comment]
> see #677

this site is not copyrighted

**Comment by Rexadev** [comment]
@Popolechien this site is not copyrighted

**Comment by Rexadev** [comment]
@Popolechien this site is not copyrighted

**Comment by Popolechien** [comment]
@Rexadev Happy to reopen the request but please do document your requests properly.

**Comment by Rexadev** [comment]
> @Rexadev Happy to reopen the request but please do document your requests properly.

done
@Rexadev @Popolechien

**Comment by Rexadev** [comment]
@Popolechien updates ?

**Comment by RavanJAltaie** [comment]
@Rexadev the size of logo is incorrect and licensee is missing

**Comment by Rexadev** [comment]
> @Rexadev the size of logo is incorrect and licensee is missing

The website has no info about licensee https://www.freestompboxes.org/ucp.php?mode=terms

**Comment by Rexadev** [comment]
@RavanJAltaie Why closed

**Comment by Rexadev** [comment]
@RavanJAltaie fixed the request
