### ISSUE TITLE
Tag « prepper » all ZIM dedicated to prepper thematic

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#669]
First thing, an inventory of all recipes should be done.

**Comment by Popolechien** [comment]
Here's the list:
[fas-military-medicine](https://farm.openzim.org/recipes/fas-military-medicine)

**Comment by Popolechien** [comment]
Couldn't find any other, but there's clearly some broader thinking re:tagging that needs to be done. Will discuss with @RavanJAltaie

**Comment by kelson42** [comment]
@Popolechien ZIM files have not been tags (most of them, because I have configure the tag for 2 of them). Think twice: you are confusing recipe tags and ZIM tags!

**Comment by Popolechien** [comment]
Pardon my French, but dafuq is the difference and why is there a difference?

**Comment by Popolechien** [comment]
Ok all recipes have tagged and restarted
