### ISSUE TITLE
The Military Learning Library

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#671]
- Website URL: http://the-military-learning-library.343.s1.nabble.com/
- License: **CC** (licensed via ticket https://kiwix.freshdesk.com/a/tickets/50789)
- Desired ZIM Title: **The Military Learning Library**
- Desired ZIM Description: Things that military professionals might like to read
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

Note: the website is an archive of sorts, so no need to set a refresh rate in the recipe.

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/military_library_en
Will post the library file link here once ready
