### ISSUE TITLE
New request: azlyrics.com )copyrighted material on copyrighted  site)

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#672]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: azlyrics.com 
- License: copyrighted material on copyrighted  site
- Desired ZIM Title: azlyrics.com 
- Desired ZIM Description: **Short description (80 characters or less)**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **abc**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
see #677
