### ISSUE TITLE
Bulbapedia update for 2023

### ISSUE THREAD

**Issue by blueandyellowtaco38** [openzim/zim-requests#673]
Please do a 2023 update of the bulbapedia wiki.

- Website URL: https://bulbapedia.bulbagarden.net/wiki
- License: Public domain
- Desired ZIM Title: bulbagarden_en_all_maxi_2023-06.zim
- Desired ZIM Description: From Bulbapedia, the community-driven Pokemon encyclopedia.
- Desired ZIM Icon –png (URL or attach one): https://archives.bulbagarden.net/media/upload/thumb/d/d4/Bulbapedia_bulb.png/60px-Bulbapedia_bulb.png
- Language (ISO 639-3): Eng
- Is this a MediaWiki?: yes

**Comment by kelson42** [comment]
@blueandyellowtaco38 Not possible (anymore, or for the moment) because the wiki does not have the necessary API enf-point (Visual Editor). The recipe is deactivated for the moment.
