### ISSUE TITLE
New request:  Zelda Wiki

### ISSUE THREAD

**Issue by justinweston1988** [openzim/zim-requests#674]
- Website URL: https://zelda.fandom.com/
- License: Creative Commons
- Desired ZIM Title: Zelda Wiki
- Desired ZIM Description: Zelda Wiki is a The Legend of Zelda encyclopedia that anyone can edit and is maintained by fans just like you
- Desired ZIM Icon –png (URL or attach one): https://static.wikia.nocookie.net/zelda_gamepedia_en/images/e/e6/Site-logo.png
- Language (ISO 639-3): eng
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/zelda_wiki_en
