### ISSUE TITLE
[Request] guitarcharts.net

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#675]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://guitarcharts.net/
- License: I can't see it on the website nor the owner info.
- Desired ZIM Title: guitarcharts.net
- Desired ZIM Description: 
- Desired ZIM Icon –png (URL or attach one): ![image](https://github.com/openzim/zim-requests/assets/62152714/0e1c33dc-02e6-4479-8bfe-3ecec62ab58c)
- Language (ISO 639-3): 
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Any place mentioning the license of this website?

**Comment by Rexadev** [comment]
> Any place mentioning the license of this website?

I can't see it on the website nor the owner info.

**Comment by Rexadev** [comment]
@RavanJAltaie not [Entertainment](https://github.com/openzim/zim-requests/labels/Entertainment) It is Educational

**Comment by RavanJAltaie** [comment]
We categorize any music related websites to Entertainment, I'll add label general information as well.

**Comment by RavanJAltaie** [comment]
@Rexadev I'll close this issue for now as you don't have enough info about the license.
Feel free to reopen it once you obtain the information.
