### ISSUE TITLE
[Request] merriam-webster.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#676]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.merriam-webster.com/
- License: 
- Desired ZIM Title: Merriam Webster
- Desired ZIM Description: Merriam Webster
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Merriam-Webster_logo.svg/1200px-Merriam-Webster_logo.svg.png
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
copyrighted content.
