### ISSUE TITLE
New request: healthline.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#677]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.healthline.com/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **My title**
- Desired ZIM Description: **Short description (80 characters or less)**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **abc**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
@Rexadev I'll be closing this request. You have been around long enough to know that the licensing, description and other fields need to be documented.
