### ISSUE TITLE
New request: Necyklopedie

### ISSUE THREAD

**Issue by Vuizur** [openzim/zim-requests#679]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://necyklopedie.org/
- License: **Creative Commons-Attribution-NonCommercial-ShareAlike 2.5** 
- Desired ZIM Title: **Necyklopedie**
- Desired ZIM Description: **Satirická „encyklopedie“ parodující Wikipedii**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Uncyclopedia_logo_notext.svg/1280px-Uncyclopedia_logo_notext.svg.png
- Language (ISO 639-3): **ces**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/necyklopedie.org_cs_all
I'll update the library file once ready
