### ISSUE TITLE
New request: teoria.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#682]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.teoria.com/
- License: [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](http://creativecommons.org/licenses/by-nc-nd/4.0/)
- Desired ZIM Title: teoria.com
- Desired ZIM Description: teoría : Music Theory Web
- Desired ZIM Icon –png (URL or attach one): https://www.teoria.com/res/images/common/logo_32.png
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/teoria.com_en
Will update the library file once ready
