### ISSUE TITLE
New Recipe : dicoado

### ISSUE THREAD

**Issue by gitubbi** [openzim/zim-requests#686]
Could you please make a new zim recipe for dicoado ?

There is already one, but is is in status failed for months and is tagged nopic, novid :

[https://farm.openzim.org/recipes/dicoado](https://farm.openzim.org/recipes/dicoado)

It would better with pictures included (only tag novid to avoid too much size).

- Website URL:  https://fr.dicoado.org
- License:  CC BY-SA 4.0
- Desired ZIM Title:  dicoado
- Desired ZIM Description:  Le Dico des Ados
- Desired ZIM Icon –png (URL or attach one):   https://fr.dicoado.org/w/images/thumb/e/ef/Logo-big.png/x500px-Logo-big.png.pagespeed.ic.AHT4YcRART.png
- Language (ISO 639-3):  french (fr)
- Is this a MediaWiki?:  yes
- tag:  novid  (but keep pictures)

Thank you very much.

**Comment by Popolechien** [comment]
@gitubbi Seems things are on their way to being fixed, see https://github.com/openzim/mwoffliner/issues/1857
