### ISSUE TITLE
Request: fonts.google.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#687]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://fonts.google.com/
- License: *Creative Commons
- Desired ZIM Title: Google Fonts
- Desired ZIM Description: Google Fonts, Icons, Symbols
- Desired ZIM Icon –png (URL or attach one): ![image](https://github.com/openzim/zim-requests/assets/62152714/55aa4800-aa01-4b99-9867-ecbe1249a343)
- Language (ISO 639-3): **abc**
- Is this a MediaWiki?: **no**

https://github.com/google/fonts

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/fonts.google_en
Will update the library link once ready

**Comment by RavanJAltaie** [comment]
The recipe failed because the logo was not 48*48 as it should be.
This time I resized it and requested the recipe again. 
@Rexadev please in your next recipes make sure the logo you request is in the correct size.
![Google fonts](https://github.com/openzim/zim-requests/assets/116940574/346d19ef-c933-4f85-ab68-99f17cd8cfcb)

**Comment by Rexadev** [comment]
@RavanJAltaie What is the logo specs ?

**Comment by RavanJAltaie** [comment]
> @RavanJAltaie What is the logo specs ?

48x48 px

**Comment by RavanJAltaie** [comment]
The library link is:
https://library.kiwix.org/viewer#fonts.google_en_2023-09

**Comment by benoit74** [comment]
I'm not sure to understand why this is already in production. It is not possible to open individual fonts by clicking on them, nor to download them. As such, the ZIM is only useful to have a list of Google fonts and try some text in all of them. Was it really the intended purpose of this ZIM?
