### ISSUE TITLE
New request: en.xen.wiki

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#688]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.xen.wiki/w/Main_Page
- License: Creative Commons
- Desired ZIM Title: Xenharmonic Wiki
- Desired ZIM Description: The xenharmonic wiki is an open resource for information about [musical tuning](https://en.xen.wiki/w/Musical_tuning). This includes information about systems of tuning, the relationships between those systems, and the theory and math behind them.
- Desired ZIM Icon –png (URL or attach one): https://en.xen.wiki/images/4/4b/Xenwikilogo.png?ac2eb
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **yes**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/Xenharmonic_wiki_en/edit
Will update the library file once ready

**Comment by Rexadev** [comment]
@RavanJAltaie It is not here https://library.kiwix.org/#lang=eng&q=xen.wiki

**Comment by Rexadev** [comment]
@RavanJAltaie updates

**Comment by Rexadev** [comment]
@RavanJAltaie please reopen it
