### ISSUE TITLE
Issue with PZHZ openedx Mooc platform

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#689]
All [recipes configured on the Zimfarm for the PZHZ](https://farm.openzim.org/recipes?category=openedx&name=phzh) (Pädagogische Hochschule Zürich) are failing due to a scrapper bug.

While investigating (and fixing ^^) this bug, I realized that PZHZ Mooc platform at https://mooc.phzh.ch seems to not be here anymore.

Is there someone we could contact or should we just disable these recipes?

**Comment by Popolechien** [comment]
I spoke with PHZH:  they've dropped the hosting because they had no plan to update the content, but IIRC it's been moved somewhere else. In any case they're still using the offline version so the recipe can be suspended but the zim files should be kept.

**Comment by Popolechien** [comment]
I have deactivated all recipes. Closing ticket.
