### ISSUE TITLE
African Storybooks

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#690]
- Website URL: https://africanstorybook.org/
- License: CC-by (sometimes -NC)
- Desired ZIM Title: African Storybooks
- Desired ZIM Description: Picture storybooks for children’s literacy, enjoyment and imagination
- Language (ISO 639-3): **many**
- Is this a MediaWiki?: **no**

This has to handled by an `kolibri` offliner. Channel ID is f9d3e0e46ea25789bbed672ff6a399ed.

Original ticket with more details : https://github.com/openzim/kolibri/issues/13

**Comment by RavanJAltaie** [comment]
https://farm.openzim.org/recipes/africanstorybook.org_en_all
Recipe moved to main library
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
Link to the library is below:
https://library.kiwix.org/viewer#africanstorybook.org_en_all_2023-08
