### ISSUE TITLE
New request: ZIM for the https://www.dwds.de/

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#691]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.dwds.de/ (but a snapshot should be provided)
- License: Exception (https://www.dwds.de/d/nutzungsbedingungen)
- Desired ZIM Title: Der deutsche Wortschatz
- Desired ZIM Description: Der deutsche Wortschatz von 1600 bis heute
- Desired ZIM Icon –png (URL or attach one): https://www.dwds.de/dwds_static/images/dwds.svg
- Language (ISO 639-3): deu

**Comment by kelson42** [comment]
@benoit74 The idea is to get a dump (with HTML/CSS/...) and make a ZIM of it within the Zimfarm. Technology approach to discuss.

**Comment by benoit74** [comment]
I'm ready 🚀
