### ISSUE TITLE
New request: ZIM for sigidwiki.com

### ISSUE THREAD

**Issue by artiommocrenco** [openzim/zim-requests#694]
- Website URL: https://www.sigidwiki.com/wiki/Signal_Identification_Guide
- License: Public domain
- Desired ZIM Title: Signal Identification Guide
- Desired ZIM Description: Signal Identification Guide (sigidwiki) is intended to help identify radio signals through example sounds and waterfall images
- Desired ZIM Icon –png (URL or attach one): 
![sigidwiki](https://github.com/openzim/zim-requests/assets/28516476/7b6d1d28-0ab1-48f2-af9f-806916ba81d1)

- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

They do have this `Artemis 3` desktop software which allows for offline access, but having a ZIM that can be used with Kiwix might also prove to be useful for mobile device users.

**Comment by artiommocrenco** [comment]
Seems to be too old for mwoffliner:
```
mwoffliner --mwApiPath=/api.php --mwModulePath=/load.php --mwWikiPath=/wiki/Signal_Identification_Guide  --mwUrl=https://www.sigidwiki.com/ --adminEmail=sigidwiki@gmail.com --outputDirectory=/out/
```
results in
> Mediawiki version 1.22.3 not supported should be >=1.27

**Comment by Popolechien** [comment]
I guess that solves the issue on our end.

@artiommocrenco Any chance you could ping the website owners and gently nudge them towards an update?
