### ISSUE TITLE
New request: "species wikimedia"

### ISSUE THREAD

**Issue by FAISEL95595** [openzim/zim-requests#696]
- Website URL: https://species.wikimedia.org
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **wikispecies**
- Language (ISO 639-3): **heb**
- Is this a MediaWiki?: **yes**

**Comment by kelson42** [comment]
It'd already made, look at https://library.kiwix.org/#lang=&q=wikispecies

**Comment by FAISEL95595** [comment]
I meant this file in the Hebrew language

**Comment by Popolechien** [comment]
@FAISEL95595 AFAIK Wikispecies is only available in English.
