### ISSUE TITLE
Answers.com

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#70]
_From @amirh123123 on March 10, 2018 4:50_

hi please make zim file for Answers.com

_Copied from original issue: openzim/mwoffliner#228_

**Comment by kelson42** [comment]
I'm not even sure about the licenses here. Clarification would be welcome.

**Comment by kelson42** [comment]
_From @amirh123123 on March 18, 2018 12:45_

hi please see this 
http://www.answers.com/page/legal_notices#terms

**Comment by RavanJAltaie** [comment]
@amirh123123 
Rejected.
The License: [Copyright ©2022](https://www.answers.com/pages/copyright) System1, LLC. All Rights Reserved. The material on this site can not be reproduced, distributed, transmitted, cached or otherwise used, except with prior written permission of Answers.
