### ISSUE TITLE
Need to change lowtechmagazine scrape to https://solar.lowtechmagazine.com/

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zim-requests#702]
We currently scrape and publish https://www.lowtechmagazine.com/ as a Warc2Zim / Zimit site. However, looking at the home page of the site, it seems they are about to move definitively to a new address based on a solar-powered site: https://solar.lowtechmagazine.com/ . This site only runs when there is sufficient sunlight to power the server, which is based in Spain, so it would be necessary to ensure scrapes occur only during daylight hours if that is possible. Although they will redirect the old site to the new one, I presume this will be an issue for the Warc2Zim scraper, and it would be better to scrape the new site directly.

The notice on the old site is as follows:

> As of June 8, 2023, we will no longer update this website (www.lowtechmagazine.com). New articles and comments will only appear on the [solar-powered website of Low-tech Magazine](https://solar.lowtechmagazine.com/), if the weather allows it. The old website remains online until we have moved all articles, which we plan for July 2023. Once we have finished the migration, this website disappears, and the web address will point to the solar website. Subscribers do not have to do anything: they will keep receiving newsletters and feed updates.

**Comment by Popolechien** [comment]
Not sure we can manage daylight scraping, but @RavanJAltaie can at least update the address.

**Comment by kelson42** [comment]
Lets wait this happens, before doing anything.

**Comment by Jaifroid** [comment]
I think the issue is that no new articles have been published on the old server for quite some time, and they're only being published on the solar server. Hence, any scrapes we do are kind of useless now. Maybe redirection will solve things, but it very much depends how it's done, because the scrapes are domain-locked (links to solar server currently blocked).

**Comment by anomalouscowherd** [comment]
I just downloaded that .zim archive.  This is what I see when I try to open it on Kiwix 2.3.1 ( windows 11 ):

The requested URL can not be loaded because service workers are not supported here.

If you use Firefox in Private Mode, try regular mode instead.

If you use Kiwix-Serve locally, replace the IP in your browser address bar with localhost.

I get the same thing with all of the .zims in the zimit folder that I have downloaded ( google fonts, Military med, opentextbooks, based.cooking, thestacks, Lowtech, offthegrid, ready.gov.

If this isn't the place to report this please let me know.

**Comment by Jaifroid** [comment]
@anomalouscowherd Kiwix Desktop doesn't unfortunately support reading this type of ZIM currently. There are two workarounds:

* Open the Kiwix Serve implementation that is provided with Kiwix Desktop (look in menus), start the server, then visit the URL it indicates in a browser;
* Use the PWA version: https://pwa.kiwix.org - this has experimental support for Zimit-based ZIMs. It can be installed in Chromium browsers and bookmarked in Firefox and will work offline.

**Comment by anomalouscowherd** [comment]
Thanks.  The servers works a treat.  Too bad these sites can't be packaged without a server.


> @anomalouscowherd Kiwix Desktop doesn't unfortunately support reading this type of ZIM currently. There are two workarounds:
> 
>     * Open the Kiwix Serve implementation that is provided with Kiwix Desktop (look in menus), start the server, then visit the URL it indicates in a browser;
> 
>     * Use the PWA version: https://pwa.kiwix.org - this has experimental support for Zimit-based ZIMs. It can be installed in Chromium browsers and bookmarked in Firefox and will work offline.

**Comment by Jaifroid** [comment]
> Lets wait this happens, before doing anything.

@kelson42 @Popolechien It's happened, and it's a simple redirect in browser from www.lowtechmagazine.com to solar.lowtechmagazine.com, which means that (most likely) scrapes will be useless unless the scope is changed to solar.lowtechmagazine.com.

**Comment by Jaifroid** [comment]
@RavanJAltaie Are you able to update the address of this recipe (https://farm.openzim.org/recipes/lowtechmagazine.com/config) from "https://www.lowtechmagazine.com" to "https://solar.lowtechmagazine.com/"? There is now a redirect in place from the former to the latter, and I believe that because of scope, this will cause the scrape to fail.

This scrape is biannual, but it would be good to run it straight after the change to ensure it all works.

**Comment by anomalouscowherd** [comment]
Maybe we can pool our resources and buy this guy a battery?  What kind of battery would let a raspberry pi stay up for a few days?

**Comment by Jaifroid** [comment]
> Maybe we can pool our resources and buy this guy a battery? What kind of battery would let a raspberry pi stay up for a few days?

I think you're missing the point! It's about sustainability, and a demonstration of what is possible with self-sustaining technology. Lithium Ion batteries (at least) consume a huge amount of (fossil) fuel to manufacture, and he's written articles about the evils of this. I think he does actually have a Nickel-Iron or Lead-acid battery. I think we should follow his lead and run zimfarm on solar power only 🌞😵.

**Comment by kelson42** [comment]
I have created a dedicated https://farm.openzim.org/recipes/solar.lowtechmagazine.com with appropriate params. Lets way a sunny day to launch it manually and look how it looks like!

**Comment by Jaifroid** [comment]
Cool, thanks! Solar server is located in Spain, where it's pretty much always sunny 🌞, well except at night🌛, but in any case I think the server has a backup battery, so feel free to run it whenever, and we'll see if there are any issues.

Server seems to be running and fully charged now. See https://solar.lowtechmagazine.com/.

**Comment by RavanJAltaie** [comment]
@kelson42 https://dev.library.kiwix.org/viewer#solar.lowtechmagazine.com_en_all_2024-01 the resulted file looks fine.
But before moving it to the library let's decide if we will delete the old files and keep the new one only.
@Popolechien what do you think?

**Comment by Popolechien** [comment]
@RavanJAltaie If it is good to go, it is good to go. 

I am also generally against maintaining duplicates: we're not in the archiving business (that's internetarchive's purpose) but in the offline internet one (I also haven't checked but it sounds like the old content has been migrated to the new site anyway).

**Comment by Jaifroid** [comment]
Looks like we ended up scraping during the night when the battery was down to 28% (hence the meter line being 28% up the page on all scraped pages), but it worked from what I can tell.

I think we generally keep the two most recent scrapes. It's a good insurance against problems being found with the most recent one some time after it has been posted.

**Comment by RavanJAltaie** [comment]
I'll just disable the old recipe for now

**Comment by kelson42** [comment]
This is not a duplicate, keep old zim file please

**Comment by RavanJAltaie** [comment]
Old file is in the library, I've renamed the new version file as: **Solar Powered LowTech Magazine** to differentiate between the old version file and the new updated file.
