### ISSUE TITLE
open street

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#71]
_From @amirh123123 on March 12, 2018 5:55_

hi please make ozim file for open street maps

_Copied from original issue: openzim/mwoffliner#231_

**Comment by kelson42** [comment]
Yes... this is a long term goal.

**Comment by RavanJAltaie** [comment]
Requested 
https://farm.openzim.org/recipes/openstreet_map

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by Popolechien** [comment]
File does not appear in library, but generally speaking I think this is typically the type of content for which we'd need to build a dedicated scraper.
