### ISSUE TITLE
worldfactbook has no icon

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#717]
[Recipe](https://farm.openzim.org/recipes/theworldfactbook_en_all/config) uses an incorrect icon URL: Commons page instead of image file

**Comment by RavanJAltaie** [comment]
The logo is changed to PNG, uploaded on server and attached to recipe.
https://drive.farm.openzim.org/Corrected%20Logos%20for%20recipes/The_World_Factbook_emblema.png
