### ISSUE TITLE
cheatography has no icon

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#718]
[Recipe](https://farm.openzim.org/recipes/cheatography.com/config) uses an incorrect icon URL, pointing to a non-existent facebook link!

**Comment by benoit74** [comment]
Recipe has been updated by someone to use https://drive.farm.openzim.org/Corrected%20Logos%20for%20recipes/cheatography.com_en_all.png ; next ZIM produced (don't know when, see https://github.com/openzim/zim-requests/issues/1056) will be OK
