### ISSUE TITLE
OLPC Educational Packages 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#72]
_From @amirh123123 on March 12, 2018 5:56_

hi please make zim file for OLPC Educational Packages

_Copied from original issue: openzim/mwoffliner#232_

**Comment by kelson42** [comment]
URL please?

**Comment by kelson42** [comment]
_From @amirh123123 on March 12, 2018 11:21_

http://dev.worldpossible.org/cgi/viewmod.pl?module_id=11

**Comment by kelson42** [comment]
The URL is dead.

**Comment by RavanJAltaie** [comment]
Rejected
The URL is broken
(The requested URL was not found on this server.)
