### ISSUE TITLE
Clarify nodet flavour usage

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#720]
For a long time now, we've settled on the following flavours:

- `mini`: smallest, only includes an excerpt of each article and no media (mwoffliner only)
- `nopic`: content without pictures and videos
- `maxi`: content without videos
- ` `: no specific media removal

In the whole catalog, we have two recipes that also creates an additional `nodet` flavour file:

- [wikipedia_uk_medicine](https://farm.openzim.org/pipeline/wikipedia_uk_medicine)
- [wikipedia_en_medicine](https://farm.openzim.org/recipes/wikipedia_en_medicine)

As you can see by looking at the config and the file size, those `nodet` are excerpt-only **plus pictures**. I suppose the goal is to have the Infobox with the infobox picture.

I know that wikimed is _special_ in terms of audience, usage and importance: it has its own custom app for instance so I am asking for clarification:Is this on purpose or the remains of the wild-flavours-time? Are we supporting this flavour or is this a special exception for wikimed?

@kelson42

**Comment by Popolechien** [comment]
I would suspect it is an error. Or at least nothing I remember requesting formally (irrespective of the audience/purpose).

**Comment by kelson42** [comment]
Seems an error indeed, should be fixable in the recipe.

**Comment by rgaudin** [comment]
ok I'll fix and remove the files

**Comment by rgaudin** [comment]
Done
