### ISSUE TITLE
Fix Africanstorybook publishing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#721]
I'm opening this issue because what I mentioned on Slack seems to have been lost somewhere in the loop.

The [recipe](https://farm.openzim.org/recipes/africanstorybook.org_mul_all) is still wrong from my PoV (but I might be plain wrong, at least I did not got any answers / feedbacks on these comments in Slack):
- the warehouse path is `/zimit` while the file is created by `kolibri` offliner
- the filename is `africanstorybook.org_en_all` while it contains multiple language ; `en` is probably wrong ; and I'm not sure it is really useful to use the whole domain name, `africanstorybooks` is maybe sufficient since it is a well known project

The ZIM file is still not available on https://library.kiwix.org (at least search produced nothing) and some cleanup is obviously needed on https://dev.library.kiwix.org where there are too many versions: https://dev.library.kiwix.org/#lang=&q=african+storybook

Should you need any help on those topics or should there by any issue with the last ZIM file produced, do not hesitate to ask for help.

**Comment by Popolechien** [comment]
I think the convention would want the file to be named `africanstorybook.org_mul_all`, however as you say it's not like there are alternative options.

I would 100% support an automated clean-up of dev.library.kiwix.org every once in a while, as after a while it is just filled with garbage files and impedes quick check of the latest test runs.

**Comment by benoit74** [comment]
Until automated clean-up is approved and in place, which files should be removed for africanstorybook?

**Comment by Popolechien** [comment]
All of them I guess if the zim file is now working correctly and can be moved to library.kiwix.org, but the problem is more systemic: @RavanJAltaie decides, at the end of the day she probably is the main user.

**Comment by RavanJAltaie** [comment]
Thanks @benoit74 for your ticket.
- The warehouse path is changed to (Other).
- The file name states mul which is multiple languages as we agreed upon earlier.
- The file is showing in the main library, here is the link: [](https://library.kiwix.org/viewer#africanstorybook.org_en_all_2023-10/f9d3e0e46ea25789bbed672ff6a399ed
)
- For all the versions in dev library, I prefer all of them to be deleted as they are confusing. I will place a ticket for deleting the files.

**Comment by RavanJAltaie** [comment]
https://github.com/openzim/zim-requests/issues/725

**Comment by benoit74** [comment]
@RavanJAltaie : I just realized that ZIM name is still incorrect, I wasn't specific enough, sorry.

**Comment by benoit74** [comment]
![image](https://github.com/openzim/zim-requests/assets/7102089/702c1c7d-0a64-4106-905e-3d07099a6cf6)

**Comment by RavanJAltaie** [comment]
<img width="800" alt="image" src="https://github.com/openzim/zim-requests/assets/116940574/52a07e58-117a-4003-86bf-de8984c4530f">
Fixed!

**Comment by Popolechien** [comment]
I concur.

**Comment by RavanJAltaie** [comment]
Recipe succeeded.
File's link in the library
https://library.kiwix.org/viewer#africanstorybook.org_mul_all_2024-01/f9d3e0e46ea25789bbed672ff6a399ed
