### ISSUE TITLE
Fix `workers` parameter is `zimit` recipes

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#722]
Currently, most `zimit` recipes on the Zimfarm have a `workers` parameter set to 6. `zimit` default is 1. This is what is used on youzim.it. This parameter means that there is like 6 browser tabs processing the website at the same time.

While setting this parameter to 6 might make sense in some situations (when the website is very slow AND capable to handle the load of 6 parallel users), we agreed last week (or the week before) that it is a problem in most situations. This value can either hurt the target website or trigger protection against bots and denial of service.

I've just fixed all recipes (as decided in last team meeting) to not set this flag anymore in any recipe.

Below is the configuration of all zimit recipes before my change. 

@RavanJAltaie Do not hesitate to revert some of those changes if you consider original value was appropriate.

| name | offliner | workers |
| :--- | :--- | :--- |
| birds-of-ladakh | zimit | 6 |
| scp-wiki\_en | zimit | 6 |
| radiopaedia\_en | zimit | null |
| sheetmusicintl\_en\_all | zimit | 6 |
| solidarite-numerique | zimit | 6 |
| ben-yehuda\_he | zimit | 6 |
| questionsexualite\_fr\_all | zimit | 6 |
| alexandria.dk\_en\_all | zimit | 6 |
| ghana-bece-past-questions\_en | zimit | 6 |
| theworldfactbook\_en\_all | zimit | 6 |
| ready-gov\_en | zimit | 6 |
| blockly\_games | zimit | null |
| coopmaths | zimit | null |
| developer.mozilla.org\_en | zimit | 6 |
| manioc.org | zimit | 1 |
| der-postillon.com | zimit | 6 |
| internet-encyclopedia-philosophy\_en | zimit | 6 |
| bibnum | zimit | 6 |
| edu.gcfglobal.org\_pt | zimit | 6 |
| mesquartierschinois\_fr | zimit | 6 |
| ncert\_audiobooks | zimit | 6 |
| scp\_survival\_guides | zimit | null |
| wordnet\_en\_all | zimit | null |
| opentextbooks\_en\_all | zimit | 6 |
| globalnames.org\_en | zimit | 6 |
| bnr\_fr\_all | zimit | 6 |
| raspberrypi\_docs | zimit | null |
| bibnum\_education\_fr | zimit | 6 |
| based.cooking\_lukesmith | zimit | null |
| tvtropes | zimit | 6 |
| devdocs.io | zimit | 6 |
| maison-des-maternelles | zimit | 6 |
| musopen.org\_en\_all | zimit | 6 |
| h-node\_en\_all | zimit | 6 |
| cloudflare\_en\_all | zimit | 6 |
| dart.dev\_en\_all | zimit | 6 |
| lesfondamentaux | zimit | 6 |
| edu.gcfglobal.org\_en | zimit | 6 |
| unboundeq.creativitycourse\_en\_alle.org/categ | zimit | 6 |
| musictheory.net | zimit | 6 |
| cheatography.com | zimit | 6 |
| lowtechmagazine.com | zimit | 6 |
| armypubs\_en\_all | zimit | 6 |
| core\_knowledge | zimit | 6 |
| bestedlessons.org\_en\_all | zimit | 6 |
| courses.lumenlearning.com\_en\_all | zimit | 4 |
| harmony-project.org\_en\_all | zimit | 6 |
| marinespecies.org\_en | zimit | 6 |
| openmed | zimit | 6 |
| us\_code | zimit | 6 |
| revisenow\_all | zimit | 6 |
| fonts.google\_en | zimit | 6 |
| bookdash\_en\_all | zimit | 6 |
| bouquineux | zimit | 6 |
| barmaga.io | zimit | 1 |
| ready-gov\_es | zimit | 6 |
| att\_connected\_learning\_en | zimit | 6 |
| openstax.org\_en\_all | zimit | 6 |
| mankier | zimit | 6 |
| websters1913 | zimit | 6 |
| langelyfiles\_en | zimit | 6 |
| ki4u\_en | zimit | null |
| footballdatabase.com\_en | zimit | 6 |
| feed\_the\_beast\_wiki | zimit | 6 |
| tobyrush\_en | zimit | 6 |
| penser-critique | zimit | 6 |
| owasp | zimit | 6 |
| fipeco | zimit | 6 |
| unboundeq.creativitycourse.org\_en | zimit | 6 |
| ivelt.com | zimit | 6 |
| hackteria.org\_en | zimit | 6 |
| modern\_philosophy | zimit | 6 |
| stacks.math.columbia.edu | zimit | 6 |
| codingfortomorrow\_de\_all | zimit | 6 |
| emergency-war-surgery | zimit | 6 |
| military\_library\_en | zimit | 6 |
| openstreet\_map | zimit | 6 |
| saint\_libere | zimit | null |
| tahrir\_ar\_all | zimit | 6 |
| fas-military-medicine | zimit | 6 |
| flexbooks\_en\_all | zimit | null |
| mitscratch | zimit | 6 |
| bibebook.com\_fr\_all | zimit | 6 |
| practical\_action\_en\_all | zimit | 6 |
| deployed-medicine | zimit | 6 |
| teoria.com\_en | zimit | 6 |
| culturegnum | zimit | 6 |
| ndla.no\_no\_all | zimit | null |
| weforum.org\_en\_all | zimit | 6 |
| perseus-hopper | zimit | 6 |
| ganjoor.net | zimit | null |
| h2g2.com | zimit | null |
| encyclopedie-environnement.org\_en | zimit | 6 |
| dp.la\_en\_all | zimit | 6 |
| mutopiaproject.org\_en | zimit | 6 |
| athena\_fr\_all | zimit | 6 |
| storyweaver.org\_en | zimit | 6 |
| openlibrary.org | zimit | 6 |
| mitopencourse\_en\_all | zimit | 6 |
| edu.gcfglobal.org\_es | zimit | 6 |
| localwiki.org\_en\_all | zimit | 6 |
| ncatlab | zimit | 6 |

**Comment by benoit74** [comment]
For reference, SQL queries used:

```
SELECT schedule.name, json_extract_path(schedule.config, 'task_name')::text as task_name,  json_extract_path(schedule.config, 'flags', 'workers')::text as workers
FROM schedule
WHERE json_extract_path(schedule.config, 'task_name')::text = '"zimit"'
```

```
UPDATE schedule SET config = config::jsonb #- '{flags, workers}'
WHERE json_extract_path(schedule.config, 'task_name')::text = '"zimit"'
```

**Comment by benoit74** [comment]
@rgaudin I updated only the `flags` setting in the `config`, is it correct or should I have also updated the `command` and `str_command`.
It looks like those two properties are recomputed on the fly by the `expanded_config` in the GET API in any case, and this is what is used by workers to retrieve the schedule configuration.
Did I missed something?

**Comment by rgaudin** [comment]
AFAIK a PATCH to schedules doesn't update it so it's OK.

**Comment by RavanJAltaie** [comment]
Thank you @benoit74. Well Noted.
