### ISSUE TITLE
Add fon.wikipedia.org scraping to Zimfarm

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#724]
- Website URL: https://fon.wikipedia.org
- License: cc-by-sa
- Desired ZIM Title: **Wikipedya**
- Desired ZIM Description: **Núdyin é hun nù mɛ bi é**
- Language (ISO 639-3): **fon**
- Is this a MediaWiki?: **yes**

**Comment by kelson42** [comment]
Would be great to check as well that libkiwix supports it first. Considering we ate just about to make a new telease, might even be the first thing to do.

**Comment by Popolechien** [comment]
I've opened a ticket there. https://github.com/kiwix/libkiwix/issues/1002

**Comment by benoit74** [comment]
@RavanJAltaie please update https://github.com/openzim/zimfarm/issues/842 with all requested information

**Comment by RavanJAltaie** [comment]
[Adding new language request](https://github.com/openzim/zimfarm/issues/846)

**Comment by benoit74** [comment]
https://github.com/openzim/zimfarm/issues/846 done

**Comment by kelson42** [comment]
I have:
* Reactivate the recipe
* Made a new run
* Verify the output (which is OK)

Therefore I close this ticket.
