### ISSUE TITLE
Deleting unnecessary African Story book files from Dev Library

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#725]
Please delete the files below from dev library:
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_mul_all_2022-07.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_2023-07.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_en_all_2023-07.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_en_all_2023-08.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_mul_all_2022-06.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_mul_all_2022-07.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_mul_all_2023-01.zim
https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_mul_all_2023-07.zim

**Comment by benoit74** [comment]
@rgaudin I will need your help on this one.
I think that I need to know how to do it so that I can do it on my own.
Let's discuss about it next week.

**Comment by kelson42** [comment]
@benoit74 @rgaudin AFAIK, the deletion of these files is done via a service account using SSH.

Could we setup the infra and the documentation to:
* Have personal accounts
* To access download.kiwix.org download.openzim.org (or part of them, depending of roles)
* Share these accounts when necessary
* log properly actions using this tool

So people in charge don't depend of @rgaudin ?

**Comment by rgaudin** [comment]
@benoit74 has access ; it's just that he didn't know where the hidden zims where because those are not part of the regular download tree. This has been covered yesterday when this ticket was created.

What you describe seems unnecessary at this stage (because it requires finding and setting up a new service). current process works fine and the requests are low.
We discussed with @benoit74 reviving rules for obsolescence of dev files (that you discarded) because those should be numerous, as per the zim creation process.

**Comment by kelson42** [comment]
@rgaudin Considering the amount of tickets and comments (including from me) requesting changes at filesystem level, I pretty much disagree that a proper process (following minimal requirements given by me) is overkill.

**Comment by rgaudin** [comment]
Creating tickets for deletion requests IS the process and those have all been handled smoothly AFAIK.

I am all for having a proper tool that does what you describe but I regard it as low priority given it requires an effort and it's already working.

Open a separate ticket then (in k8s)

**Comment by kelson42** [comment]
> Open a separate ticket then (in k8s)

I suspect I will simply put the ticket https://github.com/openzim/cms/issues/82 in emphasis for the next CMS milestone.

**Comment by rgaudin** [comment]
Indeed, makes more sense

**Comment by benoit74** [comment]
All requested files have been deleted, changes will be reflected in dev library UI in more or less 10 minutes.
