### ISSUE TITLE
openstax Textbooks 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#73]
_From @amirh123123 on March 12, 2018 5:57_

hi please make zim file for openstax Textbooks 

_Copied from original issue: openzim/mwoffliner#233_

**Comment by kelson42** [comment]
URL please?

**Comment by kelson42** [comment]
_From @amirh123123 on March 12, 2018 11:19_

http://dev.worldpossible.org/cgi/viewmod.pl?module_id=116

**Comment by Popolechien** [comment]
duplicate of #136
