### ISSUE TITLE
Request: ultimate-guitar.com [1950's Songs Only]

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#732]
- Website URL: https://www.ultimate-guitar.com/explore?decade[]=1950
- License: Discuss
- Desired ZIM Title: Ultimate Guitar 1950's Songs
- Desired ZIM Description: UltimateGuitar Song Tabs, Chords of 1950s songs
- Desired ZIM Icon –png (URL or attach one): ![image](https://github.com/openzim/zim-requests/assets/62152714/49871246-d7fd-44b0-bede-68adf70e624f)
- Language (ISO 639-3): Many
- Is this a MediaWiki?: **no**

In US songs enter public domain after 70 years. Does Ultimate guitar hold copyright to tabs of 1950's Songs if no. We can Scrape it

**Comment by Popolechien** [comment]
Three comments:
1. Why 1950s only and not the whole thing?
2. Songs are likely to still be under copyright (death of author + 70 years)
3. The whole website states `© 2023 Ultimate-Guitar.com All rights reserved`
