### ISSUE TITLE
Generate African Cup Wikipedia Subsets (en/fr)

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#734]
Within the ambit of publishing a CAN offline app by December, we first need to generate the corresponding zim file:

-the main article of the 2023 African Cup and all related articles (the qualifying phases) which are in the corresponding category
-the general article of the African Cup of Nations
-the articles of each participating national selection
-the articles of the players who are going to play
-the articles of the coaches of the selections
-items from the stadiums which will host the matches
-articles from the cities where the matches will take place
-articles from old editions and articles from old finals
-the article on the List of scorers at the African Cup of Nations

In the end we should have two zim files (e.g. `wikipedia_en_afcon_maxi` and `wikipedia_fr_can_maxi` as the cup's acronym is afcon and can in these languages) and if entries are missing in one or the other language then a list we can share with Wikimedians of Ivory Coast UG so that they can run an editathon.

- Desired ZIM Title: AFCON 2024 offline (en) or _CAN 2024 hors-ligne_ (fr)
- Desired ZIM Description: _Every bit of info  the 2024 Africa Cup of Nations_ / _Tout sur la Coupe d'Afrique des Nations 2024_
- Desired ZIM Icon –png: Afcon logo is protected, maybe ask @siemsie to extract the Africa map from this image on Commons
- Language (ISO 639-3): **en** + **fr**
- Is this a MediaWiki?: **yes**

Once this is done, open a ticket in /kiwix/kiwix-android-custom and generate the playstore entries + apps

**Comment by rgaudin** [comment]
I see two mwoffliner recipes with custom articles list which will be hosted on the drive.
Those two files would be a concatenation of multiple ones obtained via WP1.

Is that how you plan to do it?

**Comment by Popolechien** [comment]
Not sure I get the question, but yes, the initial list of entries would be obtained via WP1

**Comment by RavanJAltaie** [comment]
Do we need to generate .tsv files or zim files (For the subsets)?

**Comment by Popolechien** [comment]
@RavanJAltaie we're looking for zim files because the next step it to package them with Kiwix-Android so as to have a custom app.

**Comment by RavanJAltaie** [comment]
Project completed.
