### ISSUE TITLE
Rename opentextbooks_en_all to B.C. Open Collection by BCcampus

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#736]
https://library.kiwix.org/viewer#opentextbooks_en_all_2023-08 / https://farm.openzim.org/recipes/opentextbooks_en_all

### Reason

It is related to https://open.bccampus.ca/browse-our-collection/find-open-textbooks/
and it creates confusion with https://github.com/openzim/zim-requests/issues/231  https://open.umn.edu/opentextbooks

and description to
```
Course Materials for Educators
Find free, open, and customizable materials by course or subject.
```

**Comment by Rexadev** [comment]
@RavanJAltaie

**Comment by RavanJAltaie** [comment]
Recipe name changed to bccampus_opentextbooks_en_all
https://farm.openzim.org/recipes/bccampus_opentextbooks_en_all
