### ISSUE TITLE
Revamp Canadian prepper playlist(s)

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#738]
We had reports from users that the Canadian prepper Youtube playlist that we had has turned a bit on the batshit side.

Please:
- Delete zim files associated with the recipe here : https://farm.openzim.org/recipes/canadian_prepper (and then the recipe as well)
- Generate new recipes covering Bug-out roll, Prepping food, Bug out concepts and Winter prepping from this list here: https://www.youtube.com/@CanadianPrepper/playlists

**Comment by Popolechien** [comment]
See #740 for API keys that can be used for these three new recipes.

**Comment by RavanJAltaie** [comment]
The Library link is [here](https://library.kiwix.org/viewer#canadianprepper_en_all_2023-11).
