### ISSUE TITLE
Make ZIM of "Oregon Youth Authority"

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#74]
_From @amirh123123 on March 12, 2018 6:0_

hi please make zim file for Oregon Youth Authority 

_Copied from original issue: openzim/mwoffliner#234_

**Comment by kelson42** [comment]
url?

**Comment by kelson42** [comment]
_From @amirh123123 on March 18, 2018 12:40_

http://oer2go.org/viewmod/en-oya

**Comment by RavanJAltaie** [comment]
Rejected
The URL is directed to a gambling site
