### ISSUE TITLE
Delete Canadian Prepper wrong Zim files

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#741]
Please delete the two zim files below:
1- https://download.kiwix.org/zim/videos/canadian_prepper_en_surviving-disaster_2023-06.zim
2- https://download.kiwix.org/zim/videos/canadian_prepper_en_surviving-disaster_2023-09.zim

**Comment by benoit74** [comment]
As per our procedure to avoid accidental deletion of important prod files, files have been moved to dev library for now. Will be finally deleted once we will cleanup the dev library. Prod library update will be done automatically in at most 2 hours.
