### ISSUE TITLE
[Request] Youtube Channel ::::: L'esprit Sorcier

### ISSUE THREAD

**Issue by cheznewa** [openzim/zim-requests#742]
url :: https://www.youtube.com/channel/UCH6rAZUDfVIoVSJjm3vlcnw
language :: French
name :: esprit sorcier

**Comment by kelson42** [comment]
@Popolechien @benoit74 Anything stoping us to do that one?

**Comment by Popolechien** [comment]
@kelson42 licensing I guess?

**Comment by kelson42** [comment]
@Popolechien AFAIK there is nothing written about a special licensing on the Youtube channel

**Comment by Popolechien** [comment]
If there is no license specified, the default license is "all rights reserved". The procedure here is to write to the channel owners and copy hello at kiwix.org so it gets filed with a licensing tag.

**Comment by Popolechien** [comment]
Looking at a random video on this channel I find © L’Esprit Sorcier - Octobre 2024

**Comment by cheznewa** [comment]
And You Looking The Rayons X ::::: https://github.com/openzim/zim-requests/issues/727
