### ISSUE TITLE
College Credit Courses 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#75]
_From @amirh123123 on March 12, 2018 6:1_

hi please make zim file for College Credit Courses 

_Copied from original issue: openzim/mwoffliner#235_

**Comment by kelson42** [comment]
url?

**Comment by kelson42** [comment]
_From @amirh123123 on March 18, 2018 12:39_

http://oer2go.org/viewmod/en-rachelcourses

**Comment by RavanJAltaie** [comment]
Rejected
The URL is for a gambling site.
