### ISSUE TITLE
Wikipedia for Schools Update and Clean Up

### ISSUE THREAD

**Issue by SolarSPELL-Main** [openzim/zim-requests#758]
This request is for the wikipedia_en_for_schools_maxi Zim file. We have cleaned up the CSV a bit and have added a small selection of new articles that are applicable to regions we soon plan on releasing WfS to. If possible, could this replace the previous Zim recipe? Thank you!
[Final_FA23_Kiwix_format_Working Document - Articles List.xlsx - Update_Final_SU21_Kiwix_Format.csv](https://github.com/openzim/zim-requests/files/13573004/Final_FA23_Kiwix_format_Working.Document.-.Articles.List.xlsx.-.Update_Final_SU21_Kiwix_Format.csv)

**Comment by Popolechien** [comment]
@SolarSPELL-Main I guess we'll see it when we open it but this update is only for the English version (and not the Arabic one, correct?)

**Comment by kelson42** [comment]
@SolarSPELL-Main Can you manage these lists  directly on wp1.openzim.org?

**Comment by Popolechien** [comment]
@kelson42 How would this help update the recipe that is currently in the zimfarm?

**Comment by kelson42** [comment]
@Popolechien Its unrelated, recipes have almost nothing to do with WP article lists.

**Comment by RavanJAltaie** [comment]
File is updated successfully
The library file is
https://library.kiwix.org/viewer#wikipedia_en_for_schools_maxi_2023-12
