### ISSUE TITLE
Removing files from Library

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#764]
Please remove the following files from library:

1- https://download.kiwix.org/zim/other/westeros_en_all_maxi_2021-02.zim
2- https://download.kiwix.org/zim/other/westeros_en_all_maxi_2021-03.zim
3- https://download.kiwix.org/zim/other/westeros_en_all_nopic_2021-02.zim
4- https://download.kiwix.org/zim/other/westeros_en_all_nopic_2021-03.zim
5- https://download.kiwix.org/zim/other/allthetropes_en_all_maxi_2020-11.zim
6- https://download.kiwix.org/zim/other/halachipedia_en_all_maxi_2021-01.zim
7- https://download.kiwix.org/zim/other/halachipedia_en_all_maxi_2021-03.zim
8- https://download.kiwix.org/zim/other/halachipedia_en_all_nopic_2021-01.zim
9- https://download.kiwix.org/zim/other/halachipedia_en_all_nopic_2021-03.zim

**Comment by benoit74** [comment]
Done, library will refresh in few minutes.
