### ISSUE TITLE
Remove Canadian Prepper Multi playlist file

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#765]
Please remove the file below
https://download.kiwix.org/zim/videos/canadianprepper_en_all_2023-11.zim

I've replaced it with a file for each playlist as agreed upon.
I disabled the recipe as well.

**Comment by benoit74** [comment]
Are you sure this is what you want to do? As discussed with @Popolechien and you in https://github.com/openzim/zimfarm/issues/878#issuecomment-1852402451, `Canadian Prepper` had no issue. We do not mind about creating one ZIM with multiple playlists.

**Comment by RavanJAltaie** [comment]
Yes please delete it because the new zim files are working and ready, so no need to duplicate the content. @benoit74

**Comment by benoit74** [comment]
Done, library will refresh in few minutes.
