### ISSUE TITLE
E-Paath

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#77]
_From @amirh123123 on March 12, 2018 6:3_

hi please make zim file for E-Paath 

_Copied from original issue: openzim/mwoffliner#237_

**Comment by kelson42** [comment]
URL please?

**Comment by kelson42** [comment]
_From @amirh123123 on March 12, 2018 11:18_

http://www.olenepal.org/e-paath

**Comment by kelson42** [comment]
Here too, I'm not sure at all about the licence.

**Comment by RavanJAltaie** [comment]
Rejected
The License is not CC or Public domain.
(© 2021 OLE Nepal)
