### ISSUE TITLE
Aimhi playlists don't exist anymore on Youtube

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#770]
I found out that Aimhi playlists don't exist anymore on Youtube, I disables the recipe here.
I need your input on below:

1- Shall I delete the recipe permanently?
2- We have 9 resulted files in the library dated back to January 2022, shall we keep them or delete them?

The files:
1- https://download.kiwix.org/zim/videos/aimhi_en_english-website_2022-01.zim
2- https://download.kiwix.org/zim/videos/aimhi_en_geography-website_2022-01.zim
3- https://download.kiwix.org/zim/videos/aimhi_en_hilights-website_2022-01.zim
4- https://download.kiwix.org/zim/videos/aimhi_en_hischool-biology_2022-01.zim
5- https://download.kiwix.org/zim/videos/aimhi_en_hischool-physics_2022-01.zim
6- https://download.kiwix.org/zim/videos/aimhi_en_inspiring-guests_2022-01.zim
7- https://download.kiwix.org/zim/videos/aimhi_en_philosophy-website_2022-01.zim
8- https://download.kiwix.org/zim/videos/aimhi_en_science-website_2022-01.zim
9- https://download.kiwix.org/zim/videos/aimhi_en_what-is-cancer_2022-01.zim

**Comment by benoit74** [comment]
What about the Zimfarm recipe? If it is disabled "forever", I see very little interest to keep it.

**Comment by RavanJAltaie** [comment]
@Popolechien Shall we keep the files and delete the recipe?

**Comment by Popolechien** [comment]
@RavanJAltaie Yep sounds like the way forward

**Comment by RavanJAltaie** [comment]
Noted.
