### ISSUE TITLE
New request: Introduction sections from Wikipedia articles

### ISSUE THREAD

**Issue by gd4c** [openzim/zim-requests#773]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Desired ZIM Title: **Wikipedia Intros**
- Desired ZIM Description: **The first few paragraphs of every Wikipedia article. Easy on the bandwidth, high on value!**
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

1. The Full English Wikipedia zim is over 100 GB. Most people don't need it realistically and it is too much to transfer (on both ends) and keep (storage and speed).
2. Most of the time, I just want a quick explanation of a topic/person. Only occasionally do I read past the table of contents of a Wikipedia article.
3. The other Wikipedia zims are either too specialized or have too few articles. And you go to Wikipedia in the first place often because the subject isn't a popular one. So there is a value to keeping all the articles.
4. My suggestion is for a zim that contains everything text before the table of contents (and maybe the categories at the bottom). It should be of a manageable size while covering 90% of use cases.

**Comment by rgaudin** [comment]
That's exactly what's inside the "mini" variant of all wikimedia ZIMs.
Was called nodet when first introduced (years ago)

**Comment by gd4c** [comment]
Could you please link me to it. I can't find it

https://library.kiwix.org/#lang=eng&category=wikipedia&q=nodet
https://library.kiwix.org/#lang=eng&category=wikipedia&q=mini

**Comment by Popolechien** [comment]
It would be [this one here](https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_mini_2023-12.zim) but at 53Gb there must be a bug of sorts that made it way bigger than it should be (I would have expected 15-20 Gb or so). 

I know the issue has been reported somewhere already but I can't find it.

**Comment by gd4c** [comment]
Even 15GB is more than I thought it would be if I am honest. Are you sure it's without images?

**Comment by Popolechien** [comment]
@gd4c well it's 6.4 _million_ articles, eh.

**Comment by rgaudin** [comment]
https://github.com/openzim/mwoffliner/issues/1893

**Comment by gd4c** [comment]
> @gd4c well it's 6.4 _million_ articles, eh.

Yeah, but I thought compression should squeeze that quite a bit!
