### ISSUE TITLE
New request: afaqattaiseer.net/vb

### ISSUE THREAD

**Issue by hamoudak** [openzim/zim-requests#776]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.afaqattaiseer.net/vb/
- License: Powered by vBulletin® Copyright ©2000 - 2024, Jelsoft Enterprises Ltd. 
- Desired ZIM Title: afaqattaiseer Institute 
- Desired ZIM Description: a scientific website that combines scientific analysis a long with teamwork. Improving the use of information technology to preserve science .
- Desired ZIM Icon –png (URL or attach one): 
- https://i122.fastpic.org/big/2024/0106/76/1a787b2df61edb353314a5e63cf1a876.jpg
- Language (ISO 639-1): Arabic
- Is this a MediaWiki?: no

**Comment by hamoudak** [comment]
Could you please create a recipe for me . I really need this to work on it  offline . anyway thank you for providing requests .

**Comment by hamoudak** [comment]
Is there any chance to get this created?

**Comment by RavanJAltaie** [comment]
@hamoudak Please if you want to create zim files of copyrighted content, you need to inform the content owners to grant us permission at [contact@kiwix.org](mailto:contact@kiwix.org). Until then, we will not be able to create the file.

**Comment by hamoudak** [comment]
ok RavanJAltaie, am gonna try with them .
