### ISSUE TITLE
Remove bestedlessons.org_en_all zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#778]
[Best Ed lessons](https://library.kiwix.org/viewer#bestedlessons.org_en_all) works fine except for that part where, at the end, the zim attempts (and fails) to retrieve documents on another source URL (e.g. Dropbox, chino.k12.ca.us, etc.).

It looks many of these works are copyrighted anyway, so we'll need to remove them. I have also already disabled the recipe in the zimfarm.

Files to remove are: https://download.kiwix.org/zim/zimit/bestedlessons.org_en_all_2023-08.zim and https://download.kiwix.org/zim/zimit/bestedlessons.org_en_all_2023-11.zim

**Comment by benoit74** [comment]
Done
