### ISSUE TITLE
Fantastic Phonics - Adult 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#78]
_From @amirh123123 on March 12, 2018 6:4_

hi please make zim file for Fantastic Phonics - Adult 

_Copied from original issue: openzim/mwoffliner#238_

**Comment by kelson42** [comment]
URL please?

**Comment by kelson42** [comment]
_From @amirh123123 on March 12, 2018 11:17_

http://dev.worldpossible.org/cgi/viewmod.pl?module_id=123

**Comment by RavanJAltaie** [comment]
URL doesn't exist anymore!
