### ISSUE TITLE
New request: Bundeszentrale für politische Bildung

### ISSUE THREAD

**Issue by JensKorte** [openzim/zim-requests#781]
- Website URL: https://www.bpb.de/
- License: Many pages use CC in different flavours, some proprietary, see https://www.bpb.de/die-bpb/faq/184955/nutzungsrechte/ 
- Desired ZIM Title: Bundeszentrale für politische Bildung
- Desired ZIM Description: Förderung des Bewusstseins für Demokratie und politische Partizipation
- Desired ZIM Icon –png (URL or attach one): https://www.bpb.de/cache/images/2/49552_article_side.jpg
- Language (ISO 639-3): deu
- Is this a MediaWiki?: no

- contact: info@bpb.de
- phone: +49 (0)228 99515-0

The search provides a licence field but always shows the numbers of 0 or 250 results. I don't know how useful this is. Maybe asking them to provide a URL containing all CC articles would be the easiest.

**Comment by RavanJAltaie** [comment]
@JensKorte As some of the website parts are copyrighted. you need to inform the content owners to grant us permission at [contact@kiwix.org](mailto:contact@kiwix.org). Until then, we will not be able to create the file.
