### ISSUE TITLE
Request: patents.google.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#785]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://patents.google.com/
- License: Can't find
- Desired ZIM Title: Google patents
- Desired ZIM Description: 
- Desired ZIM Icon –png (URL or attach one): 
![image](https://github.com/openzim/zim-requests/assets/62152714/1fb43ff7-9442-4cfe-8b0a-e9779603cf5c)

- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
@Rexadev Please you need to confirm the state of the copyrighted material, you need to inform the content owners to grant us permission at [contact@kiwix.org](mailto:contact@kiwix.org). Until then, we will not be able to create the file.

**Comment by Rexadev** [comment]
https://console.cloud.google.com/marketplace/product/google_patents_public_datasets/google-patents-public-data

Creative Commons Attribution 4.0 International License.

Also See: https://console.cloud.google.com/marketplace/product/google_patents_public_datasets/patentsview
https://console.cloud.google.com/marketplace/product/google_patents_public_datasets/google-patents-research-data
https://console.cloud.google.com/marketplace/product/google/compute.googleapis.com

**Comment by Rexadev** [comment]
@RavanJAltaie isn't it Creative Commons Attribution 4.0 International License
