### ISSUE TITLE
Delete 100r-off-the-grid_en_* files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#786]
Following our discussion I have changed the description and title for what is now [100 rabbits](https://farm.openzim.org/recipes/100rabbits/edit), and the following zim files should be deleted:
https://download.kiwix.org/zim/zimit/100r-off-the-grid_en_2023-12.zim
https://download.kiwix.org/zim/zimit/100r-off-the-grid_en_2023-09.zim

**Comment by benoit74** [comment]
Let's do it only once the file is really published to prod (see https://github.com/openzim/warc2zim/issues/153#issuecomment-1900864131) and next comments

**Comment by Jaifroid** [comment]
Yes, plus there is an opportunity to use a comparison between this 2023-12 version and the 2024-01 zimit2 version in the dev server for debugging the unplayable video issue in zimit2. This is a small file with a number of videos (e.g. in the "orca" article), and at least the "orca" article's video in the zimit2 versions suffers from the issue reported in https://github.com/openzim/warc2zim/issues/149 (whereas in 2023-12, zimit classic, the video plays fine).

**Comment by benoit74** [comment]
Now better tracked in #1074
