### ISSUE TITLE
New request: Korean Learning Language Website

### ISSUE THREAD

**Issue by SpitfirePls** [openzim/zim-requests#787]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.howtostudykorean.com/
- License: Public Domain
- Desired ZIM Title: How to Study Korean
- Desired ZIM Description: Studying Korean on a large scale, this resource will cover the majority of what you need to begin your journey into learning this beautiful language.
- Desired ZIM Icon –[png (URL or attach one): https://example.com/example_icon.png](https://yt3.googleusercontent.com/ytc/AIf8zZRUSf8loeRCo7R3pBqDJuqyFnUYUBhDUnrmvIGTuA=s900-c-k-c0x00ffffff-no-rj)
- Language (ISO 639-3): English
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
@SpitfirePls The website clearly states © 2023. All Rights Reserved. How did you get to the conclusion that this was under a public domain license?

**Comment by SpitfirePls** [comment]
Oh Christ my bad, I hadn't seen that. To be honest, I've been up for a few hours just trying to figure out how to install Kiwix on my RaspbPi 4, so I'm sorry for missing that.

**Comment by Popolechien** [comment]
no worries. We can't scrape coyprighted material (unless we get permission to), but if you're into learning Korean I suspect there's a Stack Exchange that's available for download.
