### ISSUE TITLE
Fantastic Phonics - Child 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#79]
_From @amirh123123 on March 12, 2018 6:5_

hi please make zim file for Fantastic Phonics - Child 

_Copied from original issue: openzim/mwoffliner#239_

**Comment by kelson42** [comment]
URL please?

**Comment by kelson42** [comment]
_From @amirh123123 on March 12, 2018 11:16_

http://dev.worldpossible.org/cgi/viewmod.pl?module_id=124

**Comment by RavanJAltaie** [comment]
URL doesn't exist anymore.
