### ISSUE TITLE
TED: rework `ted_all_playlists` to set metadata properly

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#790]
Just like for youtube, we do not want to use the `indiv-zims: true` of the TED scraper, which allows to create many ZIMs with one recipe, because it leads to low quality ZIM metadata (title, description, zim name, ...).

We hence want to get rid of https://farm.openzim.org/recipes/ted_all_playlists (which seems pretty broken anyway) and create one recipe per playlist.

Action plan:
- @benoit74 : collect list of playlists / recipes to create
- @RavanJAltaie : confirm details about the recipes to create (description, title, ...)
- @benoit74 : create one first recipe automatically (pushing ZIMs to dev)
- @RavanJAltaie : confirm recipe and ZIM are ok and move to prod
- @benoit74 : create all remaining recipes
- @RavanJAltaie : check all ZIMs and move to prod
- @RavanJAltaie : remove old recipe and request removal of old ZIMs (list to be confirmed by you)

Any remark or should we go according to this plan?

**Comment by RavanJAltaie** [comment]
Plan looks fine to me.

**Comment by benoit74** [comment]
We do not create any TED playlists anymore, so this issue is not relevant anymore.
