### ISSUE TITLE
wikipedia biology 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#80]
_From @amirh123123 on March 12, 2018 15:2_

hi please make zim file for wikipedia biology animals plant and other species thanks

_Copied from original issue: openzim/mwoffliner#241_

**Comment by kelson42** [comment]
Is Wikispecies not what you need?

**Comment by kelson42** [comment]
_From @amirh123123 on March 16, 2018 9:2_

hi no wikipedia articles about animals example dog cat and other species thanks

**Comment by kelson42** [comment]
@Popolechien We need an offline home page and a list of articles (wikiproject).

**Comment by kelson42** [comment]
_From @Popolechien on April 3, 2018 10:43_

@kelson42 I've made an offline landing page but https://en.wikipedia.org/wiki/Biology actually seems quite thorough and we could/should try to use it. For the zim logo, see:
![biology](https://user-images.githubusercontent.com/21675885/38244767-fb5151b4-373b-11e8-991e-e8430d861a34.png)

As a side note the zim should probably not include articles intersecting with WikiProject Biography but should include those from WikiProject Mammals (if OP wants cats and dogs).

**Comment by RavanJAltaie** [comment]
@amirh123123 We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
