### ISSUE TITLE
wikipedia_as_medicine has improper title

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#801]
https://farm.openzim.org/recipes/wikipedia_as_medicine is failing since 7 months ago with error "MetaData Title: must NOT have more than 30 characters"

We should fix it. I disabled the recipe until it is fixed.

**Comment by RavanJAltaie** [comment]
@benoit74 title has been fixed and recipe re-run.

**Comment by RavanJAltaie** [comment]
Recipe succeeded.
