### ISSUE TITLE
New request: GrimGrains recipes

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#805]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: `https://grimgrains.com`
- License: `Creative Commons BY-NC-SA-4.0`
- Desired ZIM Title: `GrimGrains recipes`
- Desired ZIM Description: `GrimGrains is a collection of recipes by Rek Bell and Devine Lu Linvega`
- Desired ZIM Long Description: `GrimGrains is a collection of recipes by Rek Bell and Devine Lu Linvega, living on a small 10m(33ft) sailboat somewhere on the shores of the Pacific Ocean. They started Grimgrains to learn how to cook. This blog helps them track their habits as they adapt to the locally-available produce. Their recipes are plant-based, and contain no tree nuts due to Rek's allergy.`
- Desired ZIM Icon –png (URL or attach one): `https://grimgrains.com/media/services/favicon.ico`
- Language (ISO 639-3): `eng`
- Is this a MediaWiki?: `no`

**Comment by benoit74** [comment]
Nota: since they live on a sailboat, this could probably be added to the prepper collection with the associated tag.

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/grimgrains_en_all
I'll post the library link once ready.

**Comment by RavanJAltaie** [comment]
File is ready in the library
https://library.kiwix.org/viewer#grimgrains_en_all_2024-02
