### ISSUE TITLE
New request: Python Enhancement Proposals (PEPs)

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#806]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: `https://peps.python.org/`
- License: `PSF License` (see https://docs.python.org/3/license.html#terms-and-conditions-for-accessing-or-otherwise-using-python)
- Desired ZIM Title: `Python PEPs`
- Desired ZIM Description: `All Python Enhancement Proposals (PEPs)`
- Desired ZIM Icon –png (URL or attach one): `https://www.python.org/favicon.ico`
- Language (ISO 639-3): `eng`
- Is this a MediaWiki?: `no`

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/peps.python_en_all
I'll post the library link once ready

**Comment by RavanJAltaie** [comment]
The file is ready at the library
https://library.kiwix.org/viewer#peps.python_en_all_2024-02
