### ISSUE TITLE
New request: NixOS unofficial wiki

### ISSUE THREAD

**Issue by gtespe** [openzim/zim-requests#808]
- Website URL: https://nixos.wiki/
- License: MIT
- Desired ZIM Title: NixOS Wiki
- Desired ZIM Description: The NixOS unofficial user's wiki
- Desired ZIM Icon –png (URL or attach one): https://nixos.wiki/nixos-logo-small.png
- Language (ISO 639-3): eng
- Is this a MediaWiki?: no

**Comment by benoit74** [comment]
Duplicate of #636
