### ISSUE TITLE
New request: updating the Zim version of Chabadpedia, wiki in Hebrew

### ISSUE THREAD

**Issue by 586222** [openzim/zim-requests#810]
- Website URL: https://chabadpedia.co.il
- License: ** GNU Free Documentation License 1.2**
- Desired ZIM Title: **חב"דפדיה**
- Desired ZIM Description: **אנצקלופדיה חב"דית המקיפה את כלל מושגי ואישי חסידות חב"ד**
- Desired ZIM Icon:
**https://chabadpedia.co.il/index.php/%D7%A7%D7%95%D7%91%D7%A5:%D7%9C%D7%A2%D7%A8%D7%9A_%D7%94%D7%A8%D7%91%D7%99_%D7%A9%D7%9C%D7%99%D7%98%22%D7%90.png#mw-jump-to-license**
- Language (ISO 639-3): **Hebrew**
- Is this a MediaWiki?:  **yes**

**Comment by Popolechien** [comment]
This is a recurring demand (see #348) and there is, in fact, a recipe available but on hold as there is a recurring issue (see #217) :

Not sure what we can do in the short term, but medium term that is a use case where the community has a vested interest in supporting an upgrade to mwoffliner.
@586222 Do you know if chabadpedia is in any way related or within scope for the folks at chabad.org?

**Comment by 586222** [comment]
@Popolechien   First, thanks for the quick reply.

That's right, this is a repeated request for a number (#348). I would be very happy if you update the file. He is very old.

Chabadpedia is not so related to chabad.org, we are a wiki site. But the varieties of the sites talk about the same topics more or less.

**Comment by Popolechien** [comment]
@586222 When you say "we", are you by any chance related to the website admins? If yes, a first step would be to make sure that the website is running the latest Mediawiki, including visual editor.

**Comment by 586222** [comment]
@Popolechien Yes, I am one of the operators of the site. Wiki's media software is out of date and has no visual editor.

**Comment by RavanJAltaie** [comment]
@586222 Will you be able to install visual editor on your website?

**Comment by 586222** [comment]
@RavanJAltaie Due to a serious malfunction on the site, this is not possible.  thank you very much for the help.  This referral can be closed.

**Comment by RavanJAltaie** [comment]
@586222 Thank you for informing us.

**Comment by Popolechien** [comment]
@586222 Hey can you please check https://dev.library.kiwix.org/viewer#chabadpedia_he_all_maxi_2025-10/%D7%9E%D7%9C%D7%90%D7%9A#%D7%9E%D7%99%D7%9B%D7%90%D7%9C

Also, can you confirm the difference between this site and text.chabadpedia.org?
