### ISSUE TITLE
New request: github.com

### ISSUE THREAD

**Issue by SSBAGPC** [openzim/zim-requests#815]
- Website URL: https://github.com/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **github**
- Desired ZIM Description: **What do you want but please an entire github**
- Desired ZIM Icon –png (URL or attach one): https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
- Language (ISO 639-3): **what do you want**
- Is this a MediaWiki?: **no**
- And please make libzim available on windows, please

**Comment by kelson42** [comment]
@SSBAGPC Not sure I got you right, but if you want to have all GitHub in one ZIM, this is simply not doable for us, we don't have the hardware resources to do so.
