### ISSUE TITLE
ZIM Tags must be a semi-colon-separated list with no spaces

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#816]
When ZIM tags are configured in a recipe, if multiple values are passed they must be separated by a semi-colon without any spaces. E.g. `religion;catholicism` of [saint_libere](https://farm.openzim.org/recipes/saint_libere/config) is appropriate.

Two recipes have improper values:

| Recipe | ZIM Tags - current | ZIM Tags - corrected |
|--|--|--|
| fas-military-medicine | `preppers, medicine` | `preppers;medicine` |
| zimgit-medicine_en | `preppers, medical` | `preppers;medical` |

@RavanJAltaie please fix these two recipes
@Popolechien FYI since you probably configure this as well

FYI I've open an issue to find a better solution to warn you when you do improper configurations like these ones so that we do not fall into this trap again: https://github.com/openzim/zimfarm/issues/916 ; you will nevertheless need to be careful until this is implemented

**Comment by RavanJAltaie** [comment]
All Fixed.
