### ISSUE TITLE
Raspberry Pi Docs is failing

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#817]
See https://library.kiwix.org/viewer#rapsberry_pi_docs_2023-01

I see the recipe has been put on hold already but I can't find the file in downloads.kiwix.org ? Should be rapsberry_pi_docs_2023-01

@benoit74 Any idea there?

**Comment by benoit74** [comment]
It is in https://download.kiwix.org/zim/zimit/ (mind the typo in **rapsberry**)

**Comment by Popolechien** [comment]
Ok then let's delete https://download.kiwix.org/zim/zimit/rapsberry_pi_docs_2022-12.zim and https://download.kiwix.org/zim/zimit/rapsberry_pi_docs_2023-01.zim

**Comment by benoit74** [comment]
Done, library will be updated in about 1 hour.
