### ISSUE TITLE
New request: Wikimedia Cookbook

### ISSUE THREAD

**Issue by hamoudak** [openzim/zim-requests#818]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.wikibooks.org/wiki/Cookbook:Table_of_Contents
- License: Creative Commons 
- Desired ZIM Title: Wikimedia Cookbook
- Desired ZIM Description: A growing, world-wide, collection of recipes in English, with links to other languages.
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

Could anyone create this please ? !

**Comment by hamoudak** [comment]
could you please create the recipe for me ? I have waited so long . I think it will be useful for others too. thank you for your great efforts and I appreciate the whole work.

**Comment by Popolechien** [comment]
I would gladly encourage this however at this stage MWoffliner does not handle categories (so you could not see the list of cucumber recipes, for instance).

Another avenue would be using the [WP1 selection tool ](wp1.openzim.org): my own attempt failed, but I encourage you to try directly and play around your own zim file (the tool is open to anyone, you just need to use your wikimedia/wikibooks login) and let us know so we can reproduce on our end.

**Comment by hamoudak** [comment]
this tool is somehow difficult to my knowledge so I asked help from the best in here . I have created parts of this categories  with youzim a long last month but I liked to have them in one file. I also have noticed in wikibooks.zim what you're saying to me . If there's a chance to let any geek is interested of this request to help me , I'll be thankful to you . thank you for your tries on the page .

**Comment by hamoudak** [comment]
this tool is somehow difficult to my knowledge so I asked help from the best in here . I have created parts of this categories with youzim a long last month but I liked to have them in one file. I also have noticed in wikibooks.zim what you're saying to me . If there's a chance to let any geek is interested of this request to help me , I'll be thankful to you . thank you for your attemps on the page .

**Comment by hamoudak** [comment]
this tool is somehow difficult to my knowledge so I asked help from the best in here . I have created parts of this categories with youzim a long last month but I liked to have them in one file. I also have noticed in wikibooks.zim what you're saying to me . If there's a chance to let any geek is interested of this request to help me , I'll be thankful to you .  your attemps on the page truly appreciated .

**Comment by Popolechien** [comment]
Well the easy way would be to copy the list of pages into the tool and build the corresponding zim file from scratch (but then if there's 1,000 recipes that might be long and tedious).

**Comment by hamoudak** [comment]
okay am gonna try to do this, I do my best . thank you, Popolechien.

**Comment by hamoudak** [comment]
hiii Popolechien, i have made a list on wp1.openzim website and it ended successfully, see screenshots here https://github.com/openzim/wp1/issues/717

**Comment by hamoudak** [comment]
yes , you can . wish you a good day.

**Comment by hamoudak** [comment]
I have made a test with zimit image yesterday on this wikimedia_cookbook and it was very good to me, everthing works fine even categories, but with --depth="2". if you need the whole cookbook, I guess you can try this command: 

docker run -v %cd%/my-cookbook:/my-cookbook --name zimit_en.wikibooks.org_cookbook  ghcr.io/openzim/zimit:2.1.5 zimit  --description="A growing, world-wide, collection of recipes in English" --favicon="https://en.wikibooks.org/static/favicon/wikibooks.ico"   --name="wikimedia_cookbook_en_all" --workers="2"  --noMobileDevice  --diskUtilization 0  --output="/my-cookbook" --title="wikimedia cookbook" --url="https://en.wikibooks.org/wiki/Cookbook:Table_of_Contents" --keep --zim-lang="eng"
