### ISSUE TITLE
Remove Energypedia

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#824]
File is empty
https://download.kiwix.org/zim/other/energypedia_en_all_nopic_2021-02.zim
https://download.kiwix.org/zim/other/energypedia_en_all_maxi_2021-02.zim
https://download.kiwix.org/zim/other/energypedia_en_all_nopic_2021-01.zim
https://download.kiwix.org/zim/other/energypedia_en_all_nopic_2021-02.zim

**Comment by benoit74** [comment]
Done, library will be updated soon.
