### ISSUE TITLE
Remove Practical action

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#825]
© 2023 Practical Action Publishing. All Rights Reserved.

Not sure how it got there. Also it's mostly a publisher's catalogue, no useful content.
https://download.kiwix.org/zim/zimit/practical_action_en_all_2023-06.zim
https://download.kiwix.org/zim/zimit/practical_action_en_all_2023-12.zim

**Comment by benoit74** [comment]
Done, library will be updated soon.
