### ISSUE TITLE
Farsi websites to test with Zimit 2.0

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#826]
Sponsor finally came back with a list of websites that should be tested:

https://ir.voanews.com/
https://iranwire.com/fa/
https://www.radiozamaneh.com/
https://www.hra-news.org/

they also indicated having a relationship with them and could enquire about whitelisting if Cloudflare or the like is causing issues.

**Comment by benoit74** [comment]
- [iranwire.com](https://iranwire.com/fa/) and [hra-news.org](https://www.hra-news.org/) are served by Cloudflare
- [ir.voanews.com/](https://ir.voanews.com/) is served by Akamai
- [radiozamaneh.com/](https://www.radiozamaneh.com/) is protected by Deflect.ca

I'm pretty sure we will face a problem with Cloudflare (just like other websites), I don't know much about Akamai and Deflect.ca

I've created all recipes, please review them before activation.

I propose to do a first run without whitelisting to confirm which sites are causing an issue, and request the whitelisting only once we have confirmed there is a problem.

For the record, the whitelisting will have to be done for our `ondemand` worker, public IP `92.243.27.71` and `2001:4b98:dc0:43:f816:3eff:fe32:84fc/64`.

**Comment by benoit74** [comment]
Oups, I posted the message by mistake, I've not yet created all recipes. Sorry

**Comment by benoit74** [comment]
I've created all recipes, please fix the title, description and illustration (I had no idea what to put) and review other details (not sure they are all correct):
- iranwire.com: https://farm.openzim.org/recipes/iranwire.com_persian/edit
- hra-news.org: https://farm.openzim.org/recipes/hra-news.org_persian/edit
- ir.voanews.com: https://farm.openzim.org/recipes/ir.voanews.com_persian/edit
- radiozamaneh.com: https://farm.openzim.org/recipes/radiozamaneh.com_persian/edit

**Comment by RavanJAltaie** [comment]
@benoit74 all recipes are updated, shall I enable them or you'll take care of that?

**Comment by benoit74** [comment]
Thank you, I requested them so they start asap

**Comment by Popolechien** [comment]
LGTM
