### ISSUE TITLE
New request: Tom Lehrer’s Songs

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#827]
- Website URL: https://tomlehrersongs.com/
- License: ** Public domain **
- Desired ZIM Title: Tom Lehrer’s Songs
- Desired ZIM Description: All Tom Lehrer’s Songs: lyrics, music sheet, and/or MP3 audio files
- Desired ZIM Long Description: On November 26, 2022, Tom Lehrer released all his songs to the public domain: lyrics, music sheet, and/or MP3 audio files. Tom Lehrer’s satirical songs include such classics as: New Math, The Elements, National Brotherhood Week, Bright College Days, It Makes a Fellow Proud to Be a Soldier, Lobachevsky. In addition to these, all of the lesser-known songs he wrote and performed for the children’s television show The Electric Company are included.
- Desired ZIM Icon –png (URL or attach one): ?
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

Nota: 
- This ZIM should be created only once, source website won't get updated
- This ZIM should be created soon if possible, there is a shutdown notice on the website

```
NOTICE:
	
THIS WEBSITE WILL BE SHUT DOWN AT SOME DATE IN THE NOT TOO DISTANT FUTURE, SO IF YOU WANT TO DOWNLOAD ANYTHING, DON’T WAIT TOO LONG.
```

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/tomlehrersongs.com_en
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
File is ready in library
https://library.kiwix.org/viewer#tomlehrersongs.com_en_2024-02

**Comment by benoit74** [comment]
Reopening, file has been done with zimit2 and this is not yet OK, let's redo it with zimit1 for now

**Comment by RavanJAltaie** [comment]
File recreated with zimit 1.6.3 and succeeded.
The library link is:
https://library.kiwix.org/viewer#tomlehrersongs.com_en_2024-02

**Comment by benoit74** [comment]
Great!

**Comment by Rexadev** [comment]
@RavanJAltaie  Edit Description to `Official site for Lyrics, Sheet Music for songs by musical satirist Tom Lehrer`

**Comment by RavanJAltaie** [comment]
@Rexadev Done!
