### ISSUE TITLE
noted.lol

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#834]
- Website URL: https://www.noted.lol
- License: licensed via email (ticket [64011](https://kiwix.freshdesk.com/a/tickets/64011))
- Desired ZIM Title: Noted.lol
- Desired ZIM Description: An independent publication about self-hosting and open-source software
- Desired ZIM Icon –png (URL or attach one): https://noted.lol/content/images/2023/11/Logo-2.1.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

Note: the site owner went through zimit already and it ran fine.

**Comment by RavanJAltaie** [comment]
Recipe created, succeeded and the file is ready at the library
https://library.kiwix.org/viewer#noted.lol_en_2024-02

**Comment by benoit74** [comment]
Reopening, file is not OK and was done with zimit2 which is not ready.

**Comment by RavanJAltaie** [comment]
File has been recreated with zimit 1.6.3, succeeded and moved to library
https://library.kiwix.org/viewer#noted.lol_en_2024-02
