### ISSUE TITLE
Is scp_wiki ready to move to main?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#835]
The zim file is currently in [dev.library](https://dev.library.kiwix.org/#lang=eng&q=scp) (recipe is [here](https://farm.openzim.org/recipes/scp-wiki_en/edit)) and seems overall fine, yet it has been flagged in #731 . What's the status there?

**Comment by benoit74** [comment]
I think the problem is some instability in zimit processing, but if ZIM content is ok then you should probably proceed to main.

**Comment by Popolechien** [comment]
Ah but I see that [scp-wiki_en_all_2023-01.zim](https://mirror.download.kiwix.org/zim/.hidden/dev/scp-wiki_en_all_2023-01.zim) is 4G while [scp-wiki_en_all_2023-12.zim](https://mirror.download.kiwix.org/zim/.hidden/dev/scp-wiki_en_all_2023-12.zim) is only 301 MB. I did poke around some more and there is, in fact, quite a bit of content missing. Shame.
