### ISSUE TITLE
חב"דפיה 

### ISSUE THREAD

**Issue by simchafisch** [openzim/zim-requests#837]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://chabadpedia.co.il/
- License: **Creative Commons | Public domain 
- Desired ZIM Title: **חב"דפדיה**
- Desired ZIM Description**חב"דפדיה הינה אנציקלופדיה חב"דית, חופשית לקריאה, כתיבה ועריכה**
- Desired ZIM Icon –png (URL or attach one): https://static.timesofisrael.com/blogs/uploads/2020/04/Lubavitcher_Rebbe_circa_1987.jpg
- Language (ISO 639-3): **עברית**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment]
see discussion at #810 - TL;DR: site is not up to date and for some reason the admins can not update it.
