### ISSUE TITLE
Fix `los_miserables_audiobook_es` wrong ZIM name metadata and ZIM filename

### ISSUE THREAD

**Issue by B-root74** [openzim/zim-requests#839]
I think that following ZIM does not obey [openZIM naming convention](https://github.com/openzim/overview/wiki/ZIMs-Naming-Convention).

```
"id": "c56b5d85-cf2c-b284-3701-1e5ecfb8471f",
"size": "2090699",
"url": "https://download.kiwix.org/zim/other/los_miserables_audiobook_es_2022-03.zim.meta4",
"mediaCount": "152",
"articleCount": "391",
"title": "Los Miserables - Audiolibro",
"description": "Los Miserables  by Victor Hugo (1802 - 1885) Full Book, Part 1: https://www.youtube.com/watch?v=wHn3cJwUOwk Full Book, Part 2: https://www.youtube.com/watch?v=Ml0XwA5uBbI  Copyright: CC. Both the book and the audio are in the public domain. The audio is the records of LibriVox.",
"language": "spa",
"creator": "Mongope",
"publisher": "Kiwix",
"name": "los_miserables_audiobook_es",
"tags": "_category:other;_videos:yes;_ftindex:no;_pictures:yes;_details:yes",
"date": "2022-03-16",
```

ZIM Name metadata is `los_miserables_audiobook_es` while it should probably be `los-miserables-audiobook_es_all`.
ZIM filename is `los_miserables_audiobook_es_2022-03` while it should probably be `los-miserables-audiobook_es_all-2022-03`.

You might also want to fix description which does not match the spec recommendation (80 chars).

Or (second alternative) you might decide to simply delete this file, since according to original issue #137 and last comment https://github.com/openzim/zim-requests/issues/137#issuecomment-1336250569 it seems there is a kind of copyright issue associated with the ZIM content.

**Comment by B-root74** [comment]
Recipe seems to be failing because playlists / channel have been suspended: https://farm.openzim.org/recipes/los_miserables_audiobook

**Comment by kelson42** [comment]
Indeed the source has vanished and probably, we will have to remove both recipe and ZIM.

**Comment by B-root74** [comment]
The source has not purely vanished, Youtube decided to terminate the source because of multiple third-party copyright infringement claims. These claims would probably apply to openZIM as well.

**Comment by kelson42** [comment]
> The source has not purely vanished, Youtube decided to terminate the source because of multiple third-party copyright infringement claims.

How do you know that?

**Comment by B-root74** [comment]
See screenshot in last comment of https://github.com/openzim/zim-requests/issues/137#issuecomment-1336250569

**Comment by benoit74** [comment]
Since Youtube channel has been suspended for copyright issues, and given we would like to update to VP9 instead of VP8 for proper ZIM operation, I propose to delete the recipe and delete the ZIMs.

@Popolechien @RavanJAltaie ok for you?

**Comment by RavanJAltaie** [comment]
@benoit74 Yes, we should delete them.
I've deleted the recipe.
For the files, we have both files below for you to delete:
1- https://download.kiwix.org/zim/other/los_miserables_audiobook_es_2021-12.zim
2- https://download.kiwix.org/zim/other/los_miserables_audiobook_es_2022-03.zim

**Comment by benoit74** [comment]
ZIM deletion tracked in https://github.com/openzim/zim-requests/issues/1101
