### ISSUE TITLE
wikipedia nintendo

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#84]
_From @amirh123123 on March 13, 2018 15:29_

hi please make zim file for nintendo articles on wikipedia thanks

_Copied from original issue: openzim/mwoffliner#245_

**Comment by kelson42** [comment]
There is no wikiproject Nintendo on Wikipedia... this is going to be hard.

**Comment by kelson42** [comment]
_From @amirh123123 on March 18, 2018 12:33_

hi please add articles from this address 
https://en.wikipedia.org/wiki/Category:Nintendo_task_force_articles

**Comment by RavanJAltaie** [comment]
@amirh123123 We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
