### ISSUE TITLE
TED topic Humanities has no suitable videos

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#849]
## Recipe

https://farm.openzim.org/recipes/ted_topic_humanities

## Issue

TED topic [humanities](https://www.ted.com/topics/humanities) has only two videos: https://ted.com/talks/stephen_gianotti_lessons_from_the_african_elephant and https://ted.com/talks/william_sieghart_the_connective_potential_of_poetry

Both videos seems to be somehow broken on TED side, at least there is no download link found by the scraper and when opening above links manually in my browser, the video fails to play on TED website

I've disabled the corresponding recipe, we should check in few months if the problem is resolved on TED side.

**Comment by Popolechien** [comment]
I'm watching the elephant video and it looks fine so far (I'm 1/3 in). What's the issue?

**Comment by benoit74** [comment]
That's interesting, it is not loading on Firefox but works well on Chrome and Brave ... Did you used on of these?

**Comment by Popolechien** [comment]
I'm on Chrome.

**Comment by benoit74** [comment]
OK, then the problem is on our side, I've opened the issue in scraper repo.

**Comment by benoit74** [comment]
Upstream issue fixed, not yet released so I updated the recipe to use `dev` tag temporarily and confirm ZIM is OK. I requested the recipe.
