### ISSUE TITLE
wikipedia games

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#85]
_From @amirh123123 on March 13, 2018 17:7_

hi please make zim file for wikipedia games articles video games bord games sports games and many more

_Copied from original issue: openzim/mwoffliner#246_

**Comment by RavanJAltaie** [comment]
@amirh123123 We are working on a tool which makes it possible to include all the articles related to a specific project in 1 zim file, it should be ready soon, I will close this issue for now and if you still need these project articles please open a new issue with these specific steps mentioned in the link below so we can respond quickly and effectively to your request
https://github.com/openzim/zim-requests/blob/master/README.md
