### ISSUE TITLE
Unofficial Elder Scrolls Pages (wiki)

### ISSUE THREAD

**Issue by TonytusIII** [openzim/zim-requests#855]
Please use the following format for a ZIM creation request (and delete unnecessary information)

Website URL: https://en.uesp.net/
License: Attribution-ShareAlike 2.5 License
Desired ZIM Title: En_Uesp.zim
Desired ZIM Description: "A collaborative source for all knowledge on the Elder Scrolls series since 1995"
Desired ZIM Icon –png (URL or attach one): https://en.uesp.net/favicon.ico
Language (ISO 639-3): eng
Is this a MediaWiki?: Yes

**Comment by TonytusIII** [comment]
Note: if there is a resource where I can pay to have this site made into a zim file already, please let me know, it's just too big for zimit's 4GB limit.

**Comment by kai11** [comment]
https://farm.openzim.org/recipes/elder-scrolls-wiki/config
This recipe dont work

**Comment by Popolechien** [comment]
Recipe suspended until MWoffliner update. Will close as duplicate.

**Comment by kai11** [comment]
@Popolechien what kind of update is? Can you provide detalis? For example PR or issue I can subscribe to.
