### ISSUE TITLE
ZIMs of the Rachel project

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#86]
_From @amirh123123 on March 12, 2018 14:50_

http://dev.worldpossible.org/cgi/rachelmods.pl have more files please make files to zim format example i download medline plus but format is html i want all files to this  address is zim files thanks

_Copied from original issue: openzim/mwoffliner#240_

**Comment by kelson42** [comment]
Many of them are already in ZIM format, what do you need precisely ?

**Comment by kelson42** [comment]
_From @amirh123123 on March 16, 2018 9:5_

hi 
Files that do not have a zim format

**Comment by RavanJAltaie** [comment]
@Popolechien @kelson42 do we have these zim files already?

**Comment by Popolechien** [comment]
@RavanJAltaie I think that a separate ticket should be opened for each of the websites listed here that we do not already have https://rachel.worldpossible.org/content
