### ISSUE TITLE
Remove files

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#873]
Please remove the files below:

1- https://download.kiwix.org/zim/zimit/bestedlessons.org_en_all_2024-02.zim (recipe disabled)
2- https://download.kiwix.org/zim/videos/madrasa_astronomy_ar_all_2024-03.zim (name corrected)
3- https://download.kiwix.org/zim/videos/madrasa_biology_ar_all_2024-03.zim (name corrected)
4- https://download.kiwix.org/zim/videos/madrasa_chemistry_ar_all_2024-03.zim (name corrected)
5- https://download.kiwix.org/zim/videos/madrasa_futureencyclopedia_ar_all_2024-03.zim (name corrected)

**Comment by benoit74** [comment]
Done, library will be updated in at most 30 minutes

**Comment by RavanJAltaie** [comment]
@benoit74 Thank you
