### ISSUE TITLE
Make a ZIM file of Unencylopedia

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#88]
_From @kelson42 on February 4, 2018 7:48_

http://uncyclopedia.wikia.com

_Copied from original issue: openzim/mwoffliner#188_

**Comment by kelson42** [comment]
Original website has been closed. It seems we have now two forks:
* https://en.uncyclopedia.co/
* https://uncyclopedia.ca/wiki/Main_Page

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/unencylopedia
