### ISSUE TITLE
New request: WROLPi Youtube Channel

### ISSUE THREAD

**Issue by lrnselfreliance** [openzim/zim-requests#929]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.youtube.com/@wrolpi/videos
- License: Creative Commons
- Desired ZIM Title: WROLPi
- Desired ZIM Description: A software package that allows you to create your own off-gird library.
- Desired ZIM Icon –png (URL or attach one): https://github.com/lrnselfreliance/wrolpi/blob/master/icon.png
- Language (ISO 639-3): en
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
@lrnselfreliance Thanks for your request.
I've reviewed the youtube channel, there is only 2 videos there.
I'll close the issue for now, and you are very welcome to request the channel again once you have a full release and considerable number of videos.
