### ISSUE TITLE
New request: Learning Self-Reliance

### ISSUE THREAD

**Issue by lrnselfreliance** [openzim/zim-requests#930]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.youtube.com/@lrnselfreliance
- License: Creative Commons
- Desired ZIM Title: Learning Self-Reliance
- Desired ZIM Description: A Youtube channel about prepping, survival, and bee keeping.
- Desired ZIM Icon –png (URL or attach one): https://yt3.googleusercontent.com/ytc/AIdro_kpKGB1bVaOu8kYB_tiiXlXg2ECWHHNqCAncrk1=s176-c-k-c0x00ffffff-no-rj
- Language (ISO 639-3): en
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/lrnselfreliance_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
The recipe is failing, I guess it's the same bug for issues #1146 and #1145

**Comment by benoit74** [comment]
The two issues you mentioned had two different underlying issues, so it can be same bug, there was two bugs ^^

I don't take time to investigate more, using `dev` image is again sufficient for the moment (but please don't do it systematically, this is very exceptional and should be decided only by a dev somehow).

**Comment by benoit74** [comment]
ZIM is ready for review at https://dev.library.kiwix.org/#lang=&q=self+learning

**Comment by Popolechien** [comment]
LGTM

**Comment by benoit74** [comment]
Requested in prod, will update with link here once ready.

**Comment by benoit74** [comment]
ZIM ready in production: https://library.kiwix.org/#lang=eng&q=self-reliance
