### ISSUE TITLE
New request: ifixit english updated

### ISSUE THREAD

**Issue by TheWanderer1983** [openzim/zim-requests#932]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.ifixit.com/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: IfixIt English latest date
- Desired ZIM Description: **Short description (80 characters or less)** Update ifixit to latest date in english
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **abc** English
- Is this a MediaWiki?: **yes | no** no

**Comment by kelson42** [comment]
This will happen in the few next weeks. Closing as there is nothing more we can do.
