### ISSUE TITLE
Blender Studio

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#939]
- Website URL: https://www.youtube.com/watch?v=u9lj-c29dxI&list=PLav47HAVZMjnTFVZL-aImCQIC0uLZtNCz
- License: ** Creative Commons Attribution 4.0.**
- Desired ZIM Title: **Blender films**
- Desired ZIM Description: **Iconic Blender Open Movies.**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Blender_logo_no_text.svg/293px-Blender_logo_no_text.svg.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/blenderstudio_en_all
I'll update the library file once ready

**Comment by benoit74** [comment]
Recipe is crap, I've disabled it for now

**Comment by benoit74** [comment]
Recipe fixed and moved to https://farm.openzim.org/recipes/studio.blender.org_en_open-movies to align with ZIM name and better aligne ZIM name with content

**Comment by Popolechien** [comment]
Checked it and it works. Moved to PROD.

**Comment by benoit74** [comment]
Shouldn't we create the ZIM with high quality videos? I mean, there are only few videos, current ZIM is fairly small (<140M) and the purpose of these films is somehow their "beauty", which is not that cool in low quality. Generally speaking low quality makes sense to limit the ZIM size and because low quality is sufficient to get the essential of the video. 
Shall I give it a try in dev?

**Comment by Popolechien** [comment]
@benoit74 Yep good idea

**Comment by benoit74** [comment]
This multiplied the ZIM size by more than 10x. But I find this is way better to propose this ZIM than the low quality one. 
Low res: https://library.kiwix.org/#lang=eng&q=blender+studio
High res: https://dev.library.kiwix.org/#lang=eng&q=blender+studio

WDYT?

**Comment by Popolechien** [comment]
Low res fullscreen:
![Image](https://github.com/user-attachments/assets/d8cb2ab6-0853-4eee-8e9e-88a654308c48)
High res:
![Image](https://github.com/user-attachments/assets/f468b2d8-475a-418f-bad1-7d3754ed026b)
Much better indeed and well worth it.

**Comment by benoit74** [comment]
Update of prod ZIM requested with high res.
