### ISSUE TITLE
Encyclopedia of Turkey

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#94]
_From @kelson42 on May 5, 2017 6:47_

In turkish

_Copied from original issue: openzim/mwoffliner#67_

**Comment by kelson42** [comment]
_From @Popolechien on July 29, 2017 6:51_

Is this really needed? It's not like Venezuela and Tunisia were huge successes.

**Comment by kelson42** [comment]
Not sure. Was a second choice' as full WPTR seems difficukt to implement.

**Comment by Popolechien** [comment]
Closing for now.
