### ISSUE TITLE
wikipedia_en_medicine is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#943]
### Recipe URL

https://farm.openzim.org/recipes/wikipedia_en_medicine

### Last log lines

```true
[error] [2024-03-25T17:39:10.188Z] Error downloading article Remineralisation_of_teeth
[error] [2024-03-25T17:39:10.189Z] Failed to run mwoffliner after [2991s]: {
	"name": "AxiosError",
	"message": "Request failed with status code 504",
	"url": "https://en.wikipedia.org/api/rest_v1/page/html/Remineralisation_of_teeth",
	"status": 504,
	"responseType": "json",
	"data": {
		"type": "https://mediawiki.org/wiki/HyperSwitch/errors/unknown_error",
		"method": "get",
		"detail": "upstream request timeout",
		"uri": "/en.wikipedia.org/v1/page/html/Remineralisation_of_teeth"
	}
}
[error] [2024-03-25T17:39:10.189Z] 

**********

Request failed with status code 504

**********
```

### How many times the recipe failed in a row?

Once

### How many ZIM have been produced before failure?

Zero

### Which action did you undertake so far?

I have requested the recipe again to confirm failure

### What's next?

This can be fixed by content team

### More details

To be monitored

**Comment by kelson42** [comment]
Was a sporadic upstream backend error. The last two task [have run successfuly](https://farm.openzim.org/recipes/wikipedia_en_medicine).
