### ISSUE TITLE
NHS website

### ISSUE THREAD

**Issue by Giugiulinu** [openzim/zim-requests#947]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://www.nhs.uk/
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **NHS**
- Desired ZIM Description: **NHS website**
- Desired ZIM Icon –png (URL or attach one): https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/National_Health_Service_%28England%29_logo.svg/800px-National_Health_Service_%28England%29_logo.svg.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment]
© Crown copyright -> cannot be copied, sorry.
