### ISSUE TITLE
ZIM of wikifab

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#95]
_From @dattaz on October 1, 2017 12:54_

ZIM of http://wikifab.org/ and http://lab.lowtechlab.org/ (they use wikilab which is based on mediawiki)

_Copied from original issue: openzim/mwoffliner#139_

**Comment by kelson42** [comment]
_From @Popolechien on October 10, 2017 8:9_

The site is available in five languages, we should generate five separate zim files (it's probably obvious but just in case ^^).

**Comment by kelson42** [comment]
I should have try, but I see two difficulties:
* Multilanguage wiki (with custom solution to switch from one language to an other)
* Video coming from youtube (not supported in mwoffliner)

**Comment by Popolechien** [comment]
The website is under copyright. As indicated elsewhere, we won't zim non-free content without clear consent from the owner. Closing for now.
