### ISSUE TITLE
Request: musicbrainz.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#954]
- Website URL: https://musicbrainz.org/
- License: **Public domain**
- Desired ZIM Title: MusicBrainz
- Desired ZIM Description: Song Metadata Database
- Desired ZIM Icon –png (URL or attach one): https://static.metabrainz.org/MB/header-logo-1f7dc2a.svg
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

- Use database https://metabrainz.org/datasets/postgres-dumps#musicbrainz instead of scraping - 
1. https://musicbrainz.org/search?query=
2. https://musicbrainz.org/release-group/
3. https://musicbrainz.org/release/
4. https://musicbrainz.org/recording/
5. https://musicbrainz.org/label/
6. https://musicbrainz.org/artist/

- Exclude: https://picard.musicbrainz.org/

**Comment by Popolechien** [comment]
Musicbrainz is a database, we would need to build a dedicated scraper for that and I'm not sure what the use case would be for offline end-users.

**Comment by Rexadev** [comment]
Only scrape Doumentation at 
https://musicbrainz.org/doc/*
https://musicbrainz.org/genres
https://musicbrainz.org/instruments
https://musicbrainz.org/relationships

@Popolechien
