### ISSUE TITLE
ZIM hesperian.org wiki

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#96]
_From @kelson42 on August 17, 2017 20:17_

http://en.hesperian.org/hhg/A_Health_Handbook_for_Women_with_Disabilities

_Copied from original issue: openzim/mwoffliner#122_

**Comment by RavanJAltaie** [comment]
Rejected
The License in the website:
© Copyright 2022 Hesperian Health Guides. All Rights Reserved.
