### ISSUE TITLE
youscribe_primaire has changed warehouse path

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#961]
youscribe_primaire was previously hosted in `other` warehouse path. Zimfarm recipe is now configured to use `zimit`.

This cause the https://github.com/kiwix/k8s/issues/181 incident.

For now, I've disabled the recipe and archived the `zimit/youscribe_fr_primaire_2024-04.zim`.

Should we move all youscribe_primaire ZIMs to zimit warehouse path? all youscribe?

Once this question is settled, I can then restore the archived `zimit/youscribe_fr_primaire_2024-04.zim`

**Comment by benoit74** [comment]
@RavanJAltaie what about this ZIM? Do you wanna move it to `zimit` or keep it in `other`?

**Comment by RavanJAltaie** [comment]
@benoit74 this one we can keep it in other to follow the same rule as the offliner is nautilus not zimit.
Thanks in advance

**Comment by benoit74** [comment]
OK, I've restored the new 2024_04 ZIM in `other` warehouse path, updated the recipe warehouse path and re-enabled it. Library will be updated with new 2024_04 ZIM automatically.
