### ISSUE TITLE
editions-ganndal_fr_fo-livres has changed warehouse path

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#962]
`editions-ganndal_fr_fo-livres` was previously hosted in `zimit` warehouse path. Zimfarm recipe is now configured to use `other`.

This cause a reoccurence of the https://github.com/kiwix/k8s/issues/181 incident.

For now, I've disabled the recipe and archived the `other/editions-ganndal_fr_fo-livres_2024-04.zim`.

Should we move all editions-ganndal_fr_fo-livres ZIMs to zimit warehouse path? all youscribe?

Once this question is settled, I can then restore the archived `other/editions-ganndal_fr_fo-livres_2024-04.zim`.

**Comment by RavanJAltaie** [comment]
I checked that you've returned the warehouse path to (Other) then disabled the recipe.
I believe for both Ganndal and Youscribe recipes, let's keep them for now in Other warehouse path, as we are having a more comprehensive discussion about warehouse paths and how to categorize files in the future.

**Comment by benoit74** [comment]
You got it wrong. I've only disabled the recipe, I did not changed the warehouse path, only you did. 

Please read again the two tickets (this one and https://github.com/openzim/zim-requests/issues/961) first comment with scrutiny.

`editions-ganndal_fr_fo-livres` was previously in `zimit` warehouse path. You changed it to `other` warehouse path.

`youscribe_primaire` was previously in `other` warehouse path. You changed it to `zimit` warehouse path.

It is pretty easy for me to do the necessary to change the warehouse path, we just need to synchronize, i.e. you need to inform me of the needed change before running again the recipe.

What do you want to do for this recipe? And please explain what you what to do for youzimit in youzimit ticket, do not mix stuff, it is already sufficiently complex!

**Comment by RavanJAltaie** [comment]
@benoit74 Apologies for mixing stuff. In regards to editions-ganndal_fr, I changed the warehouse path because the offliner is nautilus, I learned that Zimit is only for recipes made with zimit offliter, that's why I changed the warehouse path.
Now for this case, can we keep it in (Other) and enable the recipe? or it will cause a problem to the system?

**Comment by benoit74** [comment]
Of course we can, let met just reconfigure the warehouse for that and we will be able to re-enable the recipe.

**Comment by benoit74** [comment]
I've move the files in the warehouse, library will be updated soon. 

I've kept only the last ZIM which ran in the Zimfarm: https://farm.openzim.org/pipeline/e8d5bcd1-3589-4490-91ab-941e66f506ce

I've re-enabled the recipe (probably no need to run it again, the library will automatically be updated with the ZIM I mention above in less than one hour).
