### ISSUE TITLE
ncert_audiobooks is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#965]
### Recipe URL

https://farm.openzim.org/recipes/ncert_audiobooks

### Last log lines

```true
zimit: error: argument --waitUntil: invalid choice: 'load,networkidle0' (choose from 'load', 'domcontentloaded', 'networkidle', 'load,domcontentloaded', 'load,networkidle', 'domcontentloaded,networkidle')
```

### How many times the recipe failed in a row?

Many

### How many ZIM have been produced before failure?

Many

### Which action did you undertake so far?

I have disabled the recipe for now

### What's next?

This has to be fixed by dev team (upstream scraper / zimfarm problem)

### More details

This has been originally reported by @kelson42 

This is a known upstream issue https://github.com/openzim/zimit/issues/289 which is not intended to be fixed before zimit2 release.

**Comment by benoit74** [comment]
To be precise, `networkidle0` is the proper value for the crawler but it is not yet supported by the scraper.

I've aligned the few recipes which where still mentioning `networkidle` since it is not supported by the crawler anymore anyway.

I've disable all recipes needing the `load,networkidle0` setting:
- https://farm.openzim.org/recipes/devdocs.io
- https://farm.openzim.org/recipes/lesfondamentaux
- https://farm.openzim.org/recipes/stacks.math.columbia.edu
- https://farm.openzim.org/recipes/benyehuda.org_he_all
- https://farm.openzim.org/recipes/maison-des-maternelles
- https://farm.openzim.org/recipes/ncatlab
- https://farm.openzim.org/recipes/ncert_audiobooks
- https://farm.openzim.org/recipes/penser-critique
- https://farm.openzim.org/recipes/birds-of-ladakh

The following recipe was already disabled:
- https://farm.openzim.org/recipes/perseus-hopper

**Comment by benoit74** [comment]
@Rexadev what do you mean by useless? the ZIM is not working? or do you just want to say that you were the original requestor and do not use it anymore? I'm not sure to get it right. 

If you just wanna say that you do not use it anymore, we do not care indeed. Once we've made the decision to create and publish a ZIM, we are not anymore in a position to know who is using this ZIM. There might be way more users than the original requestor. So unless we have content or copyright issues, we usually do not stop to publish a ZIM.

**Comment by Rexadev** [comment]
I am not the original requester and I am saying the website is useless it is Indian education books' audio book for class 5 and below mostly and mostly for literature which I think is better used directly via website

1.  While we at it, We should add more categories to Library and Metadata, I asked about it ~2years back (and said I will manually tag each Zim if they want me to) and they said they will get to it later.

Zim Library categories are bad. Categories should be by Topic. There Should be more categories, some are  - Gaming, Science, Math, Computer, Computer-Linux, Prepper

Example - MathOverflow has 'Stack exchange' as category which is it's source and is about topic Maths

2. Better Title 

Add nopic maxi to Title
![image](https://github.com/openzim/zim-requests/assets/62152714/13472d02-15c4-4c59-9f20-487a83cfc0c1)

Don't have to use exact title as website can use better title for understanding in content of Zim library

3. Better descriptions

- Add website URL to description
- Better describe them

4. Add Rating to zim quality and website content quality

5. Add a counter to downloads to better understand Zim usage. Trending page is possible


@benoit74

**Comment by benoit74** [comment]
> I am not the original requester and I am saying the website is useless it is Indian education books' audio book for class 5 and below mostly and mostly for literature which I think is better used directly via website

How do you permit yourself to judge other persons use cases? I'm glad to know you find it useless, but it does not help us at all. Our main usecase is for people which are **offline**, so by design not able to access the website 🤣

While sometimes relevant, all your other comments are completely off-topic and we are already doing our best to progress on these topics. I've noted that you volunteer to help on content metadata sanitation. We first need to ensure internally we are all aligned, but we might well come back to ask for your help if you accept we have our own guidelines on what we want to do which might not be aligned with your point of view.

**Comment by Rexadev** [comment]
> How do you permit yourself to judge other persons use cases?

I am saying Zim is not ideal for this website. For the some people that find the site useful may download the content manually, zims are bigger.

**Comment by Popolechien** [comment]
Yup looks good, thanks.

**Comment by benoit74** [comment]
File move to prod, thank you
