### ISSUE TITLE
New request: create one "all TED videos" ZIM

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#969]
We are close to publish many TED ZIMs with videos filtered per topic (i.e. we will have one ZIM per TED topic).

What about creating one "all TED videos" ZIM, where we would fetch TED videos of all topics, no matter the associated topic? 

I would personally prefer to use such a ZIM (even if quite big, probably in the order of 100GB) rather than choosing which topic I prefer and having videos duplicated between the ZIMs (because the topics I like are in fact close to one another and multiple videos are hence present in multiple topics / ZIMs I've chosen).

**Comment by Popolechien** [comment]
@RavanJAltaie thoguhts?

**Comment by benoit74** [comment]
I propose:
- Recipe Name: ted_topic_all
- ZIM Name: ted_mul_all
- Title: TED all
- Description: The big collection of ALL videos published in any TED topic

**Comment by RavanJAltaie** [comment]
I agree with @benoit74 suggestion but truly I don't know why shall we do this?
This will be a very big file with ultimately few people who will want/be able to download it.
So what's the point?

**Comment by Popolechien** [comment]
> I would personally prefer to use such a ZIM (even if quite big, probably in the order of 100GB) rather than choosing which topic I prefer and having videos duplicated between the ZIMs

I am not convinced either but then the cost is minimal and in a long-tail scenario I guess we'll always have users going for one or the other.

**Comment by benoit74** [comment]
Recipe created and requested: https://farm.openzim.org/recipes/ted_topic_all

**Comment by benoit74** [comment]
Task failed due to https://github.com/openzim/ted/issues/213

I passed the list of all topics "manually". 

It made me realize there is 5 new topics (generosity, wildlife, reproductive health, artificial intelligence, tech). I've created the corresponding recipes and they've started automatically.

**Comment by Popolechien** [comment]
> It made me realize
I take it you realized it because these names struck you as new, but there is no automatized way to know when a new topic appears?

**Comment by benoit74** [comment]
> I take it you realized it because these names struck you as new, but there is no automatized way to know when a new topic appears?

Just the total number of recipes was displayed and it said "360" where I knew it was supposed to be "355".

Creating again the missing recipes is mostly automated, I "just" need to run a script on my machine. I still prefer to not fully automate this since it is quite important to check before really requesting the new topics, should the tool go wild for instance.

I propose to setup a workflow to create a quarterly issue to update the list of recipes (it takes me between 5 minutes - if nothing needs to be done - to 15 minutes - if new recipes needs to be created and I need to check them - to run this). Would that be ok?

**Comment by Popolechien** [comment]
LGTM

**Comment by RavanJAltaie** [comment]
LGTM as well.

**Comment by benoit74** [comment]
ZIM ready at https://library.kiwix.org/#lang=&q=all+ted

File size is is little bit less than 79GB. Interesting since total size of all other TED ZIMs is 419GiB.

**Comment by Popolechien** [comment]
> File size is is little bit less than 79GB

Do we know how many videos are in there? I suspect the reduced size tells us a lot about how many duplicates are used over several topical lists.

**Comment by Popolechien** [comment]
Ah, I see 165 pages with 40 videos each = 6600 TEDs

**Comment by kelson42** [comment]
This can also be checked with tge "Counter* ZIM metadata

**Comment by benoit74** [comment]
Yep, see https://library.kiwix.org/raw/ted_mul_all_2024-07/meta/Counter
