### ISSUE TITLE
Request: hindupedia.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#971]
- Website URL: https://hindupedia.com/en/Main_Page
- License: Probably Public Domain
- Desired ZIM Title: hindupedia
- Desired ZIM Description: Hinduism Encyclopedia
- Desired ZIM Icon –png (URL or attach one): https://hindupedia.com/images/hp_banner_shreyans-2.gif
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
@Rexadev Please be informed that we can't accept (Probably public domain) as License.
I tried to confirm but there is no information in the website about the License.
I will close the issue for now, if you can contact the owners and confirm the License, feel free to re open the issue.
