### ISSUE TITLE
New request: https://game8.co/games/[TITLE] compatibility 

### ISSUE THREAD

**Issue by JonathanCopeland** [openzim/zim-requests#974]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://xxx
- License: **Creative Commons | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **My title**
- Desired ZIM Description: **Short description (80 characters or less)**
- Desired ZIM Icon –png (URL or attach one): https://example.com/example_icon.png
- Language (ISO 639-3): **abc**
- Is this a MediaWiki?: **yes | no**

**Comment by Popolechien** [comment]
@JonathanCopeland Please fill in the requested fields when opening a request. You ask something of us, the service is free, the effort we require from you is fairly minimal I believe.
