### ISSUE TITLE
per-language phet ZIMs

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#976]
Although we have a whole category for it, we are only producing two ZIM files out of PhET: an English only one and a multi one that contains all content.

I believe every supported language deserves its own individual ZIM file.

For once, it will bring clarity as it will allow proper metadata with localized titles and descriptions.

it will also make the `mul` version less appealing, probably rarely used even. Since phet is very popular and phet-mul is the only non-english option, it's included in many setups (including hotspot ones). The fact that it supports, even barely, so many languages, including that single ZIM usually pollutes the Language filters of all kiwix readers.

It certainly isn't Content's job to fix reader's UX issues but it made it stand out and reveal the fact that PhET is not that useful as a multilang version. A single ZIM (or two) would most likely satisfy most users.

**Comment by rgaudin** [comment]
> There was also a discussion somewhere that `mul` zims weren't that great an idea to begin with.

Yes, I now fall short of actually useful examples.

**Comment by kelson42** [comment]
> Although we have a whole category for it, we are only producing two ZIM files out of PhET: an English only one and a multi one that contains all content.
> 
> I believe every supported language deserves its own individual ZIM file.

I don't get it, you see at http://download.kiwix.org/zim/phet/ that we have one per language?!
