### ISSUE TITLE
New request: https://w3schools.com

### ISSUE THREAD

**Issue by MrnateGeek** [openzim/zim-requests#977]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://w3schools.com
- License: Public domain (I hope its the right license but I know there is NONE of copyrighted content)
- Desired ZIM Title: W3Schools
- Desired ZIM Description: Well organized and easy to understand Web building tutorials...
- Desired ZIM Icon –png (URL or attach one): https://www.w3schools.com/apple-touch-icon.png
- Language (ISO 639-3): en
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
@MrnateGeek It litterally took one second to find `Copyright 1999-2024 by Refsnes Data. All Rights Reserved` at the bottom of the page, and an additional 30s to find this on the Terms of Service page:
```
Not Favorable Use:
Copying for profitable or commercial use.
Massive or verbatim copying.
Copying large quantities.
```

Unfortunate but above everything please be careful.

**Comment by MrnateGeek** [comment]
I did not know that, I guess I learned something. I also tried to do this myself and it only managed to get one page so it would fail anyway if you was going to let this go thru. I was thinking the docs its self is public domain, they don't own Vue.JS, HTML, CSS, JavaScript and all that. But if it does not allow you to crawl the website, its better to leave it alone and deny this request
