### ISSUE TITLE
New request: https://scientific-alliance.obscurative.ru

### ISSUE THREAD

**Issue by ghost** [openzim/zim-requests#983]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://scientific-alliance.obscurative.ru
- License: Creative Commons Attribution-ShareAlike 3.0 License
- Desired ZIM Title: Андивионский Научный Альянс
- Desired ZIM Description: Межмировой центр возможностей и приключений
- Desired ZIM Icon –png (URL or attach one): https://files.scientific-alliance.obscurative.ru/local--files/admin%3Amanage/logo
- Language (ISO 639-3): rus
- Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe Created
https://farm.openzim.org/recipes/scientific-alliance.obscurative.ru_ru_all
I'll update the library file link once ready
