### ISSUE TITLE
Delete code.org zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#987]
Content is missing at lesson level, see for instance videos and exercises at https://library.kiwix.org/content/code.org_en_all_2024-04/A/studio.code.org/s/csp3-virtual

File to delete:
https://download.kiwix.org/zim/zimit/code.org_en_all_2024-04.zim

I have put the recipe on hold and point to /dev

**Comment by benoit74** [comment]
Done, library will be updated soon
