### ISSUE TITLE
Algorithms by Jeff Erickson

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#989]
- Website URL: https://jeffe.cs.illinois.edu/teaching/algorithms/
- License: CC-BY
- Desired ZIM Title: **Algorithms**
- Desired ZIM Description: **A free electronic version of the Algorithms textbook, along with lecture notes**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
recipe created
https://farm.openzim.org/recipes/jeffe.cs.illinois.edu_en_all
I'll update the library link once ready

**Comment by Popolechien** [comment]
FYI @jeffgerickson

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#jeffe.cs.illinois.edu_en_all_2024-05
