### ISSUE TITLE
New request: 

### ISSUE THREAD

**Issue by pfifo** [openzim/zim-requests#990]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

there is a lack of cookbooks for making food
I have no idea how to determine if a recipe has a copyright so I cant really suggest a website, but maybe https://www.allrecipes.com/

**Comment by Popolechien** [comment]
I fully agree with your comment but since this is not immediately actionable (allrecipes.com is copyrighted) I'm going to close this specific ticket.
