### ISSUE TITLE
Medline plus in English

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#991]
- Website URL: https://medlineplus.gov/ency/
- License: **Public domain**
- Desired ZIM Title: **Medline Plus**
- Desired ZIM Description: **Trusted Health Information for You**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

See also #992

**Comment by Popolechien** [comment]
I would also exclude everything under medlineplus.gov/languages/

**Comment by Popolechien** [comment]
If the scrape does not work then https://iiab.me/modules/en-medline_plus/ is a possible alternative.

**Comment by MrnateGeek** [comment]
I got the icon in 5 seconds
https://medlineplus.gov/images/touch-icon.png

**Comment by kelson42** [comment]
@Popolechien Why only the encyclopedia part? For example https://medlineplus.gov/healthtopics.html seems of interest as well?

**Comment by Popolechien** [comment]
@kelson42 that would be #994

**Comment by benoit74** [comment]
Recipe created at https://farm.openzim.org/recipes/medlineplus.gov_en_ency ; limit set to only 100 pages for now to check website behavior (custom CSS will be needed anyway)

**Comment by benoit74** [comment]
Discussed atm with Popolechien, we will ZIM the whole website, we do not see real arguments for ZIMing only the encyclopedia

**Comment by benoit74** [comment]
Custom CSS developed and recipe reconfigured.

Launching with only 1000 pages for now.

Will probably have an issue with pages with videos like https://medlineplus.gov/ency/anatomyvideos/000002.htm (will probably clob the ZIM but not work at all, same issue as https://github.com/openzim/zim-requests/issues/323: https://github.com/openzim/zimit/issues/353)

**Comment by benoit74** [comment]
Recipe moved to https://farm.openzim.org/recipes/medlineplus.gov_en_all/

**Comment by benoit74** [comment]
No issue found with video, file is simply an mp4 and everything is working well on test page mentioned above.

Just started the full ZIM creation in dev.

**Comment by benoit74** [comment]
File is ready in dev: https://dev.library.kiwix.org/#lang=eng&q=medline, looks ok to me.

Please review as well before moving to prod

**Comment by Popolechien** [comment]
LGTM. 

On a side note, the huge number of external links makes it all the more important to look into openzim/zimit/issues/374 and decide on blocking them or at a very minimum flag them.

**Comment by benoit74** [comment]
Requested in production, will update when file is ready.

**Comment by benoit74** [comment]
File is ready in production. 

Note that on library.kiwix.org it is impacted (and Medline ES too) by https://github.com/kiwix/operations/issues/280 but ZIM is OK, this is only a problem with our infra / kiwix-serve instance, not the ZIM itself, so I close the issue.

ZIM is playing fine in dev, with kiwix apple reader, and would probably play fine on a hotspot.
