### ISSUE TITLE
Medline Plus in Spanish

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#992]
- Website URL: https://iiab.me/modules/es-medline_plus/spanish/index.html
- License: **Public domain**
- Desired ZIM Title: **Medline Plus**
- Desired ZIM Description: **Informaciòn de Salud para Usted**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **esp**
- Is this a MediaWiki?: **no**

See also #991

**Comment by kelson42** [comment]
Real URL seems to be https://medlineplus.gov/spanish/

**Comment by benoit74** [comment]
Recipe created at https://farm.openzim.org/recipes/medlineplus.gov_es_ency ; limit set to only 100 pages for now to check website behavior (custom CSS will be needed anyway)

**Comment by benoit74** [comment]
Recipe moved to https://farm.openzim.org/recipes/medlineplus.gov_es_all/

Custom CSS custom and limit increased to 1000.

See https://github.com/openzim/zim-requests/issues/991#issuecomment-2372163963 for probable issue with videos

(testable here on https://medlineplus.gov/spanish/videos-de-medlineplus/histamina-de-lo-que-esta-hecha-la-alergia/ if needed)

**Comment by benoit74** [comment]
No issue found with video, file is simply an mp4 and everything is working well on test page mentioned above.

Just started the full ZIM creation in dev.

**Comment by benoit74** [comment]
File is ready in dev: https://dev.library.kiwix.org/#lang=spa&q=medline, looks OK to me.

Please review as well.

**Comment by Popolechien** [comment]
LGTM.

**Comment by benoit74** [comment]
Thanks, requested in prod.

**Comment by benoit74** [comment]
File is ready in production: https://library.kiwix.org/#lang=&q=medline
