### ISSUE TITLE
https://wwwnc.cdc.gov/travel/

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#995]
- Website URL: https://wwwnc.cdc.gov/travel/
- License: **Public domain** 
- Desired ZIM Title: **Travelers' Health**
- Desired ZIM Description: **Advice from the Center for Disease Control and Prevention**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by MrnateGeek** [comment]
I do have a .png icon:
https://wwwnc.cdc.gov/TemplatePackage/3.0/images/Win8_tile_70x70.png

Sounds like someone don't know how to read the html code

**Comment by RavanJAltaie** [comment]
File is ready in the library 
https://library.kiwix.org/viewer#wwwnc.cdc.gov_en_all_2024-08
