### ISSUE TITLE
Open Data Structures

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#996]
- Website URL: https://opendatastructures.org/
- License: **Creative Commons**
- Desired ZIM Title: **Open Data Structures**
- Desired ZIM Description: **Data structures for lists, queues, dictionaries, dictionaries, and graphs.**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng** +tur, slv, jap, por
- Is this a MediaWiki?: **no**

**Note that there are versions in Turkish, Slovenian, Portuguese and Japanese** Those should be created as additional, separate zim files

**Comment by RavanJAltaie** [comment]
File is ready at the library
https://library.kiwix.org/viewer#opendatastructures.org_en_all_2024-05
